### ISSUE TITLE
tilda: segmentation fault

### ISSUE THREAD

**Issue by wmcbtech30** [termux/termux-packages#10119]
### Problem description

Just got tilda installed. and it segfaults when opened. however previously tilda used to launch normally. not sure what changed caused tilda to segfault

![2022-01-19-204941_1024x768_scrot](https://user-images.githubusercontent.com/65075766/150231642-bbab7857-d732-475a-8659-2af9c535a5b4.png)

### What steps will reproduce the bug?

* Install tilda `pkg in tilda`
* Setup X11 Environment (VNC/XSDL)
* Run tilda via Terminal and you'll get segmentation fault

### What is the expected behavior?

It should run

### System information

termux-info:

```
Application version:
0.118.0
Packages CPU architecture:
arm
Subscribed repositories:
# sources.list
deb https://packages-cf.termux.org/apt/termux-main/ stable main
# x11-repo (sources.list.d/x11.list)
deb https://grimler.se/x11-packages x11 main
Updatable packages:
nodejs/stable 17.4.0 arm [upgradable from: 17.3.1]
termux-tools/stable 0.157 all [upgradable from: 0.156]
Android version:
11
Kernel build information:
Linux localhost 4.14.180-perf+ termux/x11-packages#2 SMP PREEMPT Sat Nov 27 17:39:09 CST 2021 armv8l Android
Device manufacturer:
OPPO
Device model:
CPH1933

```

**Comment by xtkoba** [comment]
Just my observation (on Android 8.1.0 aarch64):

```
Thread 1 "tilda" received signal SIGSEGV, Segmentation fault.
0x0000007fb799d9e0 in strlen () from target:/system/lib64/libc.so
(gdb) bt
#0  0x0000007fb799d9e0 in strlen () from target:/system/lib64/libc.so
#1  0x0000007fb713ba2c in g_strdup () from target:/data/data/com.termux/files/usr/lib/libglib-2.0.so
#2  0x0000007fb79179b4 in vte::glib::dup_string (str=0x676e00736e6153 <error: Cannot access memory at address 0x676e00736e6153>) at ../vte-0.62.2/src/glib-glue.hh:52
#3  0x0000007fb79165d4 in vte::base::SpawnContext::set_argv (this=this@entry=0x7ffffff248, arg0=0x676e00736e6153 <error: Cannot access memory at address 0x676e00736e6153>, argv=argv@entry=0x7fb2f21678) at ../vte-0.62.2/src/spawn.hh:86
#4  0x0000007fb7915368 in spawn_context_from_args (pty=<optimized out>, working_directory=<optimized out>, argv=<optimized out>, argv@entry=0x7fb2f21678, envv=<optimized out>, envv@entry=0x0, fds=<optimized out>, fds@entry=0x0, n_fds=<optimized out>, n_fds@entry=0, fd_map_to=<optimized out>, fd_map_to@entry=0x0, n_fd_map_to=<optimized out>, n_fd_map_to@entry=0, spawn_flags=G_SPAWN_DEFAULT, child_setup=0x0, child_setup_data=0x0, child_setup_data_destroy=0x0) at ../vte-0.62.2/src/vtepty.cc:634
#5  0x0000007fb7915624 in vte_pty_spawn_with_fds_async (pty=0x7fb220fa20, working_directory=0x0, argv=0x7fb2f21678, envv=0x0, fds=0x0, n_fds=0, fd_map_to=0x0, n_fd_map_to=0, spawn_flags=(G_SPAWN_SEARCH_PATH | G_SPAWN_STDERR_TO_DEV_NULL | G_SPAWN_CHILD_INHERITS_STDIN | G_SPAWN_FILE_AND_ARGV_ZERO | G_SPAWN_SEARCH_PATH_FROM_ENVP | unknown: 0x2ae4ac00), child_setup=0x0, child_setup_data=0x0, child_setup_data_destroy=0x0, timeout=3000, cancellable=0x0, callback=0x7fb794972c <spawn_async_cb(_GObject*, _GAsyncResult*, void*)>, user_data=0x7fb223f360) at ../vte-0.62.2/src/vtepty.cc:817
#6  0x0000007fb79495f0 in vte_terminal_spawn_with_fds_async (terminal=0x7fb225da50, pty_flags=<optimized out>, working_directory=working_directory@entry=0x0, argv=<optimized out>, argv@entry=0x7fb2f21678, envv=<optimized out>, fds=0x0, n_fds=0, fd_map_to=0x0, n_fd_map_to=0, spawn_flags=G_SPAWN_DEFAULT, child_setup=0x0, child_setup_data=0x0, child_setup_data_destroy=0x0, timeout=3000, cancellable=0x0, callback=0x5555573134 <shell_spawned_cb>, user_data=0x7fb227e930) at ../vte-0.62.2/src/vtegtk.cc:3454
#7  0x0000007fb79499fc in vte_terminal_spawn_async (terminal=0x676e00736e6153, pty_flags=(VTE_PTY_NO_LASTLOG | VTE_PTY_NO_UTMP | VTE_PTY_NO_FALLBACK | VTE_PTY_NO_CTTY | unknown: 0x736e6100), working_directory=0x7fb2f21678 "Sans", working_directory@entry=0x0, argv=0x0, argv@entry=0x7fb2f21678, envv=0x153, spawn_flags=spawn_flags@entry=G_SPAWN_DEFAULT, child_setup=<optimized out>, child_setup_data=<optimized out>, child_setup_data_destroy=0x0, timeout=3000, cancellable=0x0, callback=0x5555573134 <shell_spawned_cb>, user_data=0x7fb227e930) at ../vte-0.62.2/src/vtegtk.cc:3511
#8  0x000000555557310c in start_default_shell (tt=0x7fb227e930) at src/tilda_terminal.c:581
#9  0x0000005555572c28 in start_shell (tt=tt@entry=0x7fb227e930, ignore_custom_command=0) at src/tilda_terminal.c:533
#10 0x00000055555723f0 in tilda_term_init (tw=<optimized out>, tw@entry=0x7ffffff710) at src/tilda_terminal.c:240
#11 0x00000055555746a8 in tilda_window_add_tab (tw=tw@entry=0x7ffffff710) at src/tilda_window.c:1106
#12 0x000000555557435c in tilda_window_init (config_file=<optimized out>, instance=<optimized out>, tw=tw@entry=0x7ffffff710) at src/tilda_window.c:980
#13 0x000000555556efcc in main (argc=1, argv=0x7ffffff8a8) at src/tilda.c:291
(gdb)
```
