### ISSUE TITLE
[Bug]: get_cmake_version raises Error when install opencv-python

### ISSUE THREAD

**Issue by laoyur** [termux/termux-packages#10278]
### Problem description

I have trouble installing `opencv-python`
this issue is very helpful #10065
but this time, `get_cmake_version` fails, cmake is already installed via `pkg install cmake`

```
$ cmake --version
cmake version 3.23.1

CMake suite maintained and supported by Kitware (kitware.com/cmake).
```

and this is the build error:
```
$ pip install opencv-python --find-links ~/wheels
Looking in links: /data/data/com.termux/files/home/wheels
Collecting opencv-python
  Using cached opencv-python-4.5.5.64.tar.gz (89.9 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting numpy>=1.17.3
  Using cached numpy-1.22.3-cp310-cp310-linux_aarch64.whl
Building wheels for collected packages: opencv-python
  Building wheel for opencv-python (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for opencv-python (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [23 lines of output]
      Traceback (most recent call last):
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-iy7q7879/overlay/bin/cmake", line 8, in <module>
          sys.exit(cmake())
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-iy7q7879/overlay/lib/python3.10/site-packages/cmake/__init__.py", line 47, in cmake
          raise SystemExit(_program('cmake', sys.argv[1:]))
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-iy7q7879/overlay/lib/python3.10/site-packages/cmake/__init__.py", line 43, in _program
          return subprocess.call([os.path.join(CMAKE_BIN_DIR, name)] + args)
        File "/data/data/com.termux/files/usr/lib/python3.10/subprocess.py", line 345, in call
          with Popen(*popenargs, **kwargs) as p:
        File "/data/data/com.termux/files/usr/lib/python3.10/subprocess.py", line 966, in __init__
          self._execute_child(args, executable, preexec_fn, close_fds,
        File "/data/data/com.termux/files/usr/lib/python3.10/subprocess.py", line 1840, in _execute_child
          raise child_exception_type(errno_num, err_msg, err_filename)
      OSError: [Errno 8] Exec format error: '/data/data/com.termux/files/usr/tmp/pip-build-env-iy7q7879/overlay/lib/python3.10/site-packages/cmake/data/bin/cmake'
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-iy7q7879/overlay/lib/python3.10/site-packages/skbuild/setuptools_wrap.py", line 613, in setup
          cmkr = cmaker.CMaker(cmake_executable)
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-iy7q7879/overlay/lib/python3.10/site-packages/skbuild/cmaker.py", line 141, in __init__
          self.cmake_version = get_cmake_version(self.cmake_executable)
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-iy7q7879/overlay/lib/python3.10/site-packages/skbuild/cmaker.py", line 95, in get_cmake_version
          raise SKBuildError(
      Traceback (most recent call last):
      
      Problem with the CMake installation, aborting build. CMake executable is cmake
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for opencv-python
```
I find the source code for `get_cmake_version`, but have no idea why it fails: 
https://github.com/scikit-build/scikit-build/blob/master/skbuild/cmaker.py#L93

### What steps will reproduce the bug?

pip install opencv-python

### What is the expected behavior?

install opencv-python

### System information

termux-info:

```
Termux Variables:
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://mirror.mwt.me/termux/main/ stable main
deb https://its-pointless.github.io/files/24 termux extras
# sources.list.d/pointless.list
deb https://its-pointless.github.io/files/21 termux extras
Updatable packages:
All packages up to date
Android version:
12
Kernel build information:
Linux localhost 4.19.152-perf+ #1 SMP PREEMPT Sat Apr 2 20:58:25 CST 2022 aarch64 Android
Device manufacturer:
vivo
Device model:
V2118A
```

**Comment by xtkoba** [comment]
That is why we provide the `opencv-python` package in our official repo.

**Comment by laoyur** [comment]
😱 I see...

```
$ pkg install opencv-python
$ python
>>> import cv2
>>>
```

Don't try using `pip install opencv-python`, or you will waste half a day like me...

**Comment by Joker-Bat** [comment]
> scream I see...
> 
> ```
> $ pkg install opencv-python
> $ python
> >>> import cv2
> >>>
> ```
> 
> Don't try using `pip install opencv-python`, or you will waste half a day like me...

Thankyou for your help, it helped me to install opencv-python in termux, but when i run some scripts with it i got some errors, how your journey with opencv in termux gone.

**Comment by laoyur** [comment]
> > scream I see...
> > ```
> > $ pkg install opencv-python
> > $ python
> > >>> import cv2
> > >>>
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Don't try using `pip install opencv-python`, or you will waste half a day like me...
> 
> Thankyou for your help, it helped me to install opencv-python in termux, but when i run some scripts with it i got some errors, how your journey with opencv in termux gone.

I use `cv2.matchTemplate`, it works great. What's your error?

**Comment by Joker-Bat** [comment]
> 

I've got some errors related to cmake, but i resolved after some google search, but i just done this for fun like detecting moving objects with mobile camera using cv2, but it didn't work because termux has GUI part to show output.
