### ISSUE TITLE
[Bug]: Nodejs uv_interface_addresses returned Unknown system error 13

### ISSUE THREAD

**Issue by neophob** [termux/termux-packages#10868]
### Problem description

When I use the Termux app, install Node.js (latest and lts) and run Node.js - the call to os.networkInterfaces() works.

However when I build Node.js myself using the Termux Docker images (./build-package.sh openssl nodejs), each call to os.networkInterfaces() fails with A system error occurred: uv_interface_addresses returned Unknown system error 13 (Unknown system error 13) on my Android 11 system. (Permission denied).

it looks like this is because Android 11 forbids apps to query MAC addresses. Links:
- Analyse https://gitlab.com/staltz/manyverse/-/issues/1411
- a potential fix here https://github.com/JaneaSystems/nodejs-mobile/commit/73d5d375dbd672c3df8556a83ad122a078d21ed2

> 

### What steps will reproduce the bug?

start self compiled nodejs binary on your Android 11 phone, enter `os.networkInterfaces()` in the repl.

Tested with the latest nodejs and nodejs-lts version

### What is the expected behavior?

call does not fail

### System information

termux-info:

```

```

**Comment by Grimler91** [comment]
Did you build in the docker image, or by git cloning termux-packages and running ./build-package.sh on device? 

Building in the docker image should give an identical nodejs{-lts} package as the one in our repos, unless you've made changes to the build recipe?

**Comment by neophob** [comment]
Note: I did NOT build the node package on my Android device, but on my Macbook in a Docker container. I the installed the node binary on my Android device. So I think the "on-device packaging" tag is wrong.

**Comment by neophob** [comment]
More info:
- the Android Termux App has targetSDK 28, that's why the os.networkInterfaces() call works
- if the Termux App targets SDK 30, the os.networkInterfaces() call will fail with the error described

**Comment by thunder-coding** [comment]
@neophob Can you try building Node.js with the following additional patch:-

```diff
--- ./deps/uv/src/unix/linux-core.c.orig	2022-06-03 12:37:01.127102137 +0530
+++ ./deps/uv/src/unix/linux-core.c	2022-06-03 12:37:11.887102132 +0530
@@ -43,14 +43,6 @@
 #include <fcntl.h>
 #include <time.h>
 
-#define HAVE_IFADDRS_H 1
-
-#ifdef __UCLIBC__
-# if __UCLIBC_MAJOR__ < 0 && __UCLIBC_MINOR__ < 9 && __UCLIBC_SUBLEVEL__ < 32
-#  undef HAVE_IFADDRS_H
-# endif
-#endif
-
 #ifdef HAVE_IFADDRS_H
 # if defined(__ANDROID__)
 #  include "uv/android-ifaddrs.h"
```

This will make sure that `uv_inteface_addresses()` will return `UV_ENOSYS` which makes much more sense then failing as above.

Also would like to know what's your use case of `os.networkInterfaces()`.

**Comment by neophob** [comment]
I applied the patch building nodejs:

```
...
Applying patch: deps-uv-src-unix-core.c.patch
Applying patch: deps-uv-src-unix-net.c.patch       << thats the patch above
Applying patch: deps-uv-src-unix-process.c.patch
Applying patch: deps-uv-uv.gyp.patch
Applying patch: deps-v8-src-flags-flag-definitions.h.patch
Applying patch: deps-v8-src-logging-log.cc.patch
Applying patch: deps-v8-src-trap-handler-trap-handler.h.patch
...
```

but then the build fails:

```
  aarch64-linux-android-clang -o /home/builder/.termux-build/nodejs/src/out/Release/obj.target/libuv/deps/uv/src/unix/pthread-fixes.o ../deps/uv/src/unix/pthread-fixes.c '-DV8_DEPRECATION_WARNINGS' '-DV8_IMMINENT_DEPRECATION_WARNINGS' '-D_GLIBCXX_USE_CXX11_ABI=1' '-D__STDC_FORMAT_MACROS' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-D_GLIBCXX_USE_C99_MATH' -I../deps/uv/include -I../deps/uv/src -I/data/data/com.termux/files/usr/include  -Wall -Wextra -Wno-unused-parameter -fvisibility=hidden -g --std=gnu89 -Wall -Wextra -Wno-unused-parameter -Wstrict-prototypes -fno-strict-aliasing -O3 -fno-omit-frame-pointer -fPIC  -MMD -MF /home/builder/.termux-build/nodejs/src/out/Release/.deps//home/builder/.termux-build/nodejs/src/out/Release/obj.target/libuv/deps/uv/src/unix/pthread-fixes.o.d.raw  -I/data/data/com.termux/files/usr/include  -fstack-protector-strong -Oz -c
../deps/uv/src/unix/linux-core.c:636:38: warning: declaration of 'struct ifaddrs' will not be visible outside of this function [-Wvisibility]
static int uv__ifaddr_exclude(struct ifaddrs *ent, int exclude_type) {
                                     ^
../deps/uv/src/unix/linux-core.c:637:13: error: incomplete definition of type 'struct ifaddrs'
  if (!((ent->ifa_flags & IFF_UP) && (ent->ifa_flags & IFF_RUNNING)))
         ~~~^
../deps/uv/src/unix/linux-core.c:636:38: note: forward declaration of 'struct ifaddrs'
static int uv__ifaddr_exclude(struct ifaddrs *ent, int exclude_type) {
                                     ^
../deps/uv/src/unix/linux-core.c:637:42: error: incomplete definition of type 'struct ifaddrs'
  if (!((ent->ifa_flags & IFF_UP) && (ent->ifa_flags & IFF_RUNNING)))
                                      ~~~^
../deps/uv/src/unix/linux-core.c:636:38: note: forward declaration of 'struct ifaddrs'
static int uv__ifaddr_exclude(struct ifaddrs *ent, int exclude_type) {
                                     ^
../deps/uv/src/unix/linux-core.c:639:10: error: incomplete definition of type 'struct ifaddrs'
  if (ent->ifa_addr == NULL)
      ~~~^
../deps/uv/src/unix/linux-core.c:636:38: note: forward declaration of 'struct ifaddrs'
static int uv__ifaddr_exclude(struct ifaddrs *ent, int exclude_type) {
                                     ^
../deps/uv/src/unix/linux-core.c:645:10: error: incomplete definition of type 'struct ifaddrs'
  if (ent->ifa_addr->sa_family == PF_PACKET)
      ~~~^
../deps/uv/src/unix/linux-core.c:636:38: note: forward declaration of 'struct ifaddrs'
static int uv__ifaddr_exclude(struct ifaddrs *ent, int exclude_type) {
                                     ^
1 warning and 4 errors generated.
make[1]: *** [deps/uv/libuv.target.mk:141: /home/builder/.termux-build/nodejs/src/out/Release/obj.target/libuv/deps/uv/src/unix/linux-core.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make: *** [Makefile:113: node] Error 2
```

> Also would like to know what's your use case of os.networkInterfaces().

My use case is reuse a nodejs application in a mobile app. the os.networkInterfaces() call if not used directly - BUT there are some parts the use that code. the problem today is the error case which could lead to weird situations

**Comment by thunder-coding** [comment]
@neophob The following updated patch should work:-

```diff
--- ./deps/uv/src/unix/linux-core.c.orig	2022-06-03 12:37:01.127102137 +0530
+++ ./deps/uv/src/unix/linux-core.c	2022-06-03 14:36:13.308341930 +0530
@@ -43,14 +43,6 @@
 #include <fcntl.h>
 #include <time.h>
 
-#define HAVE_IFADDRS_H 1
-
-#ifdef __UCLIBC__
-# if __UCLIBC_MAJOR__ < 0 && __UCLIBC_MINOR__ < 9 && __UCLIBC_SUBLEVEL__ < 32
-#  undef HAVE_IFADDRS_H
-# endif
-#endif
-
 #ifdef HAVE_IFADDRS_H
 # if defined(__ANDROID__)
 #  include "uv/android-ifaddrs.h"
@@ -640,7 +632,7 @@
   return val;
 }
 
-
+#ifdef HAVE_IFADDRS_H
 static int uv__ifaddr_exclude(struct ifaddrs *ent, int exclude_type) {
   if (!((ent->ifa_flags & IFF_UP) && (ent->ifa_flags & IFF_RUNNING)))
     return 1;
@@ -654,6 +646,7 @@
     return exclude_type;
   return !exclude_type;
 }
+#endif
 
 int uv_interface_addresses(uv_interface_address_t** addresses, int* count) {
 #ifndef HAVE_IFADDRS_H
```

And yeah, it's an upstream bug that `uv__ifaddr_exclude` is compiled even when `HAVE_IFADDRS_H` is not defined. The updated patch should fix it!

**Comment by neophob** [comment]
Nice, that patch worked. 

Now i get a different error: `A system error occurred: undefined returned undefined (undefined)` with stacktrace:

```
at Object.networkInterfaces (node:os:264:16)
at userspace js code where os.networkInterfaces() is used
```

**Comment by thunder-coding** [comment]
> Now i get a different error: A system error occurred: undefined returned undefined (undefined) with stacktrace:

Well that's because your code (or most probably one of your dependencies) hasn't been designed to work in situations where `uv_network_interfaces` might not be implemented. Can you share the full stack trace, so that the culprit dependency (or your package) can be tracked

**Comment by neophob** [comment]
> Well that's because your code (or most probably one of your dependencies) hasn't been designed to work in situations where uv_network_interfaces might not be implemented.

Not sure if I fully agree, as Nodejs docs say, that `os.networkInterfaces()` returns an Object (which includes an empty object) - but a system error should not be thrown there. 

> Can you share the full stack trace, so that the culprit dependency (or your package) can be tracked

that _IS_ the whole usable stacktrace of the code, my function call looks like `return os.networkInterfaces();`, that's it. Here's the raw stacktrace:

```
"SystemError [ERR_SYSTEM_ERROR]: A system error occurred: undefined returned undefined (undefined)
    at Object.networkInterfaces (node:os:264:16)
    at E._getInterfaces (/data/data/app.fqdn/files/nodeapp/index.js:1:260599)
    at E.getLanInterface (/data/data/app.fqdn/files/nodeapp/index.js:1:260702)
    at E.getLanAddressIPv4 (/data/data/app.fqdn/files/nodeapp/index.js:1:260898)
    at E.getLanAddress (/data/data/app.fqdn/files/nodeapp/index.js:1:261111)
    at /data/data/app.fqdn/files/nodeapp/index.js:1:326359
    at Layer.handle [as handle_request] (/data/data/app.fqdn/files/nodeapp/node_modules/express/lib/router/layer.js:95:5)
    at next (/data/data/app.fqdn/files/nodeapp/node_modules/express/lib/router/route.js:144:13)
    at Route.dispatch (/data/data/app.fqdn/files/nodeapp/node_modules/express/lib/router/route.js:114:3)
    at Layer.handle [as handle_request] (/data/data/app.fqdn/files/nodeapp/node_modules/express/lib/router/layer.js:95:5)
    at /data/data/app.fqdn/files/nodeapp/node_modules/express/lib/router/index.js:284:15
    at Function.process_params (/data/data/app.fqdn/files/nodeapp/node_modules/express/lib/router/index.js:346:12)
    at next (/data/data/app.fqdn/files/nodeapp/node_modules/express/lib/router/index.js:280:10)
    at Function.handle (/data/data/app.fqdn/files/nodeapp/node_modules/express/lib/router/index.js:175:3)
    at router (/data/data/app.fqdn/files/nodeapp/node_modules/express/lib/router/index.js:47:12)
    at Layer.handle [as handle_request] (/data/data/app.fqdn/files/nodeapp/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/data/data/app.fqdn/files/nodeapp/node_modules/express/lib/router/index.js:328:13)
    at /data/data/app.fqdn/files/nodeapp/node_modules/express/lib/router/index.js:286:9
    at Function.process_params (/data/data/app.fqdn/files/nodeapp/node_modules/express/lib/router/index.js:346:12)
    at next (/data/data/app.fqdn/files/nodeapp/node_modules/express/lib/router/index.js:280:10)
    at Function.handle (/data/data/app.fqdn/files/nodeapp/node_modules/express/lib/router/index.js:175:3)
    at router (/data/data/app.fqdn/files/nodeapp/node_modules/express/lib/router/index.js:47:12)"
```

**Comment by thunder-coding** [comment]
> is there anything I can do help diagnose this issue? I'm pretty clueless tbh at the moment, any hints are appreciated!

It seems like you're using a bundler to bundle your application. If you can give me access to the source code of your app, I can certainly look into the place where `os.networkInterfaces()` is called and whether there is a possible workaround for the same.
Best regards, Yaksh.

**Comment by neophob** [comment]
Thanks @thunder-coding for your feedback, is my example above enough or is there anything I can do to help you reproducing the problem?

**Comment by Grimler91** [comment]
Termux targets sdk level 28 [for a reason](https://github.com/termux/termux-app/issues/2155), so I guess we won't be able to reproduce the issue. 

IMHO this issue isn't really termux related. Maybe other nodejs developers can help if you open an issue in their repo

**Comment by thunder-coding** [comment]
> IMHO this issue isn't really termux related. Maybe other nodejs developers can help if you open an issue in their repo

Instead of opening the issue in the nodejs GitHub repo, it'll make more sense to open it in the package's repo which depends on `os.networkInterfaces()`. Just grep through the `node_modules/` directory to find out which package makes use of it.

**Comment by neophob** [comment]
>Termux targets sdk level 28 https://github.com/termux/termux-app/issues/2155, so I guess we won't be able to reproduce the issue.

Yeah, I wanted to bring that issue up for the future (and my use case). Maybe it's my fault thinking that the termux packages support also post SDK 28 devices.

> Instead of opening the issue in the nodejs GitHub repo, it'll make more sense to open it in the package's repo which depends on os.networkInterfaces(). 

This does not make sense as `os.networkInterfaces()` is a NodeJS API call. There is no reason to use something else from a developers point of view.

**Comment by zhoufenqin** [comment]
I also meet the same problem, after some investigation, it was because the node had some problem, and I change a node for my pod then it solved, just share the info for others who may meet the same problem with me.

```
node:os:68
      throw new ERR_SYSTEM_ERROR(ctx);
      ^

SystemError [ERR_SYSTEM_ERROR]: A system error occurred: uv_interface_addresses returned Unknown system error 13 (Unknown system error 13)    at Object.networkInterfaces (node:os:259:16)
    at getAllIPAddresses (/layers/tanzu-buildpacks_new-relic/new-relic-nodejs/node_modules/newrelic/lib/collector/facts.js:95:25)
    at factMapCb (/layers/tanzu-buildpacks_new-relic/new-relic-nodejs/node_modules/newrelic/lib/collector/facts.js:72:27)
    at /layers/tanzu-buildpacks_new-relic/new-relic-nodejs/node_modules/async/dist/async.js:3681:19
    at wrapper (/layers/tanzu-buildpacks_new-relic/new-relic-nodejs/node_modules/async/dist/async.js:271:20)
    at iterateeCallback (/layers/tanzu-buildpacks_new-relic/new-relic-nodejs/node_modules/async/dist/async.js:427:28)
    at /layers/tanzu-buildpacks_new-relic/new-relic-nodejs/node_modules/async/dist/async.js:327:20
    at /layers/tanzu-buildpacks_new-relic/new-relic-nodejs/node_modules/async/dist/async.js:3679:17
    at onRefreshFinish (/layers/tanzu-buildpacks_new-relic/new-relic-nodejs/node_modules/newrelic/lib/environment.js:609:5)
  code: 'ERR_SYSTEM_ERROR',
  info: {
    errno: 13,
    code: 'Unknown system error 13',
    message: 'Unknown system error 13',
    syscall: 'uv_interface_addresses'
  },
  errno: [Getter/Setter],
  syscall: [Getter/Setter]
}
```

**Comment by noonesimg** [comment]
Facing the same problem. 
Is there any workaround / temporary fix for this?
uv_interface_addresses is pretty common node API. 
Almost any dev server relies on it.

**Comment by neophob** [comment]
@noonesimg The workaround is to use targets sdk level 28 - let me know if you found another solution

**Comment by noonesimg** [comment]
@neophob thanks!
Can you specify plz, do I need to rebuild the whole termux-app with sdk level 28, or is there a way to just rebuild the nodejs package?

**Comment by VayuDev** [comment]
For those comming here after trying to use the C++ extension for code-server, I found a workaround:

1. Format the file with the error with prettier
   1. npm i --global prettier
   2. prettier -w /data/data/com.termux/files/usr/lib/code-server/lib/vscode/out/vs/server/node/server.main.js
2. Edit /data/data/com.termux/files/usr/lib/code-server/lib/vscode/out/vs/server/node/server.main.js and add befor line 16050 (the line with error, might be another line for you) to:


```return '00:00:00:00:00:00';```


So the whole function becomes:

```
function I() {
        return '00:00:00:00:00:00';
        const L = (0, os.networkInterfaces())();
        for (const R in L) { 
        const b = L[R];
                  if (b) {
                    for (const { mac: d } of b) if (a(d)) return d;
                  }
                }
        throw new Error("Unable to retrieve mac address (unexpected format)");
}
```

I found this out after reading the documentation for os.networkInterfaces() and noticing that this function just returns the first mac address of the first interface in the system. Seems to work for me for now.

**Comment by twaik** [comment]
Is this still reproducible/relevant?

**Comment by Silver-Volt4** [comment]
I can reproduce this in proot-distro, but not in "vanilla Termux".

**Comment by 2001zhaozhao** [comment]
I just ran into this when trying to run a Kotlin/JS project on proot ubuntu distro (which spins up a webpack dev server)

**Comment by petkar** [comment]
I ran into this while trying to run a NextJs project on Termux using proot in ubuntu distro (which spins up a turbopack)
Attaching the logs:
```
zink@localhost:~/my_project$ pnpm dev

> @ dev /home/zink/my_project
> next dev --turbopack

node:internal/errors:496
    ErrorCaptureStackTrace(err);
    ^

NodeError [SystemError]: A system error occurred: uv_interface_addresses returned Unknown system error 13 (Unknown system error 13)
    at __node_internal_captureLargerStackTrace (node:internal/errors:496:5)
    at new SystemError (node:internal/errors:256:5)
    at new NodeError (node:internal/errors:367:7)
    at __node_internal_checkError (node:os:68:13)
    at Object.networkInterfaces (node:os:277:16)
    at getNetworkHosts (/home/zink/my_project/node_modules/.pnpm/next@15.2.0-canary.67_@babel+core@7.26.9_react-dom@19.0.0_react@19.0.0__react@19.0.0/node_modules/next/dist/lib/get-network-host.js:18:36)
    at getNetworkHost (/home/zink/my_project/node_modules/.pnpm/next@15.2.0-canary.67_@babel+core@7.26.9_react-dom@19.0.0_react@19.0.0__react@19.0.0/node_modules/next/dist/lib/get-network-host.js:40:19)
    at Server.<anonymous> (/home/zink/my_project/node_modules/.pnpm/next@15.2.0-canary.67_@babel+core@7.26.9_react-dom@19.0.0_react@19.0.0__react@19.0.0/node_modules/next/dist/server/lib/start-server.js:215:84)
    at Server.emit (node:events:529:35)
    at emitListeningNT (node:net:1845:10)
    at process.processTicksAndRejections (node:internal/process/task_queues:81:21) {
  code: 'ERR_SYSTEM_ERROR',
  info: {
    errno: 13,
    code: 'Unknown system error 13',
    message: 'Unknown system error 13',
    syscall: 'uv_interface_addresses'
  },
  errno: [Getter/Setter],
  syscall: [Getter/Setter]
}

Node.js v18.19.1
```

**Comment by etienne-85** [comment]
Same here while trying to run `vite` within `archlinux` proot.
 I tried the workaround suggested before by patching the file where the error occured (in my case with vite in that folder: `node_modules/vite/dist/node/chunks/`)
to replace the call to `os.networkInterfaces()`, with hardcoded data:
```
// BEGIN PATCH
const hardcodedNetworkInterfaces = [
  { address: "127.0.0.1", family: "IPv4" }, // Localhost (IPv4)
  { address: "192.168.0.169", family: "IPv4" }, // Example network IP
];
// REPLACE
// Object.values(os$3.networkInterfaces())
// WITH 
hardcodedNetworkInterfaces
// END PATCH
.flatMap((nInterface) => nInterface ?? []).filter(
```

**Comment by absolutegravitas** [comment]
i ran into this attempting to get RooCode extension running / activated.

```
2025-04-06 11:31:36.832 [info] ExtensionService#_doActivateExtension RooVeterinaryInc.roo-cline, startup: false, activationEvent: 'onLanguage'
2025-04-06 11:31:38.599 [error] Activating extension RooVeterinaryInc.roo-cline failed due to an error:
2025-04-06 11:31:38.599 [error] SystemError: A system error occurred: uv_interface_addresses returned Unknown system error 13 (Unknown system error 13)
	at Object.networkInterfaces (node:os:277:16)
	at zgo (/root/.local/share/code-server/extensions/rooveterinaryinc.roo-cline-3.11.8-universal/dist/extension.js:3322:16580)
	at <instance_members_initializer> (/root/.local/share/code-server/extensions/rooveterinaryinc.roo-cline-3.11.8-universal/dist/extension.js:3322:16367)
	at new sj (/root/.local/share/code-server/extensions/rooveterinaryinc.roo-cline-3.11.8-universal/dist/extension.js:3322:16105)
	at new S3 (/root/.local/share/code-server/extensions/rooveterinaryinc.roo-cline-3.11.8-universal/dist/extension.js:3322:16770)
	at Object.<anonymous> (/root/.local/share/code-server/extensions/rooveterinaryinc.roo-cline-3.11.8-universal/dist/extension.js:3322:22323)
	at Module._compile (node:internal/modules/cjs/loader:1469:14)
	at Module._extensions..js (node:internal/modules/cjs/loader:1548:10)
	at Module.load (node:internal/modules/cjs/loader:1288:32)
	at Module._load (node:internal/modules/cjs/loader:1104:12)
	at e._load (file:///usr/lib/code-server/lib/vscode/out/vs/workbench/api/node/extensionHostProcess.js:175:10896)
	at t._load (file:///usr/lib/code-server/lib/vscode/out/vs/workbench/api/node/extensionHostProcess.js:167:22534)
	at i._load (file:///usr/lib/code-server/lib/vscode/out/vs/workbench/api/node/extensionHostProcess.js:159:21232)
	at Module.require (node:internal/modules/cjs/loader:1311:19)
	at require (node:internal/modules/helpers:179:18)
	at Vz.xb (file:///usr/lib/code-server/lib/vscode/out/vs/workbench/api/node/extensionHostProcess.js:167:24417)
	at async Promise.all (index 0)
```

**Comment by gjtiquia** [comment]
> Same here while trying to run `vite` within `archlinux` proot. I tried the workaround suggested before by patching the file where the error occured (in my case with vite in that folder: `node_modules/vite/dist/node/chunks/`) to replace the call to `os.networkInterfaces()`, with hardcoded data:
> 
> ```
> // BEGIN PATCH
> const hardcodedNetworkInterfaces = [
>   { address: "127.0.0.1", family: "IPv4" }, // Localhost (IPv4)
>   { address: "192.168.0.169", family: "IPv4" }, // Example network IP
> ];
> // REPLACE
> // Object.values(os$3.networkInterfaces())
> // WITH 
> hardcodedNetworkInterfaces
> // END PATCH
> .flatMap((nInterface) => nInterface ?? []).filter(
> ```

this worked for me thanks @etienne-85 !!!

**Comment by rax35** [comment]
>@2001zhaozhao: I just ran into this when trying to run a Kotlin/JS project on proot ubuntu distro (which spins up a webpack dev server)

I am running into same problem. Did you find any solutions?

**Comment by dpurnam** [comment]
After hours of banging my head, i figured this patch for nodejs, especially on UNIQID pkg.

```
// ./patch-os.js file
const os = require('os');
const original = os.networkInterfaces;
os.networkInterfaces = function() {
  if (process.env.UNIQID_DISABLE_NETWORK_INTERFACES === '1')
    return {};
  return original.apply(this, arguments);
};

```

Inject into your main app as:
`require('./patch-os.js');`

**Comment by agcrisbp** [comment]
maybe this will help: [Resolving NodeError: Unknown system error 13](https://aghea.vercel.app/blog/node-error-returned-system-error-13)

**Comment by Alexsandrua** [comment]
Hi. I heve the same problem
npm start

My project on git:
https://github.com/Alexsandrua/EOM191721UNR.git
Branch : git checout EOM191721UN-A

> EOM191721UNR@1.0.0 start
> webpack serve --mode=development --open --hot

[webpack-cli] SystemError [ERR_SYSTEM_ERROR]: A system error occurred: uv_interface_addresses returned Unknown system error 13 (Unknown system error 13)
    at Object.networkInterfaces (node:os:277:16)
    at Server.findIp (/home/tof/MyProjects/EOM191721UNR/node_modules/webpack-dev-server/lib/Server.js:408:41)
    at Server.logStatus (/home/tof/MyProjects/EOM191721UNR/node_modules/webpack-dev-server/lib/Server.js:2958:36)
    at Server.start (/home/tof/MyProjects/EOM191721UNR/node_modules/webpack-dev-server/lib/Server.js:3484:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Command.<anonymous> (/home/tof/MyProjects/EOM191721UNR/node_modules/@webpack-cli/serve/lib/index.js:161:21)
    at async Command.parseAsync (/home/tof/MyProjects/EOM191721UNR/node_modules/webpack-cli/node_modules/commander/lib/command.js:1092:5)
    at async Command.<anonymous> (/home/tof/MyProjects/EOM191721UNR/node_modules/webpack-cli/lib/webpack-cli.js:1340:13)
    at async Command.parseAsync (/home/tof/MyProjects/EOM191721UNR/node_modules/webpack-cli/node_modules/commander/lib/command.js:1092:5)
    at async WebpackCLI.run (/home/tof/MyProjects/EOM191721UNR/node_modules/webpack-cli/lib/webpack-cli.js:1344:9) {
  code: 'ERR_SYSTEM_ERROR',
  info: {
    errno: 13,
    code: 'Unknown system error 13',
    message: 'Unknown system error 13',
    syscall: 'uv_interface_addresses'
  },
  errno: [Getter/Setter: 13],
  syscall: [Getter/Setter: 'uv_interface_addresses']
