### ISSUE TITLE
[Bug]: termux-am stopped sending activity intents on Android 12

### ISSUE THREAD

**Issue by twaik** [termux/termux-packages#10940]
### Problem description

termux-am throws `java.lang.reflect.InvocationTargetException` when I am trying to send an intent. `termux-app` has `SYSTEM_ALERT_WINDOW` permission.
<details>
  <summary>log</summary>

  ```
// Checking if am works
~ $ am start -n com.package.name/com.package.name.ActivityName
Starting: Intent { cmp=com.package.name/.ActivityName }
Error type 3
Error: Activity class {com.package.name/com.package.name.ActivityName} does not exist.

// Checking if am is able to start activity
~ $ am start -n com.termux.x11/.MainActivity
Starting: Intent { cmp=com.termux.x11/.MainActivity }
java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at com.termux.termuxam.CrossVersionReflectedMethod.invoke(CrossVersionReflectedMethod.java:175)
	at com.termux.termuxam.IActivityManager.startActivityAsUser(IActivityManager.java:165)
	at com.termux.termuxam.Am.runStart(Am.java:635)
	at com.termux.termuxam.Am.onRun(Am.java:353)
	at com.termux.termuxam.BaseCommand.run(BaseCommand.java:46)
	at com.termux.termuxam.Am.main(Am.java:74)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:374)
Caused by: java.lang.NullPointerException
	at android.os.Parcel.createExceptionOrNull(Parcel.java:2443)
	at android.os.Parcel.createException(Parcel.java:2421)
	at android.os.Parcel.readException(Parcel.java:2404)
	at android.os.Parcel.readException(Parcel.java:2346)
	at com.android.internal.app.IAppOpsService$Stub$Proxy.reportRuntimeAppOpAccessMessageAndGetConfig(IAppOpsService.java:1680)
	at android.app.AppOpsManager$1.reportStackTraceIfNeeded(AppOpsManager.java:291)
	at android.app.AppOpsManager$1.onNoted(AppOpsManager.java:266)
	at android.app.AppOpsManager.readAndLogNotedAppops(AppOpsManager.java:9610)
	at android.os.Parcel.readExceptionCode(Parcel.java:2368)
	at android.os.Parcel.readException(Parcel.java:2343)
	at android.app.IActivityManager$Stub$Proxy.startActivityAsUser(IActivityManager.java:9560)
	... 9 more
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.internal.util.AnnotationValidations.validate(AnnotationValidations.java:129)
	at android.app.SyncNotedAppOp.<init>(SyncNotedAppOp.java:227)
	at android.app.SyncNotedAppOp$1.createFromParcel(SyncNotedAppOp.java:243)
	at android.app.SyncNotedAppOp$1.createFromParcel(SyncNotedAppOp.java:235)
	at com.android.internal.app.IAppOpsService$Stub.onTransact(IAppOpsService.java:735)

  ```

</details>

### What steps will reproduce the bug?

`am start -n com.termux.x11/.MainActivity`
Device's screen should be switched off...

The same thing happens with Shizuku's rish... https://github.com/RikkaApps/Shizuku/issues/197
Also it happens when I am trying to use am through ssh when `termux-app` when another app is in front...

### What is the expected behavior?

My application should start with an Intent I've sent.

### System information

<details>
  <summary>termux-info:</summary>

  ```
Termux Variables:
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://packages-cf.termux.org/apt/termux-main/ stable main
# x11-repo (sources.list.d/x11.list)
deb https://packages.termux.org/apt/termux-x11 x11 main
Updatable packages:
termux-tools/stable 0.185 all [upgradable from: 0.184]
termux-tools version:
0.184
Android version:
12
Kernel build information:
Linux localhost 4.19.87-23741619 #1 SMP PREEMPT Mon Apr 25 10:58:55 KST 2022 aarch64 Android
Device manufacturer:
samsung
Device model:
SM-G780F

  ```
 
</details>

**Comment by agnostic-apollo** [comment]
Seems to exist on Android `11` as well and likely os bug.

https://issuetracker.google.com/issues/160631716

However, in my case on Android 12 avd, the activity does start, only exception is thrown my `TermuxAm`.

For some reason `mPackageName` is `null`.

https://cs.android.com/android/platform/superproject/+/android-12.0.0_r32:frameworks/base/core/java/android/app/SyncNotedAppOp.java;l=227

**Comment by twaik** [comment]
Can we fix it? Or find another way to achieve this inside apk started using app_process? The only way I see is to get Binder of termux app to send a command to start Activity...

**Comment by agnostic-apollo** [comment]
Doesn't seem to occur when called from `TermuxActivity` itself with screen is off with `startActivity()` call.

Maybe for now just wait or abort till screen is on `Android >=11` **only** by checking if `getprop debug.tracing.screen_state` does not equal `2` (screen on). Prop won't be available on older versions. Also seems to be unset on boot if screen not turned off and on again. This shouldn't require root or `DUMP` permission to get screen state with `dumpsys`.

https://cs.android.com/android/_/android/platform/frameworks/base/+/5ae7df18221d1e2ec6838cd1c0d52e8097293a45

https://cs.android.com/android/platform/superproject/+/android-11.0.0_r1:frameworks/base/services/core/java/com/android/server/display/DisplayPowerController.java;l=1262

https://cs.android.com/android/platform/superproject/+/android-11.0.0_r1:frameworks/base/core/java/android/view/Display.java;l=332

**Comment by twaik** [comment]
I fixed this in my local repo by using `ActivityTaskManager` instead of `ActivityManager` or `ActivityManagerNative` in combination with [scrcpy's `fillAppInfo`](https://github.com/Genymobile/scrcpy/blob/ed84e18b1ae3e51d368f8c7bc88ba4db088e6855/server/src/main/java/com/genymobile/scrcpy/Workarounds.java#L33).
[This bug](https://github.com/termux/TermuxAm/issues/7) still can be reproduced.
Should I post code here?

**Comment by agnostic-apollo** [comment]
Interesting fix.

Yeah, I saw the bug solution, will look into testing and merging it.

Yeah, post the code or open pull request.

**Comment by twaik** [comment]
It doesn't look good but it works as a part of another project I am trying to debug...
I used parts of `scrcpy` code to achieve this.
```

    @SuppressLint({"BlockedPrivateApi", "PrivateApi", "DiscouragedPrivateApi"})
    public static final class ServiceManager {
        class ActivityManager {
            IInterface am;
            private final Method startActivityMethod;
            public ActivityManager(IInterface am) {
                this.am = am;
                Method m = null;
                try {
                    m = am.getClass().getMethod("startActivity",
                            Class.forName("android.app.IApplicationThread"),
                            String.class, String.class, Intent.class, String.class, IBinder.class,
                            String.class, int.class, int.class, Class.forName("android.app.ProfilerInfo"),
                            Bundle.class);
                } catch (NoSuchMethodException | ClassNotFoundException e) {
                    e.printStackTrace();
                }

                startActivityMethod = m;
            }

            void startActivity(Intent intent) {
                try {
                    startActivityMethod.invoke(am, null, "com.termux", null, intent, null, null, null, 0, 0, null, null);
                } catch (IllegalAccessException | InvocationTargetException e) {
                    e.printStackTrace();
                }
            }
        }

        private final Method getServiceMethod;
        public ServiceManager() {
            try {
                getServiceMethod = Class.forName("android.os.ServiceManager").getDeclaredMethod("getService", String.class);
            } catch (Exception e) {
                throw new AssertionError(e);
            }
        }

        private IInterface getService(String service, String type) {
            try {
                IBinder binder = (IBinder) getServiceMethod.invoke(null, service);
                Method asInterfaceMethod = Class.forName(type + "$Stub").getMethod("asInterface", IBinder.class);
                return (IInterface) asInterfaceMethod.invoke(null, binder);
            } catch (Exception e) {
                throw new AssertionError(e);
            }
        }

        public ActivityManager getActivityTaskManager() {
            try {
                Class<?> cls = Class.forName("android.app.ActivityTaskManager");
                Method getDefaultMethod = cls.getDeclaredMethod("getService");
                IInterface am = (IInterface) getDefaultMethod.invoke(null);
                return new ActivityManager(am);
            } catch (Exception e) {
                throw new AssertionError(e);
            }
        }
    }
```
Usage is 
```
...
static {
    fillAppInfo();
}
...
(new ServiceManager()).getActivityTaskManager().startActivity(someIntent);
...
```

**Comment by twaik** [comment]
Isn't it better to use something like [`HiddenApi`](https://github.com/RikkaW/HiddenApi) and [`HiddenApiRefinePlugin`](https://github.com/RikkaApps/HiddenApiRefinePlugin) instead of `CrossVersionReflectedMethod`?
