### ISSUE TITLE
K2PDFOPT: FORTIFY: fseeko: null FILE* aborted

### ISSUE THREAD

**Issue by ajay9634** [termux/termux-packages#11162]
Only default mode is working perfectly with reflow text but other mode -  fitwidth, fitpage, crop etc  are not working
And This is error
FORTIFY: fseeko: null FILE*
![Screenshot_2022-07-05-11-23-06-545_com termux](https://user-images.githubusercontent.com/78233144/177259406-98d42cc2-5ec4-4892-9566-cb7dc84c1703.jpg)

Aborted

_Originally posted by @ajay9634 in https://github.com/termux/termux-packages/issues/11089#issuecomment-1174647814_

**Comment by ajay9634** [comment]
K2PDFOPT 2.53 aarch64 version is working in Debian no root by enabling permission of allowing executed as program .
So Please fix this in termux

**Comment by ajay9634** [comment]
This is difference between official version and in Termux 
![Screenshot_2022-07-12-09-28-38-871_com termux](https://user-images.githubusercontent.com/78233144/178405836-551556d8-d71e-414c-acab-7bf399e44511.jpg)
K2PDFOPT in Termux

![images](https://user-images.githubusercontent.com/78233144/178405907-bc005c39-8bb6-483f-827b-044e95349b42.jpeg)
K2PDFOPT in Linux

**Comment by ajay9634** [comment]
Native pdf output is missing from Termux

**Comment by xtkoba** [comment]
Just an observation, on Android 8.1.0 aarch64, with command `k2pdfopt -mode fp in.pdf -o out.pdf`:

```
Program received signal SIGSEGV, Segmentation fault.
0x0000007fb78085b8 in __fseeko64(__sFILE*, long, int, int) ()
                   from target:/system/lib64/libc.so
(gdb) bt
#0  0x0000007fb78085b8 in __fseeko64(__sFILE*, long, int, int) ()
                       from target:/system/lib64/libc.so
#1  0x00000055555fd5f4 in pdffile_new_object (pdf=0x5555639ca8 <k2pdfopt_proc_one._masterinfo+1032>, flags=3)
                       at willuslib/pdfwrite.c:1147
#2  0x00000055555fdd10 in pdffile_add_bitmap_with_ocrwords (pdf=0x5555639ca8 <k2pdfopt_proc_one._masterinfo+1032>, bmp=0x7fffff9958, dpi=300, quality=-1, halfsize=186, ocrwords=0x0, ocr_render_flags=1)
                       at willuslib/pdfwrite.c:627
#3  0x00000055555fdc28 in pdffile_add_bitmap (pdf=0x5555639ca8 <k2pdfopt_proc_one._masterinfo+1032>, bmp=0x7fffff9958, dpi=300, quality=-1, halfsize=186)
                       at willuslib/pdfwrite.c:567
#4  0x00000055555c5b78 in masterinfo_publish (masterinfo=0x55556398a0 <k2pdfopt_proc_one._masterinfo>, k2settings=0x55556332b8 <k2pdfopt_proc_one._k2settings>, flushall=1)
                       at k2pdfoptlib/k2publish.c:230
#5  0x00000055555adc24 in masterinfo_flush (masterinfo=0x55556398a0 <k2pdfopt_proc_one._masterinfo>, k2settings=0x55556332b8 <k2pdfopt_proc_one._k2settings>, clearbitmap=0)
                       at k2pdfoptlib/k2master.c:189
#6  0x00000055555bec90 in bmpregion_source_box_process (region=0x7fffffaac0, k2settings=0x55556332b8 <k2pdfopt_proc_one._k2settings>, masterinfo=0x55556398a0 <k2pdfopt_proc_one._masterinfo>, level=1, pages_done=0)
                       at k2pdfoptlib/k2proc.c:472
#7  0x00000055555be4cc in bmpregion_source_page_add (region=0x7fffffaac0, k2settings=0x55556332b8 <k2pdfopt_proc_one._k2settings>, masterinfo=0x55556398a0 <k2pdfopt_proc_one._masterinfo>, level=1, pages_done=0)
                       at k2pdfoptlib/k2proc.c:173
#8  0x000000555559dd14 in k2pdfopt_proc_one (k2settings0=0x5555626698 <main._k2conv>, filename=0x7fffffe8d0 "in.pdf", k2fileproc=0x7fffffece8)
                       at k2pdfoptlib/k2file.c:899
#9  0x000000555559c824 in k2pdfopt_preprocess_single_doc (k2settings=0x5555626698 <main._k2conv>, srcfilename_passed=0x7fffffed78 "in.pdf", k2listproc=0x7ffffff920)
                       at k2pdfoptlib/k2file.c:339
#10 0x000000555559b0ac in k2pdfopt_proc_file_or_folder (k2settings=0x5555626698 <main._k2conv>, filename=0x7fb702d0d8 "in.pdf", k2listproc=0x7ffffff920)
                       at k2pdfoptlib/k2file.c:172
#11 0x000000555559aec4 in k2pdfopt_proc_wildarg (k2settings=0x5555626698 <main._k2conv>, arg=0x7fb702d0d8 "in.pdf", k2listproc=0x7ffffff920)
                       at k2pdfoptlib/k2file.c:109
#12 0x000000555559acc4 in main (argc=6, argv=0x7ffffff9f8)
                       at k2pdfopt.c:269
(gdb) f 1
#1  0x00000055555fd5f4 in pdffile_new_object (pdf=0x5555639ca8 <k2pdfopt_proc_one._masterinfo+1032>, flags=3)
                       at willuslib/pdfwrite.c:1147
1147        fseek(pdf->f,0L,1);
(gdb) p pdf->f
$1 = (FILE *) 0x0
(gdb)
```

**Comment by ajay9634** [comment]
I don't understand, but that error still present

**Comment by ajay9634** [comment]
I don't understand, but that error still present my device is poko M2 pro (Android 11)

**Comment by xtkoba** [comment]
PR #11985 (enabling MuPDF support) may be what is really requested here.
