### ISSUE TITLE
[Package]: error in installing scikit-image

### ISSUE THREAD

**Issue by eldon97** [termux/termux-packages#11190]
### Package description

i want to install scikit-image in termux but this following error is occurred.

----------------------------------------------------------------------------------------------------
````
$ pip install scikit-image                                                                          Collecting scikit-image                             Downloading scikit-image-0.19.3.tar.gz (22.2 MB)     ━━━━━━━━━━ 22.2/22.2   899.4 kB/s eta 0:00:00
                MB                                  Installing build dependencies ... done
  Getting requirements to build wheel ... error     error: subprocess-exited-with-error
                                                    × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [54 lines of output]
      Traceback (most recent call last):
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-9grdn7gb/overlay/lib/python3.10/site-packages/numpy/core/__init__.py", line 22, in <module>
          from . import multiarray                        File "/data/data/com.termux/files/usr/tmp/pip-build-env-9grdn7gb/overlay/lib/python3.10/site-packages/numpy/core/multiarray.py", line 12, in <module>                                                     from . import overrides                         File "/data/data/com.termux/files/usr/tmp/pip-build-env-9grdn7gb/overlay/lib/python3.10/site-packages/numpy/core/overrides.py", line 7, in <module>
          from numpy.core._multiarray_umath import (
      ImportError: dlopen failed: library "libgfortran.so.5" not found
                                                        During handling of the above exception, another exception occurred:                           
      Traceback (most recent call last):                  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
          main()                                          File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 130, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-9grdn7gb/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 162, in get_requires_for_build_wheel
          return self._get_build_requires(
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-9grdn7gb/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 143, in _get_build_requires                                         self.run_setup()
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-9grdn7gb/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 267, in run_setup
          super(_BuildMetaLegacyBackend,
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-9grdn7gb/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 158, in run_setup
          exec(compile(code, __file__, 'exec'), locals())
        File "setup.py", line 9, in <module>
          from numpy.distutils.command.build_ext import build_ext as npy_build_ext
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-9grdn7gb/overlay/lib/python3.10/site-packages/numpy/__init__.py", line 150, in <module>                                                           from . import core                              File "/data/data/com.termux/files/usr/tmp/pip-build-env-9grdn7gb/overlay/lib/python3.10/site-packages/numpy/core/__init__.py", line 48, in <module>                                                       raise ImportError(msg)
      ImportError:                                
      IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!                            
      Importing the numpy C-extensions failed. This error can happen for
      many reasons, often due to issues with your setup or how NumPy was                                  installed.                                                                                          We have compiled some common reasons and troubleshooting tips at:                             
          https://numpy.org/devdocs/user/troubleshooting-importerror.html
                                                        Please note and check the following:

        * The Python version is: Python3.10 from "/data/data/com.termux/files/usr/bin/python3"
        * The NumPy version is: "1.21.4"

      and make sure that they are the versions you expect.
      Please carefully study the documentation linked above for further help.                       
      Original error was: dlopen failed: library "libgfortran.so.5" not found                       
      [end of output]                                                                                 note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.                                     │ exit code: 1
╰─> See above for output.
                                                  note: This error originates from a subprocess, and is likely not a problem with pip.
WARNING: You are using pip version 22.0.4; however, version 22.1.2 is available.
You should consider upgrading via the '/data/data/com.termux/files/usr/bin/python3 -m pip install --upgrade pip' command.
````
----------------------------------------------------------------------------------------------------

is there something i can do to solve this? or request for another package for scikit-image like another python library e.g. scipy that i can install through pkg. thank you

### Source code URL

https://scikit-image.org/

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

**Comment by zairullahdev** [comment]
Try installing fortran by

```
apt install lfortran
```

**Comment by eldon97** [comment]
> Try installing fortran by
> 
> ```
> apt install lfortran
> ```

Already installed it but it stills doesn’t work. The same error still occurred

**Comment by xtkoba** [comment]
Seems like a wrong binary package of NumPy is used, in which a C extension is linked against `libgfortran.so.5`, which should not happen when NumPy is built from source on device with our official toolchain. I don't know in detail though.

FYI SciPy has a separate package request #471.

**Comment by lucas-ildefonso** [comment]
I am getting an error too. Any help?

**Comment by xtkoba** [comment]
I would suggest `--no-binary :all:` option for `pip`. Occasionally seems to pull in binary packages built for GNU/Linux.

**Comment by xtkoba** [comment]
I'm pretty sure this is an issue of some third-party `numpy` package, which we are not in charge of.
