### ISSUE TITLE
Gevent Install Failure. Issue #283 fix does not help

### ISSUE THREAD

**Issue by kedestin** [termux/termux-packages#1153]
I've been trying to install gevent in termux, but I keep getting an error saying that one of the of commands could not be run. My problem is similar to the one from issue #283 but the proposed solution does not seem to help (see code below).

```
$ pip install gevent
Collecting gevent
  Using cached gevent-1.2.2.tar.gz
Requirement already satisfied: greenlet>=0.4.10 in /data/data/com.termux/files/usr/lib/python3.6/site-packages (from gevent)
Installing collected packages: gevent
  Running setup.py install for gevent ... error
    Complete output from command /data/data/com.termux/files/usr/bin/python -u -c "import setuptools, tokenize;__file__='/data/data/com.termux/files/usr/tmp/pip-build-g2dr83ia/gevent/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /data/data/com.termux/files/usr/tmp/pip-0drzxwcq-record/install-record.txt --single-version-externally-managed --compile:
    /data/data/com.termux/files/usr/lib/python3.6/distutils/dist.py:261: UserWarning: Unknown distribution option: 'cffi_modules'
      warnings.warn(msg)
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-aarch64-3.6
    creating build/lib.linux-aarch64-3.6/gevent
    copying src/gevent/__init__.py -> build/lib.linux-aarch64-3.6/gevent
    copying src/gevent/_compat.py -> build/lib.linux-aarch64-3.6/gevent
    copying src/gevent/_fileobjectcommon.py -> build/lib.linux-aarch64-3.6/gevent
    copying src/gevent/_fileobjectposix.py -> build/lib.linux-aarch64-3.6/gevent
    copying src/gevent/_semaphore.py -> build/lib.linux-aarch64-3.6/gevent
    copying src/gevent/_socket2.py -> build/lib.linux-aarch64-3.6/gevent
    copying src/gevent/_socket3.py -> build/lib.linux-aarch64-3.6/gevent
    copying src/gevent/_socketcommon.py -> build/lib.linux-aarch64-3.6/gevent
    copying src/gevent/_ssl2.py -> build/lib.linux-aarch64-3.6/gevent
    copying src/gevent/_ssl3.py -> build/lib.linux-aarch64-3.6/gevent
    copying src/gevent/_sslgte279.py -> build/lib.linux-aarch64-3.6/gevent
    copying src/gevent/_tblib.py -> build/lib.linux-aarch64-3.6/gevent
    copying src/gevent/_threading.py -> build/lib.linux-aarch64-3.6/gevent
    copying src/gevent/_util.py -> build/lib.linux-aarch64-3.6/gevent
    copying src/gevent/_util_py2.py -> build/lib.linux-aarch64-3.6/gevent
    copying src/gevent/backdoor.py -> build/lib.linux-aarch64-3.6/gevent
    copying src/gevent/baseserver.py -> build/lib.linux-aarch64-3.6/gevent
    copying src/gevent/builtins.py -> build/lib.linux-aarch64-3.6/gevent
    copying src/gevent/core.py -> build/lib.linux-aarch64-3.6/gevent
    copying src/gevent/event.py -> build/lib.linux-aarch64-3.6/gevent
    copying src/gevent/fileobject.py -> build/lib.linux-aarch64-3.6/gevent
    copying src/gevent/greenlet.py -> build/lib.linux-aarch64-3.6/gevent
    copying src/gevent/hub.py -> build/lib.linux-aarch64-3.6/gevent
    copying src/gevent/local.py -> build/lib.linux-aarch64-3.6/gevent
    copying src/gevent/lock.py -> build/lib.linux-aarch64-3.6/gevent
    copying src/gevent/monkey.py -> build/lib.linux-aarch64-3.6/gevent
    copying src/gevent/os.py -> build/lib.linux-aarch64-3.6/gevent
    copying src/gevent/pool.py -> build/lib.linux-aarch64-3.6/gevent
    copying src/gevent/pywsgi.py -> build/lib.linux-aarch64-3.6/gevent
    copying src/gevent/queue.py -> build/lib.linux-aarch64-3.6/gevent
    copying src/gevent/resolver_ares.py -> build/lib.linux-aarch64-3.6/gevent
    copying src/gevent/resolver_thread.py -> build/lib.linux-aarch64-3.6/gevent
    copying src/gevent/select.py -> build/lib.linux-aarch64-3.6/gevent
    copying src/gevent/server.py -> build/lib.linux-aarch64-3.6/gevent
    copying src/gevent/signal.py -> build/lib.linux-aarch64-3.6/gevent
    copying src/gevent/socket.py -> build/lib.linux-aarch64-3.6/gevent
    copying src/gevent/ssl.py -> build/lib.linux-aarch64-3.6/gevent
    copying src/gevent/subprocess.py -> build/lib.linux-aarch64-3.6/gevent
    copying src/gevent/thread.py -> build/lib.linux-aarch64-3.6/gevent
    copying src/gevent/threading.py -> build/lib.linux-aarch64-3.6/gevent
    copying src/gevent/threadpool.py -> build/lib.linux-aarch64-3.6/gevent
    copying src/gevent/timeout.py -> build/lib.linux-aarch64-3.6/gevent
    copying src/gevent/util.py -> build/lib.linux-aarch64-3.6/gevent
    copying src/gevent/win32util.py -> build/lib.linux-aarch64-3.6/gevent
    copying src/gevent/wsgi.py -> build/lib.linux-aarch64-3.6/gevent
    creating build/lib.linux-aarch64-3.6/gevent/libev
    copying src/gevent/libev/__init__.py -> build/lib.linux-aarch64-3.6/gevent/libev
    copying src/gevent/libev/_corecffi_build.py -> build/lib.linux-aarch64-3.6/gevent/libev
    copying src/gevent/libev/corecffi.py -> build/lib.linux-aarch64-3.6/gevent/libev
    running egg_info
    writing src/gevent.egg-info/PKG-INFO
    writing dependency_links to src/gevent.egg-info/dependency_links.txt
    writing requirements to src/gevent.egg-info/requires.txt
    writing top-level names to src/gevent.egg-info/top_level.txt
    warning: manifest_maker: standard file '-c' not found

    reading manifest file 'src/gevent.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no files found matching 'changelog.rst'
    warning: no files found matching 'known_failures.py'
    warning: no files found matching '.pep8'
    no previously-included directories found matching '*/__pycache__'
    warning: no previously-included files matching '*.so' found anywhere in distribution
    warning: no previously-included files matching '*.o' found anywhere in distribution
    warning: no previously-included files matching '*.lo' found anywhere in distribution
    warning: no previously-included files matching '*.la' found anywhere in distribution
    warning: no previously-included files matching 'config.log' found anywhere in distribution
    warning: no previously-included files matching 'config.status' found anywhere in distribution
    no previously-included directories found matching 'doc/_build'
    warning: no previously-included files matching '*.pyc' found anywhere in distribution
    warning: no previously-included files matching '.coverage' found under directory 'src/greentest'
    no previously-included directories found matching 'src/greentest/htmlcov'
    warning: no previously-included files matching 'stamp-h?' found under directory 'deps/c-ares'
    warning: no previously-included files matching 'ares_build.h.orig' found under directory 'deps/c-ares'
    no previously-included directories found matching 'deps/libev/.deps'
    warning: no previously-included files matching 'Makefile' found under directory 'deps/libev'
    warning: no previously-included files matching 'libtool' found under directory 'deps/libev'
    warning: no previously-included files matching 'stamp-h?' found under directory 'deps/libev'
    warning: no previously-included files matching 'config.h' found under directory 'deps/libev'
    warning: no previously-included files matching '_corecffi.c' found under directory 'src/gevent'
    warning: no previously-included files found matching 'Makefile'
    warning: no previously-included files found matching 'configure-output'
    writing manifest file 'src/gevent.egg-info/SOURCES.txt'
    copying src/gevent/_semaphore.pxd -> build/lib.linux-aarch64-3.6/gevent
    copying src/gevent/ares.pyx -> build/lib.linux-aarch64-3.6/gevent
    copying src/gevent/cares.pxd -> build/lib.linux-aarch64-3.6/gevent
    copying src/gevent/cares_ntop.h -> build/lib.linux-aarch64-3.6/gevent
    copying src/gevent/cares_pton.h -> build/lib.linux-aarch64-3.6/gevent
    copying src/gevent/dnshelper.c -> build/lib.linux-aarch64-3.6/gevent
    copying src/gevent/gevent._semaphore.c -> build/lib.linux-aarch64-3.6/gevent
    copying src/gevent/gevent.ares.c -> build/lib.linux-aarch64-3.6/gevent
    copying src/gevent/gevent.ares.h -> build/lib.linux-aarch64-3.6/gevent
    copying src/gevent/python.pxd -> build/lib.linux-aarch64-3.6/gevent
    copying src/gevent/libev/_corecffi_cdef.c -> build/lib.linux-aarch64-3.6/gevent/libev
    copying src/gevent/libev/_corecffi_source.c -> build/lib.linux-aarch64-3.6/gevent/libev
    copying src/gevent/libev/callbacks.c -> build/lib.linux-aarch64-3.6/gevent/libev
    copying src/gevent/libev/callbacks.h -> build/lib.linux-aarch64-3.6/gevent/libev
    copying src/gevent/libev/corecext.ppyx -> build/lib.linux-aarch64-3.6/gevent/libev
    copying src/gevent/libev/corecext.pyx -> build/lib.linux-aarch64-3.6/gevent/libev
    copying src/gevent/libev/gevent.corecext.c -> build/lib.linux-aarch64-3.6/gevent/libev
    copying src/gevent/libev/libev.h -> build/lib.linux-aarch64-3.6/gevent/libev
    copying src/gevent/libev/libev.pxd -> build/lib.linux-aarch64-3.6/gevent/libev
    copying src/gevent/libev/libev_vfd.h -> build/lib.linux-aarch64-3.6/gevent/libev
    copying src/gevent/libev/stathelper.c -> build/lib.linux-aarch64-3.6/gevent/libev
    running build_ext
    Running '(cd  "/data/data/com.termux/files/usr/tmp/pip-build-g2dr83ia/gevent/deps/libev"  && sh ./configure   && cp config.h "$OLDPWD" ) > configure-output.txt' in /data/data/com.termux/files/usr/tmp/pip-build-g2dr83ia/gevent/build/temp.linux-aarch64-3.6/libev
    ./configure: 1: eval: /bin/sh: not found
    configure: WARNING: 'missing' script is too old or missing
    configure: error: cannot run /bin/sh ./config.sub
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/data/data/com.termux/files/usr/tmp/pip-build-g2dr83ia/gevent/setup.py", line 183, in <module>
        run_setup(EXT_MODULES, run_make=_BUILDING)
      File "/data/data/com.termux/files/usr/tmp/pip-build-g2dr83ia/gevent/setup.py", line 168, in run_setup
        "Development Status :: 4 - Beta"
      File "/data/data/com.termux/files/usr/lib/python3.6/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/data/data/com.termux/files/usr/lib/python3.6/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/data/data/com.termux/files/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/data/data/com.termux/files/usr/lib/python3.6/distutils/command/install.py", line 545, in run
        self.run_command('build')
      File "/data/data/com.termux/files/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/data/data/com.termux/files/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/data/data/com.termux/files/usr/lib/python3.6/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/data/data/com.termux/files/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/data/data/com.termux/files/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/setuptools/command/build_ext.py", line 75, in run
        _build_ext.run(self)
      File "/data/data/com.termux/files/usr/lib/python3.6/distutils/command/build_ext.py", line 339, in run
        self.build_extensions()
      File "/data/data/com.termux/files/usr/lib/python3.6/distutils/command/build_ext.py", line 448, in build_extensions
        self._build_extensions_serial()
      File "/data/data/com.termux/files/usr/lib/python3.6/distutils/command/build_ext.py", line 473, in _build_extensions_serial
        self.build_extension(ext)
      File "/data/data/com.termux/files/usr/tmp/pip-build-g2dr83ia/gevent/_setuputils.py", line 159, in build_extension
        self.gevent_prepare(ext)
      File "/data/data/com.termux/files/usr/tmp/pip-build-g2dr83ia/gevent/_setuputils.py", line 156, in gevent_prepare
        configure(self, ext)
      File "/data/data/com.termux/files/usr/tmp/pip-build-g2dr83ia/gevent/_setuplibev.py", line 55, in configure_libev
        system(libev_configure_command)
      File "/data/data/com.termux/files/usr/tmp/pip-build-g2dr83ia/gevent/_setuputils.py", line 139, in system
        if _system(cmd):
      File "/data/data/com.termux/files/usr/tmp/pip-build-g2dr83ia/gevent/_setuputils.py", line 135, in _system
        return check_call(cmd, shell=True)
      File "/data/data/com.termux/files/usr/lib/python3.6/subprocess.py", line 291, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '(cd  "/data/data/com.termux/files/usr/tmp/pip-build-g2dr83ia/gevent/deps/libev"  && sh ./configure   && cp config.h "$OLDPWD" ) > configure-output.txt' returned non-zero exit status 127.

    ----------------------------------------
Command "/data/data/com.termux/files/usr/bin/python -u -c "import setuptools, tokenize;__file__='/data/data/com.termux/files/usr/tmp/pip-build-g2dr83ia/gevent/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /data/data/com.termux/files/usr/tmp/pip-0drzxwcq-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /data/data/com.termux/files/usr/tmp/pip-build-g2dr83ia/gevent/
$ apt install make libev-dev c-ares-dev gcc python-dev
Reading package lists... Done
Building dependency tree
Reading state information... Done
Package gcc is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  libllvm

E: Package 'gcc' has no installation candidate
$ EMBED=0 pip install gevent
Collecting gevent
  Using cached gevent-1.2.2.tar.gz
Requirement already satisfied: greenlet>=0.4.10 in /data/data/com.termux/files/usr/lib/python3.6/site-packages (from gevent)
Installing collected packages: gevent
  Running setup.py install for gevent ... error
    Complete output from command /data/data/com.termux/files/usr/bin/python -u -c "import setuptools, tokenize;__file__='/data/data/com.termux/files/usr/tmp/pip-build-rtqt5xgj/gevent/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /data/data/com.termux/files/usr/tmp/pip-me2nffdn-record/install-record.txt --single-version-externally-managed --compile:
    Running '(cd  "/data/data/com.termux/files/usr/tmp/pip-build-rtqt5xgj/gevent/deps/libev"  && sh ./configure   && cp config.h "$OLDPWD" ) > configure-output.txt' in /data/data/com.termux/files/usr/tmp/pip-build-rtqt5xgj/gevent
    ./configure: 1: eval: /bin/sh: not found
    configure: WARNING: 'missing' script is too old or missing
    configure: error: cannot run /bin/sh ./config.sub
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/data/data/com.termux/files/usr/tmp/pip-build-rtqt5xgj/gevent/setup.py", line 183, in <module>
        run_setup(EXT_MODULES, run_make=_BUILDING)
      File "/data/data/com.termux/files/usr/tmp/pip-build-rtqt5xgj/gevent/setup.py", line 125, in run_setup
        system(libev_configure_command)
      File "/data/data/com.termux/files/usr/tmp/pip-build-rtqt5xgj/gevent/_setuputils.py", line 139, in system
        if _system(cmd):
      File "/data/data/com.termux/files/usr/tmp/pip-build-rtqt5xgj/gevent/_setuputils.py", line 135, in _system
        return check_call(cmd, shell=True)
      File "/data/data/com.termux/files/usr/lib/python3.6/subprocess.py", line 291, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '(cd  "/data/data/com.termux/files/usr/tmp/pip-build-rtqt5xgj/gevent/deps/libev"  && sh ./configure   && cp config.h "$OLDPWD" ) > configure-output.txt' returned non-zero exit status 127.

    ----------------------------------------
Command "/data/data/com.termux/files/usr/bin/python -u -c "import setuptools, tokenize;__file__='/data/data/com.termux/files/usr/tmp/pip-build-rtqt5xgj/gevent/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /data/data/com.termux/files/usr/tmp/pip-me2nffdn-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /data/data/com.termux/files/usr/tmp/pip-build-rtqt5xgj/gevent/
$

```

**Comment by kedestin** [comment]
I believe I've figured out the issue. Pip is trying to import the setup file for gevent from '/data/data/com.termux/files/usr/tmp/pip-build-rtqt5xgj/gevent/setup.py', but that file doesn't exist because the 'tmp' directory is empty.

Any ideas are welcome

**Comment by kedestin** [comment]
I found the solution from termux/termux-app#104

Running the following commands allowed me to successfully install gevent

```
mkdir /data/data/com.termux/files/tmp
export BIN_SH=/system/bin/sh
export TMPDIR=/data/data/com.termux/files/tmp
export TMP=$TMPDIR
export TEMP=$TMPDIR
CONFIG_SHELL=/system/bin/sh

```
