### ISSUE TITLE
[Bug]: python-numpy doesn't work

### ISSUE THREAD

**Issue by licy183** [termux/termux-packages#11870]
### Problem description

`numpy` doesn't work since `1.23.0`, probably because of the wrong `EXT_SUFFIX`. But I have really no idea why this happens.

```
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/numpy-1.23.3-py3.10-linux-i686.egg/numpy/core/__init__.py", line 23, in <module>
    from . import multiarray
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/numpy-1.23.3-py3.10-linux-i686.egg/numpy/core/multiarray.py", line 10, in <module>
    from . import overrides
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/numpy-1.23.3-py3.10-linux-i686.egg/numpy/core/overrides.py", line 6, in <module>
    from numpy.core._multiarray_umath import (
ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/numpy-1.23.3-py3.10-linux-i686.egg/numpy/__init__.py", line 140, in <module>
    from . import core
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/numpy-1.23.3-py3.10-linux-i686.egg/numpy/core/__init__.py", line 49, in <module>
    raise ImportError(msg)
ImportError:

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.10 from "/data/data/com.termux/files/usr/bin/python"
  * The NumPy version is: "1.23.3"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: No module named 'numpy.core._multiarray_umath'
```

After I rename some `.so` from `*.cpython-310-i686-linux-android.so` to `*.cpython-310.so`, the errors disappear.

### What steps will reproduce the bug?

```
pkg i python-numpy
python -c "import numpy"
```

### What is the expected behavior?

Numpy is loaded successfully.

### System information

termux-info:

```
Termux Variables:
TERMUX_APK_RELEASE=GITHUB
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=2775
TERMUX_IS_DEBUGGABLE_BUILD=1
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
Packages CPU architecture:
i686
Subscribed repositories:
# sources.list
deb https://mirrors.ustc.edu.cn/termux/apt/termux-main stable main
# tur-repo (sources.list.d/tur.list)
deb https://tur.kcubeterm.com tur-packages tur tur-on-device
Updatable packages:
All packages up to date
termux-tools version:
1.29.2
Android version:
7.1.1
Kernel build information:
Linux localhost 4.14.67-android #1 SMP Tue Apr 12 02:28:36 IST 2022 i686 Android
Device manufacturer:
OnePlus
Device model:
ONEPLUS A3010
```

**Comment by Grimler91** [comment]
Works fine on arm and aarch64, so perhaps i686 (or i686+x86_64) specific

**Comment by licy183** [comment]
It seems doesn't work on my aarch64/arm device either...

```
> python -c "import numpy"
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/numpy-1.23.3-py3.10-linux-aarch64.egg/numpy/core/__init__.py", line 23, in <module>
    from . import multiarray
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/numpy-1.23.3-py3.10-linux-aarch64.egg/numpy/core/multiarray.py", line 10, in <module>
    from . import overrides
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/numpy-1.23.3-py3.10-linux-aarch64.egg/numpy/core/overrides.py", line 6, in <module>
    from numpy.core._multiarray_umath import (
ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/numpy-1.23.3-py3.10-linux-aarch64.egg/numpy/__init__.py", line 140, in <module>
    from . import core
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/numpy-1.23.3-py3.10-linux-aarch64.egg/numpy/core/__init__.py", line 49, in <module>
    raise ImportError(msg)
ImportError:

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.10 from "/data/data/com.termux/files/usr/bin/python"
  * The NumPy version is: "1.23.3"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: No module named 'numpy.core._multiarray_umath'

> termux-info
Termux Variables:
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.117
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://packages-cf.termux.dev/apt/termux-main stable main
# tur-repo (sources.list.d/tur.list)
deb https://tur.kcubeterm.com tur-packages tur tur-on-device
Updatable packages:
All packages up to date
termux-tools version:
1.29.2
Android version:
12
Kernel build information:
Linux localhost 5.4.147-qgki-g4ae49e8272b4 #1 SMP PREEMPT Thu Jul 28 01:15:51 CST 2022 f2fs-hash:9f5701dafc aarch64 Android
Device manufacturer:
Xiaomi
Device model:
2106118C
```

```
~ $ python -c "import numpy"
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/numpy-1.23.3-py3.10-linux-arm.egg/numpy/core/__init__.py", line 23, in <module>
    from . import multiarray
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/numpy-1.23.3-py3.10-linux-arm.egg/numpy/core/multiarray.py", line 10, in <module>
    from . import overrides
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/numpy-1.23.3-py3.10-linux-arm.egg/numpy/core/overrides.py", line 6, in <module>
    from numpy.core._multiarray_umath import (
ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/numpy-1.23.3-py3.10-linux-arm.egg/numpy/__init__.py", line 140, in <module>
    from . import core
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/numpy-1.23.3-py3.10-linux-arm.egg/numpy/core/__init__.py", line 49, in <module>
    raise ImportError(msg)
ImportError:

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.10 from "/data/data/com.termux/files/usr/bin/python"
  * The NumPy version is: "1.23.3"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: No module named 'numpy.core._multiarray_umath'

~ $ termux-info
Termux Variables:
TERMUX_APK_RELEASE=GITHUB
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=9040
TERMUX_IS_DEBUGGABLE_BUILD=1
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
Packages CPU architecture:
arm
Subscribed repositories:
# sources.list
deb https://packages-cf.termux.dev/apt/termux-main stable main
Updatable packages:
All packages up to date
termux-tools version:
1.29.2
Android version:
10
Kernel build information:
Linux localhost 4.9.186-perf-g10af704 #1 SMP PREEMPT Wed Jul 7 13:06:12 CST 2021 armv8l Android
Device manufacturer:
Xiaomi
Device model:
MIX 2S
```

**Comment by licy183** [comment]
> Fixed?

It is fixed by 11890. But I'd like to open this issue until the cause of wrong `ext_suffix` is found out.
