### ISSUE TITLE
[Bug]: python-wsgidav doesn't work 

### ISSUE THREAD

**Issue by gphg** [termux/termux-packages#11936]
### Problem description

`wsgidav` doesn't work and I have no idea what happened. It happened after I updated the packages, and `pip` packages too, I recall. This is the error messages:
```
Running without configuration file.
18:16:39.177 - WARNING : App wsgidav.mw.cors.Cors(None).is_disabled() returned True: skipping.
18:16:39.197 - INFO    : WsgiDAV/4.0.2 Python/3.10.7 Linux-4.9.190-aarch64-with-libc
18:16:39.197 - INFO    : Lock manager:      LockManager(LockStorageDict)
18:16:39.198 - INFO    : Property manager:  None
18:16:39.198 - INFO    : Domain controller: SimpleDomainController()
18:16:39.199 - INFO    : Registered DAV providers by route:
18:16:39.200 - INFO    :   - '/:dir_browser': FilesystemProvider for path '/data/data/com.termux/files/usr/lib/python3.10/site-packages/wsgidav/dir_browser/htdocs' (Read-Only) (anonymous)
18:16:39.201 - INFO    :   - '/': FilesystemProvider for path '/data/data/com.termux/files/usr/tmp' (Read-Write) (anonymous)
18:16:39.201 - WARNING : Basic authentication is enabled: It is highly recommended to enable SSL.
18:16:39.202 - WARNING : Share '/' will allow anonymous write access.
18:16:39.203 - WARNING : Share '/:dir_browser' will allow anonymous read access.
18:16:39.855 - ERROR   : Could not import Cheroot (https://cheroot.cherrypy.dev/).
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/wsgidav/server/server_cli.py", line 433, in _run_cheroot
    from cheroot import server, wsgi
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/cheroot/server.py", line 89, in <module>
    import six
ModuleNotFoundError: No module named 'six'
18:16:39.860 - ERROR   : Try `pip install cheroot`.
```
The errors shows module `six` is not found and `cheroot` have to be installed, but It's installed.

### What steps will reproduce the bug?

```
python -m pip install --upgrade wsgidav cheroot
wsgidav --auth=anonymous -r $PREFIX/tmp
```

### What is the expected behavior?

WsgiDAV is running normally.

### System information

termux-info:

```
Termux Variables:
TERMUX_API_VERSION=0.50.1
TERMUX_APK_RELEASE=F_DROID
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=31726
TERMUX_IS_DEBUGGABLE_BUILD=0
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://mirrors.sahilister.in/termux/termux-main stable main
Updatable packages:
All packages up to date
termux-tools version:
1.29.2
Android version:
10
Kernel build information:
Linux localhost 4.9.190 #1 SMP PREEMPT Wed Oct 14 15:47:23 CST 2020 aarch64 Android
Device manufacturer:
ELEVATE
Device model:
LUNA G5
```

**Comment by gphg** [comment]
The problem is on `six` module.
```
$ python -c "import six"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'six'
```
I had to reinstall it then it works just fine.
```
pip uninstall six
pip install six
```
