### ISSUE TITLE
Can't Install Scikit Learn 

### ISSUE THREAD

**Issue by lucas-ildefonso** [termux/termux-packages#12430]
### Problem description

Tried to install Scikit Learn via pip and got a error.

### What steps will reproduce the bug?

pip install scikit-learn

### What is the expected behavior?

Successful installment 

### System information

termux-info:

```
~/sklearn-venv $ pip install scikit-learn                  Collecting scikit-learn
  Using cached scikit-learn-1.1.2.tar.gz (7.0 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [47 lines of output]
      Partial import of sklearn during the build process.
      Traceback (most recent call last):
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-t3qdghdp/overlay/lib/python3.10/site-packages/scipy/__init__.py", line 166, in <module>
          from scipy._lib._ccallback import LowLevelCallable
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-t3qdghdp/overlay/lib/python3.10/site-packages/scipy/_lib/_ccallback.py", line 1, in <module>
          from . import _ccallback_c
      ImportError: dlopen failed: cannot locate symbol "PyExc_ImportError" referenced by "/data/data/com.termux/files/usr/tmp/pip-build-env-t3qdghdp/overlay/lib/python3.10/site-packages/scipy/_lib/_ccallback_c.cpython-310.so"...

      The above exception was the direct cause of the following exception:

      Traceback (most recent call last):
        File "setup.py", line 200, in check_package_status
          module = importlib.import_module(package)
        File "/data/data/com.termux/files/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
          return _bootstrap._gcd_import(name[level:], package, level)
        File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
        File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
        File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
        File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
        File "<frozen importlib._bootstrap_external>", line 883, in exec_module
        File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-t3qdghdp/overlay/lib/python3.10/site-packages/scipy/__init__.py", line 171, in <module>
          raise ImportError(msg) from e
      ImportError: The `scipy` install you are using seems to be broken, (extension modules cannot be imported), please try reinstalling.
      Traceback (most recent call last):
        File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 351, in <module>
          main()
        File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 333, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 152, in prepare_metadata_for_build_wheel
          return hook(metadata_directory, config_settings)
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-t3qdghdp/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 174, in prepare_metadata_for_build_wheel
          self.run_setup()
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-t3qdghdp/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 267, in run_setup
          super(_BuildMetaLegacyBackend,
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-t3qdghdp/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 158, in run_setup
          exec(compile(code, __file__, 'exec'), locals())
        File "setup.py", line 329, in <module>
          setup_package()
        File "setup.py", line 305, in setup_package
          check_package_status("scipy", min_deps.SCIPY_MIN_VERSION)
        File "setup.py", line 227, in check_package_status
          raise ImportError(
      ImportError: scipy is not installed.
      scikit-learn requires scipy >= 1.3.2.
      Installation instructions are available on the scikit-learn website: http://scikit-learn.org/stable/install.html

      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by lucas-ildefonso** [comment]
A user on Reddit give the advice to reinstall Python-scipy with previous uninstalling python-numpy. After that, I used the following command to clean cache e install :

pip cache purge && pip install scikit-lean --no-build-isolation

The installation was a success.

**Comment by trolzen** [comment]
@lucas-ildefonso Hi! How did you manage to pass the "Installing build dependencies" step? I'm stuck on it, can't pass because it can't build the `ninja` pip-package, which would be used in building the `scikit-learn` later. Maybe you have installed some additional pip- or apt-packages?

In my case the `scikit-learn-1.1.2.tar.gz` is being installed and the versions are: pip 22.3, python 3.11.

**Comment by xtkoba** [comment]
In the build log, this part:

```
ImportError: dlopen failed: cannot locate symbol "PyExc_ImportError" referenced by "/data/data/com.termux/files/usr/tmp/pip-build-env-t3qdghdp/overlay/lib/python3.10/site-packages/scipy/_lib/_ccallback_c.cpython-310.so"...
```

seems to be due to notorious android/ndk#201. `export LDFLAGS+=" -lpython3.11"` (or any other appropriate Python version than `3.11`) may fix this.

**Comment by xtkoba** [comment]
There are some workarounds for `pip` trying to "build everything", including dependencies that are already installed. We see a bunch of cases where `pip install` fails due to `cmake` not being able to build. (Note that Termux by default installs `cmake` together with `python` due to `TERMUX_PKG_RECOMMENDS`.)

One is to use option `--no-use-pep517`. As suggested above, another would be `--no-build-isolation`. There may be others that I do not know.

**Comment by xtkoba** [comment]
I assume this is already resolved, or at most just a matter of documentation.

**Comment by xtkoba** [comment]
Closing as answered.
