### ISSUE TITLE
Issues with installing nodejs

### ISSUE THREAD

**Issue by Rehan587** [termux/termux-packages#12505]
Im trying to install nodejs but im getting the following error:

```
Reading package lists... Done
Building dependency tree... Done                                            Reading state information... Done
nodejs is already the newest version (18.10.0).
nodejs set to manually installed.
The following packages were automatically installed and are no longer required:
  imagemagick libde265 libheif libjxl                                       Use 'apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
1 not fully installed or removed.
After this operation, 0 B of additional disk space will be used.
Do you want to continue? [Y/n] y
Setting up nodejs (18.10.0) ...
/data/data/com.termux/files/usr/lib/node_modules/npm/node_modules/socks-proxy-agent/dist/index.js:110
class SocksProxyAgent extends agent_base_1.Agent {
                                           ^

TypeError: Class extends value undefined is not a constructor or null
    at Object.<anonymous> (/data/data/com.termux/files/usr/lib/node_modules/npm/node_modules/socks-proxy-agent/dist/index.js:110:44)
    at Module._compile (node:internal/modules/cjs/loader:1149:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1203:10)
    at Module.load (node:internal/modules/cjs/loader:1027:32)
    at Module._load (node:internal/modules/cjs/loader:868:12)
    at Module.require (node:internal/modules/cjs/loader:1051:19)                at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/data/data/com.termux/files/usr/lib/node_modules/npm/node_modules/make-fetch-happen/lib/agent.js:174:29)
    at Module._compile (node:internal/modules/cjs/loader:1149:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1203:10)
    at Module.load (node:internal/modules/cjs/loader:1027:32)
    at Module._load (node:internal/modules/cjs/loader:868:12)
    at Module.require (node:internal/modules/cjs/loader:1051:19)                at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/data/data/com.termux/files/usr/lib/node_modules/npm/node_modules/make-fetch-happen/lib/remote.js:7:18)
    at Module._compile (node:internal/modules/cjs/loader:1149:14)

Node.js v18.10.0
dpkg: error processing package nodejs (--configure):
 installed nodejs package post-installation script subprocess returned error exit status 1
Errors were encountered while processing:
 nodejs
E: Sub-process /data/data/com.termux/files/usr/bin/dpkg returned an error code (1)
```

Pls help

**Comment by thunder-coding** [comment]
Try 

```
rm -rf $PREFIX/lib/node_modules && apt install nodejs --reinstall
``

**Comment by 2096779623** [comment]
```bash
pkg rem nodejs -y
rm -rf $PREFIX/lib/node_modules/
pkg i nodejs -y
```

**Comment by Rehan587** [comment]
> ```bash
> pkg rem nodejs -y
> rm -rf $PREFIX/lib/node_modules/
> pkg i nodejs -y
> ```

Thank you so much it worked 🥲

**Comment by 2096779623** [comment]
Thanks both :) .

**Comment by thunder-coding** [comment]
And in order to prevent such errors in future, refrain from upgrading npm manually. i.e. **ignore** those messages asking you to **execute `npm install -g npm@<new-ver>` to upgrade**
