### ISSUE TITLE
[Bug]: pip install numpy

### ISSUE THREAD

**Issue by RandomGamer368** [termux/termux-packages#12943]
### Problem description

When i try to install numpy it gives some error.  first, it takes like 1 minute to respond. I am new to termux and i have installed python using `apt install python`
this is the transcript
```
Welcome to Termux!

Wiki:            https://wiki.termux.com
Community forum: https://termux.com/community
Gitter chat:     https://gitter.im/termux/termux
IRC channel:     #termux on freenode

Working with packages:

 * Search packages:   pkg search <query>
 * Install a package: pkg install <package>
 * Upgrade packages:  pkg upgrade

Subscribing to additional repositories:

 * Root:     pkg install root-repo
 * Unstable: pkg install unstable-repo
 * X11:      pkg install x11-repo

Report issues at https://termux.com/issues

$ pip install numpy
Collecting numpy
  Using cached numpy-1.23.4.tar.gz (10.7 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: numpy
  Building wheel for numpy (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for numpy (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [258 lines of output]
      Running from numpy source directory.
      setup.py:86: DeprecationWarning:

        `numpy.distutils` is deprecated since NumPy 1.23.0, as a result
        of the deprecation of `distutils` itself. It will be removed for
        Python >= 3.12. For older Python versions it will remain present.
        It is recommended to use `setuptools < 60.0` for those Python versions.
        For more details, see:
          https://numpy.org/devdocs/reference/distutils_status_migration.html


        import numpy.distutils.command.sdist
      Processing numpy/random/_bounded_integers.pxd.in
      Processing numpy/random/mtrand.pyx
      Processing numpy/random/_philox.pyx
      Processing numpy/random/_common.pyx
      Processing numpy/random/_sfc64.pyx
      Processing numpy/random/bit_generator.pyx
      Processing numpy/random/_generator.pyx
      Processing numpy/random/_mt19937.pyx
      Processing numpy/random/_bounded_integers.pyx.in
      Processing numpy/random/_pcg64.pyx
      Cythonizing sources
      INFO: blas_opt_info:
      INFO: blas_armpl_info:
      INFO: customize UnixCCompiler
      INFO:   libraries armpl_lp64_mp not found in ['/data/data/com.termux/files/usr/lib']
      INFO:   NOT AVAILABLE
      INFO:
      INFO: blas_mkl_info:
      INFO:   libraries mkl_rt not found in ['/data/data/com.termux/files/usr/lib']
      INFO:   NOT AVAILABLE
      INFO:
      INFO: blis_info:
      INFO:   libraries blis not found in ['/data/data/com.termux/files/usr/lib']
      INFO:   NOT AVAILABLE
      INFO:
      INFO: openblas_info:
      INFO:   libraries openblas not found in ['/data/data/com.termux/files/usr/lib']
      INFO:   NOT AVAILABLE
      INFO:
      INFO: accelerate_info:
      INFO:   NOT AVAILABLE
      INFO:
      INFO: atlas_3_10_blas_threads_info:
      INFO: Setting PTATLAS=ATLAS
      INFO:   libraries tatlas not found in ['/data/data/com.termux/files/usr/lib']
      INFO:   NOT AVAILABLE
      INFO:
      INFO: atlas_3_10_blas_info:
      INFO:   libraries satlas not found in ['/data/data/com.termux/files/usr/lib']
      INFO:   NOT AVAILABLE
      INFO:
      INFO: atlas_blas_threads_info:
      INFO: Setting PTATLAS=ATLAS
      INFO:   libraries ptf77blas,ptcblas,atlas not found in ['/data/data/com.termux/files/usr/lib']
      INFO:   NOT AVAILABLE
      INFO:
      INFO: atlas_blas_info:
      INFO:   libraries f77blas,cblas,atlas not found in ['/data/data/com.termux/files/usr/lib']
      INFO:   NOT AVAILABLE
      INFO:
      /data/data/com.termux/files/usr/tmp/pip-install-4ut392nr/numpy_c9ea7c9ed65e43e9b2ee60d52082f8f8/numpy/distutils/system_info.py:2077: UserWarning:
          Optimized (vendor) Blas libraries are not found.
          Falls back to netlib Blas library which has worse performance.
          A better performance should be easily gained by switching
          Blas library.
        if self._calc_info(blas):
      INFO: blas_info:
      INFO:   libraries blas not found in ['/data/data/com.termux/files/usr/lib']
      INFO:   NOT AVAILABLE
      INFO:
      /data/data/com.termux/files/usr/tmp/pip-install-4ut392nr/numpy_c9ea7c9ed65e43e9b2ee60d52082f8f8/numpy/distutils/system_info.py:2077: UserWarning:
          Blas (http://www.netlib.org/blas/) libraries not found.
          Directories to search for the libraries can be specified in the
          numpy/distutils/site.cfg file (section [blas]) or by setting
          the BLAS environment variable.
        if self._calc_info(blas):
      INFO: blas_src_info:
      INFO:   NOT AVAILABLE
      INFO:
      /data/data/com.termux/files/usr/tmp/pip-install-4ut392nr/numpy_c9ea7c9ed65e43e9b2ee60d52082f8f8/numpy/distutils/system_info.py:2077: UserWarning:
          Blas (http://www.netlib.org/blas/) sources not found.
          Directories to search for the sources can be specified in the
          numpy/distutils/site.cfg file (section [blas_src]) or by setting
          the BLAS_SRC environment variable.
        if self._calc_info(blas):
      INFO:   NOT AVAILABLE
      INFO:
      non-existing path in 'numpy/distutils': 'site.cfg'
      INFO: lapack_opt_info:
      INFO: lapack_armpl_info:
      INFO:   libraries armpl_lp64_mp not found in ['/data/data/com.termux/files/usr/lib']
      INFO:   NOT AVAILABLE
      INFO:
      INFO: lapack_mkl_info:
      INFO:   libraries mkl_rt not found in ['/data/data/com.termux/files/usr/lib']
      INFO:   NOT AVAILABLE
      INFO:
      INFO: openblas_lapack_info:
      INFO:   libraries openblas not found in ['/data/data/com.termux/files/usr/lib']
      INFO:   NOT AVAILABLE
      INFO:
      INFO: openblas_clapack_info:
      INFO:   libraries openblas,lapack not found in ['/data/data/com.termux/files/usr/lib']
      INFO:   NOT AVAILABLE
      INFO:
      INFO: flame_info:
      INFO:   libraries flame not found in ['/data/data/com.termux/files/usr/lib']
      INFO:   NOT AVAILABLE
      INFO:
      INFO: atlas_3_10_threads_info:
      INFO: Setting PTATLAS=ATLAS
      INFO:   libraries tatlas,tatlas not found in /data/data/com.termux/files/usr/lib
      INFO: <class 'numpy.distutils.system_info.atlas_3_10_threads_info'>
      INFO:   NOT AVAILABLE
      INFO:
      INFO: atlas_3_10_info:
      INFO:   libraries satlas,satlas not found in /data/data/com.termux/files/usr/lib
      INFO: <class 'numpy.distutils.system_info.atlas_3_10_info'>
      INFO:   NOT AVAILABLE
      INFO:
      INFO: atlas_threads_info:
      INFO: Setting PTATLAS=ATLAS
      INFO:   libraries ptf77blas,ptcblas,atlas not found in /data/data/com.termux/files/usr/lib
      INFO: <class 'numpy.distutils.system_info.atlas_threads_info'>
      INFO:   NOT AVAILABLE
      INFO:
      INFO: atlas_info:
      INFO:   libraries f77blas,cblas,atlas not found in /data/data/com.termux/files/usr/lib
      INFO: <class 'numpy.distutils.system_info.atlas_info'>
      INFO:   NOT AVAILABLE
      INFO:
      INFO: lapack_info:
      INFO:   libraries lapack not found in ['/data/data/com.termux/files/usr/lib']
      INFO:   NOT AVAILABLE
      INFO:
      /data/data/com.termux/files/usr/tmp/pip-install-4ut392nr/numpy_c9ea7c9ed65e43e9b2ee60d52082f8f8/numpy/distutils/system_info.py:1902: UserWarning:
          Lapack (http://www.netlib.org/lapack/) libraries not found.
          Directories to search for the libraries can be specified in the
          numpy/distutils/site.cfg file (section [lapack]) or by setting
          the LAPACK environment variable.
        return getattr(self, '_calc_info_{}'.format(name))()
      INFO: lapack_src_info:
      INFO:   NOT AVAILABLE
      INFO:
      /data/data/com.termux/files/usr/tmp/pip-install-4ut392nr/numpy_c9ea7c9ed65e43e9b2ee60d52082f8f8/numpy/distutils/system_info.py:1902: UserWarning:
          Lapack (http://www.netlib.org/lapack/) sources not found.
          Directories to search for the sources can be specified in the
          numpy/distutils/site.cfg file (section [lapack_src]) or by setting
          the LAPACK_SRC environment variable.
        return getattr(self, '_calc_info_{}'.format(name))()
      INFO:   NOT AVAILABLE
      INFO:
      INFO: numpy_linalg_lapack_lite:
      INFO:   FOUND:
      INFO:     language = c
      INFO:     define_macros = [('HAVE_BLAS_ILP64', None), ('BLAS_SYMBOL_SUFFIX', '64_')]
      INFO:
      Warning: attempted relative import with no known parent package
      /data/data/com.termux/files/usr/tmp/pip-build-env-2j1mlgfm/overlay/lib/python3.11/site-packages/setuptools/_distutils/dist.py:275: UserWarning: Unknown distribution option: 'define_macros'
        warnings.warn(msg)
      running bdist_wheel
      running build
      running config_cc
      INFO: unifing config_cc, config, build_clib, build_ext, build commands --compiler options
      running config_fc
      INFO: unifing config_fc, config, build_clib, build_ext, build commands --fcompiler options
      running build_src
      INFO: build_src
      INFO: building py_modules sources
      creating build
      creating build/src.linux-x86_64-3.11
      creating build/src.linux-x86_64-3.11/numpy
      creating build/src.linux-x86_64-3.11/numpy/distutils
      INFO: building library "npymath" sources
      WARN: Could not locate executable armflang
      WARN: Could not locate executable gfortran
      WARN: Could not locate executable f95
      WARN: Could not locate executable ifort
      WARN: Could not locate executable ifc
      WARN: Could not locate executable lf95
      WARN: Could not locate executable pgfortran
      WARN: Could not locate executable nvfortran
      WARN: Could not locate executable f90
      WARN: Could not locate executable f77
      WARN: Could not locate executable fort
      WARN: Could not locate executable efort
      WARN: Could not locate executable efc
      WARN: Could not locate executable g77
      WARN: Could not locate executable g95
      WARN: Could not locate executable pathf95
      WARN: Could not locate executable nagfor
      WARN: Could not locate executable frt
      WARN: don't know how to compile Fortran code on platform 'posix'
      CANNOT LINK EXECUTABLE "x86_64-linux-android-clang": cannot locate symbol "__emutls_get_address" referenced by "/data/data/com.termux/files/usr/lib/libclang-cpp.so"...
      Traceback (most recent call last):
        File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 351, in <module>
          main()
        File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 333, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 249, in build_wheel
          return _build_backend().build_wheel(wheel_directory, config_settings,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-2j1mlgfm/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 230, in build_wheel
          return self._build_with_temp_dir(['bdist_wheel'], '.whl',
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-2j1mlgfm/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 215, in _build_with_temp_dir
          self.run_setup()
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-2j1mlgfm/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 268, in run_setup
          self).run_setup(setup_script=setup_script)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-2j1mlgfm/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 158, in run_setup
          exec(compile(code, __file__, 'exec'), locals())
        File "setup.py", line 494, in <module>
          setup_package()
        File "setup.py", line 486, in setup_package
          setup(**metadata)
        File "/data/data/com.termux/files/usr/tmp/pip-install-4ut392nr/numpy_c9ea7c9ed65e43e9b2ee60d52082f8f8/numpy/distutils/core.py", line 169, in setup
          return old_setup(**new_attr)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-2j1mlgfm/overlay/lib/python3.11/site-packages/setuptools/__init__.py", line 153, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-2j1mlgfm/overlay/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 148, in setup
          dist.run_commands()
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-2j1mlgfm/overlay/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 967, in run_commands
          self.run_command(cmd)
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-2j1mlgfm/overlay/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
          cmd_obj.run()
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-2j1mlgfm/overlay/lib/python3.11/site-packages/wheel/bdist_wheel.py", line 299, in run
          self.run_command('build')
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-2j1mlgfm/overlay/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-2j1mlgfm/overlay/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
          cmd_obj.run()
        File "/data/data/com.termux/files/usr/tmp/pip-install-4ut392nr/numpy_c9ea7c9ed65e43e9b2ee60d52082f8f8/numpy/distutils/command/build.py", line 62, in run
          old_build.run(self)
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-2j1mlgfm/overlay/lib/python3.11/site-packages/setuptools/_distutils/command/build.py", line 135, in run
          self.run_command(cmd_name)
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-2j1mlgfm/overlay/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-2j1mlgfm/overlay/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
          cmd_obj.run()
        File "/data/data/com.termux/files/usr/tmp/pip-install-4ut392nr/numpy_c9ea7c9ed65e43e9b2ee60d52082f8f8/numpy/distutils/command/build_src.py", line 144, in run
          self.build_sources()
        File "/data/data/com.termux/files/usr/tmp/pip-install-4ut392nr/numpy_c9ea7c9ed65e43e9b2ee60d52082f8f8/numpy/distutils/command/build_src.py", line 155, in build_sources
          self.build_library_sources(*libname_info)
        File "/data/data/com.termux/files/usr/tmp/pip-install-4ut392nr/numpy_c9ea7c9ed65e43e9b2ee60d52082f8f8/numpy/distutils/command/build_src.py", line 288, in build_library_sources
          sources = self.generate_sources(sources, (lib_name, build_info))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/data/data/com.termux/files/usr/tmp/pip-install-4ut392nr/numpy_c9ea7c9ed65e43e9b2ee60d52082f8f8/numpy/distutils/command/build_src.py", line 378, in generate_sources
          source = func(extension, build_dir)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/data/data/com.termux/files/usr/tmp/pip-install-4ut392nr/numpy_c9ea7c9ed65e43e9b2ee60d52082f8f8/numpy/core/setup.py", line 758, in get_mathlib_info
          raise RuntimeError(
      RuntimeError: Broken toolchain: cannot link a simple C program.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for numpy
Failed to build numpy
ERROR: Could not build wheels for numpy, which is required to install pyproject.toml-based projects
$
```

### What steps will reproduce the bug?

idk

### What is the expected behavior?

To install numpy

### System information

termux-info:

```
Welcome to Termux!

Wiki:            https://wiki.termux.com
Community forum: https://termux.com/community
Gitter chat:     https://gitter.im/termux/termux
IRC channel:     #termux on freenode

Working with packages:

 * Search packages:   pkg search <query>
 * Install a package: pkg install <package>
 * Upgrade packages:  pkg upgrade

Subscribing to additional repositories:

 * Root:     pkg install root-repo
 * Unstable: pkg install unstable-repo
 * X11:      pkg install x11-repo

Report issues at https://termux.com/issues

$ termux-info
Packages CPU architecture:
x86_64
Subscribed repositories:
# sources.list
deb https://termux.org/packages/ stable main
# game-repo (sources.list.d/game.list)
deb https://dl.bintray.com/grimler/game-packages-24 games stable
# science-repo (sources.list.d/science.list)
deb https://dl.bintray.com/grimler/science-packages-24 science stable
Updatable packages:
All packages up to date
Android version:
11
Kernel build information:
Linux localhost 5.10.134-987359-g12c9ae48aa48 #1 SMP PREEMPT Thu Oct 13 19:11:36 PDT 2022 x86_64 Android
Device manufacturer:
Google
Device model:
hatch
$
```

**Comment by licy183** [comment]
Please update your packages, `pkg upgrade`.

numpy is not recommended to build from source, so we package it and you could install it using `pkg install python-numpy`. If you really want to build it, you should run `MATHLIB=m pip install numpy`.

**Comment by xtkoba** [comment]
The direct cause of the failure is:

```
> CANNOT LINK EXECUTABLE "x86_64-linux-android-clang": cannot locate symbol "__emutls_get_address" referenced by "/data/data/com.termux/files/usr/lib/libclang-cpp.so"...
```

I remember that about a year ago we saw a bunch of reports of this kind, due to `libc++` (IIRC) not being up to date. The message

```
Updatable packages:
All packages up to date
```

in termux-info is bogus I believe. The content of `sources.list` looks stale to me.

As @licy183 mentioned, `pkg up` may resolve this. I am unfamiliar with the bindist infrastructure (as always.)

**Comment by truboxl** [comment]
```
# sources.list
deb https://termux.org/packages/ stable main
# game-repo (sources.list.d/game.list)
deb https://dl.bintray.com/grimler/game-packages-24 games stable
# science-repo (sources.list.d/science.list)
deb https://dl.bintray.com/grimler/science-packages-24 science stable
```
https://github.com/termux/termux-packages/issues/6726

Reminding that Play Store builds of Termux are not supported. Use F-Droid builds, here is direct link to the current stable version: https://f-droid.org/repo/com.termux_118.apk.

**Comment by Glimpsytips** [comment]
> Please update your packages, `pkg upgrade`.
> 
> numpy is not recommended to build from source, so we package it and you could install it using `pkg install python-numpy`. If you really want to build it, you should run `MATHLIB=m pip install numpy`.



That worked
