### ISSUE TITLE
Unable to install opencv for python 3.9

### ISSUE THREAD

**Issue by w1nsid** [termux/termux-packages#13864]
### Problem description

Unable to install opencv from pip on python 3.9

```
~/opencv $ pip3.9 install opencv-python
Collecting opencv-python
  Using cached opencv-python-4.6.0.66.tar.gz (90.3 MB)
  Installing build dependencies ... error
  error: subprocess-exited-with-error

  × pip subprocess to install build dependencies did not run successfully.
  │ exit code: 1
  ╰─> [386 lines of output]
      Ignoring numpy: markers 'python_version == "3.6" and platform_machine != "aarch64" and platform_machine != "arm64"' don't match your environment
      Ignoring numpy: markers 'python_version == "3.7" and platform_machine != "aarch64" and platform_machine != "arm64"' don't match your environment
      Ignoring numpy: markers 'python_version == "3.8" and platform_machine != "aarch64" and platform_machine != "arm64"' don't match your environment
      Ignoring numpy: markers 'python_version <= "3.9" and sys_platform == "linux" and platform_machine == "aarch64"' don't match your environment
      Ignoring numpy: markers 'python_version <= "3.9" and sys_platform == "darwin" and platform_machine == "arm64"' don't match your environment
      Ignoring numpy: markers 'python_version >= "3.10"' don't match your environment
      Collecting setuptools==59.2.0
        Using cached setuptools-59.2.0-py3-none-any.whl (952 kB)
      Collecting wheel==0.37.0
        Using cached wheel-0.37.0-py2.py3-none-any.whl (35 kB)
      Collecting cmake>=3.1
        Using cached cmake-3.25.0.tar.gz (33 kB)
        Installing build dependencies: started
        Installing build dependencies: finished with status 'done'
        Getting requirements to build wheel: started
        Getting requirements to build wheel: finished with status 'done'
        Preparing metadata (pyproject.toml): started
        Preparing metadata (pyproject.toml): finished with status 'done'
      Collecting pip
        Using cached pip-22.3.1-py3-none-any.whl (2.1 MB)
      Collecting scikit-build>=0.13.2
        Using cached scikit_build-0.16.3-py3-none-any.whl (78 kB)
      Collecting numpy==1.19.3
        Using cached numpy-1.19.3-cp39-cp39-linux_armv8l.whl
      Collecting packaging
        Using cached packaging-22.0-py3-none-any.whl (42 kB)
      Collecting distro
        Using cached distro-1.8.0-py3-none-any.whl (20 kB)
      Building wheels for collected packages: cmake
        Building wheel for cmake (pyproject.toml): started
        Building wheel for cmake (pyproject.toml): finished with status 'error'
        error: subprocess-exited-with-error

        × Building wheel for cmake (pyproject.toml) did not run successfully.
        │ exit code: 1
        ╰─> [344 lines of output]


            --------------------------------------------------------------------------------
            -- Trying "Ninja" generator
            --------------------------------
            ---------------------------
            ----------------------
            -----------------
            ------------
            -------
            --
            Not searching for unused variables given on the command line.
            CMake Error: CMake was unable to find a build program corresponding to "Ninja".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
            -- Configuring incomplete, errors occurred!
            See also "/data/data/com.termux/files/usr/tmp/pip-install-3pbzn0n4/cmake_b5195d529a664583811eebfe063002a7/_cmake_test_compile/build/CMakeFiles/CMakeOutput.log".
            --
            -------
            ------------
            -----------------
            ----------------------
            ---------------------------
            --------------------------------
            -- Trying "Ninja" generator - failure
            --------------------------------------------------------------------------------



            --------------------------------------------------------------------------------
            -- Trying "Unix Makefiles" generator
            --------------------------------
            ---------------------------
            ----------------------
            -----------------
            ------------
            -------
            --
            Not searching for unused variables given on the command line.
            -- The C compiler identification is Clang 15.0.6
            -- Detecting C compiler ABI info
            -- Detecting C compiler ABI info - done
            -- Check for working C compiler: /data/data/com.termux/files/usr/bin/cc - skipped
            -- Detecting C compile features
            -- Detecting C compile features - done
            -- The CXX compiler identification is Clang 15.0.6
            -- Detecting CXX compiler ABI info
            -- Detecting CXX compiler ABI info - done
            -- Check for working CXX compiler: /data/data/com.termux/files/usr/bin/c++ - skipped
            -- Detecting CXX compile features
            -- Detecting CXX compile features - done
            -- Configuring done
            -- Generating done
            -- Build files have been written to: /data/data/com.termux/files/usr/tmp/pip-install-3pbzn0n4/cmake_b5195d529a664583811eebfe063002a7/_cmake_test_compile/build
            --
            -------
            ------------
            -----------------
            ----------------------
            ---------------------------
            --------------------------------
            -- Trying "Unix Makefiles" generator - success
            --------------------------------------------------------------------------------

            Configuring Project
              Working directory:
                /data/data/com.termux/files/usr/tmp/pip-install-3pbzn0n4/cmake_b5195d529a664583811eebfe063002a7/_skbuild/linux-armv8l-3.9/cmake-build
              Command:
                cmake /data/data/com.termux/files/usr/tmp/pip-install-3pbzn0n4/cmake_b5195d529a664583811eebfe063002a7 -G 'Unix Makefiles' -DCMAKE_INSTALL_PREFIX:PATH=/data/data/com.termux/files/usr/tmp/pip-install-3pbzn0n4/cmake_b5195d529a664583811eebfe063002a7/_skbuild/linux-armv8l-3.9/cmake-install/src/cmake/data -DPYTHON_VERSION_STRING:STRING=3.9.16 -DSKBUILD:INTERNAL=TRUE -DCMAKE_MODULE_PATH:PATH=/data/data/com.termux/files/usr/tmp/pip-build-env-74wsc0tf/overlay/lib/python3.9/site-packages/skbuild/resources/cmake -DPYTHON_EXECUTABLE:PATH=/data/data/com.termux/files/usr/bin/python3.9 -DPYTHON_INCLUDE_DIR:PATH=/data/data/com.termux/files/usr/include/python3.9 -DPYTHON_LIBRARY:PATH=/data/data/com.termux/files/usr/lib/libpython3.9.so -DPython_EXECUTABLE:PATH=/data/data/com.termux/files/usr/bin/python3.9 -DPython_ROOT_DIR:PATH=/data/data/com.termux/files/usr -DPython_INCLUDE_DIR:PATH=/data/data/com.termux/files/usr/include/python3.9 -DPython_FIND_REGISTRY:STRING=NEVER -DPython3_EXECUTABLE:PATH=/data/data/com.termux/files/usr/bin/python3.9 -DPython3_ROOT_DIR:PATH=/data/data/com.termux/files/usr -DPython3_INCLUDE_DIR:PATH=/data/data/com.termux/files/usr/include/python3.9 -DPython3_FIND_REGISTRY:STRING=NEVER -DCMAKE_BUILD_TYPE:STRING=Release

            -- The CXX compiler identification is Clang 15.0.6
            -- Detecting CXX compiler ABI info
            -- Detecting CXX compiler ABI info - done
            -- Check for working CXX compiler: /data/data/com.termux/files/usr/bin/c++ - skipped
            -- Detecting CXX compile features
            -- Detecting CXX compile features - done
            -- ***************************************************
            -- Build CMake from source: ON
            -- ***************************************************
            CMake Warning (dev) at /data/data/com.termux/files/usr/share/cmake-3.25/Modules/ExternalProject.cmake:3075 (message):
              The DOWNLOAD_EXTRACT_TIMESTAMP option was not given and policy CMP0135 is
              not set.  The policy's OLD behavior will be used.  When using a URL
              download, the timestamps of extracted files should preferably be that of
              the time of extraction, otherwise code that depends on the extracted
              contents might not be rebuilt if the URL changes.  The OLD behavior
              preserves the timestamps from the archive instead, but this is usually not
              what you want.  Update your project to the NEW behavior or specify the
              DOWNLOAD_EXTRACT_TIMESTAMP option with a value of true to avoid this
              robustness issue.
            Call Stack (most recent call first):
              /data/data/com.termux/files/usr/share/cmake-3.25/Modules/ExternalProject.cmake:4185 (_ep_add_download_command)
              CMakeLists.txt:134 (ExternalProject_add)
            This warning is for project developers.  Use -Wno-dev to suppress it.

            -- SuperBuild - CMakeProject-src-download
            -- SuperBuild - CMakeProject-src-download - URL: https://github.com/Kitware/CMake/releases/download/v3.25.0/cmake-3.25.0.tar.gz
            -- SuperBuild - CMakeProject-src-download - CMakeProject_SOURCE_DIR: /data/data/com.termux/files/usr/tmp/pip-install-3pbzn0n4/cmake_b5195d529a664583811eebfe063002a7/CMake-src
            -- Looking for __GLIBC__
            -- Looking for __GLIBC__ - not found
            -- Looking for __GLIBC_MINOR__
            -- Looking for __GLIBC_MINOR__ - not found
            -- SuperBuild -   CMakeProject-build
            -- SuperBuild -   CMakeProject-build - CMakeProject_BINARY_DIR: /data/data/com.termux/files/usr/tmp/pip-install-3pbzn0n4/cmake_b5195d529a664583811eebfe063002a7/_skbuild/linux-armv8l-3.9/cmake-build/CMakeProject-build
            -- SuperBuild -   CMakePythonDistributions
            -- Configuring done
            -- Generating done
            CMake Warning:
              Manually-specified variables were not used by the project:

                PYTHON_EXECUTABLE
                PYTHON_INCLUDE_DIR
                PYTHON_LIBRARY
                PYTHON_VERSION_STRING
                Python3_EXECUTABLE
                Python3_FIND_REGISTRY
                Python3_INCLUDE_DIR
                Python3_ROOT_DIR
                Python_EXECUTABLE
                Python_FIND_REGISTRY
                Python_INCLUDE_DIR
                Python_ROOT_DIR
                SKBUILD


            -- Build files have been written to: /data/data/com.termux/files/usr/tmp/pip-install-3pbzn0n4/cmake_b5195d529a664583811eebfe063002a7/_skbuild/linux-armv8l-3.9/cmake-build
            [  3%] Creating directories for 'CMakeProject-src-download'
            [  7%] Performing download step (download, verify and extract) for 'CMakeProject-src-download'
            -- Downloading...
               dst='/data/data/com.termux/files/usr/tmp/pip-install-3pbzn0n4/cmake_b5195d529a664583811eebfe063002a7/_skbuild/linux-armv8l-3.9/cmake-build/cmake-3.25.0.tar.gz'
               timeout='none'
               inactivity timeout='none'
            -- Using src='https://github.com/Kitware/CMake/releases/download/v3.25.0/cmake-3.25.0.tar.gz'
            -- [download 0% complete]
            -- [download 1% complete]
            -- [download 2% complete]
            -- [download 3% complete]
            -- [download 4% complete]
            -- [download 5% complete]
            -- [download 6% complete]
            -- [download 7% complete]
            -- [download 8% complete]
            -- [download 9% complete]
            -- [download 10% complete]
            -- [download 11% complete]
            -- [download 12% complete]
            -- [download 13% complete]
            -- [download 14% complete]
            -- [download 15% complete]
            -- [download 16% complete]
            -- [download 17% complete]
            -- [download 18% complete]
            -- [download 19% complete]
            -- [download 20% complete]
            -- [download 21% complete]
            -- [download 22% complete]
            -- [download 23% complete]
            -- [download 24% complete]
            -- [download 25% complete]
            -- [download 26% complete]
            -- [download 27% complete]
            -- [download 28% complete]
            -- [download 29% complete]
            -- [download 30% complete]
            -- [download 31% complete]
            -- [download 32% complete]
            -- [download 33% complete]
            -- [download 34% complete]
            -- [download 35% complete]
            -- [download 36% complete]
            -- [download 37% complete]
            -- [download 38% complete]
            -- [download 39% complete]
            -- [download 40% complete]
            -- [download 41% complete]
            -- [download 42% complete]
            -- [download 43% complete]
            -- [download 44% complete]
            -- [download 45% complete]
            -- [download 46% complete]
            -- [download 47% complete]
            -- [download 48% complete]
            -- [download 49% complete]
            -- [download 50% complete]
            -- [download 51% complete]
            -- [download 52% complete]
            -- [download 53% complete]
            -- [download 54% complete]
            -- [download 55% complete]
            -- [download 56% complete]
            -- [download 57% complete]
            -- [download 58% complete]
            -- [download 59% complete]
            -- [download 60% complete]
            -- [download 61% complete]
            -- [download 62% complete]
            -- [download 63% complete]
            -- [download 64% complete]
            -- [download 65% complete]
            -- [download 66% complete]
            -- [download 67% complete]
            -- [download 68% complete]
            -- [download 69% complete]
            -- [download 70% complete]
            -- [download 71% complete]
            -- [download 72% complete]
            -- [download 73% complete]
            -- [download 74% complete]
            -- [download 75% complete]
            -- [download 76% complete]
            -- [download 77% complete]
            -- [download 78% complete]
            -- [download 79% complete]
            -- [download 80% complete]
            -- [download 81% complete]
            -- [download 82% complete]
            -- [download 83% complete]
            -- [download 84% complete]
            -- [download 85% complete]
            -- [download 86% complete]
            -- [download 87% complete]
            -- [download 88% complete]
            -- [download 89% complete]
            -- [download 90% complete]
            -- [download 91% complete]
            -- [download 92% complete]
            -- [download 93% complete]
            -- [download 94% complete]
            -- [download 95% complete]
            -- [download 96% complete]
            -- [download 97% complete]
            -- [download 98% complete]
            -- [download 99% complete]
            -- [download 100% complete]
            -- verifying file...
                   file='/data/data/com.termux/files/usr/tmp/pip-install-3pbzn0n4/cmake_b5195d529a664583811eebfe063002a7/_skbuild/linux-armv8l-3.9/cmake-build/cmake-3.25.0.tar.gz'
            -- Downloading... done
            -- extracting...
                 src='/data/data/com.termux/files/usr/tmp/pip-install-3pbzn0n4/cmake_b5195d529a664583811eebfe063002a7/_skbuild/linux-armv8l-3.9/cmake-build/cmake-3.25.0.tar.gz'
                 dst='/data/data/com.termux/files/usr/tmp/pip-install-3pbzn0n4/cmake_b5195d529a664583811eebfe063002a7/CMake-src'
            -- extracting... [tar xfz]
            -- extracting... [analysis]
            -- extracting... [rename]
            -- extracting... [clean up]
            -- extracting... done
            [ 11%] No update step for 'CMakeProject-src-download'
            [ 15%] No patch step for 'CMakeProject-src-download'
            [ 19%] No configure step for 'CMakeProject-src-download'
            [ 23%] No build step for 'CMakeProject-src-download'
            [ 26%] No install step for 'CMakeProject-src-download'
            [ 30%] Completed 'CMakeProject-src-download'
            [ 30%] Built target CMakeProject-src-download
            [ 34%] Creating directories for 'CMakeProject-build'
            [ 38%] No download step for 'CMakeProject-build'
            [ 42%] No update step for 'CMakeProject-build'
            [ 46%] No patch step for 'CMakeProject-build'
            [ 50%] Performing configure step for 'CMakeProject-build'
            loading initial cache file /data/data/com.termux/files/usr/tmp/pip-install-3pbzn0n4/cmake_b5195d529a664583811eebfe063002a7/_skbuild/linux-armv8l-3.9/cmake-build/initial-cache.txt
            loading initial cache file /data/data/com.termux/files/usr/tmp/pip-install-3pbzn0n4/cmake_b5195d529a664583811eebfe063002a7/_skbuild/linux-armv8l-3.9/cmake-build/CMakeProject-build-prefix/tmp/CMakeProject-build-cache-Release.cmake
            -- The C compiler identification is Clang 15.0.6
            -- The CXX compiler identification is Clang 15.0.6
            -- Detecting C compiler ABI info
            -- Detecting C compiler ABI info - failed
            -- Check for working C compiler: /data/data/com.termux/files/usr/bin/cc
            -- Check for working C compiler: /data/data/com.termux/files/usr/bin/cc - broken
            CMake Error at /data/data/com.termux/files/usr/share/cmake-3.25/Modules/CMakeTestCCompiler.cmake:70 (message):
              The C compiler

                "/data/data/com.termux/files/usr/bin/cc"

              is not able to compile a simple test program.

              It fails with the following output:

                Change Dir: /data/data/com.termux/files/usr/tmp/pip-install-3pbzn0n4/cmake_b5195d529a664583811eebfe063002a7/_skbuild/linux-armv8l-3.9/cmake-build/CMakeProject-build/CMakeFiles/CMakeScratch/TryCompile-kdHnYp

                Run Build Command(s):/data/data/com.termux/files/usr/bin/make -f Makefile cmTC_ece6b/fast && make[3]: Entering directory '/data/data/com.termux/files/usr/tmp/pip-install-3pbzn0n4/cmake_b5195d529a664583811eebfe063002a7/_skbuild/linux-armv8l-3.9/cmake-build/CMakeProject-build/CMakeFiles/CMakeScratch/TryCompile-kdHnYp'
                /data/data/com.termux/files/usr/bin/make  -f CMakeFiles/cmTC_ece6b.dir/build.make CMakeFiles/cmTC_ece6b.dir/build
                make[4]: Entering directory '/data/data/com.termux/files/usr/tmp/pip-install-3pbzn0n4/cmake_b5195d529a664583811eebfe063002a7/_skbuild/linux-armv8l-3.9/cmake-build/CMakeProject-build/CMakeFiles/CMakeScratch/TryCompile-kdHnYp'
                Building C object CMakeFiles/cmTC_ece6b.dir/testCCompiler.c.o
                /data/data/com.termux/files/usr/bin/cc   -D_POSIX_C_SOURCE=199506L -D_POSIX_SOURCE=1 -D_SVID_SOURCE=1 -D_BSD_SOURCE=1  -O2 -g -DNDEBUG -MD -MT CMakeFiles/cmTC_ece6b.dir/testCCompiler.c.o -MF CMakeFiles/cmTC_ece6b.dir/testCCompiler.c.o.d -o CMakeFiles/cmTC_ece6b.dir/testCCompiler.c.o -c /data/data/com.termux/files/usr/tmp/pip-install-3pbzn0n4/cmake_b5195d529a664583811eebfe063002a7/_skbuild/linux-armv8l-3.9/cmake-build/CMakeProject-build/CMakeFiles/CMakeScratch/TryCompile-kdHnYp/testCCompiler.c
                Linking C executable cmTC_ece6b
                /data/data/com.termux/files/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_ece6b.dir/link.txt --verbose=1
                /data/data/com.termux/files/usr/bin/cc -D_POSIX_C_SOURCE=199506L -D_POSIX_SOURCE=1 -D_SVID_SOURCE=1 -D_BSD_SOURCE=1  -O2 -g -DNDEBUG -lstdc++ -lgcc -lrt  CMakeFiles/cmTC_ece6b.dir/testCCompiler.c.o -o cmTC_ece6b
                ld.lld: error: unable to find library -lgcc
                clang-15: error: linker command failed with exit code 1 (use -v to see invocation)
                make[4]: *** [CMakeFiles/cmTC_ece6b.dir/build.make:100: cmTC_ece6b] Error 1
                make[4]: Leaving directory '/data/data/com.termux/files/usr/tmp/pip-install-3pbzn0n4/cmake_b5195d529a664583811eebfe063002a7/_skbuild/linux-armv8l-3.9/cmake-build/CMakeProject-build/CMakeFiles/CMakeScratch/TryCompile-kdHnYp'
                make[3]: *** [Makefile:127: cmTC_ece6b/fast] Error 2
                make[3]: Leaving directory '/data/data/com.termux/files/usr/tmp/pip-install-3pbzn0n4/cmake_b5195d529a664583811eebfe063002a7/_skbuild/linux-armv8l-3.9/cmake-build/CMakeProject-build/CMakeFiles/CMakeScratch/TryCompile-kdHnYp'





              CMake will not be able to correctly generate this project.
            Call Stack (most recent call first):
              CMakeLists.txt:12 (project)


            -- Configuring incomplete, errors occurred!
            See also "/data/data/com.termux/files/usr/tmp/pip-install-3pbzn0n4/cmake_b5195d529a664583811eebfe063002a7/_skbuild/linux-armv8l-3.9/cmake-build/CMakeProject-build/CMakeFiles/CMakeOutput.log".
            See also "/data/data/com.termux/files/usr/tmp/pip-install-3pbzn0n4/cmake_b5195d529a664583811eebfe063002a7/_skbuild/linux-armv8l-3.9/cmake-build/CMakeProject-build/CMakeFiles/CMakeError.log".
            make[2]: *** [CMakeFiles/CMakeProject-build.dir/build.make:95: CMakeProject-build-prefix/src/CMakeProject-build-stamp/CMakeProject-build-configure] Error 1
            make[1]: *** [CMakeFiles/Makefile2:113: CMakeFiles/CMakeProject-build.dir/all] Error 2
            make: *** [Makefile:136: all] Error 2
            Traceback (most recent call last):
              File "/data/data/com.termux/files/usr/tmp/pip-build-env-74wsc0tf/overlay/lib/python3.9/site-packages/skbuild/setuptools_wrap.py", line 640, in setup
                cmkr.make(make_args, install_target=cmake_install_target, env=env)
              File "/data/data/com.termux/files/usr/tmp/pip-build-env-74wsc0tf/overlay/lib/python3.9/site-packages/skbuild/cmaker.py", line 672, in make
                self.make_impl(clargs=clargs, config=config, source_dir=source_dir, install_target=install_target, env=env)
              File "/data/data/com.termux/files/usr/tmp/pip-build-env-74wsc0tf/overlay/lib/python3.9/site-packages/skbuild/cmaker.py", line 703, in make_impl
                raise SKBuildError(


                =============================DEBUG ASSISTANCE=============================
                If you are seeing a compilation error please try the following steps to
                successfully install cmake:
                1) Upgrade to the latest pip and try again. This will fix errors for most
                   users. See: https://pip.pypa.io/en/stable/installing/#upgrading-pip
                2) If on Linux, with glibc < 2.12, you can set PIP_ONLY_BINARY=cmake in
                   order to retrieve the last manylinux1 compatible wheel.
                3) If on Linux, with glibc < 2.12, you can cap "cmake<3.23" in your
                   requirements in order to retrieve the last manylinux1 compatible wheel.
                4) Open an issue with the debug information that follows at
                   https://github.com/scikit-build/cmake-python-distributions/issues

                Python: 3.9.16
                platform: Linux-3.18.91-16526088-armv8l-with-libc
                machine: armv8l
                bits: 32
                pip: n/a
                setuptools: 65.6.3
                scikit-build: 0.16.3
                PEP517_BUILD_BACKEND=setuptools.build_meta
                =============================DEBUG ASSISTANCE=============================

            An error occurred while building with CMake.
              Command:
                cmake --build . --target install --config Release --
              Install target:
                install
              Source directory:
                /data/data/com.termux/files/usr/tmp/pip-install-3pbzn0n4/cmake_b5195d529a664583811eebfe063002a7
              Working directory:
                /data/data/com.termux/files/usr/tmp/pip-install-3pbzn0n4/cmake_b5195d529a664583811eebfe063002a7/_skbuild/linux-armv8l-3.9/cmake-build
            Please check the install target is valid and see CMake's output for more information.
            [end of output]

        note: This error originates from a subprocess, and is likely not a problem with pip.
        ERROR: Failed building wheel for cmake
      Failed to build cmake
      ERROR: Could not build wheels for cmake, which is required to install pyproject.toml-based projects
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

### What steps will reproduce the bug?

pkg install python3.9
pip3.9 install opencv-python

### What is the expected behavior?

Opencv correctly installed

### System information

termux-info:

```
Termux Variables:
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
Packages CPU architecture:
arm
Subscribed repositories:
# sources.list
deb https://mirror.mwt.me/termux/main stable main
# tur-repo (sources.list.d/tur.list)
deb https://tur.kcubeterm.com tur-packages tur tur-on-device tur-continuous
Updatable packages:
All packages up to date
termux-tools version:
1.34.1
Android version:
9
Kernel build information:
Linux localhost 3.18.91-16526088 #1 SMP PREEMPT Fri May 28 23:13:01 KST 2021 armv8l Android
Device manufacturer:
samsung
Device model:
SM-J730F
```

**Comment by xtkoba** [comment]
I'm tempted to close this as invalid. Is Python 3.9 installed from a third-party repo?

**Comment by w1nsid** [comment]
https://github.com/termux-user-repository/tur installed python from this repo

**Comment by xtkoba** [comment]
> https://github.com/termux-user-repository/tur installed python from this repo

We do not support packages that are installed from third-party repos. Use their own issue trackers (if any) if you ask for support. Thanks.
