### ISSUE TITLE
pip install spyder ERROR

### ISSUE THREAD

**Issue by sdrausty** [termux/termux-packages#1410]
![screenshot_20170909-012541](https://user-images.githubusercontent.com/27742457/30237335-f5fcfbea-94fd-11e7-961a-2cc3210cd9ac.png)

```
Welcome to Termux!

Online help:     https://termux.com/help
Community forum: https://termux.com/community
IRC channel:     #termux on freenode
Gitter chat:     https://gitter.im/termux/termux
Mailing list:    termux+subscribe@groups.io

Search packages:   pkg search <query>
Install a package: pkg install <package>
Upgrade packages:  pkg upgrade
Learn more:        pkg help
$ pip install spyder
Requirement already satisfied: spyder in /data/data/com.termux/files/usr/lib/python3.6/site-packages
Requirement already satisfied: numpydoc in /data/data/com.termux/files/usr/lib/python3.6/site-packages (from spyder)
Requirement already satisfied: qtawesome>=0.4.1 in /data/data/com.termux/files/usr/lib/python3.6/site-packages (from spyder)
Requirement already satisfied: sphinx in /data/data/com.termux/files/usr/lib/python3.6/site-packages (from spyder)
Requirement already satisfied: pickleshare in /data/data/com.termux/files/usr/lib/python3.6/site-packages (from spyder)
Requirement already satisfied: pygments>=2.0 in /data/data/com.termux/files/usr/lib/python3.6/site-packages (from spyder)
Requirement already satisfied: jedi>=0.9.0 in /data/data/com.termux/files/usr/lib/python3.6/site-packages (from spyder)
Requirement already satisfied: qtconsole>=4.2.0 in /data/data/com.termux/files/usr/lib/python3.6/site-packages (from spyder)
Requirement already satisfied: rope>=0.10.5 in /data/data/com.termux/files/usr/lib/python3.6/site-packages (from spyder)
Requirement already satisfied: pycodestyle in /data/data/com.termux/files/usr/lib/python3.6/site-packages (from spyder)
Requirement already satisfied: pyflakes in /data/data/com.termux/files/usr/lib/python3.6/site-packages (from spyder)
Requirement already satisfied: chardet>=2.0.0 in /data/data/com.termux/files/usr/lib/python3.6/site-packages (from spyder)
Requirement already satisfied: psutil in /data/data/com.termux/files/usr/lib/python3.6/site-packages (from spyder)
Requirement already satisfied: qtpy>=1.1.0 in /data/data/com.termux/files/usr/lib/python3.6/site-packages (from spyder)
Requirement already satisfied: nbconvert in /data/data/com.termux/files/usr/lib/python3.6/site-packages (from spyder)
Requirement already satisfied: pyzmq in /data/data/com.termux/files/usr/lib/python3.6/site-packages (from spyder)
Requirement already satisfied: pylint in /data/data/com.termux/files/usr/lib/python3.6/site-packages (from spyder)
Requirement already satisfied: Jinja2>=2.3 in /data/data/com.termux/files/usr/lib/python3.6/site-packages (from numpydoc->spyder)
Requirement already satisfied: six in /data/data/com.termux/files/usr/lib/python3.6/site-packages/six-1.10.0-py3.6.egg (from qtawesome>=0.4.1->spyder)
Requirement already satisfied: snowballstemmer>=1.1 in /data/data/com.termux/files/usr/lib/python3.6/site-packages (from sphinx->spyder)
Requirement already satisfied: sphinxcontrib-websupport in /data/data/com.termux/files/usr/lib/python3.6/site-packages (from sphinx->spyder)
Requirement already satisfied: alabaster<0.8,>=0.7 in /data/data/com.termux/files/usr/lib/python3.6/site-packages (from sphinx->spyder)
Requirement already satisfied: requests>=2.0.0 in /data/data/com.termux/files/usr/lib/python3.6/site-packages (from sphinx->spyder)
Requirement already satisfied: babel!=2.0,>=1.3 in /data/data/com.termux/files/usr/lib/python3.6/site-packages (from sphinx->spyder)
Requirement already satisfied: imagesize in /data/data/com.termux/files/usr/lib/python3.6/site-packages (from sphinx->spyder)
Requirement already satisfied: setuptools in /data/data/com.termux/files/usr/lib/python3.6/site-packages (from sphinx->spyder)
Requirement already satisfied: docutils>=0.11 in /data/data/com.termux/files/usr/lib/python3.6/site-packages (from sphinx->spyder)
Requirement already satisfied: jupyter-client>=4.1 in /data/data/com.termux/files/usr/lib/python3.6/site-packages (from qtconsole>=4.2.0->spyder)
Requirement already satisfied: traitlets in /data/data/com.termux/files/usr/lib/python3.6/site-packages (from qtconsole>=4.2.0->spyder)
Requirement already satisfied: jupyter-core in /data/data/com.termux/files/usr/lib/python3.6/site-packages (from qtconsole>=4.2.0->spyder)
Requirement already satisfied: ipykernel>=4.1 in /data/data/com.termux/files/usr/lib/python3.6/site-packages (from qtconsole>=4.2.0->spyder)
Requirement already satisfied: ipython-genutils in /data/data/com.termux/files/usr/lib/python3.6/site-packages (from qtconsole>=4.2.0->spyder)
Requirement already satisfied: mistune>=0.7.4 in /data/data/com.termux/files/usr/lib/python3.6/site-packages (from nbconvert->spyder)
Requirement already satisfied: nbformat>=4.4 in /data/data/com.termux/files/usr/lib/python3.6/site-packages (from nbconvert->spyder)
Requirement already satisfied: entrypoints>=0.2.2 in /data/data/com.termux/files/usr/lib/python3.6/site-packages (from nbconvert->spyder)
Requirement already satisfied: testpath in /data/data/com.termux/files/usr/lib/python3.6/site-packages (from nbconvert->spyder)
Requirement already satisfied: pandocfilters>=1.4.1 in /data/data/com.termux/files/usr/lib/python3.6/site-packages (from nbconvert->spyder)
Requirement already satisfied: bleach in /data/data/com.termux/files/usr/lib/python3.6/site-packages (from nbconvert->spyder)
Requirement already satisfied: astroid>=1.5.1 in /data/data/com.termux/files/usr/lib/python3.6/site-packages (from pylint->spyder)
Requirement already satisfied: mccabe in /data/data/com.termux/files/usr/lib/python3.6/site-packages (from pylint->spyder)
Requirement already satisfied: isort>=4.2.5 in /data/data/com.termux/files/usr/lib/python3.6/site-packages (from pylint->spyder)
Requirement already satisfied: MarkupSafe>=0.23 in /data/data/com.termux/files/usr/lib/python3.6/site-packages (from Jinja2>=2.3->numpydoc->spyder)
Requirement already satisfied: certifi>=2017.4.17 in /data/data/com.termux/files/usr/lib/python3.6/site-packages (from requests>=2.0.0->sphinx->spyder)
Requirement already satisfied: idna<2.7,>=2.5 in /data/data/com.termux/files/usr/lib/python3.6/site-packages (from requests>=2.0.0->sphinx->spyder)
Requirement already satisfied: urllib3<1.23,>=1.21.1 in /data/data/com.termux/files/usr/lib/python3.6/site-packages (from requests>=2.0.0->sphinx->spyder)
Requirement already satisfied: pytz>=0a in /data/data/com.termux/files/usr/lib/python3.6/site-packages (from babel!=2.0,>=1.3->sphinx->spyder)
Requirement already satisfied: python-dateutil>=2.1 in /data/data/com.termux/files/usr/lib/python3.6/site-packages (from jupyter-client>=4.1->qtconsole>=4.2.0->spyder)
Requirement already satisfied: decorator in /data/data/com.termux/files/usr/lib/python3.6/site-packages (from traitlets->qtconsole>=4.2.0->spyder)
Requirement already satisfied: tornado>=4.0 in /data/data/com.termux/files/usr/lib/python3.6/site-packages (from ipykernel>=4.1->qtconsole>=4.2.0->spyder)
Requirement already satisfied: ipython>=4.0.0 in /data/data/com.termux/files/usr/lib/python3.6/site-packages (from ipykernel>=4.1->qtconsole>=4.2.0->spyder)
Requirement already satisfied: jsonschema!=2.5.0,>=2.4 in /data/data/com.termux/files/usr/lib/python3.6/site-packages (from nbformat>=4.4->nbconvert->spyder)
Requirement already satisfied: html5lib>=0.99999999 in /data/data/com.termux/files/usr/lib/python3.6/site-packages (from bleach->nbconvert->spyder)
Requirement already satisfied: lazy-object-proxy in /data/data/com.termux/files/usr/lib/python3.6/site-packages (from astroid>=1.5.1->pylint->spyder)
Requirement already satisfied: wrapt in /data/data/com.termux/files/usr/lib/python3.6/site-packages (from astroid>=1.5.1->pylint->spyder)
Requirement already satisfied: prompt-toolkit<2.0.0,>=1.0.4 in /data/data/com.termux/files/usr/lib/python3.6/site-packages (from ipython>=4.0.0->ipykernel>=4.1->qtconsole>=4.2.0->spyder)
Requirement already satisfied: pexpect; sys_platform != "win32" in /data/data/com.termux/files/usr/lib/python3.6/site-packages (from ipython>=4.0.0->ipykernel>=4.1->qtconsole>=4.2.0->spyder)
Requirement already satisfied: simplegeneric>0.8 in /data/data/com.termux/files/usr/lib/python3.6/site-packages (from ipython>=4.0.0->ipykernel>=4.1->qtconsole>=4.2.0->spyder)
Requirement already satisfied: webencodings in /data/data/com.termux/files/usr/lib/python3.6/site-packages (from html5lib>=0.99999999->bleach->nbconvert->spyder)
Requirement already satisfied: wcwidth in /data/data/com.termux/files/usr/lib/python3.6/site-packages (from prompt-toolkit<2.0.0,>=1.0.4->ipython>=4.0.0->ipykernel>=4.1->qtconsole>=4.2.0->spyder)
Requirement already satisfied: ptyprocess>=0.5 in /data/data/com.termux/files/usr/lib/python3.6/site-packages (from pexpect; sys_platform != "win32"->ipython>=4.0.0->ipykernel>=4.1->qtconsole>=4.2.0->spyder)
$ spyder
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/qtpy/__init__.py", line 148, in <module>
    from PySide import __version__ as PYSIDE_VERSION  # analysis:ignore
ModuleNotFoundError: No module named 'PySide'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/bin/spyder", line 11, in <module>
    sys.exit(main())
  File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/spyder/app/start.py", line 140, in main
    from spyder.app import mainwindow
  File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/spyder/app/mainwindow.py", line 49, in <module>
    requirements.check_qt()
  File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/spyder/requirements.py", line 39, in check_qt
    import qtpy
  File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/qtpy/__init__.py", line 154, in <module>
    raise PythonQtError('No Qt bindings could be found')
qtpy.PythonQtError: No Qt bindings could be found
$ pip install pyside
Collecting pyside
  Using cached PySide-1.2.4.tar.gz
    Complete output from command python setup.py egg_info:
    only these python versions are supported: [(2, 6), (2, 7), (3, 2), (3, 3), (3, 4)]

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /data/data/com.termux/files/usr/tmp/pip-build-06malbpd/pyside/
$
```
![screenshot_20170909-013644](https://user-images.githubusercontent.com/27742457/30237420-8d978f78-94ff-11e7-9040-86f50297c1f7.png)

**Comment by sdrausty** [comment]
![screenshot_20170909-014349](https://user-images.githubusercontent.com/27742457/30237459-62e8f6bc-9500-11e7-92c2-f4665b849a52.png)
Keep up your great work! ☺

**Comment by xeffyr** [comment]
It requires PyQt, it is not available for Termux.

**Comment by sdrausty** [comment]
@xeffer Thanks for your reply. I got word of https://github.com/spyder-ide/spyder by reviewing https://wiki.termux.com/wiki/List_of_Python_packages_known_to_work

**Comment by sdrausty** [comment]
@fornwall can you please state a little bit behind your choice to close this issue?

**Comment by sdrausty** [comment]
I'm not too concerned myself, since I was merely filling in top ten search results for https://wiki.termux.com/wiki/List_of_Python_packages_known_to_work It did not install, so I posted this issue. This program ran into errors. Can you please suggest a course of resolution?  

spyder is active and has 2.3K+ 🌟 stars https://wiki.termux.com/wiki/Package_Management#Package_requests

It seems to fullfil necessary requirements for inclusion. However, if Admin @fornwall beg to differ, can a course of resolution be issued here please?

**Comment by Neo-Oli** [comment]
Spyder also seems like a GUI thing.
