### ISSUE TITLE
termux-info gives java error (aarch64, android 7.0)

### ISSUE THREAD

**Issue by Grimler91** [termux/termux-packages#1426]
Recently bought a new phone, just noticed that termux-info gives a java error: 

```
android.os.DeadObjectException: Transaction failed on small parcel; remote process probably died
	at android.os.BinderProxy.transactNative(Native Method)
	at android.os.BinderProxy.transact(Binder.java:628)
	at android.os.BinderProxy.shellCommand(Binder.java:675)
	at com.android.commands.pm.Pm.runShellCommand(Pm.java:295)
	at com.android.commands.pm.Pm.runList(Pm.java:644)
	at com.android.commands.pm.Pm.run(Pm.java:130)
	at com.android.commands.pm.Pm.main(Pm.java:99)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:307)
Termux version:
<=0.48
Installed Termux apps:
Updatable packages:
busybox/stable 1.27.2 aarch64 [upgradable from: 1.27.1-2]
harfbuzz/stable 1.5.1 aarch64 [upgradable from: 1.4.8]
harfbuzz-icu/stable 1.5.1 aarch64 [upgradable from: 1.4.8]
libxml2/stable 2.9.5 aarch64 [upgradable from: 2.9.4-1]
ncurses/stable 6.0.20170902 aarch64 [upgradable from: 6.0.20170827]
ncurses-ui-libs/stable 6.0.20170902 aarch64 [upgradable from: 6.0.20170827]
ncurses-utils/stable 6.0.20170902 aarch64 [upgradable from: 6.0.20170827]
pango/stable 1.40.12 aarch64 [upgradable from: 1.40.9]
rcs/stable 5.9.4-1 aarch64 [upgradable from: 5.9.4]
System information:
Linux localhost 4.4.13-11814589 #1 SMP PREEMPT Wed Jul 12 17:43:57 KST 2017 aarch64 Android
Termux-packages arch:
aarch64
Android version:
7.0
Device manufacturer:
samsung
Device model:
SM-G955N
```

I've flashed a custom ROM (sources aren't available) so that could be the culprit.

**Comment by sdrausty** [comment]
```
$ termux-info
android.os.DeadObjectException: Transaction failed on small parcel; remote process probably died
        at android.os.BinderProxy.transactNative(Native Method)
        at android.os.BinderProxy.transact(Binder.java:615)
        at android.os.BinderProxy.shellCommand(Binder.java:662)
        at com.android.commands.pm.Pm.runShellCommand(Pm.java:304)
        at com.android.commands.pm.Pm.runList(Pm.java:710)
        at com.android.commands.pm.Pm.run(Pm.java:139)
        at com.android.commands.pm.Pm.main(Pm.java:108)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:262)
Termux version:
<=0.48
Installed Termux apps:
Updatable packages:
freetype/stable 2.8.1 arm [upgradable from: 2.8-1]
System information:
Linux localhost 3.18.31-perf-g162e916 #1 SMP PREEMPT Thu Jun 29 17:29:03 CDT 2017 armv7l Android
Termux-packages arch:
arm
Android version:
7.1.1
Device manufacturer:
motorola
Device model:
Moto E (4)
```
![screenshot_20170919-212311](https://user-images.githubusercontent.com/27742457/30622715-5f45c330-9d81-11e7-98f7-5fe674e5e013.png)

**Comment by christianrondeau** [comment]
For the sake of completeness, same issue with the latest version :

```
android.os.DeadObjectException: Transaction failed on small parcel; remote process probably died
	at android.os.BinderProxy.transactNative(Native Method)
	at android.os.BinderProxy.transact(Binder.java:628)
	at android.os.BinderProxy.shellCommand(Binder.java:675)
	at com.android.commands.pm.Pm.runShellCommand(Pm.java:295)
	at com.android.commands.pm.Pm.runList(Pm.java:644)
	at com.android.commands.pm.Pm.run(Pm.java:130)
	at com.android.commands.pm.Pm.main(Pm.java:99)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:301)
Termux version:
<=0.48
Installed Termux apps:
Updatable packages:
All packages up to date
System information:
Linux localhost 3.18.14-12046623 #1 SMP PREEMPT Tue Aug 8 17:23:43 KST 2017 aarch64 Android
Termux-packages arch:
aarch64
Android version:
7.0
Device manufacturer:
samsung
Device model:
SM-G935W8
Terminated
```

**Comment by pschulz** [comment]
The same on Huawei P10 lite with EMUI 5.1, based on Nougat.
Any idea?

**Comment by fornwall** [comment]
Should be fixed in the latest termux-tools package version now, run `pkg up` to install it!

I dropped the `Installed Termux apps:` section, which called `pm` and causes the problem om some devices, as it's not that important.
