### ISSUE TITLE
[Bug]: recoll default hardcoded `RECOLL_DATADIR` path does not exist

### ISSUE THREAD

**Issue by JCGoran** [termux/termux-packages#14269]
### Problem description

Trying to run recoll's webui (available [here](https://framagit.org/medoc92/recollwebui/)) via `python3 webui-standalone.py` works, however when trying to access the server it throws an error.

### What steps will reproduce the bug?

1. install the Python wrapper to recoll: `apt install recoll-python`
2. clone [this repo](https://framagit.org/medoc92/recollwebui/): `git clone https://framagit.org/medoc92/recollwebui.git`
3. install a required Python package: `pip install waitress`
4. run `python3 webui-standalone.py`
5. open a web browser and go to `http://localhost:8080`

The backend then responds with:

```plaintext
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/recollwebui/bottle.py", line 871, in _handle
    return route.call(**args)
           ^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/home/recollwebui/bottle.py", line 1757, in wrapper
    rv = callback(*a, **ka)
         ^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/home/recollwebui/bottle.py", line 3686, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/home/recollwebui/webui.py", line 381, in main
    config = get_config()
             ^^^^^^^^^^^^
  File "/data/data/com.termux/files/home/recollwebui/webui.py", line 142, in get_config
    rclconf = rclconfig.RclConfig(envdir)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/recoll/rclconfig.py", line 83, in __init__
    raise(Exception(
Exception: Can't open default/system recoll.conf. Please set RECOLL_DATADIR in the environment to point to the installed recoll data files.
```

### What is the expected behavior?

The package should not throw an error.

I think the issue is that recoll hardcodes the location of the datadir (to `/usr/share/recoll`), as shown in the `rclconfig.py` file:

```python
if self.datadir is None:
    self.datadir = "/usr/share/recoll"
f = None
try:
    f = open(os.path.join(self.datadir, "examples", "recoll.conf"), "r")
```

As a workaround, one can run this command instead in step 4. above (there are probably other locations of `recoll.conf`, this is just one of them that I found using `find`):

```sh
RECOLL_DATADIR='/data/user/0/com.termux/files/usr/share/recoll/' python3 webui-standalone.py
```

which fixes the problem, but it would be nice if it was not required.

### System information

termux-info:

```
Termux Variables:
TERMUX_APK_RELEASE=F_DROID
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=26230
TERMUX_IS_DEBUGGABLE_BUILD=0
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://grimler.se/termux/termux-main stable main
Updatable packages:
All packages up to date
termux-tools version:
1.35.0
Android version:
11
Kernel build information:
Linux localhost 4.14.212-gccfcc225a50c-ab7508431 #1 SMP PREEMPT Wed Jun 30 09:53:57 UTC 2021 aarch64 Android
Device manufacturer:
Google
Device model:
Pixel 4a
```

**Comment by xtkoba** [comment]
A few other hard-coded paths are found. I will purge them all.

**Comment by SedapnyaTidur** [comment]
This may not gonna help but this something I made 5/6 years ago to deal with hardcoded paths / shebangs. It usually works wonder. One thing I still remember to this day is that you need to exclude `man` folder for `autoconf` or `automake` package - why? no idea. Try it for yourself.

**patchproject.sh**
```bash
#!/system/bin/sh -e

usage () {
	echo "Usage: ${0##*/} [OPTIONS] <FILES/DIRECTORIES>"
	echo 'Patch source code files to fix hardcoded shebangs and paths.'
	echo ''
	echo '-c|--color             Color substitutions.'
	echo '-i|--include <REGEX>   Print and highlight only matched regexp.'
	echo "-x|--exclude <REGEX>   Don't print matched regexp."
	echo '-H|--highlight <REGEX> Highlight matched regexp.'
	echo '-p|--patch             Patch files permenantly quietly.'
	echo '-h|--help              Print this help message.'
	exit "$1"
}

hasCommands () {
	local cmd error=0
	for cmd in awk find sed; do
		if ! command -v "$cmd" 2>/dev/null 1>&2; then
			echo '[ERROR]: Command is not installed: '"$cmd"
			error=1
		fi
	done
	if [ $error -eq 1 ]; then exit 1; fi
}

validTargets () {
	if [ -z "$1" ]; then
		echo '[ERROR]: Target files or directories is required!'
		exit 1
	fi
	local file
	for file in "$@"; do
		if [ ! -f "$file" ] && [ ! -d "$file" ]; then
			echo "[ERROR]: No such file or directory: '$file'"
			exit 1
		fi
	done
}

colors () {
	if [ $1 -eq 0 ]; then return 0; fi
	local c i=1
	for c in $(awk 'BEGIN { print "\x1B[0m","\x1B[1;30m" }'); do
		if [ $i -eq 1 ]; then
			_DEFAULT="$c"; i=2
		else
			_GRAY="$c"
		fi
	done
}

if [ "$#" -eq 0 ]; then usage 1; fi
hasCommands

_COLORS=0
_EXCLUDE=
_HIGHLIGHT=
_INCLUDE=
_SED_FLAGS='gp'
_SED_OPTIONS='-En'
_SHIFT=1

_DEFAULT=
_GRAY=

while [ -n "$1" ]; do
	case "$1" in
		-c|--color)     _COLORS=1 ;;
		-i|--include)   _INCLUDE="$2"; _SHIFT=2 ;;
		-x|--exlude)    _EXCLUDE="$2"; _SHIFT=2 ;;
		-H|--highlight) _HIGHLIGHT="$2"; _SHIFT=2 ;;
		-p|--patch)     _COLORS=0; _SHIFT=1; _SED_OPTIONS='-Ei'; _SED_FLAGS='g' ;;
		-h|--help)      usage 0 ;;
		*)  break ;;
	esac
	if [ "$#" -lt $_SHIFT ]; then
		echo "[ERROR]: Invalid arguments: '$@'"
		echo "         Make sure to quote the arguments properly."
		exit 1
	fi
	shift "$_SHIFT"
done

validTargets "$@"
colors "$_COLORS"

for file in "$@"; do
	if [ -d "$file" ]; then
		find "$file" -type f -regextype gnu-awk ! -iregex '^.*\.(dvi|m4f|png|svg)$' -exec sed "$_SED_OPTIONS" \
		-e 's/(-| )?(\/usr)?\/bin\/sh/'"$_GRAY"'\1\/system\/bin\/sh'"$_DEFAULT"'/'"$_SED_FLAGS" \
		-e 's/( |\()?(\/usr)?\/bin\/uname /'"$_GRAY"'\1uname '"$_DEFAULT"'/'"$_SED_FLAGS" \
		-e 's/\/usr\/(bin|etc|include|lib||lib32|lib64|libexec|sbin|share|tmp)([ \/"}:])/'"$_GRAY"'\/data\/data\/com\.termux\/files\/usr\/\1\2'"$_DEFAULT"'/'"$_SED_FLAGS" \
		-e 's/\/usr\/local\/(bin|etc|include|lib|lib32|lib64|libexec|sbin|share|tmp)([ \/"}])/'"$_GRAY"'\/data\/data\/com\.termux\/files\/usr\/\1\2'"$_DEFAULT"'/'"$_SED_FLAGS" \
		-e 's/([=`])\/usr\/local/'"$_GRAY"'\1\/data\/data\/com\.termux\/files\/usr'"$_DEFAULT"'/'"$_SED_FLAGS" \
		-e 's/([^@)\\][ '\''‘"{(=:])\/(bin|etc|include|lib|lib32|lib64|libexec|sbin|share|tmp|var)([ '\''"\/;:)])([^\$])/'"$_GRAY"'\1\/data\/data\/com\.termux\/files\/usr\/\2\3\4'"$_DEFAULT"'/'"$_SED_FLAGS" \
		-e 's/^#! ?\/usr\/bin\/(env )?/'"$_GRAY"'#\!\/data\/data\/com\.termux\/files\/usr\/bin\/\1'"$_DEFAULT"'/'"${_SED_FLAGS#*g}" \
		'{}' + | \
		awk -v col="$_COLORS" -v exc="$_EXCLUDE" -v hig="$_HIGHLIGHT" -v inc="$_INCLUDE" '
		BEGIN {
			e=(exc!=""); i=(inc!=""); s=(inc==""); h=(hig!=""); n=0
			d="\x1B[0m"; b="\x1B[1;34m"; p="\x1B[1;35m"; y="\x1B[1;31m"
			gsub(/\\/,"\\\\&",exc); gsub(/\\/,"\\\\&",hig); gsub(/\\/,"\\\\&",inc)
		}
		e && $0 ~ exc { ++n; next }
		i && $0 ~ inc { ++n; gsub(inc,p"&"d,$0); if(h) gsub(hig,y"&"d,$0); printf("[%s%04d%s]: ",b,n,d); print $0; next } 
		{ ++n; if(s) { if(h) gsub(hig,y"&"d,$0); printf("[%s%04d%s]: ",b,n,d); print $0 }}'
	elif [ -f "$file" ]; then
		sed  "$_SED_OPTIONS" \
		-e 's/(-| )?(\/usr)?\/bin\/sh/'"$_GRAY"'\1\/system\/bin\/sh'"$_DEFAULT"'/'"$_SED_FLAGS" \
		-e 's/( |\()?(\/usr)?\/bin\/uname /'"$_GRAY"'\1uname '"$_DEFAULT"'/'"$_SED_FLAGS" \
		-e 's/\/usr\/(bin|etc|include|lib||lib32|lib64|libexec|sbin|share|tmp)([ \/"}:])/'"$_GRAY"'\/data\/data\/com\.termux\/files\/usr\/\1\2'"$_DEFAULT"'/'"$_SED_FLAGS" \
		-e 's/\/usr\/local\/(bin|etc|include|lib|lib32|lib64|libexec|sbin|share|tmp)([ \/"}])/'"$_GRAY"'\/data\/data\/com\.termux\/files\/usr\/\1\2'"$_DEFAULT"'/'"$_SED_FLAGS" \
		-e 's/([=`])\/usr\/local/'"$_GRAY"'\1\/data\/data\/com\.termux\/files\/usr'"$_DEFAULT"'/'"$_SED_FLAGS" \
		-e 's/([^@)\\][ '\''‘"{(=:])\/(bin|etc|include|lib|lib32|lib64|libexec|sbin|share|tmp|var)([ '\''"\/;:)])([^\$])/'"$_GRAY"'\1\/data\/data\/com\.termux\/files\/usr\/\2\3\4'"$_DEFAULT"'/'"$_SED_FLAGS" \
		-e 's/^#! ?\/usr\/bin\/(env )?/'"$_GRAY"'#\!\/data\/data\/com\.termux\/files\/usr\/bin\/\1'"$_DEFAULT"'/'"${_SED_FLAGS#*g}" \
		"$file" | \
		awk -v col="$_COLORS" -v exc="$_EXCLUDE" -v hig="$_HIGHLIGHT" -v inc="$_INCLUDE" '
		BEGIN {
			e=(exc!=""); i=(inc!=""); s=(inc==""); h=(hig!=""); n=0
			d="\x1B[0m"; b="\x1B[1;34m"; p="\x1B[1;35m"; y="\x1B[1;31m"
			gsub(/\\/,"\\\\&",exc); gsub(/\\/,"\\\\&",hig); gsub(/\\/,"\\\\&",inc)
		}
		e && $0 ~ exc { ++n; next }
		i && $0 ~ inc { ++n; gsub(inc,p"&"d,$0); if(h) gsub(hig,y"&"d,$0); printf("[%s%04d%s]: ",b,n,d); print $0; next } 
		{ ++n; if(s) { if(h) gsub(hig,y"&"d,$0); printf("[%s%04d%s]: ",b,n,d); print $0 }}'
	fi
done
```
