### ISSUE TITLE
mGBA: Segmentation Fault

### ISSUE THREAD

**Issue by mguinhos** [termux/termux-packages#14572]
### Problem description

mGBA wont start any gameboy advance game.

### What steps will reproduce the bug?

$ mgba pokemon.gba

### System information

termux-info:

```
Termux Variables:
TERMUX_API_VERSION=0.50.1
TERMUX_APK_RELEASE=F_DROID
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=6926
TERMUX_IS_DEBUGGABLE_BUILD=0
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://mirrors.utermux.dev/termux/termux-main stable main
# x11-repo (sources.list.d/x11.list)
deb https://mirrors.utermux.dev/termux/termux-x11 x11 main
Updatable packages:
All packages up to date
termux-tools version:
1.35.0
Android version:
13
Kernel build information:
Linux localhost 4.19.87-25304676 #1 SMP PREEMPT Wed Dec 14 06:43:44 KST 2022 aarch64 Android
Device manufacturer:
samsung
Device model:
SM-N981B
```

**Comment by xtkoba** [comment]
Needs a test case that can be shared, unless you can debug (using debug build and `gdb`) by yourself.

**Comment by xtkoba** [comment]
OK, I can reproduce this (with some free demo ROM in the wild):

```
Thread 1 "mgba" received signal SIGSEGV, Segmentation fault.
create_textures (ctx=ctx@entry=0x0, target=0, n=n@entry=2, textures=textures@entry=0x7ffffff768, caller=0x7faf5d5e49 "glGenTextures") at ../src/src/mesa/main/texobj.c:1253
1253    ../src/src/mesa/main/texobj.c: (undocumented errno 2).
(gdb) bt
#0  create_textures (ctx=ctx@entry=0x0, target=0, n=n@entry=2, textures=textures@entry=0x7ffffff768, caller=0x7faf5d5e49 "glGenTextures")
    at ../src/src/mesa/main/texobj.c:1253
#1  0x0000007fb0181fe0 in create_textures_err (ctx=0x0, target=0, n=<optimized out>, textures=<optimized out>, caller=<optimized out>)
    at ../src/src/mesa/main/texobj.c:1287
#2  _mesa_GenTextures (n=2, textures=0x7ffffff768)
    at ../src/src/mesa/main/texobj.c:1322
#3  0x0000007fb5bb8a44 in glGenTextures (n=0, n@entry=2, textures=0x0)
    at src/mapi/glapi/gen/glapi_mapi_tmp.h:3659
#4  0x0000007fb43a1340 in mGLContextInit (v=0x7ffffff700, handle=<optimized out>)
    at /home/builder/.termux-build/mgba/src/src/platform/opengl/gl.c:29
#5  0x000000555555c44c in mSDLGLInit (renderer=0x7ffffff4e8)
    at /home/builder/.termux-build/mgba/src/src/platform/sdl/gl-sdl.c:39
#6  0x000000555555bf2c in main (argc=<optimized out>, argv=<optimized out>)
    at /home/builder/.termux-build/mgba/src/src/platform/sdl/main.c:164
(gdb)
```

SEGV is in a library from `mesa`. The direct cause is a null pointer dereference.
 Interestingly, this does not happen with a very old `mesa` package (version `22.1.0-1`, which I have preserved in case of just like this.)
