### ISSUE TITLE
[Bug]: Can't install freetype-py

### ISSUE THREAD

**Issue by guranu** [termux/termux-packages#14742]
### Problem description

i typed pip install freetype-py and that's what caused this issue.

### What steps will reproduce the bug?

~ $ pip install freetype-py
Collecting freetype-py
  Downloading freetype-py-2.3.0.zip (830 kB)
     ━━━━━━━━━━━━━━━ 830.6/830.6 kB 1.5 MB/s eta 0:00:00
  Installing build dependencies ... error
  error: subprocess-exited-with-error

  × pip subprocess to install build dependencies did not run successfully.
  │ exit code: 1
  ╰─> [380 lines of output]
      Collecting setuptools>=42
        Downloading setuptools-66.1.1-py3-none-any.whl (1.3 MB)
           ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 2.4 MB/s eta 0:00:00
      Collecting wheel
        Using cached wheel-0.38.4-py3-none-any.whl (36 kB)
      Collecting setuptools_scm[toml]>=3.4
        Using cached setuptools_scm-7.1.0-py3-none-any.whl (43 kB)
      Collecting certifi
        Downloading certifi-2022.12.7-py3-none-any.whl (155 kB)
           ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 155.3/155.3 kB 10.5 MB/s eta 0:00:00
      Collecting cmake
        Downloading cmake-3.25.0.tar.gz (33 kB)
        Installing build dependencies: started
        Installing build dependencies: finished with status 'done'
        Getting requirements to build wheel: started
        Getting requirements to build wheel: finished with status 'done'
        Preparing metadata (pyproject.toml): started
        Preparing metadata (pyproject.toml): finished with status 'done'
      Collecting packaging>=20.0
        Using cached packaging-23.0-py3-none-any.whl (42 kB)
      Collecting typing-extensions
        Downloading typing_extensions-4.4.0-py3-none-any.whl (26 kB)
      Building wheels for collected packages: cmake
        Building wheel for cmake (pyproject.toml): started
        Building wheel for cmake (pyproject.toml): finished with status 'error'
        error: subprocess-exited-with-error

        × Building wheel for cmake (pyproject.toml) did not run successfully.
        │ exit code: 1
        ╰─> [344 lines of output]

            --------------------------------------------------------------------------------
            -- Trying 'Ninja' generator
            --------------------------------
            ---------------------------
            ----------------------
            -----------------
            ------------
            -------
            --
            Not searching for unused variables given on the command line.
            CMake Error: CMake was unable to find a build program corresponding to "Ninja".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
            -- Configuring incomplete, errors occurred!
            See also "/data/data/com.termux/files/usr/tmp/pip-install-xkz9abgj/cmake_a5e8189929be499799a15f557a5e0d9e/_cmake_test_compile/build/CMakeFiles/CMakeOutput.log".
            --
            -------
            ------------
            -----------------
            ----------------------
            ---------------------------
            --------------------------------
            -- Trying 'Ninja' generator - failure
            --------------------------------------------------------------------------------

            --------------------------------------------------------------------------------
            -- Trying 'Unix Makefiles' generator
            --------------------------------
            ---------------------------
            ----------------------
            -----------------
            ------------
            -------
            --
            Not searching for unused variables given on the command line.
            -- The C compiler identification is Clang 15.0.6
            -- Detecting C compiler ABI info
            -- Detecting C compiler ABI info - done
            -- Check for working C compiler: /data/data/com.termux/files/usr/bin/cc - skipped
            -- Detecting C compile features
            -- Detecting C compile features - done
            -- The CXX compiler identification is Clang 15.0.6
            -- Detecting CXX compiler ABI info
            -- Detecting CXX compiler ABI info - done
            -- Check for working CXX compiler: /data/data/com.termux/files/usr/bin/c++ - skipped
            -- Detecting CXX compile features
            -- Detecting CXX compile features - done
            -- Configuring done
            -- Generating done
            -- Build files have been written to: /data/data/com.termux/files/usr/tmp/pip-install-xkz9abgj/cmake_a5e8189929be499799a15f557a5e0d9e/_cmake_test_compile/build
            --
            -------
            ------------
            -----------------
            ----------------------
            ---------------------------
            --------------------------------
            -- Trying 'Unix Makefiles' generator - success
            --------------------------------------------------------------------------------

            Configuring Project
              Working directory:
                /data/data/com.termux/files/usr/tmp/pip-install-xkz9abgj/cmake_a5e8189929be499799a15f557a5e0d9e/_skbuild/linux-aarch64-3.11/cmake-build
              Command:
                /data/data/com.termux/files/usr/bin/cmake /data/data/com.termux/files/usr/tmp/pip-install-xkz9abgj/cmake_a5e8189929be499799a15f557a5e0d9e -G 'Unix Makefiles' -DCMAKE_INSTALL_PREFIX:PATH=/data/data/com.termux/files/usr/tmp/pip-install-xkz9abgj/cmake_a5e8189929be499799a15f557a5e0d9e/_skbuild/linux-aarch64-3.11/cmake-install/src/cmake/data -DPYTHON_VERSION_STRING:STRING=3.11.1 -DSKBUILD:INTERNAL=TRUE -DCMAKE_MODULE_PATH:PATH=/data/data/com.termux/files/usr/tmp/pip-build-env-eln0gjwk/overlay/lib/python3.11/site-packages/skbuild/resources/cmake -DPYTHON_EXECUTABLE:PATH=/data/data/com.termux/files/usr/bin/python3 -DPYTHON_INCLUDE_DIR:PATH=/data/data/com.termux/files/usr/include/python3.11 -DPYTHON_LIBRARY:PATH=/data/data/com.termux/files/usr/lib/libpython3.11.so -DPython_EXECUTABLE:PATH=/data/data/com.termux/files/usr/bin/python3 -DPython_ROOT_DIR:PATH=/data/data/com.termux/files/usr -DPython_INCLUDE_DIR:PATH=/data/data/com.termux/files/usr/include/python3.11 -DPython_FIND_REGISTRY:STRING=NEVER -DPython3_EXECUTABLE:PATH=/data/data/com.termux/files/usr/bin/python3 -DPython3_ROOT_DIR:PATH=/data/data/com.termux/files/usr -DPython3_INCLUDE_DIR:PATH=/data/data/com.termux/files/usr/include/python3.11 -DPython3_FIND_REGISTRY:STRING=NEVER -DCMAKE_BUILD_TYPE:STRING=Release

            -- The CXX compiler identification is Clang 15.0.6
            -- Detecting CXX compiler ABI info
            -- Detecting CXX compiler ABI info - done
            -- Check for working CXX compiler: /data/data/com.termux/files/usr/bin/c++ - skipped
            -- Detecting CXX compile features
            -- Detecting CXX compile features - done
            -- ***************************************************
            -- Build CMake from source: ON
            -- ***************************************************
            CMake Warning (dev) at /data/data/com.termux/files/usr/share/cmake-3.25/Modules/ExternalProject.cmake:3075 (message):
              The DOWNLOAD_EXTRACT_TIMESTAMP option was not given and policy CMP0135 is
              not set.  The policy's OLD behavior will be used.  When using a URL
              download, the timestamps of extracted files should preferably be that of
              the time of extraction, otherwise code that depends on the extracted
              contents might not be rebuilt if the URL changes.  The OLD behavior
              preserves the timestamps from the archive instead, but this is usually not
              what you want.  Update your project to the NEW behavior or specify the
              DOWNLOAD_EXTRACT_TIMESTAMP option with a value of true to avoid this
              robustness issue.
            Call Stack (most recent call first):
              /data/data/com.termux/files/usr/share/cmake-3.25/Modules/ExternalProject.cmake:4185 (_ep_add_download_command)
              CMakeLists.txt:134 (ExternalProject_add)
            This warning is for project developers.  Use -Wno-dev to suppress it.

            -- SuperBuild - CMakeProject-src-download
            -- SuperBuild - CMakeProject-src-download - URL: https://github.com/Kitware/CMake/releases/download/v3.25.0/cmake-3.25.0.tar.gz
            -- SuperBuild - CMakeProject-src-download - CMakeProject_SOURCE_DIR: /data/data/com.termux/files/usr/tmp/pip-install-xkz9abgj/cmake_a5e8189929be499799a15f557a5e0d9e/CMake-src
            -- Looking for __GLIBC__
            -- Looking for __GLIBC__ - not found
            -- Looking for __GLIBC_MINOR__
            -- Looking for __GLIBC_MINOR__ - not found
            -- SuperBuild -   CMakeProject-build
            -- SuperBuild -   CMakeProject-build - CMakeProject_BINARY_DIR: /data/data/com.termux/files/usr/tmp/pip-install-xkz9abgj/cmake_a5e8189929be499799a15f557a5e0d9e/_skbuild/linux-aarch64-3.11/cmake-build/CMakeProject-build
            -- SuperBuild -   CMakePythonDistributions
            -- Configuring done
            -- Generating done
            CMake Warning:
              Manually-specified variables were not used by the project:

                PYTHON_EXECUTABLE
                PYTHON_INCLUDE_DIR
                PYTHON_LIBRARY
                PYTHON_VERSION_STRING
                Python3_EXECUTABLE
                Python3_FIND_REGISTRY
                Python3_INCLUDE_DIR
                Python3_ROOT_DIR
                Python_EXECUTABLE
                Python_FIND_REGISTRY
                Python_INCLUDE_DIR
                Python_ROOT_DIR
                SKBUILD

            -- Build files have been written to: /data/data/com.termux/files/usr/tmp/pip-install-xkz9abgj/cmake_a5e8189929be499799a15f557a5e0d9e/_skbuild/linux-aarch64-3.11/cmake-build
            [  3%] Creating directories for 'CMakeProject-src-download'
            [  7%] Performing download step (download, verify and extract) for 'CMakeProject-src-download'
            -- Downloading...
               dst='/data/data/com.termux/files/usr/tmp/pip-install-xkz9abgj/cmake_a5e8189929be499799a15f557a5e0d9e/_skbuild/linux-aarch64-3.11/cmake-build/cmake-3.25.0.tar.gz'
               timeout='none'
               inactivity timeout='none'
            -- Using src='https://github.com/Kitware/CMake/releases/download/v3.25.0/cmake-3.25.0.tar.gz'
            -- [download 0% complete]
            -- [download 1% complete]
            -- [download 2% complete]
            -- [download 3% complete]
            -- [download 4% complete]
            -- [download 5% complete]
            -- [download 6% complete]
            -- [download 7% complete]
            -- [download 8% complete]
            -- [download 9% complete]
            -- [download 10% complete]
            -- [download 11% complete]
            -- [download 12% complete]
            -- [download 13% complete]
            -- [download 14% complete]
            -- [download 15% complete]
            -- [download 16% complete]
            -- [download 17% complete]
            -- [download 18% complete]
            -- [download 19% complete]
            -- [download 20% complete]
            -- [download 21% complete]
            -- [download 22% complete]
            -- [download 23% complete]
            -- [download 24% complete]
            -- [download 25% complete]
            -- [download 26% complete]
            -- [download 27% complete]
            -- [download 28% complete]
            -- [download 29% complete]
            -- [download 30% complete]
            -- [download 31% complete]
            -- [download 32% complete]
            -- [download 33% complete]
            -- [download 34% complete]
            -- [download 35% complete]
            -- [download 36% complete]
            -- [download 37% complete]
            -- [download 38% complete]
            -- [download 39% complete]
            -- [download 40% complete]
            -- [download 41% complete]
            -- [download 42% complete]
            -- [download 43% complete]
            -- [download 44% complete]
            -- [download 45% complete]
            -- [download 46% complete]
            -- [download 47% complete]
            -- [download 48% complete]
            -- [download 49% complete]
            -- [download 50% complete]
            -- [download 51% complete]
            -- [download 52% complete]
            -- [download 53% complete]
            -- [download 54% complete]
            -- [download 55% complete]
            -- [download 56% complete]
            -- [download 57% complete]
            -- [download 58% complete]
            -- [download 59% complete]
            -- [download 60% complete]
            -- [download 61% complete]
            -- [download 62% complete]
            -- [download 63% complete]
            -- [download 64% complete]
            -- [download 65% complete]
            -- [download 66% complete]
            -- [download 67% complete]
            -- [download 68% complete]
            -- [download 69% complete]
            -- [download 70% complete]
            -- [download 71% complete]
            -- [download 72% complete]
            -- [download 73% complete]
            -- [download 74% complete]
            -- [download 75% complete]
            -- [download 76% complete]
            -- [download 77% complete]
            -- [download 78% complete]
            -- [download 79% complete]
            -- [download 80% complete]
            -- [download 81% complete]
            -- [download 82% complete]
            -- [download 83% complete]
            -- [download 84% complete]
            -- [download 85% complete]
            -- [download 86% complete]
            -- [download 87% complete]
            -- [download 88% complete]
            -- [download 89% complete]
            -- [download 90% complete]
            -- [download 91% complete]
            -- [download 92% complete]
            -- [download 93% complete]
            -- [download 94% complete]
            -- [download 95% complete]
            -- [download 96% complete]
            -- [download 97% complete]
            -- [download 98% complete]
            -- [download 99% complete]
            -- [download 100% complete]
            -- verifying file...
                   file='/data/data/com.termux/files/usr/tmp/pip-install-xkz9abgj/cmake_a5e8189929be499799a15f557a5e0d9e/_skbuild/linux-aarch64-3.11/cmake-build/cmake-3.25.0.tar.gz'
            -- Downloading... done
            -- extracting...
                 src='/data/data/com.termux/files/usr/tmp/pip-install-xkz9abgj/cmake_a5e8189929be499799a15f557a5e0d9e/_skbuild/linux-aarch64-3.11/cmake-build/cmake-3.25.0.tar.gz'
                 dst='/data/data/com.termux/files/usr/tmp/pip-install-xkz9abgj/cmake_a5e8189929be499799a15f557a5e0d9e/CMake-src'
            -- extracting... [tar xfz]
            -- extracting... [analysis]
            -- extracting... [rename]
            -- extracting... [clean up]
            -- extracting... done
            [ 11%] No update step for 'CMakeProject-src-download'
            [ 15%] No patch step for 'CMakeProject-src-download'
            [ 19%] No configure step for 'CMakeProject-src-download'
            [ 23%] No build step for 'CMakeProject-src-download'
            [ 26%] No install step for 'CMakeProject-src-download'
            [ 30%] Completed 'CMakeProject-src-download'
            [ 30%] Built target CMakeProject-src-download
            [ 34%] Creating directories for 'CMakeProject-build'
            [ 38%] No download step for 'CMakeProject-build'
            [ 42%] No update step for 'CMakeProject-build'
            [ 46%] No patch step for 'CMakeProject-build'
            [ 50%] Performing configure step for 'CMakeProject-build'
            loading initial cache file /data/data/com.termux/files/usr/tmp/pip-install-xkz9abgj/cmake_a5e8189929be499799a15f557a5e0d9e/_skbuild/linux-aarch64-3.11/cmake-build/initial-cache.txt
            loading initial cache file /data/data/com.termux/files/usr/tmp/pip-install-xkz9abgj/cmake_a5e8189929be499799a15f557a5e0d9e/_skbuild/linux-aarch64-3.11/cmake-build/CMakeProject-build-prefix/tmp/CMakeProject-build-cache-Release.cmake
            -- The C compiler identification is Clang 15.0.6
            -- The CXX compiler identification is Clang 15.0.6
            -- Detecting C compiler ABI info
            -- Detecting C compiler ABI info - failed
            -- Check for working C compiler: /data/data/com.termux/files/usr/bin/cc
            -- Check for working C compiler: /data/data/com.termux/files/usr/bin/cc - broken
            CMake Error at /data/data/com.termux/files/usr/share/cmake-3.25/Modules/CMakeTestCCompiler.cmake:70 (message):
              The C compiler

                "/data/data/com.termux/files/usr/bin/cc"

              is not able to compile a simple test program.

              It fails with the following output:

                Change Dir: /data/data/com.termux/files/usr/tmp/pip-install-xkz9abgj/cmake_a5e8189929be499799a15f557a5e0d9e/_skbuild/linux-aarch64-3.11/cmake-build/CMakeProject-build/CMakeFiles/CMakeScratch/TryCompile-mVHLqL

                Run Build Command(s):/data/data/com.termux/files/usr/bin/make -f Makefile cmTC_b93c0/fast && make[3]: Entering directory '/data/data/com.termux/files/usr/tmp/pip-install-xkz9abgj/cmake_a5e8189929be499799a15f557a5e0d9e/_skbuild/linux-aarch64-3.11/cmake-build/CMakeProject-build/CMakeFiles/CMakeScratch/TryCompile-mVHLqL'
                /data/data/com.termux/files/usr/bin/make  -f CMakeFiles/cmTC_b93c0.dir/build.make CMakeFiles/cmTC_b93c0.dir/build
                make[4]: Entering directory '/data/data/com.termux/files/usr/tmp/pip-install-xkz9abgj/cmake_a5e8189929be499799a15f557a5e0d9e/_skbuild/linux-aarch64-3.11/cmake-build/CMakeProject-build/CMakeFiles/CMakeScratch/TryCompile-mVHLqL'
                Building C object CMakeFiles/cmTC_b93c0.dir/testCCompiler.c.o
                /data/data/com.termux/files/usr/bin/cc   -D_POSIX_C_SOURCE=199506L -D_POSIX_SOURCE=1 -D_SVID_SOURCE=1 -D_BSD_SOURCE=1  -O2 -g -DNDEBUG -MD -MT CMakeFiles/cmTC_b93c0.dir/testCCompiler.c.o -MF CMakeFiles/cmTC_b93c0.dir/testCCompiler.c.o.d -o CMakeFiles/cmTC_b93c0.dir/testCCompiler.c.o -c /data/data/com.termux/files/usr/tmp/pip-install-xkz9abgj/cmake_a5e8189929be499799a15f557a5e0d9e/_skbuild/linux-aarch64-3.11/cmake-build/CMakeProject-build/CMakeFiles/CMakeScratch/TryCompile-mVHLqL/testCCompiler.c
                Linking C executable cmTC_b93c0
                /data/data/com.termux/files/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_b93c0.dir/link.txt --verbose=1
                /data/data/com.termux/files/usr/bin/cc -D_POSIX_C_SOURCE=199506L -D_POSIX_SOURCE=1 -D_SVID_SOURCE=1 -D_BSD_SOURCE=1  -O2 -g -DNDEBUG -lstdc++ -lgcc -lrt  CMakeFiles/cmTC_b93c0.dir/testCCompiler.c.o -o cmTC_b93c0
                ld.lld: error: unable to find library -lgcc
                clang-15: error: linker command failed with exit code 1 (use -v to see invocation)
                make[4]: *** [CMakeFiles/cmTC_b93c0.dir/build.make:100: cmTC_b93c0] Error 1
                make[4]: Leaving directory '/data/data/com.termux/files/usr/tmp/pip-install-xkz9abgj/cmake_a5e8189929be499799a15f557a5e0d9e/_skbuild/linux-aarch64-3.11/cmake-build/CMakeProject-build/CMakeFiles/CMakeScratch/TryCompile-mVHLqL'
                make[3]: *** [Makefile:127: cmTC_b93c0/fast] Error 2
                make[3]: Leaving directory '/data/data/com.termux/files/usr/tmp/pip-install-xkz9abgj/cmake_a5e8189929be499799a15f557a5e0d9e/_skbuild/linux-aarch64-3.11/cmake-build/CMakeProject-build/CMakeFiles/CMakeScratch/TryCompile-mVHLqL'

              CMake will not be able to correctly generate this project.
            Call Stack (most recent call first):
              CMakeLists.txt:12 (project)

            -- Configuring incomplete, errors occurred!
            See also "/data/data/com.termux/files/usr/tmp/pip-install-xkz9abgj/cmake_a5e8189929be499799a15f557a5e0d9e/_skbuild/linux-aarch64-3.11/cmake-build/CMakeProject-build/CMakeFiles/CMakeOutput.log".
            See also "/data/data/com.termux/files/usr/tmp/pip-install-xkz9abgj/cmake_a5e8189929be499799a15f557a5e0d9e/_skbuild/linux-aarch64-3.11/cmake-build/CMakeProject-build/CMakeFiles/CMakeError.log".
            make[2]: *** [CMakeFiles/CMakeProject-build.dir/build.make:95: CMakeProject-build-prefix/src/CMakeProject-build-stamp/CMakeProject-build-configure] Error 1
            make[1]: *** [CMakeFiles/Makefile2:113: CMakeFiles/CMakeProject-build.dir/all] Error 2
            make: *** [Makefile:136: all] Error 2
            Traceback (most recent call last):
              File "/data/data/com.termux/files/usr/tmp/pip-build-env-eln0gjwk/overlay/lib/python3.11/site-packages/skbuild/setuptools_wrap.py", line 649, in setup
                cmkr.make(make_args, install_target=cmake_install_target, env=env)
              File "/data/data/com.termux/files/usr/tmp/pip-build-env-eln0gjwk/overlay/lib/python3.11/site-packages/skbuild/cmaker.py", line 686, in make
                self.make_impl(clargs=clargs, config=config, source_dir=source_dir, install_target=install_target, env=env)
              File "/data/data/com.termux/files/usr/tmp/pip-build-env-eln0gjwk/overlay/lib/python3.11/site-packages/skbuild/cmaker.py", line 717, in make_impl
                raise SKBuildError(

                =============================DEBUG ASSISTANCE=============================
                If you are seeing a compilation error please try the following steps to
                successfully install cmake:
                1) Upgrade to the latest pip and try again. This will fix errors for most
                   users. See: https://pip.pypa.io/en/stable/installing/#upgrading-pip
                2) If on Linux, with glibc < 2.12, you can set PIP_ONLY_BINARY=cmake in
                   order to retrieve the last manylinux1 compatible wheel.
                3) If on Linux, with glibc < 2.12, you can cap "cmake<3.23" in your
                   requirements in order to retrieve the last manylinux1 compatible wheel.
                4) Open an issue with the debug information that follows at
                   https://github.com/scikit-build/cmake-python-distributions/issues

                Python: 3.11.1
                platform: Linux-4.14.117-perf+-aarch64-with-libc
                machine: aarch64
                bits: 64
                pip: n/a
                setuptools: 66.1.1
                scikit-build: 0.16.6
                PEP517_BUILD_BACKEND=setuptools.build_meta
                =============================DEBUG ASSISTANCE=============================

            An error occurred while building with CMake.
              Command:
                /data/data/com.termux/files/usr/bin/cmake --build . --target install --config Release --
              Install target:
                install
              Source directory:
                /data/data/com.termux/files/usr/tmp/pip-install-xkz9abgj/cmake_a5e8189929be499799a15f557a5e0d9e
              Working directory:
                /data/data/com.termux/files/usr/tmp/pip-install-xkz9abgj/cmake_a5e8189929be499799a15f557a5e0d9e/_skbuild/linux-aarch64-3.11/cmake-build
            Please check the install target is valid and see CMake's output for more information.
            [end of output]

        note: This error originates from a subprocess, and is likely not a problem with pip.
        ERROR: Failed building wheel for cmake
      Failed to build cmake
      ERROR: Could not build wheels for cmake, which is required to install pyproject.toml-based projects
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

### What is the expected behavior?

For it to install

### System information

termux-info:

```
TERMUX_APK_RELEASE=F_DROID
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=12209
TERMUX_IS_DEBUGGABLE_BUILD=0
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://packages-cf.termux.dev/apt/termux-main stable main
Updatable packages:
apt/stable 2.5.5-1 aarch64 [upgradable from: 2.5.4]
binutils-bin/stable 2.40 aarch64 [upgradable from: 2.39-4]
binutils-libs/stable 2.40 aarch64 [upgradable from: 2.39-4]
binutils/stable 2.40 aarch64 [upgradable from: 2.39-4]
ca-certificates/stable 1:2023.01.10 all [upgradable from: 1:2022.10.11-1]
clang/stable 15.0.7 aarch64 [upgradable from: 15.0.6]
cmake/stable 3.25.2 aarch64 [upgradable from: 3.25.1]
command-not-found/stable 2.1.0-7 aarch64 [upgradable from: 2.1.0-3]
diffutils/stable 3.9 aarch64 [upgradable from: 3.8]
dpkg/stable 1.21.18 aarch64 [upgradable from: 1.21.15]
ed/stable 1.19 aarch64 [upgradable from: 1.18]
git/stable 2.39.1 aarch64 [upgradable from: 2.39.0]
glib/stable 2.74.5 aarch64 [upgradable from: 2.74.4-1]
gpgv/stable 2.4.0-2 aarch64 [upgradable from: 2.4.0]
libcompiler-rt/stable 15.0.7 aarch64 [upgradable from: 15.0.6]
libllvm/stable 15.0.7 aarch64 [upgradable from: 15.0.6]
liblzma/stable 5.4.1 aarch64 [upgradable from: 5.4.0]
libmpfr/stable 4.2.0 aarch64 [upgradable from: 4.1.1-2]
libraqm/stable 0.10.0 aarch64 [upgradable from: 0.9.0]
libwebp/stable 1.3.0 aarch64 [upgradable from: 1.2.4-1]
lld/stable 15.0.7 aarch64 [upgradable from: 15.0.6]
llvm/stable 15.0.7 aarch64 [upgradable from: 15.0.6]
lsof/stable 4.98.0 aarch64 [upgradable from: 4.96.5]
nano/stable 7.2 aarch64 [upgradable from: 7.1]
ncurses-ui-libs/stable 6.4-1 aarch64 [upgradable from: 6.4]
ncurses/stable 6.4-1 aarch64 [upgradable from: 6.4]
psmisc/stable 23.6-1 aarch64 [upgradable from: 23.6]
python-pillow/stable 9.4.0-1 aarch64 [upgradable from: 9.4.0]
python/stable 3.11.1-2 aarch64 [upgradable from: 3.11.1]
termux-tools/stable 1.36.1 all [upgradable from: 1.35.0]
unbound/stable 1.17.1 aarch64 [upgradable from: 1.17.0]
vim-runtime/stable 9.0.1200 all [upgradable from: 9.0.1100]
vim/stable 9.0.1200 aarch64 [upgradable from: 9.0.1100]
xz-utils/stable 5.4.1 aarch64 [upgradable from: 5.4.0]
termux-tools version:
1.35.0
Android version:
10
Kernel build information:
Linux localhost 4.14.117-perf+ #1 SMP PREEMPT Thu Jan 28 00:40:44 CST 2021 aarch64 Android
Device manufacturer:
OnePlus
Device model:
GM1900
```

**Comment by guranu** [comment]
> 

Please reopen this issue it still dosen't work

`~ $ pip install --no-build-isolation freetype-py
Collecting freetype-py
  Using cached freetype-py-2.3.0.zip (830 kB)
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [15 lines of output]
      /data/data/com.termux/files/usr/lib/python3.11/site-packages/setuptools/_distutils/dist.py:264: UserWarning: Unknown distribution option: 'use_scm_version'
        warnings.warn(msg)
      # Will use the system-provided FreeType.
      running dist_info
      creating /data/data/com.termux/files/usr/tmp/pip-modern-metadata-757x59rd/freetype_py.egg-info
      writing /data/data/com.termux/files/usr/tmp/pip-modern-metadata-757x59rd/freetype_py.egg-info/PKG-INFO
      writing dependency_links to /data/data/com.termux/files/usr/tmp/pip-modern-metadata-757x59rd/freetype_py.egg-info/dependency_links.txt
      writing top-level names to /data/data/com.termux/files/usr/tmp/pip-modern-metadata-757x59rd/freetype_py.egg-info/top_level.txt
      writing manifest file '/data/data/com.termux/files/usr/tmp/pip-modern-metadata-757x59rd/freetype_py.egg-info/SOURCES.txt'
      reading manifest file '/data/data/com.termux/files/usr/tmp/pip-modern-metadata-757x59rd/freetype_py.egg-info/SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      adding license file 'LICENSE.txt'
      writing manifest file '/data/data/com.termux/files/usr/tmp/pip-modern-metadata-757x59rd/freetype_py.egg-info/SOURCES.txt'
      creating '/data/data/com.termux/files/usr/tmp/pip-modern-metadata-757x59rd/freetype_py-0.0.0.dist-info'
      error: invalid command 'bdist_wheel'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
~ $ pip install --no-build-isolation freetype-py
Collecting freetype-py
  Using cached freetype-py-2.3.0.zip (830 kB)
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [15 lines of output]
      /data/data/com.termux/files/usr/lib/python3.11/site-packages/setuptools/_distutils/dist.py:264: UserWarning: Unknown distribution option: 'use_scm_version'
        warnings.warn(msg)
      # Will use the system-provided FreeType.
      running dist_info
      creating /data/data/com.termux/files/usr/tmp/pip-modern-metadata-36ykof6m/freetype_py.egg-info
      writing /data/data/com.termux/files/usr/tmp/pip-modern-metadata-36ykof6m/freetype_py.egg-info/PKG-INFO
      writing dependency_links to /data/data/com.termux/files/usr/tmp/pip-modern-metadata-36ykof6m/freetype_py.egg-info/dependency_links.txt
      writing top-level names to /data/data/com.termux/files/usr/tmp/pip-modern-metadata-36ykof6m/freetype_py.egg-info/top_level.txt
      writing manifest file '/data/data/com.termux/files/usr/tmp/pip-modern-metadata-36ykof6m/freetype_py.egg-info/SOURCES.txt'
      reading manifest file '/data/data/com.termux/files/usr/tmp/pip-modern-metadata-36ykof6m/freetype_py.egg-info/SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      adding license file 'LICENSE.txt'
      writing manifest file '/data/data/com.termux/files/usr/tmp/pip-modern-metadata-36ykof6m/freetype_py.egg-info/SOURCES.txt'
      creating '/data/data/com.termux/files/usr/tmp/pip-modern-metadata-36ykof6m/freetype_py-0.0.0.dist-info'
      error: invalid command 'bdist_wheel'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above`

**Comment by guranu** [comment]
Can you please reopen this issue "pip install --no-build-isolation freetype-py" also didn't work.
