### ISSUE TITLE
[Bug]: Problems with pip

### ISSUE THREAD

**Issue by RuslanFF** [termux/termux-packages#14838]
### Problem description

If you try to remove the module by pip uninstall you get the same error. Also if you try to install dependencies (pip install -r requirements) you get exactly the same error

Error:

$ pip uninstall colorama
ERROR: Exception:
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/pip/_internal/cli/base_command.py", line 160, in exc_logging_wrapper
    status = run_func(*args)
             ^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/pip/_internal/commands/uninstall.py", line 64, in run
    session = self.get_default_session(options)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/pip/_internal/cli/req_command.py", line 98, in get_default_session
    self._session = self.enter_context(self._build_session(options))
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/pip/_internal/cli/req_command.py", line 125, in _build_session
    session = PipSession(
              ^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/pip/_internal/network/session.py", line 343, in __init__
    self.headers["User-Agent"] = user_agent()
                                 ^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/pip/_internal/network/session.py", line 140, in user_agent
    linux_distribution = distro.name(), distro.version(), distro.codename()
                         ^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/pip/_vendor/distro/distro.py", line 319, in name
    return _distro.name(pretty)
           ^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/pip/_vendor/distro/distro.py", line 865, in name
    or self.lsb_release_attr("distributor_id")
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/pip/_vendor/distro/distro.py", line 1066, in lsb_release_attr
    return self._lsb_release_info.get(attribute, "")
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/functools.py", line 1001, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/pip/_vendor/distro/distro.py", line 1161, in _lsb_release_info
    stdout = subprocess.check_output(cmd, stderr=subprocess.DEVNULL)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/run/__init__.py", line 145, in __new__
    process = cls.create_process(command, stdin, cwd=cwd, env=env, shell=shell)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/run/__init__.py", line 121, in create_process
    shlex.split(command),
    ^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/shlex.py", line 315, in split
    return list(lex)
           ^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/shlex.py", line 300, in __next__
    token = self.get_token()
            ^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/shlex.py", line 109, in get_token
    raw = self.read_token()
          ^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/shlex.py", line 140, in read_token
    nextchar = self.instream.read(1)
               ^^^^^^^^^^^^^^^^^^
AttributeError: 'tuple' object has no attribute 'read'

### What steps will reproduce the bug?

pip install -r requirements
pip uninstall 

### What is the expected behavior?

Module must be removed, dependencies will be installed 

### System information

termux-info:

```
Termux Variables:
TERMUX_APK_RELEASE=F_DROID
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=15853
TERMUX_IS_DEBUGGABLE_BUILD=0
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://packages-cf.termux.dev/apt/termux-main/ stable main
Updatable packages:
All packages up to date
termux-tools version:
1.36.1
Android version:
10
Kernel build information:
Linux localhost 4.9.190+ #1 SMP PREEMPT Mon Jun 13 16:28:27 CST 2022 aarch64 Android
Device manufacturer:
LENOVO
Device model:
Lenovo TB-X606X
```

**Comment by xtkoba** [comment]
Seems like the same as https://github.com/python/cpython/issues/86565.

I don't know which package the directory `[...]/site-packages/run` belongs to, but I recommend removing it.

**Comment by RuslanFF** [comment]
The problem with all the modules that I am trying to remove now try to reinstall termux if anything I will write

**Comment by RuslanFF** [comment]
After reinstalling the termux it all worked
