### ISSUE TITLE
[Bug]: Failed to run venv with python 3.11.2

### ISSUE THREAD

**Issue by hahastudio** [termux/termux-packages#15111]
### Problem description

When I try to run venv, it shows errors:
```
$ python -m venv .
Error: Command '['/data/data/com.termux/files/home/jupyter/gpt-60lines/picoGPT/bin/python', '-m', 'ensurepip', '--upgrade', '--default-pip']' returned non-zero exit status 1.
$ python -m ensurepip --upgrade --default-pip
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/data/data/com.termux/files/usr/lib/python3.11/ensurepip/__main__.py", line 5, in <module>
    sys.exit(ensurepip._main())
             ^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/ensurepip/__init__.py", line 286, in _main
    return _bootstrap(
           ^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/ensurepip/__init__.py", line 178, in _bootstrap
    whl = wheel_path.read_bytes()
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/pathlib.py", line 1050, in read_bytes
    with self.open(mode='rb') as f:
         ^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/pathlib.py", line 1044, in open
    return io.open(self, mode, buffering, encoding, errors, newline)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/data/data/com.termux/files/usr/lib/python3.11/ensurepip/_bundled/setuptools-65.5.0-py3-none-any.whl'
```

I checked that the path `/data/data/com.termux/files/usr/lib/python3.11/ensurepip/_bundled` doesn't exist.
`bin` folder is generated by `venv`.

Gernal info:
* Python 3.11.2 in /data/data/com.termux/files/usr/bin/python
* pip 23.0 in /data/data/com.termux/files/usr/lib/python3.11/site-packages/pip

### What steps will reproduce the bug?

1. upgrade python & python-pip
2. go to a folder and run `python -m venv .`

### System information

termux-info:

```
Termux Variables:
TERMUX_APK_RELEASE=F_DROID
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=8744
TERMUX_IS_DEBUGGABLE_BUILD=0
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://mirror.iscas.ac.cn/termux/apt/termux-main stable main
# x11-repo (sources.list.d/x11.list)
deb https://mirror.iscas.ac.cn/termux/apt/termux-x11 x11 main
Updatable packages:
All packages up to date
termux-tools version:
1.36.1
Android version:
13
Kernel build information:
Linux localhost 5.10.81-android12-9-25665538-abF9360ZSS1BWA2 #1 SMP PREEMPT Mon Jan 9 03:11:11 UTC 2023 aarch64 Android
Device manufacturer:
samsung
Device model:
SM-F9360
```

**Comment by xtkoba** [comment]
Please install `python-ensurepip-wheels`. Maybe this should be recommended.

**Comment by hahastudio** [comment]
@xtkoba thanks! It works!
