### ISSUE TITLE
[Package]: Dependencies of Autokey

### ISSUE THREAD

**Issue by starmonger999** [termux/termux-packages#15198]
### Why do you want to add this package to Termux?

programmable hotkey app.

### Home page URL

https://github.com/autokey/autokey

### Source code URL

https://github.com/autokey/autokey

### Packaging policy acknowledgement

- [X] The requested package complies with [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

### Additional information

It seems to install fine through pip but when you try to run it, you get
``` 
autokey-gtk
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/autokey/gtkui/notifier.py", line 29, in <module>
    gi.require_version('AyatanaAppIndicator3', '0.1')
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/gi/__init__.py", line 126, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace AyatanaAppIndicator3 not available

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/bin/autokey-gtk", line 5, in <module>
    from autokey.gtkui.__main__ import main
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/autokey/gtkui/__main__.py", line 4, in <module>
    from autokey.gtkapp import Application
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/autokey/gtkapp.py", line 40, in <module>
    from autokey.gtkui.notifier import get_notifier
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/autokey/gtkui/notifier.py", line 31, in <module>
    gi.require_version('AppIndicator3', '0.1')
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/gi/__init__.py", line 126, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace AppIndicator3 not available
```

**Comment by xtkoba** [comment]
Dependencies guessed from the source (not exhaustive):

- [X] dbus-python
- [X] gtksourceview3
- [ ] libayatana-appindicator
- [X] libnotify
- [X] pygobject
- [ ] wmctrl
- [X] zenity

Depends on GIR naturally.
