### ISSUE TITLE
[Bug]: problem with `random` module in python arm

### ISSUE THREAD

**Issue by Maxython** [termux/termux-packages#15199]
### Problem description

When importing the `random` module, the following error is displayed:
```python
Traceback (most recent call last):
    File "<stdin>", line 1, in <module>
    File "/data/data/com.termux/files/usr/lib/python3.11/random.py", line 58, in <module>
        import _random
ImportError: dlopen failed: cannot locate symbol "hypot" referenced by "/data/data/com.termux/files/usr/lib/python3.11/lib-dynload/_random.cpython-311.so"...
```

### What steps will reproduce the bug?

This error only appears on arm devices.

### System information

termux-info:
```
Termux Variables:
TERMUX_API_VERSION=0.48
TERMUX_APK_RELEASE=F_DROID
TERMUX_APP_PACKAGE_MANAGER=pacman
TERMUX_APP_PID=2441
TERMUX_IS_DEBUGGABLE_BUILD=0
TERMUX_MAIN_PACKAGE_FORMAT=pacman
TERMUX_VERSION=0.118.0
Packages CPU architecture:
arm
Subscribed repositories:
# /data/data/com.termux/files/usr/etc/pacman.conf
[main]
Usage = All
Server = https://service.termux-pacman.dev/main/arm
[x11]
Usage = All
Server = https://service.termux-pacman.dev/x11/arm
[root]
Usage = All
Server = https://service.termux-pacman.dev/root/arm
[tur]
Usage = All
Server = https://service.termux-pacman.dev/tur/arm
[tur-continuous]
Usage = All
Server = https://service.termux-pacman.dev/tur-continuous/arm
[tur-multilib]
Usage = All
Server = https://service.termux-pacman.dev/tur-multilib/arm
Updatable packages:
All packages up to date
termux-tools version:
1.37.0
Android version:
13
Kernel build information:
Linux localhost 4.14.113-25357580 #1 SMP PREEMPT Thu Nov 24 15:41:21 KST 2022 armv8l Android
Device manufacturer:
samsung
Device model:
SM-A515F
LD Variables:
LD_LIBRARY_PATH=
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so
```

**Comment by xtkoba** [comment]
Is this only for pacman package? The `_random` extension (*) in `python_3.11.2-2_arm.deb` does not seem to have any reference to `hypot`.

(*) `lib/python3.11/lib-dynload/_random.cpython-311.so`

Where can we get the pacman package?

**Comment by Grimler91** [comment]
I can't reproduce the issue on my arm device:

```
$ python -c "import random"
$ termux-info
Termux Variables:
TERMUX_API_APP__VERSION_NAME=0.50.1
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP__AM_SOCKET_SERVER_ENABLED=true
TERMUX_APP__APK_PATH=/data/app/~~jEmUSByi-Byt7HMYxM_cKw==/com.termux-BuuSpk9yfzSB9DBd0Oj6jw==/base.apk
TERMUX_APP__APK_RELEASE=UNKNOWN
TERMUX_APP__FILES_DIR=/data/user/0/com.termux/files
TERMUX_APP__IS_DEBUGGABLE_BUILD=false
TERMUX_APP__IS_INSTALLED_ON_EXTERNAL_STORAGE=false
TERMUX_APP__PACKAGE_MANAGER=apt
TERMUX_APP__PACKAGE_NAME=com.termux
TERMUX_APP__PACKAGE_VARIANT=apt-android-7
TERMUX_APP__PID=4680
TERMUX_APP__SE_FILE_CONTEXT=u:object_r:app_data_file:s0:c146,c256,c512,c768
TERMUX_APP__SE_INFO=default:targetSdkVersion=28:complete
TERMUX_APP__SE_PROCESS_CONTEXT=u:r:untrusted_app_27:s0:c146,c256,c512,c768
TERMUX_APP__TARGET_SDK=28
TERMUX_APP__UID=10146
TERMUX_APP__USER_ID=0
TERMUX_APP__VERSION_CODE=118
TERMUX_APP__VERSION_NAME=0.118.0
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
Packages CPU architecture:
arm
Subscribed repositories:
# sources.list
deb https://mirror.termux.dev/termux-main stable main
# root-repo (sources.list.d/root.list)
deb https://mirror.termux.dev/termux-root root stable
# x11-repo (sources.list.d/x11.list)
deb https://mirror.termux.dev/termux-x11 x11 main
Updatable packages:
All packages up to date
termux-tools version:
1.37.0
Android version:
11
Kernel build information:
Linux localhost 3.4.113-g28a19fc95c0c #40 SMP PREEMPT Tue Jul 12 22:28:01 CEST 2022 armv7l Android
Device manufacturer:
samsung
Device model:
SM-T800
LD Variables:
LD_LIBRARY_PATH=
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so
```

**Comment by Maxython** [comment]
> Where can we get the pacman package?

https://service.termux-pacman.dev/main/arm/

**Comment by xtkoba** [comment]
OK. For https://service.termux-pacman.dev/main/arm/python-3.11.2-2-arm.pkg.tar.xz:

```
$ readelf -Wa ./lib/python3.11/lib-dynload/_random.cpython-311.so | grep -E 'NOTYPE\s+GLOBAL\s+DEFAULT\s+UND'
    15: 00000000     0 NOTYPE  GLOBAL DEFAULT  UND hypot
    16: 00000000     0 NOTYPE  GLOBAL DEFAULT  UND atan2
    17: 00000000     0 NOTYPE  GLOBAL DEFAULT  UND pow
    18: 00000000     0 NOTYPE  GLOBAL DEFAULT  UND exp
    19: 00000000     0 NOTYPE  GLOBAL DEFAULT  UND log
    20: 00000000     0 NOTYPE  GLOBAL DEFAULT  UND sincos
    21: 00000000     0 NOTYPE  GLOBAL DEFAULT  UND floor
    22: 00000000     0 NOTYPE  GLOBAL DEFAULT  UND frexp
    23: 00000000     0 NOTYPE  GLOBAL DEFAULT  UND modf
    25: 00000000     0 NOTYPE  GLOBAL DEFAULT  UND fmod
    26: 00000000     0 NOTYPE  GLOBAL DEFAULT  UND ceil
    27: 00000000     0 NOTYPE  GLOBAL DEFAULT  UND round
```

Due to underlinking against libm. I don't know why this happens only for pac though.

**Comment by Maxython** [comment]
As I understand it, either this happens due to incorrect compilation logic in pacman, or it just happened in pacman so far, but they managed to compile successfully in apt (you need a test compilation).

**Comment by xtkoba** [comment]
The size of `_random.cpython-311.so` from `python_3.11.2-2_arm.deb` is 9144 bytes, whereas that from `python-3.11.2-2-arm.pkg.tar.xz` is 3322576 bytes. I would say the latter is too large and that cannot happen normally.

**Comment by xtkoba** [comment]
Is this reproducible when rebuilding the package?

**Comment by Maxython** [comment]
> Is this reproducible when rebuilding the package?

Recompiling the package does not fix this problem

**Comment by Maxython** [comment]
Ummm, after compiling in a separate branch, python worked...
https://github.com/termux-pacman/termux-packages/pull/6

**Comment by Maxython** [comment]
Fixed, after recompiling python works. Why it didn't work the first time, I don't know.
