### ISSUE TITLE
[Bug]: autokey-gtk not starting up

### ISSUE THREAD

**Issue by starmonger999** [termux/termux-packages#15348]
### Problem description

```
~ $ autokey-gtk 
2023-02-24 18:02:28,921 INFO - autokey.UI_common_functions - Commandline program "visgrep" was not found/able to be used correctly by AutoKey. This program is optional for Autokey operation, but if you wish to use functionality associated with it, Check that "visgrep" exists on your system and is in the $PATH seen by Autokey.
2023-02-24 18:02:28,922 INFO - autokey.UI_common_functions - Commandline program "import" was not found/able to be used correctly by AutoKey. This program is optional for Autokey operation, but if you wish to use functionality associated with it, Check that "import" exists on your system and is in the $PATH seen by Autokey.
2023-02-24 18:02:28,923 INFO - autokey.UI_common_functions - Commandline program "png2pat" was not found/able to be used correctly by AutoKey. This program is optional for Autokey operation, but if you wish to use functionality associated with it, Check that "png2pat" exists on your system and is in the $PATH seen by Autokey.
2023-02-24 18:02:28,923 INFO - autokey.UI_common_functions - Commandline program "xte" was not found/able to be used correctly by AutoKey. This program is optional for Autokey operation, but if you wish to use functionality associated with it, Check that "xte" exists on your system and is in the $PATH seen by Autokey.
2023-02-24 18:02:28,923 INFO - autokey.UI_common_functions - Commandline program "xmousepos" was not found/able to be used correctly by AutoKey. This program is optional for Autokey operation, but if you wish to use functionality associated with it, Check that "xmousepos" exists on your system and is in the $PATH seen by Autokey.
2023-02-24 18:02:28,926 INFO - autokey.gtkapp - Initialising application
2023-02-24 18:02:30,332 INFO - autokey.gtkapp - Initialise global hotkeys
2023-02-24 18:02:30,338 INFO - autokey.configmanager.configmanager - Loading config from existing file: /data/data/com.termux/files/home/.config/autokey/autokey.json
2023-02-24 18:02:30,345 INFO - autokey.configmanager.version_upgrading - Checking if upgrade is needed from version 0.96.0
2023-02-24 18:02:30,412 INFO - autokey.configmanager.configmanager - Configuration changed - rebuilding in-memory structures
2023-02-24 18:02:30,414 INFO - autokey.configmanager.configmanager - Successfully loaded configuration
2023-02-24 18:02:30,415 INFO - autokey.service - Starting service
2023-02-24 18:02:30,461 ERROR - autokey.gtkapp - Error starting interface: Can't connect to display ":1.0": [Errno 111] Connection refused
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/Xlib/support/unix_connect.py", line 104, in get_socket
    s = _get_unix_socket(address)
        ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/Xlib/support/unix_connect.py", line 82, in _get_unix_socket
    s.connect(address)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/Xlib/support/unix_connect.py", line 108, in get_socket
    s = _get_tcp_socket(host, dno)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/Xlib/support/unix_connect.py", line 76, in _get_tcp_socket
    s.connect((host, 6000 + dno))
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/autokey/gtkapp.py", line 111, in initialise
    self.service.start()
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/autokey/service.py", line 91, in start
    self.mediator = IoMediator(self)
                    ^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/autokey/iomediator/iomediator.py", line 67, in __init__
    self.interface = XRecordInterface(self, service.app)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/autokey/interface.py", line 216, in __init__
    self.__initMappings()
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/autokey/interface.py", line 270, in __initMappings
    self.localDisplay = display.Display()
                        ^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/Xlib/display.py", line 89, in __init__
    self.display = _BaseDisplay(display)
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/Xlib/display.py", line 71, in __init__
    protocol_display.Display.__init__(self, *args, **keys)
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/Xlib/protocol/display.py", line 89, in __init__
    self.socket = connect.get_socket(name, protocol, host, displayno)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/Xlib/support/connect.py", line 87, in get_socket
    return mod.get_socket(dname, protocol, host, dno)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/Xlib/support/unix_connect.py", line 112, in get_socket
    raise error.DisplayConnectionError(dname, str(val))
Xlib.error.DisplayConnectionError: Can't connect to display ":1.0": [Errno 111] Connection refused
```
afterwards when you click on the ok on the error prompt, it prints
```
2023-02-24 18:03:00,858 INFO - autokey.gtkapp - Entering main()
```
then stalls indefinitely.

### What steps will reproduce the bug?

1. pkg install wmctrl and libayatana-appindicator
2. pip install autokey
3. run autokey-gtk

### System information

termux-info:

```
Termux Variables:
TERMUX_APK_RELEASE=F_DROID
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=27006
TERMUX_IS_DEBUGGABLE_BUILD=0
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://mirror.bardia.tech/termux/termux-main stable main
# x11-repo (sources.list.d/x11.list)
deb https://mirror.bardia.tech/termux/termux-x11 x11 main
Updatable packages:
All packages up to date
termux-tools version:
1.37.0
Android version:
13
Kernel build information:
Linux localhost 4.14.113-25436157 #1 SMP PREEMPT Fri Jan 13 18:52:03 +07 2023 aarch64 Android
Device manufacturer:
samsung
Device model:
SM-P610
LD Variables:
LD_LIBRARY_PATH=
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so

```

**Comment by starmonger999** [comment]
images:
![Screenshot_20230224_180250_TermuxX11](https://user-images.githubusercontent.com/75457973/221188546-5f481c46-4268-412a-8765-c367340d1787.jpg)
![Screenshot_20230224_180311_TermuxX11](https://user-images.githubusercontent.com/75457973/221188574-32dc996c-3c9f-404f-bd21-6e81e60c5808.jpg)

**Comment by xtkoba** [comment]
A workaround (fixing hardcoded `/tmp`):

```diff
--- lib/python3.11/site-packages/Xlib/support/unix_connect.py.orig
+++ lib/python3.11/site-packages/Xlib/support/unix_connect.py
@@ -96,7 +96,7 @@
 
         # Unix socket.
         else:
-            address = '/tmp/.X11-unix/X%d' % dno
+            address = '/data/data/com.termux/files/usr/tmp/.X11-unix/X%d' % dno
             if not os.path.exists(address):
                 # Use abstract address.
                 address = '\0' + address
```

Note that this file is from `python-xlib` installed through pip. We do not have a mechanism to automatically patch this on the fly, unfortunately.

**Comment by xtkoba** [comment]
Workaround provided. Closing.

**Comment by xtkoba** [comment]
I noticed that now disabled `python2-xlib` package has exact the same workaround:

https://github.com/termux/termux-packages/blob/6988192dfd12144c8874f51585bba6a214aeb948/disabled-packages/python2-xlib/python-xlib-0.20_Xlib_support_unix_connect.py.patch

This package (`python2-xlib`) is disabled solely because this depends on `python2` which is EOL and unsupported upstream and has a bunch of known vulnerabilities. Not because of our packaging policy for Python modules.

So I believe we have a good reason to package `python-xlib` on our own, and I'm going to work on it. Thanks.
