### ISSUE TITLE
[Bug]: Trying to run AsciiDoctor results in /data/data/com.termux/files/usr/lib/ruby/3.2.0/rubygems.rb:263:in `find_spec_for_exe': can't find gem asciidoctor (>= 0.a) 

### ISSUE THREAD

**Issue by Oblomov** [termux/termux-packages#15539]
### Problem description

Any attempt to run `asciidoctor` results in the mentiond error. The full backtrace is:
```
/data/data/com.termux/files/usr/lib/ruby/3.2.0/rubygems.rb:263:in `find_spec_for_exe': can't find gem asciidoctor (>= 0.a) with executable asciidoctor (Gem::GemNotFoundException)
        from /data/data/com.termux/files/usr/lib/ruby/3.2.0/rubygems.rb:282:in `activate_bin_path'
        from /data/data/com.termux/files/usr/bin/asciidoctor:25:in `<main>'
```
Also note the weird version (0.a) sought by the rubygems.

### What steps will reproduce the bug?

```
pkg install asciidoctor
asciidoctor --version
```

### What is the expected behavior?

AsciiDoctor shows the version number and Ruby version.

### System information

termux-info:

```
Termux Variables:
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://mirror.accum.se/mirror/termux.dev/termux-main stable main
# x11-repo (sources.list.d/x11.list)
deb https://mirror.accum.se/mirror/termux.dev/termux-x11 x11 main
Updatable packages:
All packages up to date
termux-tools version:
1.37.0
Android version:
11
Kernel build information:
Linux localhost 4.14.113-user+ #1 SMP PREEMPT Mon May 30 00:16:49 CDT 2022 aarch64 Android
Device manufacturer:
motorola
Device model:
motorola one vision
LD Variables:
LD_LIBRARY_PATH=
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so
```
Additional information:
```
$ pkg show asciidoctor
Package: asciidoctor
Version: 2.0.18
Maintainer: @termux
Installed-Size: 6570 kB
Depends: ruby
Homepage: https://asciidoctor.org/
Download-Size: 593 kB
APT-Manual-Installed: yes
APT-Sources: https://mirror.accum.se/mirror/termux.dev/termux-main stable/main aarch64 Packages
Description: An implementation of AsciiDoc in Ruby
```

**Comment by Oblomov** [comment]
Thank you very much!
