### ISSUE TITLE
How to install python-qscintilla

### ISSUE THREAD

**Issue by risky777** [termux/termux-packages#15653]
Hi,

I'm trying to start eric-ide (python-ide), old eric6 which runs on pyqt5. I did:
- pkg install pyqt5 qscintilla
- eric-requirements except pyqt-stuff through pip
- eric6 setup.py
But it seems that qscintilla is not detected in python, "pip list" doesn't show it, and I get following error:

QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/data/data/com.termux/files/usr/tmp/runtime-u0_a239'
Error in sys.excepthook:
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/eric6/Utilities/__init__.py", line 50, in <module>
    from PyQt5.Qsci import QSCINTILLA_VERSION_STR, QsciScintilla
ModuleNotFoundError: No module named 'PyQt5.Qsci'

Original exception was:
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/eric6/eric6.py", line 417, in <module>
    main()
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/eric6/eric6.py", line 302, in main
    import Preferences
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/eric6/Preferences/__init__.py", line 37, in <module>
    from PyQt5.Qsci import QsciScintilla, QsciLexerPython
ModuleNotFoundError: No module named 'PyQt5.Qsci'

**Comment by xtkoba** [comment]
Please use our official package which will soon become available:

```bash
pkg install python-qscintilla
```

Seems like it fails to install through pip (`pip install QScintilla`) somehow and the error message (`_in_process.py: 'make' failed returning 2`) is of no use. It was much easier for me to make a package for this than to find a workaround.
