### ISSUE TITLE
Package Request :Gstreamer 

### ISSUE THREAD

**Issue by Xarchuser** [termux/termux-packages#1570]
I've installed the mopidy package through the pip command, however, it says that a Gstreamer C library is required to run perfectly , is there any possibility of Gstreamer works in the Termux or that's impossible?

The error :
`mopidy`                                                           
`ERROR: A GObject Python package was not found.`

`Mopidy requires GStreamer to work. GStreamer is a C library with a      number of dependencies itself, and cannot be installed with the regular
Python tools like pip.`

`Please see http://docs.mopidy.com/en/latest/installation/ for
instructions on how to install the required dependencies.               
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/bin/mopidy", line 11, in <module>
    load_entry_point('Mopidy==2.1.0', 'console_scripts', 'mopidy')()
  File "/data/data/com.termux/files/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 565, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/data/data/com.termux/files/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2631, in load_entry_point
    return ep.load()
  File "/data/data/com.termux/files/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2291, in load
    return self.resolve()
  File "/data/data/com.termux/files/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2297, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/data/data/com.termux/files/usr/lib/python2.7/site-packages/Mopidy-2.1.0-py2.7.egg/mopidy/__main__.py", line 8, in <module>
    from mopidy.internal.gi import Gst  # noqa: F401
  File "/data/data/com.termux/files/usr/lib/python2.7/site-packages/Mopidy-2.1.0-py2.7.egg/mopidy/internal/gi.py", line 8, in <module>
    import gi
ImportError: No module named gi`

**Comment by Grimler91** [comment]
Hi, this has been asked before, see https://github.com/termux/termux-packages/issues/289

There hasn't been any response though

**Comment by Xarchuser** [comment]
Yeah I know but I think the developer forgot to include yet, so just to remind.

**Comment by fornwall** [comment]
Closing this in favour of #289. I'm not working on gstreamer myself, but there exists a start at `disabled-packages/gstreamer`, `disabled-packages/gst-plugins-base` and `disabled-packages/gst-plugins-bad`, which someone would need to pick up and updated, fix and test before enabling!

**Comment by tristan-k** [comment]
@Xarchuser Can you provide more details which termux packages are required for mopdiy?

**Comment by araczkowski** [comment]
Hi, I think that for Mopidy we need an Python GStreamer supplement -> python-gst-1.0
https://github.com/GStreamer/gst-python
I'm new to Termux - please give me any clue how to add this package to Termux repo?
Thx

**Comment by darkphoenix** [comment]
Termux might have GStreamer, but it's still lacking gst-python, making running Mopidy pretty hard - building it on an Android device isn't really fun.
