### ISSUE TITLE
[Bug]: python-pyarrow not built with parquet support even though libarrow-cpp is

### ISSUE THREAD

**Issue by rockwalrus** [termux/termux-packages#16049]
### Problem description

The `python-pyarrow` is not being built with parquet support even though its dependency, `libarrow-cpp` is built with parquet support.

### What steps will reproduce the bug?

```
~ $ datasets-cli                                        
Traceback (most recent call last):                      
  File "/data/data/com.termux/files/usr/bin/datasets-cli", line 5, in <module>                                  
    from datasets.commands.datasets_cli import main     
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/datasets/__init__.py", line 43, in <module>
    from .arrow_dataset import Dataset                    
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/datasets/arrow_dataset.py", line 65, in <module>                                                    
    from .arrow_reader import ArrowReader                 
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/datasets/arrow_reader.py", line 28, in <module>                                                  
    import pyarrow.parquet as pq                       
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/pyarrow/parquet/__init__.py", line 20, in <module>                                                
    from .core import *                               
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/pyarrow/parquet/core.py", line 36, in <module>                                                  
    import pyarrow._parquet as _parquet                 
ModuleNotFoundError: No module named 'pyarrow._parquet' ~
```

### System information

termux-info:

```
Termux Variables:                                       TERMUX_APK_RELEASE=F_DROID                              TERMUX_APP_PACKAGE_MANAGER=apt                          TERMUX_APP_PID=6108                                     TERMUX_IS_DEBUGGABLE_BUILD=0                            TERMUX_MAIN_PACKAGE_FORMAT=debian                       TERMUX_VERSION=0.118.0                                  Packages CPU architecture:                              aarch64                                                 Subscribed repositories:                                # sources.list                                          deb https://dl.kcubeterm.com/termux-main stable main    Updatable packages:                                     All packages up to date                                 termux-tools version:                                   1.37.0                                                  Android version:                                        13                                                      Kernel build information:                               Linux localhost 5.10.107-android13-4-00020-g02b5dfab573c-ab9358130 #1 SMP PREEMPT Thu Dec 1 18:28:18 UTC 2022 aarch64 Android                                           Device manufacturer:                                    Google                                                  Device model:                                           Pixel 6                                                 LD Variables:                                           LD_LIBRARY_PATH=                                        LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so
```

**Comment by rockwalrus** [comment]
Thank you!
