### ISSUE TITLE
[Bug]: shm_open deprecation causes bug in python-torch

### ISSUE THREAD

**Issue by nacho00112** [termux/termux-packages#16408]
### Problem description

I want to run the famous [minGPT](https://github.com/karpathy/minGPT) , but i can't, the repository size is 1MB

### What steps will reproduce the bug?

```bash
pkg install python-torch
pip cache purge
pkg clean
mkdir git
cd git
git clone https://github.com/karpathy/minGPT
cd *
pip install -e .
cd projects/chargpt
wget https://raw.githubusercontent.com/karpathy/char-rnn/master/data/tinyshakespeare/input.txt
python chargpt.py

This outputs:

system:
    seed: 3407
    work_dir: ./out/chargpt
data:
    block_size: 128
model:
    model_type: gpt-mini
    n_layer: None
    n_head: None
    n_embd: None
    vocab_size: None
    block_size: None
    embd_pdrop: 0.1
    resid_pdrop: 0.1
    attn_pdrop: 0.1
trainer:
    device: auto
    num_workers: 4
    max_iters: None
    batch_size: 64
    learning_rate: 0.0005
    betas: (0.9, 0.95)
    weight_decay: 0.1
    grad_norm_clip: 1.0

data has [1115394](tel:1115394) characters, 65 unique.
number of parameters: 2.71M
running on device cpu
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/git/minGPT/projects/chargpt/chargpt.py", line 133, in <module>
    trainer.run()
  File "/data/data/com.termux/files/home/git/minGPT/mingpt/trainer.py", line 85, in run
    batch = next(data_iter)
            ^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/torch/utils/data/dataloader.py", line 634, in __next__
    data = self._next_data()
           ^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/torch/utils/data/dataloader.py", line 1346, in _next_data
    return self._process_data(data)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/torch/utils/data/dataloader.py", line 1372, in _process_data
    data.reraise()
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/torch/_utils.py", line 644, in reraise
    raise exception
RuntimeError: Caught RuntimeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/torch/utils/data/_utils/worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)
           ^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/torch/utils/data/_utils/fetch.py", line 54, in fetch
    return self.collate_fn(data)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/torch/utils/data/_utils/collate.py", line 264, in default_collate
    return collate(batch, collate_fn_map=default_collate_fn_map)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/torch/utils/data/_utils/collate.py", line 142, in collate
    return [collate(samples, collate_fn_map=collate_fn_map) for samples in transposed]  # Backwards compatibility.
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/torch/utils/data/_utils/collate.py", line 142, in <listcomp>
    return [collate(samples, collate_fn_map=collate_fn_map) for samples in transposed]  # Backwards compatibility.
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/torch/utils/data/_utils/collate.py", line 119, in collate
    return collate_fn_map[elem_type](batch, collate_fn_map=collate_fn_map)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/torch/utils/data/_utils/collate.py", line 160, in collate_tensor_fn
    storage = elem._typed_storage()._new_shared(numel, device=elem.device)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/torch/storage.py", line 709, in _new_shared
    untyped_storage = torch.UntypedStorage._new_shared(size * self._element_size(), device=device)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/torch/storage.py", line 224, in _new_shared
    return cls._new_using_fd_cpu(size)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: unable to open file </torch_[30057](tel:30057)_[527370446](tel:527370446)_0> in sharedmem mode, shm_open unavailable on this platform
```

### What is the expected behavior?

chargpt.py to run with no error

### System information
termux-info
```
Termux Variables:
TERMUX_APK_RELEASE=F_DROID
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=26831
TERMUX_IS_DEBUGGABLE_BUILD=0
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
Packages CPU architecture:
arm
Subscribed repositories:
# sources.list
deb https://termux.mentality.rip/termux-main stable main
# tur-repo (sources.list.d/tur.list)
deb https://tur.kcubeterm.com tur-packages tur tur-on-device tur-continuous
Updatable packages:
All packages up to date
termux-tools version:
1.38.1
Android version:
7.0
Kernel build information:
Linux localhost 3.10.49-gf2f82e6-00003-g39ffe37 #1 SMP PREEMPT Sat Mar 17 15:13:00 CST 2018 armv7l Android
```

I think the bug is because the deprecation said here https://github.com/apache/incubator-mxnet/issues/8707#issuecomment-347529909

So the possible solution could be patch the python-torch source code to fit to the deprecation

**Comment by xtkoba** [comment]
Please consider always sharing the `termux-info` output when filing a bug.

**Comment by nacho00112** [comment]
> Please consider always sharing the `termux-info` output when filing a bug.

Done, i also added new information too

**Comment by xtkoba** [comment]
The following is a kind of dev memo.

<a href="https://android.googlesource.com/platform/bionic/+/master/docs/status.md">`shm_{open,unlink}` are famous for missing from Bionic libc.</a> I guess they are missing not because obsolete but because disallowed by SELinux. We port these functions to individual package if necessary. We do not provide a shared lib for them due to security concerns.

in `python-torch`, these functions have been ported to some part of the code, but that does not seem to be sufficient, as this issue suggests. The relevant part of the code seems to be `$TERMUX_PKG_SRCDIR/aten/src/ATen`, in which CMake checks for these functions.

**Comment by nacho00112** [comment]
I confirmed that @kawanakaiku pull-request solves this issue, please accept it to close the issue
