### ISSUE TITLE
Permission issue when installing python - pip not working

### ISSUE THREAD

**Issue by panditarevolution** [termux/termux-packages#1652]
Hi,

I'm trying to install python however when it gets to pip, the install aborts with a permission error. I'm using a rooted Moto Z.

The python executable works fine after this failed install and opens a python prompt.

``` sh
Hit:1 http://termux.net stable InRelease
Reading package lists...
Building dependency tree...
Reading state information...
All packages are up to date.
Reading package lists...
Building dependency tree...
Reading state information...
The following NEW packages will be installed:
  python
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 5608 kB of archives.
After this operation, 23.6 MB of additional disk space will be used.
Get:1 http://termux.net stable/main aarch64 python aarch64 3.6.3 [5608 kB]
Fetched 5608 kB in 4s (1174 kB/s)
Selecting previously unselected package python.
(Reading database ... 
(Reading database ... 5%
(Reading database ... 10%
(Reading database ... 15%
(Reading database ... 20%
(Reading database ... 25%
(Reading database ... 30%
(Reading database ... 35%
(Reading database ... 40%
(Reading database ... 45%
(Reading database ... 50%
(Reading database ... 55%
(Reading database ... 60%
(Reading database ... 65%
(Reading database ... 70%
(Reading database ... 75%
(Reading database ... 80%
(Reading database ... 85%
(Reading database ... 90%
(Reading database ... 95%
(Reading database ... 100%
(Reading database ... 4805 files and directories currently installed.)
Preparing to unpack .../python_3.6.3_aarch64.deb ...
Unpacking python (3.6.3) ...
Processing triggers for man (1.14.3-1) ...
Setting up python (3.6.3) ...
Setting up pip...
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/data/data/com.termux/files/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/data/data/com.termux/files/usr/lib/python3.6/ensurepip/__main__.py", line 4, in <module>
    ensurepip._main()
  File "/data/data/com.termux/files/usr/lib/python3.6/ensurepip/__init__.py", line 189, in _main
    default_pip=args.default_pip,
  File "/data/data/com.termux/files/usr/lib/python3.6/ensurepip/__init__.py", line 102, in bootstrap
    _run_pip(args + [p[0] for p in _PROJECTS], additional_paths)
  File "/data/data/com.termux/files/usr/lib/python3.6/ensurepip/__init__.py", line 27, in _run_pip
    import pip
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "/data/data/com.termux/files/usr/tmp/tmp0lz0mu0q/pip-9.0.1-py2.py3-none-any.whl/pip/__init__.py", line 26, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "/data/data/com.termux/files/usr/tmp/tmp0lz0mu0q/pip-9.0.1-py2.py3-none-any.whl/pip/utils/__init__.py", line 27, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "/data/data/com.termux/files/usr/tmp/tmp0lz0mu0q/pip-9.0.1-py2.py3-none-any.whl/pip/_vendor/pkg_resources/__init__.py", line 3018, in <module>
  File "/data/data/com.termux/files/usr/tmp/tmp0lz0mu0q/pip-9.0.1-py2.py3-none-any.whl/pip/_vendor/pkg_resources/__init__.py", line 3004, in _call_aside
  File "/data/data/com.termux/files/usr/tmp/tmp0lz0mu0q/pip-9.0.1-py2.py3-none-any.whl/pip/_vendor/pkg_resources/__init__.py", line 3031, in _initialize_master_working_set
  File "/data/data/com.termux/files/usr/tmp/tmp0lz0mu0q/pip-9.0.1-py2.py3-none-any.whl/pip/_vendor/pkg_resources/__init__.py", line 651, in _build_master
  File "/data/data/com.termux/files/usr/tmp/tmp0lz0mu0q/pip-9.0.1-py2.py3-none-any.whl/pip/_vendor/pkg_resources/__init__.py", line 644, in __init__
  File "/data/data/com.termux/files/usr/tmp/tmp0lz0mu0q/pip-9.0.1-py2.py3-none-any.whl/pip/_vendor/pkg_resources/__init__.py", line 700, in add_entry
  File "/data/data/com.termux/files/usr/tmp/tmp0lz0mu0q/pip-9.0.1-py2.py3-none-any.whl/pip/_vendor/pkg_resources/__init__.py", line 2010, in find_on_path
PermissionError: [Errno 13] Permission denied: '/'
```

**Comment by panditarevolution** [comment]
Should perhaps reiterate that the abort during the install of pip means that pip is not available. So the immediate issue would be how to get pip installed....

**Comment by Grimler91** [comment]
Do you get the same output if you manually run `$PREFIX/bin/python -m ensurepip --upgrade --default-pip` (with this half-working python installation)?

In that case, could you run it in verbose mode? `$PREFIX/bin/python -v -m ensurepip --upgrade --default-pip`?

**Comment by panditarevolution** [comment]
This did work indeed! Thanks for this. I then ran it in verbose mode:

```
$ /data/data/com.termux/files/usr/bin/python -m ensurepip --upgrade --default-pip -v
Ignoring indexes: https://pypi.python.org/simple
0 location(s) to search for versions of setuptools:
Skipping link /data/data/com.termux/files/usr/tmp/tmpgym1bq1q (from -f); not a file
Found link file:///data/data/com.termux/files/usr/tmp/tmpgym1bq1q/setuptools-28.8.0-py2.py3-none-any.whl, version: 28.8.0
Skipping link file:///data/data/com.termux/files/usr/tmp/tmpgym1bq1q/pip-9.0.1-py2.py3-none-any.whl; wrong project name (not setuptools)
Local files found: /data/data/com.termux/files/usr/tmp/tmpgym1bq1q/setuptools-28.8.0-py2.py3-none-any.whl
Installed version (28.8.0) is most up-to-date (past versions: 28.8.0)
Requirement already up-to-date: setuptools in /data/data/com.termux/files/usr/lib/python3.6/site-packages
0 location(s) to search for versions of pip:
Skipping link file:///data/data/com.termux/files/usr/tmp/tmpgym1bq1q/setuptools-28.8.0-py2.py3-none-any.whl; wrong project name (not pip)
Found link file:///data/data/com.termux/files/usr/tmp/tmpgym1bq1q/pip-9.0.1-py2.py3-none-any.whl, version: 9.0.1
Local files found: /data/data/com.termux/files/usr/tmp/tmpgym1bq1q/pip-9.0.1-py2.py3-none-any.whl
Installed version (9.0.1) is most up-to-date (past versions: 9.0.1)
Requirement already up-to-date: pip in /data/data/com.termux/files/usr/lib/python3.6/site-packages
Cleaning up...
```

**Comment by Grimler91** [comment]
Maybe it was some kind of temporary error. 
I guess you can close this for now then!

**Comment by sogaiu** [comment]
I get a similar error as originally reported.  This is on a tablet with LineageOS 14.1.

FWIW, the suggested work-around:

manually running $PREFIX/bin/python -m ensurepip --upgrade --default-pip

appears to work here.
