### ISSUE TITLE
[Bug]: updated 32 bit samba package currently broken

### ISSUE THREAD

**Issue by jayeAch** [termux/termux-packages#16629]
### Problem description

32 bit version of samba currently broken after package upgrade.  I have two tablets, one 64 bit and the other 32 bit with the same termux app and samba configuration and a 32 bit Android TV box with the same setup.  The 64 bit version of samba is working flawlessly.   The 32 bit version is broken on both 32 bit devices.  

### What steps will reproduce the bug?

This output occurs when a connection attempt is made.

.../files/home # smbd -i
smbd version 4.16.10 started.
Copyright Andrew Tridgell and the Samba Team 1992-2022
daemon_status: daemon 'smbd' : Starting process ...
[2023/05/12 22:05:05,  0] ../../lib/util/debug.c:1225(reopen_one_log)
  reopen_one_log: Unable to open new log file '/data/data/com.termux/files/usr/var/log/samba/log./data/data/com.termux/files/usr/libexec/samba/samba-dcerpcd': No such file or directory
[2023/05/12 22:05:05,  0] ../../lib/util/debug.c:1225(reopen_one_log)
  reopen_one_log: Unable to open new log file '/data/data/com.termux/files/usr/var/log/samba/log./data/data/com.termux/files/usr/libexec/samba/samba-dcerpcd': No such file or directory
[2023/05/12 22:05:05,  0] ../../lib/util/util.c:215(directory_create_or_exist)
  directory_create_or_exist: mkdir failed on directory /data/data/com.termux/files/usr/var/log/samba/cores//data/data/com.termux/files/usr/libexec/samba/samba-dcerpcd: No such file or directory
[2023/05/12 22:05:05,  0] ../../source3/lib/dumpcore.c:73(get_default_corepath)
  Failed to create /data/data/com.termux/files/usr/var/log/samba/cores//data/data/com.termux/files/usr/libexec/samba/samba-dcerpcd for user 0 with mode 0700
[2023/05/12 22:05:05,  0] ../../source3/lib/dumpcore.c:257(dump_core_setup)
  Unable to setup corepath for /data/data/com.termux/files/usr/libexec/samba/samba-dcerpcd: No such file or directory
[2023/05/12 22:05:05,  0] ../../source3/rpc_server/rpc_host.c:2968(main)
  /data/data/com.termux/files/usr/libexec/samba/samba-dcerpcd version 4.16.10 started.
  Copyright Andrew Tridgell and the Samba Team 1992-2022
[2023/05/12 22:05:05.350334,  0] ../../lib/util/debug.c:1225(reopen_one_log)
  reopen_one_log: Unable to open new log file '/data/data/com.termux/files/usr/var/log/samba/log./data/data/com.termux/files/usr/libexec/samba/samba-dcerpcd': No such file or directory

### What is the expected behavior?

A functioning samba server.

### System information

termux-info:

```

```
Termux Variables:
TERMUX_APK_RELEASE=GITHUB
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=12663
TERMUX_IS_DEBUGGABLE_BUILD=1
TERMUX_VERSION=0.118.0
Packages CPU architecture:
arm
Subscribed repositories:
# sources.list
deb https://packages-cf.termux.dev/apt/termux-main/ stable main
Updatable packages:
All packages up to date
termux-tools version:
1.38.1
Android version:
10
Kernel build information:
Linux localhost 4.9.180 #1 SMP PREEMPT Mon May 23 09:03:57 CST 2022 armv8l Android
Device manufacturer:
askey
Device model:
sti6140d360
LD Variables:
LD_LIBRARY_PATH=
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so

**Comment by ioiioo** [comment]
I have the same problem，I report this error when I make a samba connection

```shell
[2023/08/18 00:47:41,  0] ../../source3/lib/dumpcore.c:73(get_default_corepath)
  Failed to create /data/data/com.termux/files/usr/var/log/samba/cores//data/data/com.termux/files/usr/libexec/samba/samba-dcerpcd for user 10087 with mode 0700
[2023/08/18 00:47:41,  0] ../../source3/lib/dumpcore.c:257(dump_core_setup)
  Unable to setup corepath for /data/data/com.termux/files/usr/libexec/samba/samba-dcerpcd: No such file or directory
[2023/08/18 00:47:41,  0] ../../source3/rpc_server/rpc_host.c:2968(main)
  /data/data/com.termux/files/usr/libexec/samba/samba-dcerpcd version 4.16.10 started.
  Copyright Andrew Tridgell and the Samba Team 1992-2022
```

.../libexec/samba $ termux-info

```shell
Termux Variables:
TERMUX_APK_RELEASE=GITHUB
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=5489
TERMUX_IS_DEBUGGABLE_BUILD=1
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
Packages CPU architecture:
arm
Subscribed repositories:
# sources.list
deb https://packages-cf.termux.dev/apt/termux-main stable main
Updatable packages:
vim-runtime/stable 9.0.1700 all [upgradable from: 9.0.1650]
vim/stable 9.0.1700 arm [upgradable from: 9.0.1650]
termux-tools version:
1.38.5
Android version:
9
Kernel build information:
Linux localhost 4.9.113 #1 SMP PREEMPT Thu Jul 16 00:25:53 CST 2020 armv7l Android
```

**Comment by robertkirkman** [comment]
> error on 32-bit arm `reopen_one_log: Unable to open new log file '/data/data/com.termux/files/usr/var/log/samba/log./data/data/com.termux/files/usr/libexec/samba/samba-dcerpcd': No such file or directory`

I can reproduce it, it is related to this line in some way. Patching this line makes those messages stop for me, but there is a root cause somewhere else.

https://github.com/samba-team/samba/blob/9687078251620c50420ebbeb6d7d3d53c04705a7/lib/cmdline/cmdline.c#L539

#### example patch, not for use

```diff
--- a/lib/cmdline/cmdline.c
+++ b/lib/cmdline/cmdline.c
@@ -349,11 +349,10 @@ static void popt_samba_callback(poptContext popt_ctx,
 {
 	TALLOC_CTX *mem_ctx = samba_cmdline_get_talloc_ctx();
 	struct loadparm_context *lp_ctx = samba_cmdline_get_lp_ctx();
-	const char *pname = NULL;
+	const char *pname = "smbd";
 	bool ok;
 
 	/* Find out basename of current program */
-	pname = getprogname();
 
 	if (reason == POPT_CALLBACK_REASON_PRE) {
 		if (lp_ctx == NULL) {
```

> immediate crash on 32-bit arm

I can also reproduce this. If the message above stops, this crash still happens with no messages instead. I was able to retrieve a backtrace from the debug build:

```
~ $ gdb --args smbd -F --no-process-group -s $PREFIX/etc/samba/smb.conf
GNU gdb (GDB) 15.2
Copyright (C) 2024 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "arm-linux-androideabi".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from smbd...
(gdb) run
Starting program: /data/data/com.termux/files/usr/bin/smbd -F --no-process-group -s /data/data/com.termux/files/usr/etc/samba/smb.conf
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/data/data/com.termux/files/usr/lib/libthread_db.so".
[Detaching after fork from child process 5616]
[Detaching after fork from child process 5617]

Program received signal SIGTERM, Terminated.
0xb6275d4c in kill () from /system/lib/libc.so
(gdb) bt
#0  0xb6275d4c in kill () from /system/lib/libc.so
#1  0xb627e7b0 in __cxa_finalize () from /system/lib/libc.so
#2  0xb624234e in exit () from /system/lib/libc.so
#3  0xb6701844 in dump_core () at ../../source3/lib/dumpcore.c:273
#4  0xb670faf6 in smb_panic_s3 (why=<optimized out>) at ../../source3/lib/util.c:704
#5  0xb3eabc82 in smb_panic (why=0xb6725384 <s3_global_substitution> "\365\305o\266") at ../../lib/util/fault.c:197
#6  0xb620a3c8 in exit_server_common (how=SERVER_EXIT_ABNORMAL, reason=<optimized out>)
    at ../../source3/smbd/server_exit.c:224
#7  0xb620a280 in smbd_exit_server (explanation=0xf <error: Cannot access memory at address 0xf>)
    at ../../source3/smbd/server_exit.c:241
#8  0xb669e708 in exit_server (reason=0x0) at ../../source3/lib/smbd_shim.c:113
#9  0x7f55c76a in main (argc=<optimized out>, argv=<optimized out>) at ../../source3/smbd/server.c:2099
(gdb) 
```

Unfortunately, several things I tried did not help to fix this problem, so I don't know how to fix this currently
