### ISSUE TITLE
libpulse another issue 

### ISSUE THREAD

**Issue by anishdevtech** [termux/termux-packages#17311]
Could not import the PyAudio C module 'pyaudio._portaudio'.Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/speech_recognition/__init__.py", line 108, in get_pyaudio                                                       import pyaudio
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/pyaudio/__init__.py", line 111, in <module>
    import pyaudio._portaudio as pa                        ImportError: dlopen failed: library "libpulse.so" not found: needed by /data/data/com.termux/files/usr/lib/libportaudio.so in namespace (default)                                
During handling of the above exception, another exception occurred:                                                   
Traceback (most recent call last):                           File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code               File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/speech_recognition/__main__.py", line 4, in <module>                                                            m = sr.Microphone()                                            ^^^^^^^^^^^^^^^                                      File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/speech_recognition/__init__.py", line 80, in __init__
    self.pyaudio_module = self.get_pyaudio()
                          ^^^^^^^^^^^^^^^^^^                 File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/speech_recognition/__init__.py", line 110, in get_pyaudio
    raise AttributeError("Could not find PyAudio; check installation")
AttributeError: Could not find PyAudio; check installation

**Comment by anishdevtech** [comment]
Already created a symlink

**Comment by anishdevtech** [comment]
I dont why tht dl error is popping

**Comment by anishdevtech** [comment]
In my system pyaudio is already installed

**Comment by xtkoba** [comment]
Your `$PREFIX/lib/libportaudio.so` is not the one from our `portaudio` package. Not our issue.
