### ISSUE TITLE
wscheck fails on latest version of python

### ISSUE THREAD

**Issue by linusjf** [termux/termux-packages#17328]
Checking Forecasting/installer.R for whitespace...   
                                           Traceback (most recent call last):                File "/data/data/com.termux/files/usr/bin/wscheck", line 5, in <module>                           from wscheck.__main__ import main             File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/wscheck/__main__.py", line 10, in <module>                                     from wscheck.printer import ErrorPrinter      File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/wscheck/printer.py", line 2, in <module>                                       from lxml import builder, etree               File "src/lxml/builder.py", line 44, in init lxml.builder                                     ImportError: dlopen failed: cannot find "libxml2.so" from verneed[1] in DT_NEEDED list for "/data/data/com.termux/files/usr/lib/python3.11/site-packages/lxml/etree.cpython-311.so"

--------+----------

Getting the above error while executing `wscheck` against files. Problems started with latest version of python. Worked fine earlier. Is it connected to above?

_Originally posted by @linusjf in https://github.com/termux/termux-packages/issues/17319#issuecomment-1617197883_

**Comment by xtkoba** [comment]
See https://github.com/termux/termux-packages/issues/17202#issuecomment-1616385953.
