### ISSUE TITLE
Pyaudio doesn't find any microPhone 

### ISSUE THREAD

**Issue by anishdevtech** [termux/termux-packages#17402]
### Problem description

`~ $ pactl list sources
Source #1
        State: IDLE
        Name: OpenSL_ES_sink.monitor
        Description: Monitor of OpenSL ES Output
        Driver: module-sles-sink.c
        Sample Specification: s16le 2ch 44100Hz
        Channel Map: front-left,front-right
        Owner Module: 16
        Mute: no
        Volume: front-left: 65536 / 100% / 0.00 dB,   front-right: 65536 / 100% / 0.00 dB
                balance 0.00
        Base Volume: 65536 / 100% / 0.00 dB
        Monitor of Sink: OpenSL_ES_sink
        Latency: 0 usec, configured 125000 usec                    Flags: DECIBEL_VOLUME
        Properties:
                device.description = "Monitor of OpenSL ES Output"
                device.class = "monitor"
                device.icon_name = "audio-input-microphone"
        Formats:
                pcm

Source #2
        State: IDLE
        Name: OpenSL_ES_source
        Description: OpenSL ES Input
        Driver: module-sles-source.c
        Sample Specification: s16le 2ch 44100Hz
        Channel Map: front-left,front-right
        Owner Module: 17
        Mute: no
        Volume: front-left: 65536 / 100% / 0.00 dB,   front-right: 65536 / 100% / 0.00 dB
                balance 0.00
        Base Volume: 65536 / 100% / 0.00 dB
        Monitor of Sink: n/a
        Latency: 0 usec, configured 125000 usec
        Flags: DECIBEL_VOLUME LATENCY
        Properties:
                device.description = "OpenSL ES Input"
                device.class = "abstract"
                device.icon_name = "audio-input-microphone"
        Formats:
                pcm
~ $ python
Python 3.11.4 (main, Jul  2 2023, 11:17:16) [Clang 14.0.7 (https://android.googlesource.com/toolchain/llvm-project 4c603efb0 on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import speech_recognition as sr                        >>> sr.Microphone.list_microphone_names()
[]
>>>`

### What steps will reproduce the bug?

Trying to find microphone using pyaudio

### What is the expected behavior?

It give back the information 

### System information

termux-info:

```
Termux Variables:
TERMUX_API_VERSION=0.50.1
TERMUX_APK_RELEASE=F_DROID
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=32226
TERMUX_IS_DEBUGGABLE_BUILD=0
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
Packages CPU architecture:
arm
Subscribed repositories:
# sources.list
deb https://grimler.se/termux/termux-main stable main
# root-repo (sources.list.d/root.list)
deb https://grimler.se/termux/termux-root root stable
# sources.list.d/pointless.list
deb https://its-pointless.github.io/files/21 termux extras
Updatable packages:
command-not-found/stable 2.2.0-7 arm [upgradable from: 2.2.0-6]
termux-tools version:
1.38.3
Android version:
11
Kernel build information:
Linux localhost 4.4.177-21848546 #1 SMP PREEMPT Wed Jul 13 14:26:29 KST 2022 armv8l Android
Device manufacturer:
samsung
Device model:
SM-A105F
LD Variables:
LD_LIBRARY_PATH=/data/data/com.termux/files/home/.local/lib:
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so
Installed termux plugins:
com.termux.api versionCode:51


```

**Comment by anishdevtech** [comment]
Also Already tried this pactl load-module module-sles-source

**Comment by anishdevtech** [comment]
#After tht command
`~ $ pulseaudio --start
~ $ pactl load-module module-sles-source
18
~ $ python i.py
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/i.py", line 7, in <module>
    stream = pa.open(format=pyaudio.paInt16, channels=1, rate=44100, input=True, frames_per_buffer=1024)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/PyAudio-0.2.12-py3.11-linux-armv8l.egg/pyaudio.py", line 754, in open
    stream = Stream(self, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/PyAudio-0.2.12-py3.11-linux-armv8l.egg/pyaudio.py", line 445, in __init__
    self._stream = pa.open(**arguments)                                       ^^^^^^^^^^^^^^^^^^^^
OSError: [Errno -9996] Invalid input device (no default output device)
~ $`

**Comment by anishdevtech** [comment]
# After that command 
`
~ $ pulseaudio --start
~ $ pactl load-module module-sles-source
18
~ $ python i.py
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/i.py", line 7, in <module>
    stream = pa.open(format=pyaudio.paInt16, channels=1, rate=44100, input=True, frames_per_buffer=1024)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/PyAudio-0.2.12-py3.11-linux-armv8l.egg/pyaudio.py", line 754, in open
    stream = Stream(self, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/PyAudio-0.2.12-py3.11-linux-armv8l.egg/pyaudio.py", line 445, in __init__
    self._stream = pa.open(**arguments)                                       ^^^^^^^^^^^^^^^^^^^^
OSError: [Errno -9996] Invalid input device (no default output device)
~ $`

**Comment by anishdevtech** [comment]
> Enable microphone permission in Termux:API

![Screenshot_20230710-125351_Permission controller.jpg](https://github.com/termux/termux-packages/assets/118909523/0aeda984-04b4-4ec9-a915-dbaa7e3427f9)

**Comment by anishdevtech** [comment]
Already

**Comment by truboxl** [comment]
Likely something to do with not getting microphone input from OpenSL ES. Closing as duplicate and keep track in #5422

**Comment by anishdevtech** [comment]
I don't know termux team is busy or what but this issue has not been fixed  even after 4years
