### ISSUE TITLE
[Error]: Sentencepiece installation

### ISSUE THREAD

**Issue by JackJollimore** [termux/termux-packages#17688]
### Problem description

Hi, I want to install `sentencepiece` in Termux.

Here's the error message:
```
pip install sentencepiece
Collecting sentencepiece                                     
Downloading sentencepiece-0.1.99.tar.gz (2.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━ 2.6/2.6 MB 1.7 MB/s eta 0:00:00  Installing build dependencies ... done
  Getting requirements to build wheel ... done               
Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: sentencepiece        Building wheel for sentencepiece (pyproject.toml) ... error                                                           error: subprocess-exited-with-error
                                                             
× Building wheel for sentencepiece (pyproject.toml) did not run successfully.                                         │ exit code: 1
  ╰─> [214 lines of output]                                      
running bdist_wheel
      running build                                              
running build_py
      creating build                                             
creating build/lib.linux-aarch64-cpython-311
      creating build/lib.linux-aarch64-cpython-311/sentencepiece
      copying src/sentencepiece/__init__.py -> build/lib.linux-aarch64-cpython-311/sentencepiece
      copying src/sentencepiece/_version.py -> build/lib.linux-aarch64-cpython-311/sentencepiece
      copying src/sentencepiece/sentencepiece_model_pb2.py -> build/lib.linux-aarch64-cpython-311/sentencepiece
      copying src/sentencepiece/sentencepiece_pb2.py -> build/lib.linux-aarch64-cpython-311/sentencepiece
      running build_ext                                          
Package sentencepiece was not found in the pkg-config search path.                                                    
Perhaps you should add the directory containing `sentencepiece.pc` to the PKG_CONFIG_PATH environment variable
 No package 'sentencepiece' found                           
-- VERSION: 0.1.99
      -- The C compiler identification is Clang 16.0.6           
-- The CXX compiler identification is Clang 16.0.6
      -- Detecting C compiler ABI info                           
-- Detecting C compiler ABI info - done
      -- Check for working C compiler: /data/data/com.termux/files/usr/bin/cc - skipped
      -- Detecting C compile features                            
-- Detecting C compile features - done
      -- Detecting CXX compiler ABI info                         
-- Detecting CXX compiler ABI info - done
      -- Check for working CXX compiler: /data/data/com.termux/files/usr/bin/c++ - skipped
      -- Detecting CXX compile features                          
-- Detecting CXX compile features - done
      -- Performing Test CMAKE_HAVE_LIBC_PTHREAD                 
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
      -- Looking for pthread_create in pthreads                  
-- Looking for pthread_create in pthreads - not found
      -- Looking for pthread_create in pthread                   
-- Looking for pthread_create in pthread - found
      -- Found Threads: TRUE                                     
-- Not Found TCMalloc: TCMALLOC_LIB-NOTFOUND
      -- Found atomic: /data/data/com.termux/files/usr/lib/libatomic.a
      -- Configuring done (3.1s)                                 
-- Generating done (0.0s)
      -- Build files have been written to: /data/data/com.termux/files/usr/tmp/pip-install-fp0uprvx/sentencepiece_46b10aa7b9164fc8b7b95ce97999ae64/build                               [  1%] Building CXX object src/CMakeFiles/sentencepiece-static.dir/__/third_party/protobuf-lite/bytestream.cc.o       [  3%] Building CXX object src/CMakeFiles/sentencepiece-static.dir/__/third_party/protobuf-lite/arena.cc.o            [  4%] Building CXX object src/CMakeFiles/sentencepiece-static.dir/__/third_party/protobuf-lite/coded_stream.cc.o
      [  6%] Building CXX object src/CMakeFiles/sentencepiece_train-static.dir/builder.cc.o
      [  8%] Building CXX object src/CMakeFiles/sentencepiece-static.dir/__/third_party/protobuf-lite/arenastring.cc.o
      [  9%] Building CXX object src/CMakeFiles/sentencepiece-static.dir/__/third_party/protobuf-lite/common.cc.o
      [ 11%] Building CXX object src/CMakeFiles/sentencepiece_train-static.dir/unicode_script.cc.o
      [ 12%] Building CXX object src/CMakeFiles/sentencepiece-static.dir/__/third_party/protobuf-lite/extension_set.cc.o                                                               [ 14%] Building CXX object src/CMakeFiles/sentencepiece-static.dir/__/third_party/protobuf-lite/generated_enum_util.cc.o
      [ 16%] Building CXX object src/CMakeFiles/sentencepiece-static.dir/__/third_party/protobuf-lite/generated_message_table_driven_lite.cc.o                                         [ 17%] Building CXX object src/CMakeFiles/sentencepiece_train-static.dir/trainer_factory.cc.o                         [ 19%] Building CXX object src/CMakeFiles/sentencepiece-static.dir/__/third_party/protobuf-lite/generated_message_util.cc.o
      /data/data/com.termux/files/usr/tmp/pip-install-fp0uprvx/sentencepiece_46b10aa7b9164fc8b7b95ce97999ae64/sentencepiece/src/builder.cc:47:15: warning: unused variable 'kMaxUnicode' [-Wunused-const-variable]
      constexpr int kMaxUnicode = 0x10FFFF;                                    ^
      /data/data/com.termux/files/usr/tmp/pip-install-fp0uprvx/sentencepiece_46b10aa7b9164fc8b7b95ce97999ae64/sentencepiece/src/builder.cc:49:23: warning: unused variable 'kDefaultNormalizerName' [-Wunused-const-variable]
      static constexpr char kDefaultNormalizerName[] = "nfkc";
                            ^                                    [ 20%] Building CXX object src/CMakeFiles/sentencepiece-static.dir/__/third_party/protobuf-lite/implicit_weak_message.cc.o
      [ 22%] Building CXX object src/CMakeFiles/sentencepiece_train-static.dir/trainer_interface.cc.o
      [ 24%] Building CXX object src/CMakeFiles/sentencepiece-static.dir/__/third_party/protobuf-lite/int128.cc.o
      [ 25%] Building CXX object src/CMakeFiles/sentencepiece-static.dir/__/third_party/protobuf-lite/io_win32.cc.o
      [ 27%] Building CXX object src/CMakeFiles/sentencepiece-static.dir/__/third_party/protobuf-lite/message_lite.cc.o                                                                2 warnings generated.
      [ 29%] Building CXX object src/CMakeFiles/sentencepiece_train-static.dir/unigram_model_trainer.cc.o
      [ 30%] Building CXX object src/CMakeFiles/sentencepiece-static.dir/__/third_party/protobuf-lite/parse_context.cc.o                                                               [ 32%] Building CXX object src/CMakeFiles/sentencepiece-static.dir/__/third_party/protobuf-lite/repeated_field.cc.o
      [ 33%] Building CXX object src/CMakeFiles/sentencepiece-static.dir/__/third_party/protobuf-lite/status.cc.o
      [ 35%] Building CXX object src/CMakeFiles/sentencepiece-static.dir/__/third_party/protobuf-lite/statusor.cc.o
      [ 37%] Building CXX object src/CMakeFiles/sentencepiece-static.dir/__/third_party/protobuf-lite/stringpiece.cc.o
      [ 38%] Building CXX object src/CMakeFiles/sentencepiece_train-static.dir/word_model_trainer.cc.o
      [ 40%] Building CXX object src/CMakeFiles/sentencepiece-static.dir/__/third_party/protobuf-lite/stringprintf.cc.o                                                                [ 41%] Building CXX object src/CMakeFiles/sentencepiece-static.dir/__/third_party/protobuf-lite/structurally_valid.cc.o
      [ 43%] Building CXX object src/CMakeFiles/sentencepiece-static.dir/__/third_party/protobuf-lite/strutil.cc.o
      [ 45%] Building CXX object src/CMakeFiles/sentencepiece-static.dir/__/third_party/protobuf-lite/time.cc.o
      [ 46%] Building CXX object src/CMakeFiles/sentencepiece-static.dir/__/third_party/protobuf-lite/wire_format_lite.cc.o                                                            [ 48%] Building CXX object src/CMakeFiles/sentencepiece-static.dir/__/third_party/protobuf-lite/zero_copy_stream.cc.o
      [ 50%] Building CXX object src/CMakeFiles/sentencepiece-static.dir/__/third_party/protobuf-lite/zero_copy_stream_impl.cc.o                                                       [ 51%] Building CXX object src/CMakeFiles/sentencepiece-static.dir/__/third_party/protobuf-lite/zero_copy_stream_impl_lite.cc.o
      [ 53%] Building CXX object src/CMakeFiles/sentencepiece-static.dir/builtin_pb/sentencepiece.pb.cc.o
      [ 54%] Building CXX object src/CMakeFiles/sentencepiece_train-static.dir/char_model_trainer.cc.o
      [ 56%] Building CXX object src/CMakeFiles/sentencepiece-static.dir/builtin_pb/sentencepiece_model.pb.cc.o
      [ 58%] Building CXX object src/CMakeFiles/sentencepiece-static.dir/bpe_model.cc.o
      [ 59%] Building CXX object src/CMakeFiles/sentencepiece-static.dir/char_model.cc.o
      [ 61%] Building CXX object src/CMakeFiles/sentencepiece_train-static.dir/bpe_model_trainer.cc.o
      [ 62%] Building CXX object src/CMakeFiles/sentencepiece_train-static.dir/sentencepiece_trainer.cc.o
      [ 64%] Building CXX object src/CMakeFiles/sentencepiece_train-static.dir/pretokenizer_for_training.cc.o
      [ 66%] Building CXX object src/CMakeFiles/sentencepiece-static.dir/error.cc.o
      [ 67%] Building CXX object src/CMakeFiles/sentencepiece-static.dir/filesystem.cc.o
      [ 69%] Building CXX object src/CMakeFiles/sentencepiece-static.dir/model_factory.cc.o
      [ 70%] Building CXX object src/CMakeFiles/sentencepiece-static.dir/model_interface.cc.o
      [ 72%] Building CXX object src/CMakeFiles/sentencepiece-static.dir/normalizer.cc.o
      [ 74%] Building CXX object src/CMakeFiles/sentencepiece-static.dir/sentencepiece_processor.cc.o
      [ 75%] Building CXX object src/CMakeFiles/sentencepiece-static.dir/unigram_model.cc.o
      [ 77%] Building CXX object src/CMakeFiles/sentencepiece-static.dir/util.cc.o
      [ 79%] Building CXX object src/CMakeFiles/sentencepiece-static.dir/word_model.cc.o
      [ 80%] Building CXX object src/CMakeFiles/sentencepiece-static.dir/__/third_party/absl/flags/flag.cc.o
      [ 82%] Linking CXX static library libsentencepiece_train.a
      [ 82%] Built target sentencepiece_train-static             [ 83%] Linking CXX static library libsentencepiece.a
      [ 83%] Built target sentencepiece-static                   [ 85%] Building CXX object src/CMakeFiles/spm_decode.dir/spm_decode_main.cc.o                                         [ 87%] Building CXX object src/CMakeFiles/spm_train.dir/spm_train_main.cc.o                                           [ 88%] Building CXX object src/CMakeFiles/spm_encode.dir/spm_encode_main.cc.o                                         [ 90%] Building CXX object src/CMakeFiles/spm_normalize.dir/spm_normalize_main.cc.o                                   [ 91%] Building CXX object src/CMakeFiles/spm_export_vocab.dir/spm_export_vocab_main.cc.o                             [ 93%] Linking CXX executable spm_export_vocab
      ld.lld: error: undefined symbol: __android_log_write       >>> referenced by common.cc:150 (/data/data/com.termux/files/usr/tmp/pip-install-fp0uprvx/sentencepiece_46b10aa7b9164fc8b7b95ce97999ae64/sentencepiece/third_party/protobuf-lite/common.cc:150)                                             >>>               common.cc.o:(google::protobuf::internal::DefaultLogHandler(google::protobuf::LogLevel, char const*, int, std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char>> const&)) in archive libsentencepiece.a
      >>> referenced by common.cc:158 (/data/data/com.termux/files/usr/tmp/pip-install-fp0uprvx/sentencepiece_46b10aa7b9164fc8b7b95ce97999ae64/sentencepiece/third_party/protobuf-lite/common.cc:158)
      >>>               common.cc.o:(google::protobuf::internal::DefaultLogHandler(google::protobuf::LogLevel, char const*, int, std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char>> const&)) in archive libsentencepiece.a                                        clang-16: error: linker command failed with exit code 1 (use -v to see invocation)                                    make[2]: *** [src/CMakeFiles/spm_export_vocab.dir/build.make:98: src/spm_export_vocab] Error 1                        make[1]: *** [CMakeFiles/Makefile2:286: src/CMakeFiles/spm_export_vocab.dir/all] Error 2                              make[1]: *** Waiting for unfinished jobs....
      [ 95%] Linking CXX executable spm_train                    ld.lld: error: undefined symbol: __android_log_write
      >>> referenced by common.cc:150 (/data/data/com.termux/files/usr/tmp/pip-install-fp0uprvx/sentencepiece_46b10aa7b9164fc8b7b95ce97999ae64/sentencepiece/third_party/protobuf-lite/common.cc:150)
      >>>               common.cc.o:(google::protobuf::internal::DefaultLogHandler(google::protobuf::LogLevel, char const*, int, std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char>> const&)) in archive libsentencepiece.a                                        >>> referenced by common.cc:158 (/data/data/com.termux/files/usr/tmp/pip-install-fp0uprvx/sentencepiece_46b10aa7b9164fc8b7b95ce97999ae64/sentencepiece/third_party/protobuf-lite/common.cc:158)                                             >>>               common.cc.o:(google::protobuf::internal::DefaultLogHandler(google::protobuf::LogLevel, char const*, int, std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char>> const&)) in archive libsentencepiece.a
      clang-16: error: linker command failed with exit code 1 (use -v to see invocation)
      make[2]: *** [src/CMakeFiles/spm_train.dir/build.make:100: src/spm_train] Error 1
      make[1]: *** [CMakeFiles/Makefile2:260: src/CMakeFiles/spm_train.dir/all] Error 2
      [ 96%] Linking CXX executable spm_decode                   ld.lld: error: undefined symbol: __android_log_write
      >>> referenced by common.cc:150 (/data/data/com.termux/files/usr/tmp/pip-install-fp0uprvx/sentencepiece_46b10aa7b9164fc8b7b95ce97999ae64/sentencepiece/third_party/protobuf-lite/common.cc:150)
      >>>               common.cc.o:(google::protobuf::internal::DefaultLogHandler(google::protobuf::LogLevel, char const*, int, std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char>> const&)) in archive libsentencepiece.a                                        >>> referenced by common.cc:158 (/data/data/com.termux/files/usr/tmp/pip-install-fp0uprvx/sentencepiece_46b10aa7b9164fc8b7b95ce97999ae64/sentencepiece/third_party/protobuf-lite/common.cc:158)                                             >>>               common.cc.o:(google::protobuf::internal::DefaultLogHandler(google::protobuf::LogLevel, char const*, int, std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char>> const&)) in archive libsentencepiece.a
      clang-16: error: linker command failed with exit code 1 (use -v to see invocation)
      make[2]: *** [src/CMakeFiles/spm_decode.dir/build.make:98: src/spm_decode] Error 1
      make[1]: *** [CMakeFiles/Makefile2:206: src/CMakeFiles/spm_decode.dir/all] Error 2
      [ 98%] Linking CXX executable spm_normalize                ld.lld: error: undefined symbol: __android_log_write
      >>> referenced by common.cc:150 (/data/data/com.termux/files/usr/tmp/pip-install-fp0uprvx/sentencepiece_46b10aa7b9164fc8b7b95ce97999ae64/sentencepiece/third_party/protobuf-lite/common.cc:150)
      >>>               common.cc.o:(google::protobuf::internal::DefaultLogHandler(google::protobuf::LogLevel, char const*, int, std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char>> const&)) in archive libsentencepiece.a                                        >>> referenced by common.cc:158 (/data/data/com.termux/files/usr/tmp/pip-install-fp0uprvx/sentencepiece_46b10aa7b9164fc8b7b95ce97999ae64/sentencepiece/third_party/protobuf-lite/common.cc:158)                                             >>>               common.cc.o:(google::protobuf::internal::DefaultLogHandler(google::protobuf::LogLevel, char const*, int, std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char>> const&)) in archive libsentencepiece.a
      clang-16: error: linker command failed with exit code 1 (use -v to see invocation)
      make[2]: *** [src/CMakeFiles/spm_normalize.dir/build.make:100: src/spm_normalize] Error 1
      make[1]: *** [CMakeFiles/Makefile2:233: src/CMakeFiles/spm_normalize.dir/all] Error 2
      [100%] Linking CXX executable spm_encode                   ld.lld: error: undefined symbol: __android_log_write
      >>> referenced by common.cc:150 (/data/data/com.termux/files/usr/tmp/pip-install-fp0uprvx/sentencepiece_46b10aa7b9164fc8b7b95ce97999ae64/sentencepiece/third_party/protobuf-lite/common.cc:150)
      >>>               common.cc.o:(google::protobuf::internal::DefaultLogHandler(google::protobuf::LogLevel, char const*, int, std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char>> const&)) in archive libsentencepiece.a                                        >>> referenced by common.cc:158 (/data/data/com.termux/files/usr/tmp/pip-install-fp0uprvx/sentencepiece_46b10aa7b9164fc8b7b95ce97999ae64/sentencepiece/third_party/protobuf-lite/common.cc:158)                                             >>>               common.cc.o:(google::protobuf::internal::DefaultLogHandler(google::protobuf::LogLevel, char const*, int, std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char>> const&)) in archive libsentencepiece.a
      clang-16: error: linker command failed with exit code 1 (use -v to see invocation)
      make[2]: *** [src/CMakeFiles/spm_encode.dir/build.make:98: src/spm_encode] Error 1
      make[1]: *** [CMakeFiles/Makefile2:180: src/CMakeFiles/spm_encode.dir/all] Error 2
      make: *** [Makefile:156: all] Error 2                      

Traceback (most recent call last):
        File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>                                  
main()
        File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main                                      json_out['return_val'] = hook(**hook_input['kwargs'])                                                                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                               
File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 251, in build_wheel
          return _build_backend().build_wheel(wheel_directory, config_settings,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-0buzgxd0/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 434, in build_wheel                          return self._build_with_temp_dir(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^                        
File "/data/data/com.termux/files/usr/tmp/pip-build-env-0buzgxd0/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 419, in _build_with_temp_dir
          self.run_setup()                                         
File "/data/data/com.termux/files/usr/tmp/pip-build-env-0buzgxd0/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 507, in run_setup
          super(_BuildMetaLegacyBackend, self).run_setup(setup_script=setup_script)
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-0buzgxd0/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 341, in run_setup                            exec(code, locals())
        File "<string>", line 167, in <module>                     
File "/data/data/com.termux/files/usr/tmp/pip-build-env-0buzgxd0/overlay/lib/python3.11/site-packages/setuptools/__init__.py", line 107, in setup
          return distutils.core.setup(**attrs)                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-0buzgxd0/overlay/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 185, in setup                           
return run_commands(dist)
                 ^^^^^^^^^^^^^^^^^^                                
File "/data/data/com.termux/files/usr/tmp/pip-build-env-0buzgxd0/overlay/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()                                      
File "/data/data/com.termux/files/usr/tmp/pip-build-env-0buzgxd0/overlay/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)                                    
File "/data/data/com.termux/files/usr/tmp/pip-build-env-0buzgxd0/overlay/lib/python3.11/site-packages/setuptools/dist.py", line 1233, in run_command
          super().run_command(command)                             
File "/data/data/com.termux/files/usr/tmp/pip-build-env-0buzgxd0/overlay/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()                                            
File "/data/data/com.termux/files/usr/tmp/pip-build-env-0buzgxd0/overlay/lib/python3.11/site-packages/wheel/bdist_wheel.py", line 364, in run
          self.run_command("build")                                
File "/data/data/com.termux/files/usr/tmp/pip-build-env-0buzgxd0/overlay/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)                   
File "/data/data/com.termux/files/usr/tmp/pip-build-env-0buzgxd0/overlay/lib/python3.11/site-packages/setuptools/dist.py", line 1233, in run_command
          super().run_command(command)                             
File "/data/data/com.termux/files/usr/tmp/pip-build-env-0buzgxd0/overlay/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()                                            
File "/data/data/com.termux/files/usr/tmp/pip-build-env-0buzgxd0/overlay/lib/python3.11/site-packages/setuptools/_distutils/command/build.py", line 131, in run
          self.run_command(cmd_name)                               
File "/data/data/com.termux/files/usr/tmp/pip-build-env-0buzgxd0/overlay/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)                   
File "/data/data/com.termux/files/usr/tmp/pip-build-env-0buzgxd0/overlay/lib/python3.11/site-packages/setuptools/dist.py", line 1233, in run_command
          super().run_command(command)                             
File "/data/data/com.termux/files/usr/tmp/pip-build-env-0buzgxd0/overlay/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()                                            
File "/data/data/com.termux/files/usr/tmp/pip-build-env-0buzgxd0/overlay/lib/python3.11/site-packages/setuptools/command/build_ext.py", line 88, in run
          _build_ext.run(self)
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-0buzgxd0/overlay/lib/python3.11/site-packages/setuptools/_distutils/command/build_ext.py", line 345, in run
          self.build_extensions()
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-0buzgxd0/overlay/lib/python3.11/site-packages/setuptools/_distutils/command/build_ext.py", line 467, in build_extensions
          self._build_extensions_serial()
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-0buzgxd0/overlay/lib/python3.11/site-packages/setuptools/_distutils/command/build_ext.py", line 493, in _build_extensions_serial
          self.build_extension(ext)
        File "<string>", line 87, in build_extension
        File "/data/data/com.termux/files/usr/lib/python3.11/subprocess.py", line 413, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['./build_bundled.sh', '0.1.99']' returned non-zero exit status 2.
      [end of output]                                      
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for sentencepiece
Failed to build sentencepiece
ERROR: Could not build wheels for sentencepiece, which is required to install pyproject.toml-based projects
```

### What steps will reproduce the bug?

`pip install sentencepiece`

### What is the expected behavior?

installation without Errors

### System information

termux-info:

```
termux-info
                                                           
Termux Variables:
TERMUX_APK_RELEASE=F_DROID
TERMUX_APP_PACKAGE_MANAGER=apt                            
TERMUX_APP_PID=21742                                      
TERMUX_IS_DEBUGGABLE_BUILD=0                              
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
Packages CPU architecture:
aarch64
Subscribed repositories:                                   
# sources.list                                             
deb https://packages-cf.termux.dev/apt/termux-main stable main                                                        
# sources.list.d/pointless.list
deb https://its-pointless.github.io/files/21 termux extras Updatable packages:
All packages up to date
termux-tools version:
1.38.5
Android version:
12
Kernel build information:                                  
Linux localhost 4.14.190-23725627-abG975WVLS8IWD1 #2 SMP PREEMPT Mon Apr 10 18:16:39 KST 2023 aarch64 Android        
Device manufacturer:
samsung
Device model: SM-G975W
LD Variables:
LD_LIBRARY_PATH=
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so
Installed termux plugins:                                  
com.termux.styling versionCode:30
```

Thank you.

**Comment by romanovj** [comment]
undefined symbol: __android_log_write

`LDFLAGS=-llog pip install sentencepiece`

**Comment by JackJollimore** [comment]
Solved! Thank you, and thanks for the quick response.

**Comment by woderen1** [comment]
> undefined symbol: __android_log_write
> 
> `LDFLAGS=-llog pip install sentencepiece`

Very thankful
I also solve this problem

```
Requirement already satisfied: sentencepiece in /data/data/com.termux/files/usr/lib/python3.13/site-packages (0.2.1)
```
