### ISSUE TITLE
Can't install sentencepice

### ISSUE THREAD

**Issue by guranu** [termux/termux-packages#17703]
### Problem description

sentencepiece will not install typing pip install sentencepiece nor will it install by adding `--no-build-isolation`

### What steps will reproduce the bug?

```
$ pip install sentencepiece --no-build-isolation
Collecting sentencepiece
  Using cached sentencepiece-0.1.99.tar.gz (2.6 MB)
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: sentencepiece
  Building wheel for sentencepiece (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [201 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.linux-aarch64-cpython-311
      creating build/lib.linux-aarch64-cpython-311/sentencepiece
      copying src/sentencepiece/__init__.py -> build/lib.linux-aarch64-cpython-311/sentencepiece
      copying src/sentencepiece/_version.py -> build/lib.linux-aarch64-cpython-311/sentencepiece
      copying src/sentencepiece/sentencepiece_model_pb2.py -> build/lib.linux-aarch64-cpython-311/sentencepiece
      copying src/sentencepiece/sentencepiece_pb2.py -> build/lib.linux-aarch64-cpython-311/sentencepiece
      running build_ext
      Package sentencepiece was not found in the pkg-config search path.
      Perhaps you should add the directory containing `sentencepiece.pc'
      to the PKG_CONFIG_PATH environment variable
      No package 'sentencepiece' found
      -- VERSION: 0.1.99
      -- The C compiler identification is Clang 16.0.6
      -- The CXX compiler identification is Clang 16.0.6
      -- Detecting C compiler ABI info
      -- Detecting C compiler ABI info - done
      -- Check for working C compiler: /data/data/com.termux/files/usr/bin/cc - skipped
      -- Detecting C compile features
      -- Detecting C compile features - done
      -- Detecting CXX compiler ABI info
      -- Detecting CXX compiler ABI info - done
      -- Check for working CXX compiler: /data/data/com.termux/files/usr/bin/c++ - skipped
      -- Detecting CXX compile features
      -- Detecting CXX compile features - done
      -- Performing Test CMAKE_HAVE_LIBC_PTHREAD
      -- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
      -- Looking for pthread_create in pthreads
      -- Looking for pthread_create in pthreads - not found
      -- Looking for pthread_create in pthread
      -- Looking for pthread_create in pthread - found
      -- Found Threads: TRUE
      -- Not Found TCMalloc: TCMALLOC_LIB-NOTFOUND
      -- Found atomic: /data/data/com.termux/files/usr/lib/libatomic.a
      -- Configuring done (4.3s)
      -- Generating done (0.0s)
      -- Build files have been written to: /data/data/com.termux/files/usr/tmp/pip-install-c5ijyick/sentencepiece_fcc239807f3b4ab68e4aa4b3e597bb00/build
      [  1%] Building CXX object src/CMakeFiles/sentencepiece-static.dir/__/third_party/protobuf-lite/arenastring.cc.o
      [  3%] Building CXX object src/CMakeFiles/sentencepiece_train-static.dir/unicode_script.cc.o
      [  4%] Building CXX object src/CMakeFiles/sentencepiece_train-static.dir/builder.cc.o
      [  6%] Building CXX object src/CMakeFiles/sentencepiece-static.dir/__/third_party/protobuf-lite/arena.cc.o
      [  8%] Building CXX object src/CMakeFiles/sentencepiece-static.dir/__/third_party/protobuf-lite/bytestream.cc.o
      [  9%] Building CXX object src/CMakeFiles/sentencepiece_train-static.dir/trainer_interface.cc.o
      [ 11%] Building CXX object src/CMakeFiles/sentencepiece_train-static.dir/trainer_factory.cc.o
      [ 12%] Building CXX object src/CMakeFiles/sentencepiece-static.dir/__/third_party/protobuf-lite/coded_stream.cc.o
      [ 14%] Building CXX object src/CMakeFiles/sentencepiece-static.dir/__/third_party/protobuf-lite/common.cc.o
      [ 16%] Building CXX object src/CMakeFiles/sentencepiece-static.dir/__/third_party/protobuf-lite/extension_set.cc.o
      /data/data/com.termux/files/usr/tmp/pip-install-c5ijyick/sentencepiece_fcc239807f3b4ab68e4aa4b3e597bb00/sentencepiece/src/builder.cc:47:15: warning: unused variable 'kMaxUnicode' [-Wunused-const-variable]
      constexpr int kMaxUnicode = 0x10FFFF;
                    ^
      /data/data/com.termux/files/usr/tmp/pip-install-c5ijyick/sentencepiece_fcc239807f3b4ab68e4aa4b3e597bb00/sentencepiece/src/builder.cc:49:23: warning: unused variable 'kDefaultNormalizerName' [-Wunused-const-variable]
      static constexpr char kDefaultNormalizerName[] = "nfkc";
                            ^
      [ 17%] Building CXX object src/CMakeFiles/sentencepiece-static.dir/__/third_party/protobuf-lite/generated_enum_util.cc.o
      [ 19%] Building CXX object src/CMakeFiles/sentencepiece_train-static.dir/unigram_model_trainer.cc.o
      [ 20%] Building CXX object src/CMakeFiles/sentencepiece-static.dir/__/third_party/protobuf-lite/generated_message_table_driven_lite.cc.o
      2 warnings generated.
      [ 22%] Building CXX object src/CMakeFiles/sentencepiece_train-static.dir/word_model_trainer.cc.o
      [ 24%] Building CXX object src/CMakeFiles/sentencepiece-static.dir/__/third_party/protobuf-lite/generated_message_util.cc.o
      [ 25%] Building CXX object src/CMakeFiles/sentencepiece_train-static.dir/char_model_trainer.cc.o
      [ 27%] Building CXX object src/CMakeFiles/sentencepiece-static.dir/__/third_party/protobuf-lite/implicit_weak_message.cc.o
      [ 29%] Building CXX object src/CMakeFiles/sentencepiece_train-static.dir/bpe_model_trainer.cc.o
      [ 30%] Building CXX object src/CMakeFiles/sentencepiece-static.dir/__/third_party/protobuf-lite/int128.cc.o
      [ 32%] Building CXX object src/CMakeFiles/sentencepiece-static.dir/__/third_party/protobuf-lite/io_win32.cc.o                                                           [ 33%] Building CXX object src/CMakeFiles/sentencepiece-static.dir/__/third_party/protobuf-lite/message_lite.cc.o                                                       [ 35%] Building CXX object src/CMakeFiles/sentencepiece_train-static.dir/sentencepiece_trainer.cc.o             [ 37%] Building CXX object src/CMakeFiles/sentencepiece-static.dir/__/third_party/protobuf-lite/parse_context.cc.o                                                      [ 38%] Building CXX object src/CMakeFiles/sentencepiece-static.dir/__/third_party/protobuf-lite/repeated_field.cc.o
      [ 40%] Building CXX object src/CMakeFiles/sentencepiece_train-static.dir/pretokenizer_for_training.cc.o         [ 41%] Building CXX object src/CMakeFiles/sentencepiece-static.dir/__/third_party/protobuf-lite/status.cc.o
      [ 43%] Building CXX object src/CMakeFiles/sentencepiece-static.dir/__/third_party/protobuf-lite/statusor.cc.o
      [ 45%] Building CXX object src/CMakeFiles/sentencepiece-static.dir/__/third_party/protobuf-lite/stringpiece.cc.o
      [ 46%] Building CXX object src/CMakeFiles/sentencepiece-static.dir/__/third_party/protobuf-lite/stringprintf.cc.o
      [ 48%] Building CXX object src/CMakeFiles/sentencepiece-static.dir/__/third_party/protobuf-lite/structurally_valid.cc.o                                                 [ 50%] Building CXX object src/CMakeFiles/sentencepiece-static.dir/__/third_party/protobuf-lite/strutil.cc.o                                                            [ 51%] Building CXX object src/CMakeFiles/sentencepiece-static.dir/__/third_party/protobuf-lite/time.cc.o       [ 53%] Building CXX object src/CMakeFiles/sentencepiece-static.dir/__/third_party/protobuf-lite/wire_format_lite.cc.o                                                   [ 54%] Building CXX object src/CMakeFiles/sentencepiece-static.dir/__/third_party/protobuf-lite/zero_copy_stream.cc.o                                                   [ 56%] Building CXX object src/CMakeFiles/sentencepiece-static.dir/__/third_party/protobuf-lite/zero_copy_stream_impl.cc.o                                              [ 58%] Linking CXX static library libsentencepiece_train.a
      [ 59%] Building CXX object src/CMakeFiles/sentencepiece-static.dir/__/third_party/protobuf-lite/zero_copy_stream_impl_lite.cc.o
      [ 61%] Building CXX object src/CMakeFiles/sentencepiece-static.dir/builtin_pb/sentencepiece.pb.cc.o
      [ 61%] Built target sentencepiece_train-static
      [ 62%] Building CXX object src/CMakeFiles/sentencepiece-static.dir/builtin_pb/sentencepiece_model.pb.cc.o
      [ 64%] Building CXX object src/CMakeFiles/sentencepiece-static.dir/bpe_model.cc.o
      [ 66%] Building CXX object src/CMakeFiles/sentencepiece-static.dir/char_model.cc.o                              [ 67%] Building CXX object src/CMakeFiles/sentencepiece-static.dir/error.cc.o
      [ 69%] Building CXX object src/CMakeFiles/sentencepiece-static.dir/filesystem.cc.o
      [ 70%] Building CXX object src/CMakeFiles/sentencepiece-static.dir/model_factory.cc.o
      [ 72%] Building CXX object src/CMakeFiles/sentencepiece-static.dir/model_interface.cc.o                         [ 74%] Building CXX object src/CMakeFiles/sentencepiece-static.dir/normalizer.cc.o                              [ 75%] Building CXX object src/CMakeFiles/sentencepiece-static.dir/sentencepiece_processor.cc.o                 [ 77%] Building CXX object src/CMakeFiles/sentencepiece-static.dir/unigram_model.cc.o                           [ 79%] Building CXX object src/CMakeFiles/sentencepiece-static.dir/util.cc.o
      [ 80%] Building CXX object src/CMakeFiles/sentencepiece-static.dir/word_model.cc.o
      [ 82%] Building CXX object src/CMakeFiles/sentencepiece-static.dir/__/third_party/absl/flags/flag.cc.o
      [ 83%] Linking CXX static library libsentencepiece.a
      [ 83%] Built target sentencepiece-static                [ 85%] Building CXX object src/CMakeFiles/spm_train.dir/spm_train_main.cc.o                                     [ 87%] Building CXX object src/CMakeFiles/spm_export_vocab.dir/spm_export_vocab_main.cc.o                       [ 88%] Building CXX object src/CMakeFiles/spm_encode.dir/spm_encode_main.cc.o                                   [ 90%] Building CXX object src/CMakeFiles/spm_decode.dir/spm_decode_main.cc.o                                   [ 91%] Building CXX object src/CMakeFiles/spm_normalize.dir/spm_normalize_main.cc.o                             [ 93%] Linking CXX executable spm_export_vocab
      [ 95%] Linking CXX executable spm_train                 ld.lld: error: undefined symbol: __android_log_write                                                            >>> referenced by common.cc:150 (/data/data/com.termux/files/usr/tmp/pip-install-c5ijyick/sentencepiece_fcc239807f3b4ab68e4aa4b3e597bb00/sentencepiece/third_party/protobuf-lite/common.cc:150)                                 >>>               common.cc.o:(google::protobuf::internal::DefaultLogHandler(google::protobuf::LogLevel, char const*, int, std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char>> const&)) in archive libsentencepiece.a
      >>> referenced by common.cc:158 (/data/data/com.termux/files/usr/tmp/pip-install-c5ijyick/sentencepiece_fcc239807f3b4ab68e4aa4b3e597bb00/sentencepiece/third_party/protobuf-lite/common.cc:158)
      >>>               common.cc.o:(google::protobuf::internal::DefaultLogHandler(google::protobuf::LogLevel, char const*, int, std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char>> const&)) in archive libsentencepiece.a
      clang-16: error: linker command failed with exit code 1 (use -v to see invocation)
      make[2]: *** [src/CMakeFiles/spm_export_vocab.dir/build.make:98: src/spm_export_vocab] Error 1                  make[1]: *** [CMakeFiles/Makefile2:286: src/CMakeFiles/spm_export_vocab.dir/all] Error 2
      make[1]: *** Waiting for unfinished jobs....
      ld.lld: error: undefined symbol: __android_log_write
      >>> referenced by common.cc:150 (/data/data/com.termux/files/usr/tmp/pip-install-c5ijyick/sentencepiece_fcc239807f3b4ab68e4aa4b3e597bb00/sentencepiece/third_party/protobuf-lite/common.cc:150)
      >>>               common.cc.o:(google::protobuf::internal::DefaultLogHandler(google::protobuf::LogLevel, char const*, int, std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char>> const&)) in archive libsentencepiece.a
      >>> referenced by common.cc:158 (/data/data/com.termux/files/usr/tmp/pip-install-c5ijyick/sentencepiece_fcc239807f3b4ab68e4aa4b3e597bb00/sentencepiece/third_party/protobuf-lite/common.cc:158)                                 >>>               common.cc.o:(google::protobuf::internal::DefaultLogHandler(google::protobuf::LogLevel, char const*, int, std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char>> const&)) in archive libsentencepiece.a
      clang-16: error: linker command failed with exit code 1 (use -v to see invocation)
      make[2]: *** [src/CMakeFiles/spm_train.dir/build.make:100: src/spm_train] Error 1
      make[1]: *** [CMakeFiles/Makefile2:260: src/CMakeFiles/spm_train.dir/all] Error 2
      [ 96%] Linking CXX executable spm_decode
      ld.lld: error: undefined symbol: __android_log_write                                                            >>> referenced by common.cc:150 (/data/data/com.termux/files/usr/tmp/pip-install-c5ijyick/sentencepiece_fcc239807f3b4ab68e4aa4b3e597bb00/sentencepiece/third_party/protobuf-lite/common.cc:150)                                 >>>               common.cc.o:(google::protobuf::internal::DefaultLogHandler(google::protobuf::LogLevel, char const*, int, std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char>> const&)) in archive libsentencepiece.a
      >>> referenced by common.cc:158 (/data/data/com.termux/files/usr/tmp/pip-install-c5ijyick/sentencepiece_fcc239807f3b4ab68e4aa4b3e597bb00/sentencepiece/third_party/protobuf-lite/common.cc:158)
      >>>               common.cc.o:(google::protobuf::internal::DefaultLogHandler(google::protobuf::LogLevel, char const*, int, std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char>> const&)) in archive libsentencepiece.a
      clang-16: error: linker command failed with exit code 1 (use -v to see invocation)
      make[2]: *** [src/CMakeFiles/spm_decode.dir/build.make:98: src/spm_decode] Error 1                              make[1]: *** [CMakeFiles/Makefile2:206: src/CMakeFiles/spm_decode.dir/all] Error 2
      [ 98%] Linking CXX executable spm_normalize             ld.lld: error: undefined symbol: __android_log_write                                                            >>> referenced by common.cc:150 (/data/data/com.termux/files/usr/tmp/pip-install-c5ijyick/sentencepiece_fcc239807f3b4ab68e4aa4b3e597bb00/sentencepiece/third_party/protobuf-lite/common.cc:150)                                 >>>               common.cc.o:(google::protobuf::internal::DefaultLogHandler(google::protobuf::LogLevel, char const*, int, std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char>> const&)) in archive libsentencepiece.a
      >>> referenced by common.cc:158 (/data/data/com.termux/files/usr/tmp/pip-install-c5ijyick/sentencepiece_fcc239807f3b4ab68e4aa4b3e597bb00/sentencepiece/third_party/protobuf-lite/common.cc:158)
      >>>               common.cc.o:(google::protobuf::internal::DefaultLogHandler(google::protobuf::LogLevel, char const*, int, std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char>> const&)) in archive libsentencepiece.a                         clang-16: error: linker command failed with exit code 1 (use -v to see invocation)                              make[2]: *** [src/CMakeFiles/spm_normalize.dir/build.make:100: src/spm_normalize] Error 1                       make[1]: *** [CMakeFiles/Makefile2:233: src/CMakeFiles/spm_normalize.dir/all] Error 2                           [100%] Linking CXX executable spm_encode                ld.lld: error: undefined symbol: __android_log_write
      >>> referenced by common.cc:150 (/data/data/com.termux/files/usr/tmp/pip-install-c5ijyick/sentencepiece_fcc239807f3b4ab68e4aa4b3e597bb00/sentencepiece/third_party/protobuf-lite/common.cc:150)
      >>>               common.cc.o:(google::protobuf::internal::DefaultLogHandler(google::protobuf::LogLevel, char const*, int, std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char>> const&)) in archive libsentencepiece.a                         >>> referenced by common.cc:158 (/data/data/com.termux/files/usr/tmp/pip-install-c5ijyick/sentencepiece_fcc239807f3b4ab68e4aa4b3e597bb00/sentencepiece/third_party/protobuf-lite/common.cc:158)                                 >>>               common.cc.o:(google::protobuf::internal::DefaultLogHandler(google::protobuf::LogLevel, char const*, int, std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char>> const&)) in archive libsentencepiece.a                         clang-16: error: linker command failed with exit code 1 (use -v to see invocation)                              make[2]: *** [src/CMakeFiles/spm_encode.dir/build.make:98: src/spm_encode] Error 1
      make[1]: *** [CMakeFiles/Makefile2:180: src/CMakeFiles/spm_encode.dir/all] Error 2
      make: *** [Makefile:156: all] Error 2
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/data/data/com.termux/files/usr/tmp/pip-install-c5ijyick/sentencepiece_fcc239807f3b4ab68e4aa4b3e597bb00/setup.py", line 167, in <module>                            setup(                                                File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/setuptools/__init__.py", line 107, in setup                                                            return distutils.core.setup(**attrs)                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 185, in setup                                                     return run_commands(dist)                                      ^^^^^^^^^^^^^^^^^^
        File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 201, in run_commands                                              dist.run_commands()
        File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/setuptools/dist.py", line 1233, in run_command                                                         super().run_command(command)
        File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command                                               cmd_obj.run()                                         File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/wheel/bdist_wheel.py", line 364, in run                                                                self.run_command("build")                             File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command                                                self.distribution.run_command(command)                File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/setuptools/dist.py", line 1233, in run_command                                                         super().run_command(command)
        File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command                                               cmd_obj.run()
        File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/setuptools/_distutils/command/build.py", line 131, in run
          self.run_command(cmd_name)
        File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command                                                self.distribution.run_command(command)                File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/setuptools/dist.py", line 1233, in run_command                                                         super().run_command(command)                          File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command                                               cmd_obj.run()                                         File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/setuptools/command/build_ext.py", line 88, in run                                                      _build_ext.run(self)                                  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/setuptools/_distutils/command/build_ext.py", line 345, in run                                          self.build_extensions()
        File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/setuptools/_distutils/command/build_ext.py", line 467, in build_extensions                             self._build_extensions_serial()
        File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/setuptools/_distutils/command/build_ext.py", line 493, in _build_extensions_serial
          self.build_extension(ext)
        File "/data/data/com.termux/files/usr/tmp/pip-install-c5ijyick/sentencepiece_fcc239807f3b4ab68e4aa4b3e597bb00/setup.py", line 87, in build_extension
          subprocess.check_call(['./build_bundled.sh', __version__])                                                    File "/data/data/com.termux/files/usr/lib/python3.11/subprocess.py", line 413, in check_call                      raise CalledProcessError(retcode, cmd)              subprocess.CalledProcessError: Command '['./build_bundled.sh', '0.1.99']' returned non-zero exit status 2.      [end of output]                                                                                             note: This error originates from a subprocess, and is likely not a problem with pip.                            ERROR: Failed building wheel for sentencepiece          Running setup.py clean for sentencepiece              Failed to build sentencepiece
ERROR: Could not build wheels for sentencepiece, which is required to install pyproject.toml-based projects
```

### System information

termux-info:

```
Termux Variables:
TERMUX_APK_RELEASE=F_DROID                              TERMUX_APP_PACKAGE_MANAGER=apt                          TERMUX_APP_PID=16490                                    TERMUX_IS_DEBUGGABLE_BUILD=0                            TERMUX_MAIN_PACKAGE_FORMAT=debian                       TERMUX_VERSION=0.118.0                                  Packages CPU architecture:                              aarch64                                                 Subscribed repositories:                                # sources.list                                          deb https://grimler.se/termux/termux-main stable main   Updatable packages:                                     command-not-found/stable 2.2.0-13 aarch64 [upgradable from: 2.2.0-12]                                           git/stable 2.42.0 aarch64 [upgradable from: 2.41.0]     gzip/stable 1.13 aarch64 [upgradable from: 1.12-1]
libsmartcols/stable 2.39.2 aarch64 [upgradable from: 2.39.1]
util-linux/stable 2.39.2 aarch64 [upgradable from: 2.39.1]
zlib/stable 1.3 aarch64 [upgradable from: 1.2.13]
termux-tools version:
1.38.5
Android version:
10                                                      Kernel build information:
Linux localhost 4.14.117-perf+ #1 SMP PREEMPT Thu Jan 28 00:40:44 CST 2021 aarch64 Android                      Device manufacturer:                                    OnePlus                                                 Device model:                                           GM1900                                                  LD Variables:                                           LD_LIBRARY_PATH=                                        LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so
```

**Comment by romanovj** [comment]
https://github.com/termux/termux-packages/issues/17688

**Comment by guranu** [comment]
Oh shit, i'm sorry for making duplicate issues.
