### ISSUE TITLE
Python: pip can't install anything now

### ISSUE THREAD

**Issue by kurokirasama** [termux/termux-packages#1771]
Hello, when I first installed python so I could use Octave also installed without problem sympy trough pip. Now every time I try to install anything trough pop I got:
```
Traceback (most recent call last):                 File "/data/data/com.termux/files/usr/bin/pip", line 7, in <module>                                 from pip import main
  File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/pip/__init__.py", line 28, in <module>                                             from pip.vcs import git, mercurial, subversion, bazaar  # noqa                                  File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/pip/vcs/mercurial.py", line 9, in <module>                                         from pip.download import path_to_url
  File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/pip/download.py", line 47, in <module>                                             from pip._vendor.cachecontrol import CacheControlAdapter
ModuleNotFoundError: No module named 'pip._vendor.cachecontrol'
```

**Comment by Grimler91** [comment]
Have you tried reinstalling python?

**Comment by kurokirasama** [comment]
yes, i also did a fresh install o termux. And after a while i got the same error again. Nevertheless, i can install using `easy_install`

**Comment by Grimler91** [comment]
According to this [stackexchange question&answer](https://stackoverflow.com/questions/28079395/no-module-named-pip-vendor-cachecontrol), it might be because openssl isn't installed. So try 
```
pkg install openssl
apt install python --reinstall
```

**Comment by sdrausty** [comment]
@kurokirasama  More information about your topic is requested.  Post more information regarding your machine. Use `termux-info` and share this output with us.

**Comment by amanbhandari2002** [comment]
> According to this [stackexchange question&answer](https://stackoverflow.com/questions/28079395/no-module-named-pip-vendor-cachecontrol), it might be because openssl isn't installed. So try 
> ```
> pkg install openssl
> apt install python --reinstall
> ```

Thank you

**Comment by Venom836** [comment]
How To fix problem No module Found lib

**Comment by RossComputerGuy** [comment]
@Venom836 that's a different issue, look up "python missing module" online and you should get more info on what your looking for.
