### ISSUE TITLE
[Bug]: Unable to install scikit-learn

### ISSUE THREAD

**Issue by beheshtiBlockchain** [termux/termux-packages#17829]
### Problem description

I have cloned scikit-learn from github and trying to install it by using the following command:
```
git clone https://github.com/scikit-learn/scikit-learn.git
cd scikit-learn
MATHLIB='m' pip install .
```
from the source.
I am constantly getting the same error with every proposed solutions(MATHLIB='m', --no-binary)

<details><summary>The &lt;complex.h&gt; Error</summary>
<p>

2023-09-15T13:45:48,023   extra options: '-march=armv8.2-a+fp16fml'
2023-09-15T13:45:48,216   INFO: CCompilerOpt.feature_test[1559] : testing feature 'ASIMDFHM' with flags (-march=armv8.2-a+fp16+fp16fml)
2023-09-15T13:45:48,218   INFO: C compiler: aarch64-linux-android-clang -DNDEBUG -g -fwrapv -O3 -Wall -fstack-protector-strong -O3 -fstack-protector-strong -O3 -fPIC -ftrapping-math

2023-09-15T13:45:48,223   INFO: compile options: '-Inumpy/core/src/common -Inumpy/core/src -Inumpy/core -Inumpy/core/src/npymath -Inumpy/core/src/multiarray -Inumpy/core/src/umath -Inumpy/core/src/npysort -Inumpy/core/src/_simd -I/data/data/com.termux/files/usr/include/python3.11 -Ibuild/src.linux-aarch64-3.11/numpy/core/src/common -Ibuild/src.linux-aarch64-3.11/numpy/core/src/npymath -c'
2023-09-15T13:45:48,226   extra options: '-march=armv8.2-a+fp16+fp16fml -Werror=switch -Werror'
2023-09-15T13:45:49,696   INFO: CCompilerOpt.__init__[1815] : skip features (NEON_VFPV4 ASIMD NEON NEON_FP16) since its part of baseline
2023-09-15T13:45:49,714   INFO: CCompilerOpt.__init__[1819] : initialize targets groups
2023-09-15T13:45:49,732   INFO: CCompilerOpt.__init__[1821] : parse target group simd_test
2023-09-15T13:45:49,751   INFO: CCompilerOpt._parse_target_tokens[2032] : skip targets (AVX512F VX VSX4 VSX VSX2 AVX512_SKX VSX3 VXE VXE2 XOP (FMA3 AVX2) SSE42 SSE2 FMA4) not part of baseline or dispatch-able features
2023-09-15T13:45:49,769   INFO: CCompilerOpt._parse_policy_not_keepbase[2144] : skip baseline features (ASIMD)
2023-09-15T13:45:49,786   INFO: CCompilerOpt.generate_dispatch_header[2365] : generate CPU dispatch header: (build/src.linux-aarch64-3.11/numpy/distutils/include/npy_cpu_dispatch_config.h)
2023-09-15T13:45:49,803   WARN: CCompilerOpt.generate_dispatch_header[2374] : dispatch header dir build/src.linux-aarch64-3.11/numpy/distutils/include does not exist, creating it
2023-09-15T13:45:49,809   INFO: C compiler: aarch64-linux-android-clang -DNDEBUG -g -fwrapv -O3 -Wall -fstack-protector-strong -O3 -fstack-protector-strong -O3 -fPIC -ftrapping-math

2023-09-15T13:45:49,814   creating data
2023-09-15T13:45:49,817   creating data/data
2023-09-15T13:45:49,819   creating data/data/com.termux
2023-09-15T13:45:49,822   creating data/data/com.termux/files
2023-09-15T13:45:49,825   creating data/data/com.termux/files/usr
2023-09-15T13:45:49,828   creating data/data/com.termux/files/usr/tmp
2023-09-15T13:45:49,836   creating data/data/com.termux/files/usr/tmp/tmpkult2q46
2023-09-15T13:45:49,844   INFO: compile options: '-Inumpy/core/src/common -Inumpy/core/src -Inumpy/core -Inumpy/core/src/npymath -Inumpy/core/src/multiarray -Inumpy/core/src/umath -Inumpy/core/src/npysort -Inumpy/core/src/_simd -I/data/data/com.termux/files/usr/include/python3.11 -Ibuild/src.linux-aarch64-3.11/numpy/core/src/common -Ibuild/src.linux-aarch64-3.11/numpy/core/src/npymath -c'
2023-09-15T13:45:49,846   INFO: aarch64-linux-android-clang: /data/data/com.termux/files/usr/tmp/tmpkult2q46/test.c
2023-09-15T13:45:50,003   INFO: C compiler: aarch64-linux-android-clang++ -DNDEBUG -g -fwrapv -O3 -Wall -fstack-protector-strong -O3 -fstack-protector-strong -O3 -fPIC -ftrapping-math

2023-09-15T13:45:50,009   creating data/data/com.termux/files/usr/tmp/tmp1z6gy5aw
2023-09-15T13:45:50,011   INFO: compile options: '-Inumpy/core/src/common -Inumpy/core/src -Inumpy/core -Inumpy/core/src/npymath -Inumpy/core/src/multiarray -Inumpy/core/src/umath -Inumpy/core/src/npysort -Inumpy/core/src/_simd -I/data/data/com.termux/files/usr/include/python3.11 -Ibuild/src.linux-aarch64-3.11/numpy/core/src/common -Ibuild/src.linux-aarch64-3.11/numpy/core/src/npymath -c'
2023-09-15T13:45:50,013   INFO: aarch64-linux-android-clang++: /data/data/com.termux/files/usr/tmp/tmp1z6gy5aw/test.cpp
2023-09-15T13:45:50,490   INFO: building 'npymath' library
2023-09-15T13:45:50,492   INFO: compiling C sources
2023-09-15T13:45:50,493   INFO: C compiler: aarch64-linux-android-clang -DNDEBUG -g -fwrapv -O3 -Wall -fstack-protector-strong -O3 -fstack-protector-strong -O3 -fPIC -ftrapping-math

2023-09-15T13:45:50,497   creating build/temp.linux-aarch64-3.11
2023-09-15T13:45:50,499   creating build/temp.linux-aarch64-3.11/numpy
2023-09-15T13:45:50,501   creating build/temp.linux-aarch64-3.11/numpy/core
2023-09-15T13:45:50,504   creating build/temp.linux-aarch64-3.11/numpy/core/src
2023-09-15T13:45:50,506   creating build/temp.linux-aarch64-3.11/numpy/core/src/npymath
2023-09-15T13:45:50,508   creating build/temp.linux-aarch64-3.11/build
2023-09-15T13:45:50,511   creating build/temp.linux-aarch64-3.11/build/src.linux-aarch64-3.11
2023-09-15T13:45:50,513   creating build/temp.linux-aarch64-3.11/build/src.linux-aarch64-3.11/numpy
2023-09-15T13:45:50,516   creating build/temp.linux-aarch64-3.11/build/src.linux-aarch64-3.11/numpy/core
2023-09-15T13:45:50,518   creating build/temp.linux-aarch64-3.11/build/src.linux-aarch64-3.11/numpy/core/src
2023-09-15T13:45:50,521   creating build/temp.linux-aarch64-3.11/build/src.linux-aarch64-3.11/numpy/core/src/npymath
2023-09-15T13:45:50,523   INFO: compile options: '-Ibuild/src.linux-aarch64-3.11/numpy/core/src/npymath -Inumpy/core/include -Ibuild/src.linux-aarch64-3.11/numpy/core/include/numpy -Ibuild/src.linux-aarch64-3.11/numpy/distutils/include -Inumpy/core/src/common -Inumpy/core/src -Inumpy/core -Inumpy/core/src/npymath -Inumpy/core/src/multiarray -Inumpy/core/src/umath -Inumpy/core/src/npysort -Inumpy/core/src/_simd -I/data/data/com.termux/files/usr/include/python3.11 -Ibuild/src.linux-aarch64-3.11/numpy/core/src/common -Ibuild/src.linux-aarch64-3.11/numpy/core/src/npymath -c'
2023-09-15T13:45:50,533   INFO: aarch64-linux-android-clang: numpy/core/src/npymath/npy_math.c
2023-09-15T13:45:50,536   INFO: aarch64-linux-android-clang: build/src.linux-aarch64-3.11/numpy/core/src/npymath/ieee754.c
2023-09-15T13:45:50,539   INFO: aarch64-linux-android-clang: build/src.linux-aarch64-3.11/numpy/core/src/npymath/npy_math_complex.c
2023-09-15T13:45:52,508   numpy/core/src/npymath/npy_math_complex.c.src:430:17: error: call to undeclared library function 'cpowf' with type '_Complex float (_Complex float, _Complex float)'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
2023-09-15T13:45:52,511       ret.c99_z = cpowf(xcast.c99_z, ycast.c99_z);
2023-09-15T13:45:52,513                   ^
2023-09-15T13:45:52,516   numpy/core/src/npymath/npy_math_complex.c.src:430:17: note: include the header <complex.h> or explicitly provide a declaration for 'cpowf'
2023-09-15T13:45:52,519   numpy/core/src/npymath/npy_math_complex.c.src:430:17: error: call to undeclared library function 'cpow' with type '_Complex double (_Complex double, _Complex double)'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
2023-09-15T13:45:52,522       ret.c99_z = cpow(xcast.c99_z, ycast.c99_z);
2023-09-15T13:45:52,524                   ^
2023-09-15T13:45:52,526   numpy/core/src/npymath/npy_math_complex.c.src:430:17: note: include the header <complex.h> or explicitly provide a declaration for 'cpow'
2023-09-15T13:45:52,528   numpy/core/src/npymath/npy_math_complex.c.src:430:17: error: call to undeclared library function 'cpowl' with type '_Complex long double (_Complex long double, _Complex long double)'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
2023-09-15T13:45:52,531       ret.c99_z = cpowl(xcast.c99_z, ycast.c99_z);
2023-09-15T13:45:52,534                   ^
2023-09-15T13:45:52,536   numpy/core/src/npymath/npy_math_complex.c.src:430:17: note: include the header <complex.h> or explicitly provide a declaration for 'cpowl'
2023-09-15T13:45:52,539   numpy/core/src/npymath/npy_math_complex.c.src:1779:17: error: call to undeclared library function 'clogf' with type '_Complex float (_Complex float)'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
2023-09-15T13:45:52,542       ret.c99_z = clogf(z1.c99_z);
2023-09-15T13:45:52,544                   ^
2023-09-15T13:45:52,546   numpy/core/src/npymath/npy_math_complex.c.src:1779:17: note: include the header <complex.h> or explicitly provide a declaration for 'clogf'
2023-09-15T13:45:52,549   numpy/core/src/npymath/npy_math_complex.c.src:1779:17: error: call to undeclared library function 'clog' with type '_Complex double (_Complex double)'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
2023-09-15T13:45:52,552       ret.c99_z = clog(z1.c99_z);
2023-09-15T13:45:52,555                   ^
2023-09-15T13:45:52,557   numpy/core/src/npymath/npy_math_complex.c.src:1779:17: note: include the header <complex.h> or explicitly provide a declaration for 'clog'
2023-09-15T13:45:52,560   numpy/core/src/npymath/npy_math_complex.c.src:1779:17: error: call to undeclared library function 'cexpl' with type '_Complex long double (_Complex long double)'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
2023-09-15T13:45:52,563       ret.c99_z = cexpl(z1.c99_z);
2023-09-15T13:45:52,566                   ^
2023-09-15T13:45:52,568   numpy/core/src/npymath/npy_math_complex.c.src:1779:17: note: include the header <complex.h> or explicitly provide a declaration for 'cexpl'
2023-09-15T13:45:52,571   numpy/core/src/npymath/npy_math_complex.c.src:1779:17: error: call to undeclared library function 'clogl' with type '_Complex long double (_Complex long double)'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
2023-09-15T13:45:52,574       ret.c99_z = clogl(z1.c99_z);
2023-09-15T13:45:52,576                   ^
2023-09-15T13:45:52,578   numpy/core/src/npymath/npy_math_complex.c.src:1779:17: note: include the header <complex.h> or explicitly provide a declaration for 'clogl'
2023-09-15T13:45:52,580   numpy/core/src/npymath/npy_math_complex.c.src:1779:17: error: call to undeclared library function 'ccosl' with type '_Complex long double (_Complex long double)'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
2023-09-15T13:45:52,583       ret.c99_z = ccosl(z1.c99_z);
2023-09-15T13:45:52,585                   ^
2023-09-15T13:45:52,587   numpy/core/src/npymath/npy_math_complex.c.src:1779:17: note: include the header <complex.h> or explicitly provide a declaration for 'ccosl'
2023-09-15T13:45:52,589   numpy/core/src/npymath/npy_math_complex.c.src:1779:17: error: call to undeclared library function 'csinl' with type '_Complex long double (_Complex long double)'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
2023-09-15T13:45:52,592       ret.c99_z = csinl(z1.c99_z);
2023-09-15T13:45:52,594                   ^
2023-09-15T13:45:52,597   numpy/core/src/npymath/npy_math_complex.c.src:1779:17: note: include the header <complex.h> or explicitly provide a declaration for 'csinl'
2023-09-15T13:45:52,599   numpy/core/src/npymath/npy_math_complex.c.src:1779:17: error: call to undeclared library function 'ctanl' with type '_Complex long double (_Complex long double)'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
2023-09-15T13:45:52,602       ret.c99_z = ctanl(z1.c99_z);
2023-09-15T13:45:52,604                   ^
2023-09-15T13:45:52,607   numpy/core/src/npymath/npy_math_complex.c.src:1779:17: note: include the header <complex.h> or explicitly provide a declaration for 'ctanl'
2023-09-15T13:45:52,610   numpy/core/src/npymath/npy_math_complex.c.src:1779:17: error: call to undeclared library function 'ccoshl' with type '_Complex long double (_Complex long double)'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
2023-09-15T13:45:52,612       ret.c99_z = ccoshl(z1.c99_z);
2023-09-15T13:45:52,614                   ^
2023-09-15T13:45:52,616   numpy/core/src/npymath/npy_math_complex.c.src:1779:17: note: include the header <complex.h> or explicitly provide a declaration for 'ccoshl'
2023-09-15T13:45:52,618   numpy/core/src/npymath/npy_math_complex.c.src:1779:17: error: call to undeclared library function 'csinhl' with type '_Complex long double (_Complex long double)'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
2023-09-15T13:45:52,621       ret.c99_z = csinhl(z1.c99_z);
2023-09-15T13:45:52,623                   ^
2023-09-15T13:45:52,626   numpy/core/src/npymath/npy_math_complex.c.src:1779:17: note: include the header <complex.h> or explicitly provide a declaration for 'csinhl'
2023-09-15T13:45:52,628   numpy/core/src/npymath/npy_math_complex.c.src:1779:17: error: call to undeclared library function 'ctanhl' with type '_Complex long double (_Complex long double)'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
2023-09-15T13:45:52,630       ret.c99_z = ctanhl(z1.c99_z);
2023-09-15T13:45:52,632                   ^
2023-09-15T13:45:52,634   numpy/core/src/npymath/npy_math_complex.c.src:1779:17: note: include the header <complex.h> or explicitly provide a declaration for 'ctanhl'
2023-09-15T13:45:52,636   numpy/core/src/npymath/npy_math_complex.c.src:1779:17: error: call to undeclared library function 'cacosl' with type '_Complex long double (_Complex long double)'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
2023-09-15T13:45:52,639       ret.c99_z = cacosl(z1.c99_z);
2023-09-15T13:45:52,641                   ^
2023-09-15T13:45:52,643   numpy/core/src/npymath/npy_math_complex.c.src:1779:17: note: include the header <complex.h> or explicitly provide a declaration for 'cacosl'
2023-09-15T13:45:52,645   numpy/core/src/npymath/npy_math_complex.c.src:1779:17: error: call to undeclared library function 'casinl' with type '_Complex long double (_Complex long double)'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
2023-09-15T13:45:52,648       ret.c99_z = casinl(z1.c99_z);
2023-09-15T13:45:52,650                   ^
2023-09-15T13:45:52,652   numpy/core/src/npymath/npy_math_complex.c.src:1779:17: note: include the header <complex.h> or explicitly provide a declaration for 'casinl'
2023-09-15T13:45:52,654   numpy/core/src/npymath/npy_math_complex.c.src:1779:17: error: call to undeclared library function 'catanl' with type '_Complex long double (_Complex long double)'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
2023-09-15T13:45:52,657       ret.c99_z = catanl(z1.c99_z);
2023-09-15T13:45:52,659                   ^
2023-09-15T13:45:52,661   numpy/core/src/npymath/npy_math_complex.c.src:1779:17: note: include the header <complex.h> or explicitly provide a declaration for 'catanl'
2023-09-15T13:45:52,663   numpy/core/src/npymath/npy_math_complex.c.src:1779:17: error: call to undeclared library function 'cacoshl' with type '_Complex long double (_Complex long double)'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
2023-09-15T13:45:52,665       ret.c99_z = cacoshl(z1.c99_z);
2023-09-15T13:45:52,668                   ^
2023-09-15T13:45:52,670   numpy/core/src/npymath/npy_math_complex.c.src:1779:17: note: include the header <complex.h> or explicitly provide a declaration for 'cacoshl'
2023-09-15T13:45:52,672   numpy/core/src/npymath/npy_math_complex.c.src:1779:17: error: call to undeclared library function 'casinhl' with type '_Complex long double (_Complex long double)'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
2023-09-15T13:45:52,675       ret.c99_z = casinhl(z1.c99_z);
2023-09-15T13:45:52,677                   ^
2023-09-15T13:45:52,679   numpy/core/src/npymath/npy_math_complex.c.src:1779:17: note: include the header <complex.h> or explicitly provide a declaration for 'casinhl'
2023-09-15T13:45:52,681   numpy/core/src/npymath/npy_math_complex.c.src:1779:17: error: call to undeclared library function 'catanhl' with type '_Complex long double (_Complex long double)'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
2023-09-15T13:45:52,684       ret.c99_z = catanhl(z1.c99_z);
2023-09-15T13:45:52,686                   ^
2023-09-15T13:45:52,688   numpy/core/src/npymath/npy_math_complex.c.src:1779:17: note: include the header <complex.h> or explicitly provide a declaration for 'catanhl'
2023-09-15T13:45:52,690   19 errors generated.
2023-09-15T13:45:53,806   error: Command "aarch64-linux-android-clang -DNDEBUG -g -fwrapv -O3 -Wall -fstack-protector-strong -O3 -fstack-protector-strong -O3 -fPIC -ftrapping-math -Ibuild/src.linux-aarch64-3.11/numpy/core/src/npymath -Inumpy/core/include -Ibuild/src.linux-aarch64-3.11/numpy/core/include/numpy -Ibuild/src.linux-aarch64-3.11/numpy/distutils/include -Inumpy/core/src/common -Inumpy/core/src -Inumpy/core -Inumpy/core/src/npymath -Inumpy/core/src/multiarray -Inumpy/core/src/umath -Inumpy/core/src/npysort -Inumpy/core/src/_simd -I/data/data/com.termux/files/usr/include/python3.11 -Ibuild/src.linux-aarch64-3.11/numpy/core/src/common -Ibuild/src.linux-aarch64-3.11/numpy/core/src/npymath -c build/src.linux-aarch64-3.11/numpy/core/src/npymath/npy_math_complex.c -o build/temp.linux-aarch64-3.11/build/src.linux-aarch64-3.11/numpy/core/src/npymath/npy_math_complex.o -MMD -MF build/temp.linux-aarch64-3.11/build/src.linux-aarch64-3.11/numpy/core/src/npymath/npy_math_complex.o.d" failed with exit status 1
2023-09-15T13:45:53,808   INFO:
2023-09-15T13:45:53,809   ########### CLIB COMPILER OPTIMIZATION ###########
2023-09-15T13:45:53,811   INFO: Platform      :
2023-09-15T13:45:53,812     Architecture: aarch64
2023-09-15T13:45:53,814     Compiler    : clang

2023-09-15T13:45:53,816   CPU baseline  :
2023-09-15T13:45:53,818     Requested   : 'min'
2023-09-15T13:45:53,819     Enabled     : NEON NEON_FP16 NEON_VFPV4 ASIMD
2023-09-15T13:45:53,821     Flags       : none
2023-09-15T13:45:53,822     Extra checks: none

2023-09-15T13:45:53,825   CPU dispatch  :
2023-09-15T13:45:53,826     Requested   : 'max -xop -fma4'
2023-09-15T13:45:53,828     Enabled     : ASIMDHP ASIMDDP ASIMDFHM
2023-09-15T13:45:53,829     Generated   : none
2023-09-15T13:45:53,831   INFO: CCompilerOpt.cache_flush[863] : write cache to path -> /data/data/com.termux/files/usr/tmp/pip-install-wfs77jt0/numpy_df17f1b34c5848e8916ba7fcda95f047/build/temp.linux-aarch64-3.11/ccompiler_opt_cache_clib.py
2023-09-15T13:45:54,254   ERROR: [present-rich] Building wheel for numpy (pyproject.toml) exited with 1
2023-09-15T13:45:54,302   [bold magenta]full command[/]: [blue]/data/data/com.termux/files/usr/bin/python3.11 /data/data/com.termux/files/usr/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py build_wheel /data/data/com.termux/files/usr/tmp/tmpn1pdpd1p[/]
2023-09-15T13:45:54,305   [bold magenta]cwd[/]: /data/data/com.termux/files/usr/tmp/pip-install-wfs77jt0/numpy_df17f1b34c5848e8916ba7fcda95f047
2023-09-15T13:45:54,310   ERROR: Failed building wheel for numpy
2023-09-15T13:45:54,315 Failed to build numpy
2023-09-15T13:45:54,318 ERROR: Could not build wheels for numpy, which is required to install pyproject.toml-based projects
2023-09-15T13:45:54,320 Exception information:
2023-09-15T13:45:54,320 Traceback (most recent call last):
2023-09-15T13:45:54,320   File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/pip/_internal/cli/base_command.py", line 180, in exc_logging_wrapper
2023-09-15T13:45:54,320     status = run_func(*args)
2023-09-15T13:45:54,320              ^^^^^^^^^^^^^^^
2023-09-15T13:45:54,320   File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/pip/_internal/cli/req_command.py", line 248, in wrapper
2023-09-15T13:45:54,320     return func(self, options, args)
2023-09-15T13:45:54,320            ^^^^^^^^^^^^^^^^^^^^^^^^^
2023-09-15T13:45:54,320   File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/pip/_internal/commands/install.py", line 443, in run
2023-09-15T13:45:54,320     raise InstallationError(
2023-09-15T13:45:54,320 pip._internal.exceptions.InstallationError: Could not build wheels for numpy, which is required to install pyproject.toml-based projects
2023-09-15T13:45:54,340 Removed build tracker: '/data/data/com.termux/files/usr/tmp/pip-build-tracker-cotxvn0a'
</p>
</details> 
I also tried to install it using the deprecated method:

```
python setup.py install

```

and it created .egg format in the site-package of python which I don't know how to handle.
I have installed build-essential, binutils, and also python-numpy with:
```
pkg install python-numpy
```

### What steps will reproduce the bug?

trying to install scikit-learn with termux using:
```
MATHLIB='m' pip install scikit-learn
```
in Android 8 and 10 devices.

### What is the expected behavior?

I hope that the scikit-learn installs successfully.

### System information

termux-info:

```
Termux Variables:
TERMUX_APK_RELEASE=F_DROID
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=7966
TERMUX_IS_DEBUGGABLE_BUILD=0
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://packages-cf.termux.org/apt/termux-main/ stable main
# sources.list.d/pointless.list
deb https://its-pointless.github.io/files/24 termux extras
# tur-repo (sources.list.d/tur.list)
deb https://tur.kcubeterm.com tur-packages tur tur-on-device tur-continuous
Updatable packages:
All packages up to date
termux-tools version:
1.39.0
Android version:8.0.0

Kernel build information:
Linux localhost 3.18.14-13670986-QB35745423 #1 SMP PREEMPT Sat Nov 7 19:58:20 KST 2020 aarch64 Android
Device manufacturer:Samsung

Device model:SM-A520F

LD Variables:
LD_LIBRARY_PATH=
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so

```

**Comment by licy183** [comment]
[romanovj](https://github.com/romanovj) provides a solution for this issue, see https://github.com/termux/termux-packages/issues/17552#issuecomment-1673158595.

**Comment by beheshtiBlockchain** [comment]
Yes, Thank you. the previous comment(unedited version) has a complex library instead of the one in the binutils which helped with the process of making the scikit learn.

**Comment by zamirszn** [comment]
> [romanovj](https://github.com/romanovj) provides a solution for this issue, see https://github.com/termux/termux-packages/issues/17552#issuecomment-1673158595.

hello I have this issue and the link you provided doesn't seem to work anymore
