### ISSUE TITLE
[Bug]:  Python3 when invoked by sshuttle

### ISSUE THREAD

**Issue by Cicorione** [termux/termux-packages#17875]
### Problem description

When I try to connect to Termux through both Dropbear and Openssh with sshuttle from Armbian I get this error:

```
sudo sshuttle -vNr u0_a281@192.168.71.234:8022 0/0 -x 192.168.71.234
[...]
c : Connected to server.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "assembler.py", line 47, in <module>
  File "sshuttle.server", line 289, in main
  File "sshuttle.server", line 104, in list_routes
  File "sshuttle.server", line 83, in _list_routes
  File "/data/data/com.termux/files/usr/lib/python3.11/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/data/data/com.termux/files/usr/lib/python3.11/subprocess.py", line 1948, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'ip'
```

And the connection drops.
Regular ssh session and ssh tunnel work fine.

### What steps will reproduce the bug?

On Termux side:

Installing `python` & `dropbear` (or `openssh`)

On the Armbian side install `sshuttle`.

Run this command from the `guest`:

```
sudo sshuttle -vNr user@host:8022 0/0 -x host
```

### What is the expected behavior?

To establish the connection over Termux and get the connection alive.

### System information

termux-info:

```
Version from F-Droid: 0.118.0
Android 12
```

**Comment by romanovj** [comment]
no ip binary

`pkg install iproute2`

**Comment by Cicorione** [comment]
> no ip binary
> 
> `pkg install iproute2`

Thank you! It worked!
