### ISSUE TITLE
[Bug]: Numpy circular import in packge `python-numpy`

### ISSUE THREAD

**Issue by King-Oni** [termux/termux-packages#18202]
### Problem description

```
Traceback (most recent call last):
  File "/storage/emulated/0/my_scripts/engines/Github/Particle-Engine/types.py", line 4, in <module>
    import numpy as np
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/numpy/__init__.py", line 105, in <module>
    from ._globals import _NoValue, _CopyMode
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/numpy/_globals.py", line 18, in <module>
    import enum
  File "/data/data/com.termux/files/usr/lib/python3.11/enum.py", line 3, in <module>
    from types import MappingProxyType, DynamicClassAttribute
  File "/storage/emulated/0/my_scripts/engines/Github/Particle-Engine/types.py", line 5, in <module>
    import numpy.typing as npt
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/numpy/typing/__init__.py", line 158, in <module>
    from numpy._typing import (
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/numpy/_typing/__init__.py", line 5, in <module>
    from .. import ufunc
ImportError: cannot import name 'ufunc' from partially initialized module 'numpy' (most likely due to a circular import) (/data/data/com.termux/files/usr/lib/python3.11/site-packages/numpy/__init__.py)
```

### What steps will reproduce the bug?

1: make a file sending with `.py`
2: in the file write:
```py
import numpy as np
```
3: run: `python3 file.py`

### What is the expected behavior?

no import errors

### System information

termux-info:

```
Termux Variables:
TERMUX_API_VERSION=0.50.1
TERMUX_APK_RELEASE=GITHUB
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=22388
TERMUX_IS_DEBUGGABLE_BUILD=1
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
Packages CPU architecture:
arm
Subscribed repositories:
# sources.list
deb https://mirrors.hit.edu.cn/termux/apt/termux-main stable main
# root-repo (sources.list.d/root.list)
deb https://mirrors.hit.edu.cn/termux/apt/termux-root root stable
# x11-repo (sources.list.d/x11.list)
deb https://mirrors.hit.edu.cn/termux/apt/termux-x11 x11 main
Updatable packages:
command-not-found/stable 2.3.0-5 arm [upgradable from: 2.3.0-4]
libtirpc/stable 1.3.4 arm [upgradable from: 1.3.3]
procps/stable 3.3.17-5 arm [upgradable from: 3.3.17-3]
termux-tools version:
1.39.1
Android version:
8.1.0
Kernel build information:
Linux localhost 3.18.14-17282421 #1 SMP PREEMPT Thu Aug 19 16:42:49 KST 2021 armv8l Android
Device manufacturer:
samsung
Device model:
SM-T585
LD Variables:
LD_LIBRARY_PATH=
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so
Installed termux plugins:
com.termux.api versionCode:51
com.termux.styling versionCode:30
```

**Comment by romanovj** [comment]
```
~ $ cat file.py
import numpy as np
~ $ python file.py
no error
```

**Comment by landfillbaby** [comment]
can't reproduce on aarch64...
