### ISSUE TITLE
Exception in thread "main" java.lang.UnsupportedClassVersionError: com/android/sdklib/tool/SdkManagerCli : Unsupported major.minor version 52.0         

### ISSUE THREAD

**Issue by sdrausty** [termux/termux-packages#1838]
# Exception in thread "main" java.lang.UnsupportedClassVersionError: com/android/sdklib/tool/SdkManagerCli : Unsupported major.minor version 52.0
        

```
[09:36 scripts ]$ ./setup-android-sdk.sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  130M  100  130M    0     0   576k      0  0:03:52  0:03:52 --:--:--  784k
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  812M  100  812M    0     0  2150k      0  0:06:27  0:06:27 --:--:-- 2330k
Exception in thread "main" java.lang.UnsupportedClassVersionError: com/android/sdklib/tool/SdkManagerCli : Unsupported major.minor version 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:803)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:442)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:64)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:354)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:348)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:347)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:312)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
        at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:482)
```

To reproduce this error install https://sdrausty.github.io/TermuxArch/ and run ./setup-android-sdk.sh 

![screenshot_20171126-045953](https://user-images.githubusercontent.com/27742457/33238993-b351f0d8-d266-11e7-9fa3-6274377526e5.png)
![screenshot_20171126-053130](https://user-images.githubusercontent.com/27742457/33239223-278978fa-d26b-11e7-8871-b3f2bbdd39f8.png)

`setup-archlinux.sh` works well in Arch Linux Termux PRoot environment. Thank you for the awesome setup scripts.

**Comment by xeffyr** [comment]
Which jdk installed ?
Termux-builder docker container has jdk 1.8.0:
```
xeffyr@archlinux:~/DEV/termux-packages:$ scripts/run-docker.sh
Running container 'termux-package-builder' from image 'termux/package-builder'...
builder@bd11c4e8a813:~/termux-packages$ java -version
openjdk version "1.8.0_151"
OpenJDK Runtime Environment (build 1.8.0_151-8u151-b12-0ubuntu0.17.10.2-b12)
OpenJDK 64-Bit Server VM (build 25.151-b12, mixed mode)
builder@bd11c4e8a813:~/termux-packages$ 
```

**Comment by sdrausty** [comment]
Good question @xeffyr 
```
[11:43 home ]$ java -version
java version "1.7.0_151"
OpenJDK Runtime Environment (IcedTea 2.6.11) (Arch Linux ARM build 7.u151_2.6.11-1-aarch64)
OpenJDK 64-Bit Zero VM (build 24.151-b01, interpreted mode)
```

**Comment by sdrausty** [comment]
I will try this one. `extra/jre9-openjdk 9.u181-4
    OpenJDK Java 9 full runtime environment`

**Comment by sdrausty** [comment]
```
[12:13 scripts ]$ ./setup-android-sdk.sh
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlSchema
        at com.android.repository.api.SchemaModule$SchemaModuleVersion.<init>(SchemaModule.java:156)
        at com.android.repository.api.SchemaModule.<init>(SchemaModule.java:75)
        at com.android.sdklib.repository.AndroidSdkHandler.<clinit>(AndroidSdkHandler.java:81)
        at com.android.sdklib.tool.SdkManagerCli.main(SdkManagerCli.java:117)
        at com.android.sdklib.tool.SdkManagerCli.main(SdkManagerCli.java:93)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.annotation.XmlSchema
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:185)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:496)
        ... 5 more
```
```
[12:13 scripts ]$ java -version
openjdk version "9"
OpenJDK Runtime Environment (build 9+181)
OpenJDK 64-Bit Server VM (build 9+181, mixed mode)
```

**Comment by sdrausty** [comment]
The error is slightly different.

**Comment by sdrausty** [comment]
@xeffyr I get this for docker. 
```
[12:17 scripts ]$ ./run-docker.sh
Running container 'termux-package-builder' from image 'termux/package-builder'...
Creating new container...
docker: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?.
See 'docker run --help'.
```
Any suggestions?

**Comment by xeffyr** [comment]
@sdrausty, where you run docker ? On PC (with amd64 CPU) it works good.
Try to do as root:
```
systemctl enable docker
```
Then do ```systemctl start docker``` or reboot.

**Comment by xeffyr** [comment]
I never tried to use android sdk on Termux, but I think that it will require rebuild.

**Comment by xeffyr** [comment]
Which tools you need from android sdk ?

**Comment by sdrausty** [comment]
@xeffyr it looks like docker will not run in Termux Arch.  Is there a non-deamon or non bus mode?  
```
[12:26 scripts ]$ systemctl enable docker
Created symlink /etc/systemd/system/multi-user.target.wants/docker.service → /usr/lib/systemd/system/docker.service.
[12:57 scripts ]$ systemctl start docker
Failed to connect to bus: No such file or directory
```
Good news is that `setup-android-sdk.sh` deposited some goodies in ~/lib.
```
[12:59 ~ ]$ d lib/
3.9G    lib/
```
Java exception continues. To reproduce this error install https://sdrausty.github.io/TermuxArch/ and run ./setup-android-sdk.sh 5G of free space are recommended. Use `setupTermuxArch.sh uninstall` to free the space after reproducing this error if desired.

**Comment by xeffyr** [comment]
@sdrausty docker will not work on Android.

**Comment by sdrausty** [comment]
Docker isn't necessary to build packages, is it?

**Comment by xeffyr** [comment]
Yes, you can build programs manually without termux-builder

**Comment by sdrausty** [comment]
@xeffyr and `termux-builder` needs docker? That's great we can build programs manually. How? Can you provide an example, say with `tree`?  I am unintrested in cross-compiling.  I would like to compile for the device I am using, on the device I am using.

**Comment by xeffyr** [comment]
Termux-builder is a docker image

**Comment by xeffyr** [comment]
About compiling on device - it's easy. Some packages in my [termux-rootfs](https://github.com/xeffyr/termux-rootfs) are compiled on device.

**Comment by sdrausty** [comment]
Certainly. I agree we want a guide how to build on device in Termux. Wiki would be a good place for it.

**Comment by fornwall** [comment]
> Unsupported major.minor version 52.0

This was due to trying to run on java 7, which doesn not work since sdkmanager uses java 8.

> NoClassDefFoundError: javax/xml/bind/annotation/XmlSchema

And this due to running on java 9. So sdkmanager needs java 8, no earlier version and no later.

In the future sdkmanager will probably be fixed to work with java 9 out of the box. Meanwhile, you may try

    export JAVA_OPTS="--add-modules java.xml.bind"

before running to make sdkmanager work with java 9.

> I agree we want a guide how to build on device in Termux.

Would indeed be great!

**Comment by sdrausty** [comment]
@fornwall thank you for clarifying java 8 is required. 
```
[01:56 scripts ]$ archlinux-java status
Available Java environments:
  java-7-openjdk
  java-8-openjdk/jre
  java-9-openjdk (default)
[01:56 scripts ]$ archlinux-java set java-8-openjdk/jre
[01:57 scripts ]$ archlinux-java status
Available Java environments:
  java-7-openjdk
  java-8-openjdk/jre (default)
  java-9-openjdk
```

Works beautifully in Termux Arch now. See screenshot. 
![screenshot_20171126-211036](https://user-images.githubusercontent.com/27742457/33247858-260aa754-d2ef-11e7-8459-26f32d62940d.png)
Any idea what `Warning: File /root/.android/repositories.cfg could not be loaded.` is?  I checked with https://duckduckgo.com/?q=Warning%3A+File+.android%2Frepositories.cfg+could+not+be+loaded.&t=h_&ia=qa Result, "Installing Android Studio in Ubuntu 14.04 64-Bit .android/repositories.cfg could not be loaded".  I am using Arch Linux in Termux not Ubuntu in Termux.  And I am not using Android Studio. Does it run on Android btw?
