### ISSUE TITLE
Pymupdf

### ISSUE THREAD

**Issue by masteoo** [termux/termux-packages#18393]
### Why is it worth to add this package?

Pymupdf fails to install on my Termux. Thanks

### Home page URL

https://pymupdf.readthedocs.io/en/latest/

### Source code URL

https://pymupdf.io/

### Packaging policy acknowledgement

- [X] I certify that I have read [Termux Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy) and understand that my request will be denied in case of violation.

**Comment by twaik** [comment]
https://github.com/termux/termux-packages/issues/21399#issuecomment-2337443899

**Comment by licy183** [comment]
Since `pymupdf` 1.24.0, it should be able to be installed with `pip install pymupdf`. Please confirm whether it works. Thanks!

**Comment by robertkirkman** [comment]
When I use `pip install pymupdf`, I see this strange error

```
arch64-shared-tesseract-bsymbolic-Py_LIMITED_API_0x030c0000-release/libmupdf-threads.a  @build/aarch64-shared-tesseract-bsymbolic-Py_LIMITED_API_0x030c0000-release/libmupdf-threads.a.in
      (+10m36.2s): -b: m: __main__.py:1558:build: (+0.9s): -b: m: __main__.py:1558:build: mkdir -p build/aarch64-shared-tesseract-bsymbolic-Py_LIMITED_API_0x030c0000-release/ ; cc -shared -Wl,-soname,libmupdf.so.26.12 -Wl,-Bsymbolic -Wl,--gc-sections -Wl,-s  -o build/aarch64-shared-tesseract-bsymbolic-Py_LIMITED_API_0x030c0000-release/libmupdf.so.26.12  @build/aarch64-shared-tesseract-bsymbolic-Py_LIMITED_API_0x030c0000-release/libmupdf.so.26.12.in            -lpthread -lstdc++ -lstdc++  -L/data/data/com.termux/files/usr/lib -lcrypto  -lm
      (+10m38.0s): -b: m: __main__.py:1558:build: (+0.9s): -b: m: __main__.py:1558:build: mkdir -p build/aarch64-shared-tesseract-bsymbolic-Py_LIMITED_API_0x030c0000-release/ ; ln -sf libmupdf.so.26.12 build/aarch64-shared-tesseract-bsymbolic-Py_LIMITED_API_0x030c0000-release/libmupdf.so
      (+10m38.1s): -b: m: __main__.py:1558:build: (+0.9s): -b: m: __main__.py:1558:build:
      (+10m38.1s): -b: m: __main__.py:1558:build: [returned e=0]
      (+10m38.1s): -b: 0: __main__.py:1243:build_0: Generating C++ source code ...
      (+10m38.1s): -b: 0: cpp.py:5134:close: File updated: platform/c++/include/mupdf/extra.h
      (+10m38.1s): -b: 0: cpp.py:5134:close: File updated: platform/c++/implementation/extra.cpp
      (+10m39.1s): -b: 0: cpp.py:5527:cpp_source: Creating wrapper functions...
      (+11m01.7s): -b: 0: csharp.py:115:make_outparam_helper_csharp: Cannot generate C# out-param wrapper for pdf_repair_obj because would require > 7-tuple.
      (+11m04.1s): -b: 0: cpp.py:5608:cpp_source: Creating wrapper classes...
      Traceback (most recent call last):
          scripts/mupdfwrap.py:6:<module>(): wrap.__main__.main()
          scripts/wrap/__main__.py:3052:main(): jlib.exception_info()
          ^except raise:
          scripts/wrap/__main__.py:3050:main(): main2()
          scripts/wrap/__main__.py:2433:main2(): build( build_dirs, swig_command, args, vs_upgrade, make_command)
          scripts/wrap/__main__.py:1576:build(): build_0(
          scripts/wrap/__main__.py:1266:build_0(): cpp.cpp_source(
          scripts/wrap/cpp.py:5683:cpp_source(): is_container, has_to_string = class_wrapper(
          scripts/wrap/cpp.py:4373:class_wrapper(): class_add_iterator( tu, struct_cursor, struct_name, classname, extras, refcheck_if, trace_if)
          scripts/wrap/cpp.py:2285:class_add_iterator(): assert c.type.kind == state.clang.cindex.TypeKind.POINTER
      AttributeError: 'NoneType' object has no attribute 'type'
      Traceback (most recent call last):
        File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 389, in <module>
          main()
        File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 373, in main
          json_out["return_val"] = hook(**hook_input["kwargs"])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 178, in prepare_metadata_for_build_wheel
          whl_basename = backend.build_wheel(metadata_directory, config_settings)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/data/data/com.termux/files/usr/tmp/pip-install-l52_loyc/pymupdf_cb03506a0def4bb9b5497115d70de8d3/pipcl.py", line 722, in build_wheel
          items = self._call_fn_build(config_settings)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/data/data/com.termux/files/usr/tmp/pip-install-l52_loyc/pymupdf_cb03506a0def4bb9b5497115d70de8d3/pipcl.py", line 1008, in _call_fn_build
          ret = self.fn_build()
                ^^^^^^^^^^^^^^^
        File "/data/data/com.termux/files/usr/tmp/pip-install-l52_loyc/pymupdf_cb03506a0def4bb9b5497115d70de8d3/setup.py", line 623, in build
          mupdf_build_dir = build_mupdf_unix(
                            ^^^^^^^^^^^^^^^^^
        File "/data/data/com.termux/files/usr/tmp/pip-install-l52_loyc/pymupdf_cb03506a0def4bb9b5497115d70de8d3/setup.py", line 1050, in build_mupdf_unix
          subprocess.run( command, shell=True, check=True)
        File "/data/data/com.termux/files/usr/lib/python3.12/subprocess.py", line 571, in run
          raise CalledProcessError(retcode, process.args,
      subprocess.CalledProcessError: Command 'cd /data/data/com.termux/files/usr/tmp/pip-install-l52_loyc/pymupdf_cb03506a0def4bb9b5497115d70de8d3/mupdf-1.26.12-source && XCFLAGS=-DTOFU_CJK_EXT XCXXFLAGS=-DTOFU_CJK_EXT /data/data/com.termux/files/usr/bin/python3.12 ./scripts/mupdfwrap.py -d build/aarch64-shared-tesseract-bsymbolic-Py_LIMITED_API_0x030c0000-release -b all && echo /data/data/com.termux/files/usr/tmp/pip-install-l52_loyc/pymupdf_cb03506a0def4bb9b5497115d70de8d3/mupdf-1.26.12-source/build/aarch64-shared-tesseract-bsymbolic-Py_LIMITED_API_0x030c0000-release: && ls -l /data/data/com.termux/files/usr/tmp/pip-install-l52_loyc/pymupdf_cb03506a0def4bb9b5497115d70de8d3/mupdf-1.26.12-source/build/aarch64-shared-tesseract-bsymbolic-Py_LIMITED_API_0x030c0000-release' returned non-zero exit status 1.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> pymupdf

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
~ $ 
```

**Comment by ihfandica** [comment]
Hello @robertkirkman, did you succes install pymupdf?

**Comment by robertkirkman** [comment]
I did not succeed yet unfortunately, I got an error `AttributeError: 'NoneType' object has no attribute 'type'`

**Comment by maoist2009** [comment]
I have tried all ways. Including use mupdf from x11 repo. Seems like mupdf can be compiled and error occured in wrapping.

**Comment by maoist2009** [comment]
> ~Since `pymupdf` 1.24.0, it should be able to be installed with `pip install pymupdf`. Please confirm whether it works. Thanks!~
> 
> OK. It takes too much time to compile. Maybe it should be packaged...

Won't work with lastest version. I switched of the process killer and cancel the subprocess limitation. But get errors. Even 1.24.10 failed.

**Comment by maoist2009** [comment]
It seems like we must patch pymupdf to onstall successfully. (I viewed the web, using ndk to build failed. ) Maybe we should get an AI agent tp try until success.

**Comment by ihfandica** [comment]
> Hello [@robertkirkman](https://github.com/robertkirkman), did you succes install pymupdf?

Due to unresolved issues, I ended up migrating all my projects to proot-distro. It's much better than native Termux. Even though it has to be paid with some conditions faster on native Termux coz isnt virtual env.

**Comment by maoist2009** [comment]
> > Hello [@robertkirkman](https://github.com/robertkirkman), did you succes install pymupdf?你好[，@robertkirkman](https://github.com/robertkirkman)，你成功安装了pymupdf吗？
> 
> Due to unresolved issues, I ended up migrating all my projects to proot-distro. It's much better than native Termux. Even though it has to be paid with some conditions faster on native Termux coz isnt virtual env.由于未解决的问题，我最终将所有项目迁移到了 proot-distro。它比原生的Termux好多了。虽然在原生Termux上需要支付一些条件，但因为不是虚拟环境。

For pymupdf glibc run is enough.

**Comment by Spy-God** [comment]
Is it impossible to build PyMuPDF v 1.27.2.3 in bionic libc?

@robertkirkman

**Comment by maoist2009** [comment]
> Is it impossible to build PyMuPDF v 1.27.2.3 in bionic libc?
> 
> [@robertkirkman](https://github.com/robertkirkman)

try my build script. 

<details>
#!/bin/bash
# ===========================================================================
# build_pymupdf.sh — PyMuPDF 1.28.0 在 Termux (aarch64 / Android / Python 3.14)
# 一条龙从源码编译脚本 (clang 21 / libclang 21)
#
# 背景:
#   * 本机 mupdf.com 不可达, 仅 PyPI + GitHub 可达; 系统 mupdf(1.24) 与 PyMuPDF
#     1.28 不匹配, 故从 GitHub 拉 mupdf 1.28.0 源码(含 thirdparty 子模块)自编译.
#   * 关键约束: 临时文件一律放 $HOME/tmp; LD_PRELOAD 绝不 export; 不用 sudo 改系统.
#
# 用法:  bash build_pymupdf.sh            # 全流程 (克隆/补丁/编译/wheel/安装/验证)
# 依赖:  termux pkg: git, make, clang, llvm, swig (4.4.1), m4 bison flex, patchelf(可选)
#
# 产出:  pip install 后的 fitz 模块 + wheel 在 $WORK/wheelout/
# ===========================================================================
set -euo pipefail

export CC=clang CXX=clang++ LD=clang AR=llvm-ar NM=llvm-nm RANLIB=llvm-ranlib STRIP=llvm-strip

WORK=$HOME/tmp/pmtestsrc
MU_VER=1.28.0
PYMUPDF_VER=1.28.0
MU_DIR=$WORK/mupdf
PY_DIR=$WORK/pymupdf-$PYMUPDF_VER
WHEEL_OUT=$HOME/tmp/wheelout
mkdir -p "$WORK" "$WHEEL_OUT"

# ---------------------------------------------------------------------------
# 工具函数: 幂等地把文件中的 old 替换为 new (仅当 old 存在且 new 未应用时)
# 用法: patch_file <file> <old> <new>
# ---------------------------------------------------------------------------
patch_file() {
    local f="$1" old="$2" new="$3"
    # skip fingerprint = first line of <new> (single, distinctive line).
    local fp; fp="$(printf '%s' "$new" | head -1)"
    if grep -qF "$fp" "$f"; then
        echo "  already patched (skip): $f"
    elif grep -qF "$old" "$f"; then
        python3 - "$f" "$old" "$new" <<'PYEOF'
import sys
f, old, new = sys.argv[1], sys.argv[2], sys.argv[3]
s = open(f, encoding='utf-8').read()
assert old in s, f"marker not found in {f}"
s = s.replace(old, new, 1)
open(f, 'w', encoding='utf-8').write(s)
print(f"  patched: {f}")
PYEOF
    else
        # new 不在且 old 多行不匹配 (可能源码已被手动编辑、格式略异):
        # 视为已应用, 跳过以免重复插入。
        echo "  already patched (assumed, skip): $f"
    fi
}

# ===========================================================================
# 0. 环境检查
# ===========================================================================
echo "[0] 环境检查"
command -v swig >/dev/null || { echo "  需先安装 swig (apt install swig 或自编译 4.4.1)"; exit 1; }
swig -version | head -1
command -v clang >/dev/null && clang --version | head -1
python3 --version

# ===========================================================================
# 1. 克隆 mupdf 1.28.0 + thirdparty 子模块 (full clone, 不能 --depth)
# ===========================================================================
if [ ! -d "$MU_DIR/.git" ]; then
    echo "[1] 克隆 mupdf $MU_VER (含子模块, full clone)"
    rm -rf "$MU_DIR"
    # 配置 git 以应对不稳定网络
    git config --global http.postBuffer 524288000
    git config --global http.lowSpeedLimit 0
    git config --global http.lowSpeedTime 999999
    # 先克隆主仓库
    git clone "https://github.com/ArtifexSoftware/mupdf.git" "$MU_DIR"
    ( cd "$MU_DIR" && git checkout "$MU_VER" )
    
    # 获取子模块列表并逐个初始化 (带重试), 避免单个失败导致全盘失败
    echo "  初始化子模块 (逐个重试)..."
    cd "$MU_DIR"
    git submodule init
    # 列出所有子模块路径
    mapfile -t submodules < <(git config --file .gitmodules --get-regexp '^submodule\..+\.path$' | awk '{print $2}')
    for sm_path in "${submodules[@]}"; do
        sm_name=$(basename "$sm_path")
        for attempt in 1 2 3 4 5; do
            echo "  子模块 [$sm_name] 尝试 $attempt/5..."
            if git submodule update --init --recursive -- "$sm_path" 2>/dev/null; then
                echo "  子模块 [$sm_name] 成功"
                break
            fi
            if [ $attempt -eq 5 ]; then
                echo "  警告: 子模块 [$sm_name] 多次失败, 继续尝试其他模块"
            else
                echo "  子模块 [$sm_name] 失败, 等待 15s 后重试..."
                sleep 15
            fi
        done
    done
else
    echo "[1] mupdf 已存在, 跳过克隆"
fi

# ===========================================================================
# 2. 下载 PyMuPDF sdist 并解包
# ===========================================================================
if [ ! -d "$PY_DIR" ]; then
    echo "[2] 下载并解包 PyMuPDF $PYMUPDF_VER sdist"
    rm -rf "$WORK/pymupdf_dl"
    pip download --no-deps --no-build-isolation "pymupdf==$PYMUPDF_VER" -d "$WORK/pymupdf_dl"
    tar xf "$WORK/pymupdf_dl"/*.tar.gz -C "$WORK"
else
    echo "[2] PyMuPDF 源码已存在, 跳过"
fi

# ===========================================================================
# 3. 应用兼容性补丁 (clang 21 / Android / Python 3.14)
#    根因: mupdf 包装生成器把 Linux-only 逻辑门在 state.linux 后, 而 Termux 下
#          platform.system()=='Android' 导致 linux==False.
# ===========================================================================
echo "[3] 应用 clang21/Android 兼容补丁"

# --- 补丁 A: state.py 增加 self.android ---
patch_file "$MU_DIR/scripts/wrap/state.py" \
'        self.linux = self.os_name == '"'"'Linux'"'"'
        self.macos = self.os_name == '"'"'Darwin'"'"'' \
'        self.linux = self.os_name == '"'"'Linux'"'"'
        self.android = self.os_name == '"'"'Android'"'"'
        self.macos = self.os_name == '"'"'Darwin'"'"''

# --- 补丁 B: parse.py get_members() 对 FIELD_DECL(匿名 union 成员)下钻 ---
patch_file "$MU_DIR/scripts/wrap/parse.py" \
'    if cursor.type.kind in (state.clang.cindex.TypeKind.TYPEDEF, state.clang.cindex.TypeKind.ELABORATED):
        cursor2 = cursor.underlying_typedef_type.get_declaration()
    else:
        cursor2 = cursor' \
'    if cursor.kind == state.clang.cindex.CursorKind.FIELD_DECL:
        # clang 21: a FIELD_DECL whose type is an anonymous union/struct
        # (ELABORATED) must be descended via .type.get_declaration(), not
        # .underlying_typedef_type (which is meaningless on a field cursor).
        cursor2 = cursor.type.get_declaration()
    elif cursor.type.kind in (state.clang.cindex.TypeKind.TYPEDEF, state.clang.cindex.TypeKind.ELABORATED):
        cursor2 = cursor.underlying_typedef_type.get_declaration()
    else:
        cursor2 = cursor'

# --- 补丁 C: cpp.py 前缀 size_t / intN_t (linux||macos -> +android) ---
patch_file "$MU_DIR/scripts/wrap/cpp.py" \
'            if state.state_.linux or state.state_.macos:' \
'            if state.state_.linux or state.state_.macos or state.state_.android:'
patch_file "$MU_DIR/scripts/wrap/cpp.py" \
'            if state.state_.macos:' \
'            if state.state_.macos or state.state_.android:'

# --- 补丁 D: __main__.py shared 分支的 soname 链接 (linux -> +android) ---
patch_file "$MU_DIR/scripts/wrap/__main__.py" \
'                        if state.state_.linux and so_version:' \
'                        if (state.state_.linux or state.state_.android) and so_version:'
patch_file "$MU_DIR/scripts/wrap/__main__.py" \
'                        if so_version and state.state_.linux:' \
'                        if so_version and (state.state_.linux or state.state_.android):'

# --- 补丁 E: pymupdf setup.py 打包时解析 SONAME (android 下 pipcl.get_soname 失效) ---
patch_file "$PY_DIR/setup.py" \
'linux = sys.platform.startswith( '"'"'linux'"'"') or '"'"'gnu'"'"' in sys.platform
openbsd = sys.platform.startswith( '"'"'openbsd'"'"')' \
'linux = sys.platform.startswith( '"'"'linux'"'"') or '"'"'gnu'"'"' in sys.platform
android = sys.platform == '"'"'android'"'"'
openbsd = sys.platform.startswith( '"'"'openbsd'"'"')

def _get_soname(path):
    """
    Like pipcl.get_soname(), but also resolves the SONAME on Android where
    pipcl'"'"'s linux-only check fails. Returns the versioned .so.<ver> real file
    if the library has a SONAME and that file exists, otherwise <path>.
    """
    if (linux or android or openbsd) and os.path.isfile(path):
        try:
            cp = subprocess.run(
                    f'"'"'objdump -p {path} | grep SONAME'"'"',
                    shell=1, capture_output=1, text=1, check=0)
            if cp.returncode == 0:
                m = re.search(r'"'"'SONAME\s+(\S+)'"'"', cp.stdout)
                if m:
                    soname = m.group(1)
                    candidate = os.path.join(os.path.dirname(path), soname)
                    if os.path.exists(candidate):
                        return candidate
        except Exception:
            pass
    return path'
patch_file "$PY_DIR/setup.py" \
'            add('"'"'b'"'"', pipcl.get_soname(f'"'"'{mupdf_build_dir}/libmupdfcpp.so'"'"'), to_dir)
            add('"'"'b'"'"', pipcl.get_soname(f'"'"'{mupdf_build_dir}/libmupdf.so'"'"'), to_dir)' \
'            add('"'"'b'"'"', _get_soname(f'"'"'{mupdf_build_dir}/libmupdfcpp.so'"'"'), to_dir)
            add('"'"'b'"'"', _get_soname(f'"'"'{mupdf_build_dir}/libmupdf.so'"'"'), to_dir)'

# ===========================================================================
# 4. 构建环境 (LD=clang 已在顶部 export; 这里补 mupdf 路径/编译 flags)
# ===========================================================================
echo "[4] 导出构建环境变量"
export PYMUPDF_SETUP_MUPDF_BUILD="$MU_DIR"
export PYMUPDF_SETUP_SWIG="$(command -v swig)"
export PYMUPDF_SETUP_MUPDF_BUILD_TYPE=release
export CFLAGS="-O2"
export CXXFLAGS="-O2"
export XCFLAGS="-DTOFU_CJK_EXT"
export XCXXFLAGS="-DTOFU_CJK_EXT"

# ===========================================================================
# 5. 构建 wheel (pip 会自动安装 build 依赖 pipcl, 然后调 setup 后端)
# ===========================================================================
echo "[5] 构建 wheel (mupdfwrap 生成绑定 + 编译 libmupdfcpp + swig _mupdf + _extra)"
rm -rf "$MU_DIR/build/aarch64-shared-tesseract-Py_LIMITED_API_0x030e0000-release"
cd "$PY_DIR"
pip wheel . --no-deps -w "$WHEEL_OUT"

# ===========================================================================
# 6. 安装并验证
# ===========================================================================
echo "[6] 安装 wheel"
WHEEL=$(ls -t "$WHEEL_OUT"/pymupdf-*.whl | head -1)
pip install --force-reinstall --no-deps "$WHEEL"

echo "[7] 验证 import fitz"
python3 - <<'PY'
import fitz
print("fitz imported OK:", fitz.__version__ if hasattr(fitz,'__version__') else 'n/a')
doc = fitz.open()
page = doc.new_page()
page.insert_text((72,72), "Hello PyMuPDF on Termux aarch64!")
assert "Hello PyMuPDF" in page.get_text()
pix = page.get_pixmap(dpi=72)
assert pix.width > 0
print("text extraction + pixmap render OK")
print("ALL CHECKS PASSED")
PY

echo "[*] 完成. wheel 位于: $WHEEL"

</details>

**Comment by Spy-God** [comment]
How do I even use your build script?

I haven't tried to use build script untill now.

I can't even seem to simply copy it and run it in termux which I doubt will actually work.

And why are chinese characters mixed in ? Is it a python based script or something else?

**Comment by robertkirkman** [comment]
> Is it impossible to build PyMuPDF v 1.27.2.3 in bionic libc?
> 
> [@robertkirkman](https://github.com/robertkirkman)

did you see my other message here?

- https://github.com/termux-user-repository/tur/issues/2603#issuecomment-5211928918

**Comment by Spy-God** [comment]
Yeah I replied. 

I am trying to set it up for few hours by now but can't say I have tested it yet. 

I only have one thing where I need it and its being a pain in the ass to set up.
