### ISSUE TITLE
[Package]: `pip install grpcio` failed. Require a `grpcio` package.

### ISSUE THREAD

**Issue by noobyzy** [termux/termux-packages#18444]
### Why is it worth to add this package?

`grpcio` is a remote communication framework that is built for everywhere.

For me, it's an important package (in python 'grpcio') that is key to many other packages.

### Source code URL

https://github.com/grpc/grpc

### Packaging policy acknowledgement

- [X] I certify that I have read [Termux Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy) and understand that my request will be denied in case of violation.

### Additional information

`grpcio` is unable to be installed via
```sh
pip install grpcio
```
even with the flags reported in #17583  
```sh
GRPC_PYTHON_DISABLE_LIBC_COMPATIBILITY=1 GRPC_PYTHON_BUILD_SYSTEM_OPENSSL=1 GRPC_PYTHON_BUILD_SYSTEM_ZLIB=1 GRPC_PYTHON_BUILD_SYSTEM_CARES=1 CFLAGS+=" -U__ANDROID_API__ -D__ANDROID_API__=26 -include unistd.h" LDFLAGS+=" -llog" pip install grpcio

###

CFLAGS+=" -U__ANDROID_API__ -D__ANDROID_API__=28"  pip install grpcio
```
still not working.

Part of the error message is attached as following:
```sh
× python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [2597 lines of output]
      /data/data/com.termux/files/usr/tmp/pip-install-t_dlesqn/grpcio_23481140d6e54aad8a262db7e50486d6/setup.py:40: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html

################################

  src/python/grpcio/grpc/_cython/cygrpc.cpp:100923:10: warning: 'PyEval_InitThreads' is deprecated [-Wdeprecated-declarations]
       100923 |   (void)(PyEval_InitThreads());
              |          ^
      /data/data/com.termux/files/usr/include/python3.11/ceval.h:132:1: note: 'PyEval_InitThreads' has been explicitly marked deprecated here
        132 | Py_DEPRECATED(3.9) PyAPI_FUNC(void) PyEval_InitThreads(void);
            | ^
      /data/data/com.termux/files/usr/include/python3.11/pyport.h:336:54: note: expanded from macro 'Py_DEPRECATED'
        336 | #define Py_DEPRECATED(VERSION_UNUSED) __attribute__((__deprecated__))

################################

    third_party/cares/cares/src/lib/ares_fds.c:41:11: error: too few arguments provided to function-like macro invocation
         41 |           FD_SET(server->udp_socket, read_fds);
            |           ^
      third_party/cares/config_linux/ares_config.h:456:16: note: expanded from macro 'FD_SET'
        456 |       ((void) (GRPC_CARES_FDS_BITS (set)[ (d) / NFDBITS ] |= GRPC_CARES_FD_MASK(d)))
            |                ^
      third_party/cares/config_linux/ares_config.h:448:52: note: expanded from macro 'GRPC_CARES_FDS_BITS'
        448 |     #define GRPC_CARES_FDS_BITS(set) __FDS_BITS(set)
            |                                                    ^
      /data/data/com.termux/files/usr/include/sys/select.h:63:9: note: macro '__FDS_BITS' defined here
         63 | #define __FDS_BITS(type,set) (__BIONIC_CAST(static_cast, type, set)->fds_bits)
            |         ^
      third_party/cares/cares/src/lib/ares_fds.c:41:11: error: use of undeclared identifier '__FDS_BITS'
         41 |           FD_SET(server->udp_socket, read_fds);
            |           ^
      third_party/cares/config_linux/ares_config.h:456:16: note: expanded from macro 'FD_SET'
        456 |       ((void) (GRPC_CARES_FDS_BITS (set)[ (d) / NFDBITS ] |= GRPC_CARES_FD_MASK(d)))
            |                ^
      third_party/cares/config_linux/ares_config.h:448:38: note: expanded from macro 'GRPC_CARES_FDS_BITS'
        448 |     #define GRPC_CARES_FDS_BITS(set) __FDS_BITS(set)
            |                                      ^
      third_party/cares/cares/src/lib/ares_fds.c:51:10: error: too few arguments provided to function-like macro invocation
         51 |          FD_SET(server->tcp_socket, read_fds);
            |          ^
      third_party/cares/config_linux/ares_config.h:456:16: note: expanded from macro 'FD_SET'
        456 |       ((void) (GRPC_CARES_FDS_BITS (set)[ (d) / NFDBITS ] |= GRPC_CARES_FD_MASK(d)))
            |                ^
      third_party/cares/config_linux/ares_config.h:448:52: note: expanded from macro 'GRPC_CARES_FDS_BITS'
        448 |     #define GRPC_CARES_FDS_BITS(set) __FDS_BITS(set)
            |                                                    ^
      /data/data/com.termux/files/usr/include/sys/select.h:63:9: note: macro '__FDS_BITS' defined here
         63 | #define __FDS_BITS(type,set) (__BIONIC_CAST(static_cast, type, set)->fds_bits)
            |         ^
      third_party/cares/cares/src/lib/ares_fds.c:51:10: error: use of undeclared identifier '__FDS_BITS'
         51 |          FD_SET(server->tcp_socket, read_fds);
            |          ^
      third_party/cares/config_linux/ares_config.h:456:16: note: expanded from macro 'FD_SET'
        456 |       ((void) (GRPC_CARES_FDS_BITS (set)[ (d) / NFDBITS ] |= GRPC_CARES_FD_MASK(d)))
            |                ^
      third_party/cares/config_linux/ares_config.h:448:38: note: expanded from macro 'GRPC_CARES_FDS_BITS'
        448 |     #define GRPC_CARES_FDS_BITS(set) __FDS_BITS(set)
            |                                      ^
      third_party/cares/cares/src/lib/ares_fds.c:53:12: error: too few arguments provided to function-like macro invocation
         53 |            FD_SET(server->tcp_socket, write_fds);
            |            ^
      third_party/cares/config_linux/ares_config.h:456:16: note: expanded from macro 'FD_SET'
        456 |       ((void) (GRPC_CARES_FDS_BITS (set)[ (d) / NFDBITS ] |= GRPC_CARES_FD_MASK(d)))
            |                ^
      third_party/cares/config_linux/ares_config.h:448:52: note: expanded from macro 'GRPC_CARES_FDS_BITS'
        448 |     #define GRPC_CARES_FDS_BITS(set) __FDS_BITS(set)
            |                                                    ^
      /data/data/com.termux/files/usr/include/sys/select.h:63:9: note: macro '__FDS_BITS' defined here
         63 | #define __FDS_BITS(type,set) (__BIONIC_CAST(static_cast, type, set)->fds_bits)
            |         ^
      third_party/cares/cares/src/lib/ares_fds.c:53:12: error: use of undeclared identifier '__FDS_BITS'
         53 |            FD_SET(server->tcp_socket, write_fds);
            |            ^
      third_party/cares/config_linux/ares_config.h:456:16: note: expanded from macro 'FD_SET'
        456 |       ((void) (GRPC_CARES_FDS_BITS (set)[ (d) / NFDBITS ] |= GRPC_CARES_FD_MASK(d)))
            |                ^
      third_party/cares/config_linux/ares_config.h:448:38: note: expanded from macro 'GRPC_CARES_FDS_BITS'
        448 |     #define GRPC_CARES_FDS_BITS(set) __FDS_BITS(set)
            |                                      ^
      6 errors generated.

################################

    aarch64-linux-android-clang -DNDEBUG -g -fwrapv -O3 -Wall -fstack-protector-strong -O3 -fstack-protector-strong -O3 -U__ANDROID_API__ -D__ANDROID_API__=28 -fPIC -I/data/data/com.termux/files/usr/include/python3.11 -c /data/data/com.termux/files/usr/tmp/tmplxfh016q/a.c -o None/data/data/com.termux/files/usr/tmp/tmplxfh016q/a.o
      Traceback (most recent call last):
        File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/setuptools/_distutils/unixccompiler.py", line 185, in _compile
          self.spawn(compiler_so + cc_args + [src, '-o', obj] + extra_postargs)
        File "/data/data/com.termux/files/usr/tmp/pip-install-t_dlesqn/grpcio_23481140d6e54aad8a262db7e50486d6/src/python/grpcio/_spawn_patch.py", line 58, in _commandfile_spawn
          _classic_spawn(self, command, **kwargs)
        File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/setuptools/_distutils/ccompiler.py", line 1041, in spawn
          spawn(cmd, dry_run=self.dry_run, **kwargs)
        File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/setuptools/_distutils/spawn.py", line 70, in spawn
          raise DistutilsExecError(
      distutils.errors.DistutilsExecError: command '/data/data/com.termux/files/usr/bin/aarch64-linux-android-clang' failed with exit code 1

```
and the error message is here
[output.txt](https://github.com/termux/termux-packages/files/13310407/output.txt)

**Comment by noobyzy** [comment]
System information via `termux-info`
```sh
Termux Variables:
TERMUX_APK_RELEASE=GITHUB
TERMUX_APP_AM_SOCKET_SERVER_ENABLED=true
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PACKAGE_VARIANT=apt-android-7
TERMUX_APP_PID=10543
TERMUX_IS_DEBUGGABLE_BUILD=1
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.119.1
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://mirrors.pku.edu.cn/termux/termux-main/ stable main
# root-repo (sources.list.d/root.list)
deb https://mirrors.pku.edu.cn/termux/termux-root/ root stable
Updatable packages:
All packages up to date
termux-tools version:
1.39.4
Android version:
11
Kernel build information:
Linux localhost 4.14.170-g501c771385ff-ab6716795 #1 SMP PREEMPT Tue Jul 28 22:05:21 UTC 2020 aarch64 Android
Device manufacturer:
Google
Device model:
Pixel 4a
LD Variables:
LD_LIBRARY_PATH=
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so
```

**Comment by jtplatt99** [comment]
Based on your logs it looks like the installer is still trying to build `c-ares` and failing. You mentioned that you tried several installation methods. What is the exact command you used that resulted in the log messages you posted here? Could you also post the result of running `ls /data/data/com.termux/files/usr/include`?

**Comment by noobyzy** [comment]
Thanks @jtplatt99 in #17583 , his solution worked for me to pip install grpcio.
```sh
pkg install c-ares
GRPC_PYTHON_DISABLE_LIBC_COMPATIBILITY=1 GRPC_PYTHON_BUILD_SYSTEM_OPENSSL=1 GRPC_PYTHON_BUILD_SYSTEM_ZLIB=1 GRPC_PYTHON_BUILD_SYSTEM_CARES=1 CFLAGS+=" -U__ANDROID_API__ -D__ANDROID_API__=30 -include unistd.h" LDFLAGS+=" -llog" pip install grpcio
```
However, this takes a very long time (~1h) for `pip` to build the wheel.
Hopefully termux can add this package, thanks
