### ISSUE TITLE
[Bug]: Nala Broken

### ISSUE THREAD

**Issue by GR3YH4TT3R93** [termux/termux-packages#18800]
### Problem description

When trying to run nala, I get this error:

Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/bin/nala", line 5, in <module>
    from nala.__main__ import main
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/nala/__main__.py", line 32, in <module>
    import nala.fetch as _fetch  # pylint: disable=unused-import
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/nala/fetch.py", line 60, in <module>
    from nala.downloader import print_error
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/nala/downloader.py", line 70, in <module>
    from nala.error import ExitCode, FileDownloadError
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/nala/error.py", line 38, in <module>
    from nala.debfile import NalaBaseDep, NalaDebPackage, NalaDep
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/nala/debfile.py", line 32, in <module>
    from apt.debfile import DebPackage
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/apt/debfile.py", line 28, in <module>
    import apt_inst
ImportError: dlopen failed: cannot locate symbol "PyAptWarning" referenced by "/data/data/com.termux/files/usr/lib/python3.11/site-packages/apt_inst.cpython-311.so"...

### What steps will reproduce the bug?

1) apt update && apt upgrade
2) apt install nala
2) nala

### What is the expected behavior?

The nala help menu should be printed out

### System information

termux-info:

```
Termux Variables:
TERMUX_API_VERSION=0.50.1
TERMUX_APK_RELEASE=F_DROID
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=32168
TERMUX_IS_DEBUGGABLE_BUILD=0
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://packages-cf.termux.dev/apt/termux-main stable main
# tur-repo (sources.list.d/tur.list)
deb https://tur.kcubeterm.com tur-packages tur tur-on-device tur-continuous
Updatable packages:
All packages up to date
termux-tools version:
1.39.6
Android version:
13
Kernel build information:
Linux localhost 5.10.168-android12-9-00003-gc873b6b86254-ab10823632 #1 SMP PREEMPT Mon Sep 18 13:31:53 UTC 2023 aarch64 Android
Device manufacturer:
OnePlus
Device model:
CPH2419
LD Variables:
LD_LIBRARY_PATH=
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so
Installed termux plugins:
com.termux.api versionCode:51
com.termux.tasker versionCode:6
com.termux.styling versionCode:31

```

**Comment by GR3YH4TT3R93** [comment]
Still not working.

new error:

Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/bin/nala", line 5, in <module>
    from nala.__main__ import main
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/nala/__main__.py", line 32, in <module>
    import nala.fetch as _fetch  # pylint: disable=unused-import
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/nala/fetch.py", line 60, in <module>
    from nala.downloader import print_error
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/nala/downloader.py", line 70, in <module>
    from nala.error import ExitCode, FileDownloadError
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/nala/error.py", line 38, in <module>
    from nala.debfile import NalaBaseDep, NalaDebPackage, NalaDep
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/nala/debfile.py", line 32, in <module>
    from apt.debfile import DebPackage
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/apt/debfile.py", line 28, in <module>
    import apt_inst
AttributeError: module 'apt_pkg' has no attribute 'Warning'

**Comment by licy183** [comment]
Should be fixed now.

**Comment by GR3YH4TT3R93** [comment]
Confirmed, working now. Ty!
