### ISSUE TITLE
[Bug]: am start and broadcast broken after apt upgrade of termux-am package from 0.6.0 to 0.7.1

### ISSUE THREAD

**Issue by sudomain** [termux/termux-packages#18831]
### Problem description

I upgraded termux-am from 0.6.0 to 0.7.1 and a few of my scripts that rely on am start and broadcast broke with this error:

```
Broadcasting: Intent { act=io.github.sds100.keymapper.ACTION_TRIGGER_KEYMAP_BY_UID (has extras) }
java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.termux.termuxam.CrossVersionReflectedMethod.invoke(CrossVersionReflectedMethod.java:175)
        at com.termux.termuxam.IActivityManager.broadcastIntent(IActivityManager.java:273)
        at com.termux.termuxam.Am.sendBroadcast(Am.java:867)
        at com.termux.termuxam.Am.onRun(Am.java:411)
        at com.termux.termuxam.BaseCommand.run(BaseCommand.java:46)
        at com.termux.termuxam.Am.main(Am.java:78)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:399)
Caused by: java.lang.SecurityException: Permission Denial: getIntentSender asks to run as user -2 but is calling from uid u0a35; this requires android.permission.INTERACT_ACROSS_USERS_FULL or android.permission.INTERACT_ACROSS_USERS
        at android.os.Parcel.createExceptionOrNull(Parcel.java:2373)
        at android.os.Parcel.createException(Parcel.java:2357)
        at android.os.Parcel.readException(Parcel.java:2340)
        at android.os.Parcel.readException(Parcel.java:2282)
        at android.app.IActivityManager$Stub$Proxy.getIntentSender(IActivityManager.java:6566)
        ... 9 more
Caused by: android.os.RemoteException: Remote stack trace:
        at com.android.server.am.UserController.handleIncomingUser(UserController.java:1937)
        at com.android.server.am.ActivityManagerService.getIntentSenderWithFeature(ActivityManagerService.java:5695)
        at com.android.server.am.ActivityManagerService.getIntentSender(ActivityManagerService.java:5651)
        at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:2947)
        at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2883)

Starting: Intent { cmp=android.jonas.fakestandby/.actions.StartOverlay }
java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.termux.termuxam.CrossVersionReflectedMethod.invoke(CrossVersionReflectedMethod.java:175)
        at com.termux.termuxam.IActivityManager.startActivityAsUser(IActivityManager.java:250)
        at com.termux.termuxam.Am.runStart(Am.java:706)
        at com.termux.termuxam.Am.onRun(Am.java:393)
        at com.termux.termuxam.BaseCommand.run(BaseCommand.java:46)
        at com.termux.termuxam.Am.main(Am.java:78)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:399)
Caused by: java.lang.SecurityException: Permission Denial: startActivityAsUser asks to run as user -2 but is calling from uid u0a35; this requires android.permission.INTERACT_ACROSS_USERS_FULL or android.permission.INTERACT_ACROSS_USERS
        at android.os.Parcel.createExceptionOrNull(Parcel.java:2373)
        at android.os.Parcel.createException(Parcel.java:2357)
        at android.os.Parcel.readException(Parcel.java:2340)
        at android.os.Parcel.readException(Parcel.java:2282)
        at android.app.IActivityManager$Stub$Proxy.startActivityAsUser(IActivityManager.java:8208)
        ... 9 more
```

### What steps will reproduce the bug?

am start and broadcast commands such as:
```
KEYMAP_UID=9c56f688-5083-43be-ba7a-58261fd38a91
am broadcast \
    -a io.github.sds100.keymapper.ACTION_TRIGGER_KEYMAP_BY_UID \
    --es io.github.sds100.keymapper.EXTRA_KEYMAP_UID $KEYMAP_UID

am start -n android.jonas.fakestandby/.actions.StartOverlay
```

These apps/broadcast receivers continue to work when the intent is sent from other apps, so I think termux-am is the issue

### What is the expected behavior?

am start/broadcast behavior from before the upgrade to 0.7.1

### System information

termux-info:

```
Termux Variables:
TERMUX_API_VERSION=0.50.1
TERMUX_APK_RELEASE=F_DROID
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=16113
TERMUX_IS_DEBUGGABLE_BUILD=0
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
TERMUX__USER_ID=0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://mirror.albony.xyz/termux/termux-main stable main
# x11-repo (sources.list.d/x11.list)
deb https://mirror.albony.xyz/termux/termux-x11 x11 main
Updatable packages:
All packages up to date
termux-tools version:
1.40.1
Android version:
11
Kernel build information:
Linux localhost 4.4.223-g52750b8f2138-ab6846512 #1 SMP PREEMPT Fri Sep 18 09:49:34 UTC 2020 aarch64 Android
Device manufacturer:
Google
Device model:
Pixel 2
LD Variables:
LD_LIBRARY_PATH=
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so
Installed termux plugins:
com.termux.api versionCode:51
com.termux.boot versionCode:7
com.termux.widget versionCode:13
com.termux.window versionCode:15

```

**Comment by agnostic-apollo** [comment]
I cannot reproduce this myself, but I switched to getting current user id in `TermuxAm` itself instead of letting framework handle it, can you test it by installing with `dpkg -i /sdcard/termux-am.deb` after extracting deb from zip.

[termux-am.zip](https://github.com/termux/termux-packages/files/13773928/termux-am.zip)

**Comment by sudomain** [comment]
That .deb file fixed it. Thanks

**Comment by agnostic-apollo** [comment]
Thanks for confirming, will push a release soon.
