### ISSUE TITLE
NodeJS EACCESS error

### ISSUE THREAD

**Issue by orliesaurus** [termux/termux-packages#1892]
I am trying to run the simplest webserver as I am just playing with termux but after successfully installing Node (v8.9.1 and also `nodejs-current`) I am hit with the below error
```
fs.js:646
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: EACCES: permission denied, open '/data/data/com.termux/files/home/nodeapp/server.js'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.readFileSync (fs.js:551:33)
    at Object.Module._extensions..js (module.js:645:20)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
```

Any idea what that could be related to? I thought it had to do with some ports being closed on my device but I don't think that's the case anymore after asking on IRC?
Thank you!

**Comment by orliesaurus** [comment]
Okay it was an issue with SELinux file permissions - not being able to read the file as node from termux - go figure....
