### ISSUE TITLE
fatal error: 'cairo.h' file not found

### ISSUE THREAD

**Issue by 021Bedy** [termux/termux-packages#19178]
Este erro ocorre ao tentar instalar as dependecias usando **npm i**
```
~/a/ModeraçãoNYX $ npm i
[##################] - reify:@stencil/core: http fetch GET 200 https://registry.npmjs.o
> better-sqlite3@8.7.0 install
> prebuild-install || node-gyp rebuild --release

prebuild-install warn install No prebuilt binaries found (target=18.16.1 runtime=node arch=arm64 libc= platform=android)
gyp info[##################] - reify:@stencil/core: http fetch GET 200 https://registry. it worked if it ends with ok
gyp info using node-gyp@9.3.1
gyp info using node@18.16.1 | android | arm64
gyp info find Python using Python version 3.11.6 found at "/data/data/com.termux/files/usr/bin/python3"
gyp info spawn /data/data/com.termux/files/usr/bin/python3 200 https://registry.npmjs.o
gyp info spawn args [
gyp info spawn args   '/data/data/com.termux/files/usr/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/data/data/com.termux/files/home/a/ModeraçãoNYX/node_modules/better-sqlite3/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/data/data/com.termux/files/usr/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/data/data/com.termux/files/home/.cache/node-gyp/18.16.1/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/data/data/com.termux/files/home/.cache/node-gyp/18.16.1',
gyp info spawn args   '-Dnode_gyp_dir=/data/data/com.termux/files/usr/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/data/data/com.termux/files/home/.cache/node-gyp/18.16.1/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/data/data/com.termux/files/home/a/ModeraçãoNYX/node_modules/better-sqlite3',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info spawn make] - reify:@stencil/core: http fetch GET 200 https://registry.npmjs.o
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory '/data/data/com.termux/files/home/a/ModeraçãoNYX/node_modules/better-sqlite3/build'
  TOUCH ba23eeee118cd63e16015df367567cb043fed872.intermediate
  ACTION deps_sqlite3_gyp_locate_sqlite3_target_copy_builtin_sqlite3 ba23eeee118cd63e16015df367567cb043fed872.intermediate
  TOUCH Release/obj.target/deps/locate_sqlite3.stampch GET 200 https://registry.npmjs.o
  CC(target) Release/obj.target/sqlite3/gen/sqlite3/sqlite3.o0 https://registry.npmjs.o
rm -f Release/obj.target/deps/sqlite3.a Release/obj.target/deps/sqlite3.a.ar-file-list; mkdir -p `dirname Release/obj.target/deps/sqlite3.a`
ar crs Release/obj.target/deps/sqlite3.a @Release/obj.target/deps/sqlite3.a.ar-file-list
  COPY Release/sqlite3.aeify:@stencil/core: http fetch GET 200 https://registry.npmjs.o
  CXX(target) Release/obj.target/better_sqlite3/src/better_sqlite3.o://registry.npmjs.o
./src/objects/database.lzz:180:21: warning: variable 'status' set but not used [-Wunused-but-set-variable]
  180 |                 int status = sqlite3_db_config(db_handle, SQLITE_DBCONFIG_ENABLE_LOAD_EXTENSION, 1, NULL);
      |                     ^
1 warning generated. - reify:@stencil/core: http fetch GET 200 https://registry.npmjs.o
  SOLINK_MODULE(target) Release/obj.target/better_sqlite3.node https://registry.npmjs.o
  COPY Release/better_sqlite3.nodecil/core: http fetch GET 200 https://registry.npmjs.o
  CC(target) Release/obj.target/test_extension/deps/test_extension.o://registry.npmjs.o
  SOLINK_MODULE(target) Release/obj.target/test_extension.node https://registry.npmjs.o
  COPY Release/test_extension.nodecil/core: http fetch GET 200 https://registry.npmjs.o
rm ba23eeee118cd63e16015df367567cb043fed872.intermediateET 200 https://registry.npmjs.o
make: Leaving directory '/data/data/com.termux/files/home/a/ModeraçãoNYX/node_modules/better-sqlite3/build'
gyp info ok
[##################] - reify:@stencil/core: http fetch GET 200 https://registry.npmjs.o
> canvas@2.11.2 install
> node-pre-gyp install --fallback-to-build --update-binary

node-pre-gyp info it worked if it ends with oktp fetch GET 200 https://registry.npmjs.o
node-pre-gyp info using node-pre-gyp@1.0.11
node-pre-gyp info using node@18.16.1 | android | arm64
node-pre-gyp http GET https://github.com/Automattic/node-canvas/releases/download/v2.11.2/canvas-v2.11.2-node-v108-android-unknown-arm64.tar.gz
node-pre-gyp ERR! install response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.11.2/canvas-v2.11.2-node-v108-android-unknown-arm64.tar.gz
node-pre-gyp WARN Pre-built binaries not installable for canvas@2.11.2 and node@18.16.1 (node-v108 ABI, unknown) (falling back to source compile with node-gyp)
node-pre-gyp WARN Hit error response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.11.2/canvas-v2.11.2-node-v108-android-unknown-arm64.tar.gz
gyp info it worked if it ends with ok/core: http fetch GET 200 https://registry.npmjs.o
gyp info using node-gyp@9.3.1
gyp info using node@18.16.1 | android | arm64
gyp info ok #######] / reify:@stencil/core: http fetch GET 200 https://registry.npmjs.o
gyp info it worked if it ends with ok/core: http fetch GET 200 https://registry.npmjs.o
gyp info using node-gyp@9.3.1
gyp info using node@18.16.1 | android | arm64
gyp info find Python using Python version 3.11.6 found at "/data/data/com.termux/files/usr/bin/python3"
gyp info spawn /data/data/com.termux/files/usr/bin/python3 200 https://registry.npmjs.o
gyp info spawn args [
gyp info spawn args   '/data/data/com.termux/files/usr/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/data/data/com.termux/files/home/a/ModeraçãoNYX/node_modules/canvas/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/data/data/com.termux/files/usr/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/data/data/com.termux/files/home/.cache/node-gyp/18.16.1/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/data/data/com.termux/files/home/.cache/node-gyp/18.16.1',
gyp info spawn args   '-Dnode_gyp_dir=/data/data/com.termux/files/usr/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/data/data/com.termux/files/home/.cache/node-gyp/18.16.1/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/data/data/com.termux/files/home/a/ModeraçãoNYX/node_modules/canvas',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
Package xproto was not found in the pkg-config search path.200 https://registry.npmjs.o
Perhaps you should add the directory containing `xproto.pc'
to the PKG_CONFIG_PATH environment variable
Package 'xproto', required by 'x11', not found
Package xproto was not found in the pkg-config search path.200 https://registry.npmjs.o
Perhaps you should add the directory containing `xproto.pc'
to the PKG_CONFIG_PATH environment variable
Package 'xproto', required by 'xrender', not found
gyp info ok #######] / reify:@stencil/core: http fetch GET 200 https://registry.npmjs.o
gyp info it worked if it ends with ok/core: http fetch GET 200 https://registry.npmjs.o
gyp info using node-gyp@9.3.1
gyp info using node@18.16.1 | android | arm64
gyp info spawn make] / reify:@stencil/core: http fetch GET 200 https://registry.npmjs.o
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory '/data/data/com.termux/files/home/a/ModeraçãoNYX/node_modules/canvas/build'
  SOLINK_MODULE(target) Release/obj.target/canvas-postbuild.node
  COPY Release/canvas-postbuild.nodel/core: http fetch GET 200 https://registry.npmjs.o
  CXX(target) Release/obj.target/canvas/src/backend/Backend.o0 https://registry.npmjs.o
In file included from ../src/backend/Backend.cc:1:
../src/backend/Backend.h:3:10: fatal error: 'cairo.h' file not found
    3 | #include <cairo.h>
      |          ^~~~~~~~~
1 error generated.#] / reify:@stencil/core: http fetch GET 200 https://registry.npmjs.o
make: *** [canvas.target.mk:132: Release/obj.target/canvas/src/backend/Backend.o] Error 1
make: Leaving directory '/data/data/com.termux/files/home/a/ModeraçãoNYX/node_modules/canvas/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/data/data/com.termux/files/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:203:23)
gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:291:12)
gyp ERR! System Linux 4.19.157-perf+
gyp ERR! command "/data/data/com.termux/files/usr/bin/node" "/data/data/com.termux/files/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--update-binary" "--module=/data/data/com.termux/files/home/a/ModeraçãoNYX/node_modules/canvas/build/Release/canvas.node" "--module_name=canvas" "--module_path=/data/data/com.termux/files/home/a/ModeraçãoNYX/node_modules/canvas/build/Release" "--napi_version=8" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v108"
gyp ERR! cwd /data/data/com.termux/files/home/a/ModeraçãoNYX/node_modules/canvas
gyp ERR! node -v v18.16.1
gyp ERR! node-gyp -v v9.3.1
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/data/data/com.termux/files/usr/bin/node /data/data/com.termux/files/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --update-binary --module=/data/data/com.termux/files/home/a/ModeraçãoNYX/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/data/data/com.termux/files/home/a/ModeraçãoNYX/node_modules/canvas/build/Release --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v108' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/data/data/com.termux/files/home/a/ModeraçãoNYX/node_modules/@mapbox/node-pre-gyp/lib/util/compile.js:89:23)
node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1091:16)
node-pre-gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:302:5)
node-pre-gyp ERR! System Linux 4.19.157-perf+
node-pre-gyp ERR! command "/data/data/com.termux/files/usr/bin/node" "/data/data/com.termux/files/home/a/ModeraçãoNYX/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build" "--update-binary"
node-pre-gyp ERR! cwd /data/data/com.termux/files/home/a/ModeraçãoNYX/node_modules/canvas
node-pre-gyp ERR! node -v v18.16.1
node-pre-gyp ERR! node-pre-gyp -v v1.0.11
node-pre-gyp ERR! not ok
Failed to execute '/data/data/com.termux/files/usr/bin/node /data/data/com.termux/files/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --update-binary --module=/data/data/com.termux/files/home/a/ModeraçãoNYX/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/data/data/com.termux/files/home/a/ModeraçãoNYX/node_modules/canvas/build/Release --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v108' (1)
npm ERR! code 1
npm ERR! path /data/data/com.termux/files/home/a/ModeraçãoNYX/node_modules/canvas
npm ERR! command failed
npm ERR! command sh -c node-pre-gyp install --fallback-to-build --update-binary

npm ERR! A complete log of this run can be found in:
npm ERR!     /data/data/com.termux/files/home/.npm/_logs/2024-02-08T15_39_54_231Z-debug-0.log
```
Aqui está o packge.json, caso seja útil:
```
{
  "name": "project-1.1",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "@discordjs/voice": "^0.14.0",
    "axios": "^1.2.2",
    "better-sqlite3": "^8.0.1",
    "canvacord": "^5.4.8",
    "canvas": "^2.11.0",
    "discord-html-transcripts": "^3.1.2",
    "discord-logs": "^2.2.1",
    "discord.js": "^14.7.1",
    "glob": "^8.0.3",
    "moment": "^2.29.4",
    "mongoose": "^6.9.0",
    "quick.db": "^9.0.8"
  }
}
```

**Comment by twaik** [comment]
1. Official language here is English.
2. `pkg install libcairo`.

**Comment by 021Bedy** [comment]
Sorry, I'll continue in English, I installed libcairo and the error still persists: 

```
Picking mirror: (18) /data/data/com.termux/files/usr/etc/termux/mirrors/china/mirrors.tuna.tsinghua.edu.cn
Hit:1 https://its-pointless.github.io/files/21 termux InRelease
Get:2 https://mirrors.tuna.tsinghua.edu.cn/termux/apt/termux-main stable InRelease [14.0 kB]
Get:3 https://mirrors.tuna.tsinghua.edu.cn/termux/apt/termux-x11 x11 InRelease [14.0 kB]
Get:4 https://mirrors.tuna.tsinghua.edu.cn/termux/apt/termux-main stable/main aarch64 Packages [502 kB]
Get:5 https://mirrors.tuna.tsinghua.edu.cn/termux/apt/termux-x11 x11/main aarch64 Packages [129 kB]
Fetched 658 kB in 5s (122 kB/s)
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
All packages are up to date.
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
libcairo is already the newest version (1.18.0).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
~/a/ModeraçãoNYX $ npm i
[##################] - reify:@stencil/core: timing reifyNode:node_modules/highlig
> better-sqlite3@8.7.0 install
> prebuild-install || node-gyp rebuild --release

prebuild-install warn install No prebuilt binaries found (target=18.16.1 runtime=node arch=arm64 libc= platform=android)
gyp info it worked if it ends with ok/core: timing reifyNode:node_modules/highlig
gyp info using node-gyp@9.3.1@stencil/core: timing reifyNode:node_modules/highlig
gyp info using node@18.16.1 | android | arm64
gyp info find Python using Python version 3.11.6 found at "/data/data/com.termux/files/usr/bin/python3"
gyp info spawn /data/data/com.termux/files/usr/bin/python3de:node_modules/highlig
gyp info spawn args [
gyp info spawn args   '/data/data/com.termux/files/usr/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/data/data/com.termux/files/home/a/ModeraçãoNYX/node_modules/better-sqlite3/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/data/data/com.termux/files/usr/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/data/data/com.termux/files/home/.cache/node-gyp/18.16.1/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/data/data/com.termux/files/home/.cache/node-gyp/18.16.1',
gyp info spawn args   '-Dnode_gyp_dir=/data/data/com.termux/files/usr/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/data/data/com.termux/files/home/.cache/node-gyp/18.16.1/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/data/data/com.termux/files/home/a/ModeraçãoNYX/node_modules/better-sqlite3',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info spawn make] \ reify:@stencil/core: timing reifyNode:node_modules/highlig
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory '/data/data/com.termux/files/home/a/ModeraçãoNYX/node_modules/better-sqlite3/build'
  TOUCH ba23eeee118cd63e16015df367567cb043fed872.intermediate
  ACTION deps_sqlite3_gyp_locate_sqlite3_target_copy_builtin_sqlite3 ba23eeee118cd63e16015df367567cb043fed872.intermediate
  TOUCH Release/obj.target/deps/locate_sqlite3.stampeifyNode:node_modules/highlig
  CC(target) Release/obj.target/sqlite3/gen/sqlite3/sqlite3.onode_modules/highlig
rm -f Release/obj.target/deps/sqlite3.a Release/obj.target/deps/sqlite3.a.ar-file-list; mkdir -p `dirname Release/obj.target/deps/sqlite3.a`
ar crs Release/obj.target/deps/sqlite3.a @Release/obj.target/deps/sqlite3.a.ar-file-list
  COPY Release/sqlite3.aeify:@stencil/core: timing reifyNode:node_modules/highlig
  CXX(target) Release/obj.target/better_sqlite3/src/better_sqlite3.odules/highlig
./src/objects/database.lzz:180:21: warning: variable 'status' set but not used [-Wunused-but-set-variable]
  180 |                 int status = sqlite3_db_config(db_handle, SQLITE_DBCONFIG_ENABLE_LOAD_EXTENSION, 1, NULL);
      |                     ^
1 warning generated. \ reify:@stencil/core: timing reifyNode:node_modules/highlig
  SOLINK_MODULE(target) Release/obj.target/better_sqlite3.nodeode_modules/highlig
  COPY Release/better_sqlite3.nodecil/core: timing reifyNode:node_modules/highlig
  CC(target) Release/obj.target/test_extension/deps/test_extension.odules/highlig
  SOLINK_MODULE(target) Release/obj.target/test_extension.nodeode_modules/highlig
  COPY Release/test_extension.nodecil/core: timing reifyNode:node_modules/highlig
rm ba23eeee118cd63e16015df367567cb043fed872.intermediateNode:node_modules/highlig
make: Leaving directory '/data/data/com.termux/files/home/a/ModeraçãoNYX/node_modules/better-sqlite3/build'
gyp info ok
[##################] \ reify:@stencil/core: timing reifyNode:node_modules/highlig
> canvas@2.11.2 install
> node-pre-gyp install --fallback-to-build --update-binary

node-pre-gyp info it worked if it ends with okming reifyNode:node_modules/highlig
node-pre-gyp info using node-pre-gyp@1.0.11
node-pre-gyp info using node@18.16.1 | android | arm64
node-pre-gyp http GET https://github.com/Automattic/node-canvas/releases/download/v2.11.2/canvas-v2.11.2-node-v108-android-unknown-arm64.tar.gz
node-pre-gyp ERR! install response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.11.2/canvas-v2.11.2-node-v108-android-unknown-arm64.tar.gz
node-pre-gyp WARN Pre-built binaries not installable for canvas@2.11.2 and node@18.16.1 (node-v108 ABI, unknown) (falling back to source compile with node-gyp)
node-pre-gyp WARN Hit error response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.11.2/canvas-v2.11.2-node-v108-android-unknown-arm64.tar.gz
gyp info it worked if it ends with ok/core: timing reifyNode:node_modules/highlig
gyp info using node-gyp@9.3.1
gyp info using node@18.16.1 | android | arm64
gyp info ok #######] - reify:@stencil/core: timing reifyNode:node_modules/highlig
gyp info it worked if it ends with ok/core: timing reifyNode:node_modules/highlig
gyp info using node-gyp@9.3.1
gyp info using node@18.16.1 | android | arm64
gyp info find Python using Python version 3.11.6 found at "/data/data/com.termux/files/usr/bin/python3"
gyp info spawn /data/data/com.termux/files/usr/bin/python3de:node_modules/highlig
gyp info spawn args [
gyp info spawn args   '/data/data/com.termux/files/usr/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/data/data/com.termux/files/home/a/ModeraçãoNYX/node_modules/canvas/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/data/data/com.termux/files/usr/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/data/data/com.termux/files/home/.cache/node-gyp/18.16.1/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/data/data/com.termux/files/home/.cache/node-gyp/18.16.1',
gyp info spawn args   '-Dnode_gyp_dir=/data/data/com.termux/files/usr/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/data/data/com.termux/files/home/.cache/node-gyp/18.16.1/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/data/data/com.termux/files/home/a/ModeraçãoNYX/node_modules/canvas',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
Package xproto was not found in the pkg-config search path.e:node_modules/highlig
Perhaps you should add the directory containing `xproto.pc'
to the PKG_CONFIG_PATH environment variable
Package 'xproto', required by 'x11', not found
Package xproto was not found in the pkg-config search path.e:node_modules/highlig
Perhaps you should add the directory containing `xproto.pc'
to the PKG_CONFIG_PATH environment variable
Package 'xproto', required by 'xrender', not found
gyp info ok #######] - reify:@stencil/core: timing reifyNode:node_modules/highlig
gyp info it worked if it ends with ok/core: timing reifyNode:node_modules/highlig
gyp info using node-gyp@9.3.1
gyp info using node@18.16.1 | android | arm64
gyp info spawn make] - reify:@stencil/core: timing reifyNode:node_modules/highlig
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory '/data/data/com.termux/files/home/a/ModeraçãoNYX/node_modules/canvas/build'
  SOLINK_MODULE(target) Release/obj.target/canvas-postbuild.node
  COPY Release/canvas-postbuild.nodel/core: timing reifyNode:node_modules/highlig
  CXX(target) Release/obj.target/canvas/src/backend/Backend.onode_modules/highlig
In file included from ../src/backend/Backend.cc:1: reifyNode:node_modules/highlig
../src/backend/Backend.h:3:10: fatal error: 'cairo.h' file not found
    3 | #include <cairo.h>
      |          ^~~~~~~~~
1 error generated.#] - reify:@stencil/core: timing reifyNode:node_modules/highlig
make: *** [canvas.target.mk:132: Release/obj.target/canvas/src/backend/Backend.o] Error 1
make: Leaving directory '/data/data/com.termux/files/home/a/ModeraçãoNYX/node_modules/canvas/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/data/data/com.termux/files/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:203:23)
gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:291:12)
gyp ERR! System Linux 4.19.157-perf+
gyp ERR! command "/data/data/com.termux/files/usr/bin/node" "/data/data/com.termux/files/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--update-binary" "--module=/data/data/com.termux/files/home/a/ModeraçãoNYX/node_modules/canvas/build/Release/canvas.node" "--module_name=canvas" "--module_path=/data/data/com.termux/files/home/a/ModeraçãoNYX/node_modules/canvas/build/Release" "--napi_version=8" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v108"
gyp ERR! cwd /data/data/com.termux/files/home/a/ModeraçãoNYX/node_modules/canvas
gyp ERR! node -v v18.16.1
gyp ERR! node-gyp -v v9.3.1
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/data/data/com.termux/files/usr/bin/node /data/data/com.termux/files/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --update-binary --module=/data/data/com.termux/files/home/a/ModeraçãoNYX/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/data/data/com.termux/files/home/a/ModeraçãoNYX/node_modules/canvas/build/Release --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v108' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/data/data/com.termux/files/home/a/ModeraçãoNYX/node_modules/@mapbox/node-pre-gyp/lib/util/compile.js:89:23)
node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1091:16)
node-pre-gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:302:5)
node-pre-gyp ERR! System Linux 4.19.157-perf+
node-pre-gyp ERR![##################] - reify:@stencil/core: timing reifyNode:node command "/data/data/com.termux/files/usr/bin/node" "/data/data/com.termux/files/home/a/ModeraçãoNYX/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build" "--update-binary"
node-pre-gyp ERR! cwd /data/data/com.termux/files/home/a/ModeraçãoNYX/node_modules/canvas
node-pre-gyp ERR! node -v v18.16.1
node-pre-gyp ERR! node-pre-gyp -v v1.0.11
node-pre-gyp ERR! not ok
Failed to execute '/data/data/com.termux/files/usr/bin/node /data/data/com.termux/files/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --update-binary --module=/data/data/com.termux/files/home/a/ModeraçãoNYX/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/data/data/com.termux/files/home/a/ModeraçãoNYX/node_modules/canvas/build/Release --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v108' (1)
npm ERR! code 1
npm ERR! path /data/data/com.termux/files/home/a/ModeraçãoNYX/node_modules/canvas
npm ERR! command failed
npm ERR! command sh -c node-pre-gyp install --fallback-to-build --update-binary

npm ERR! A complete log of this run can be found in:
npm ERR!     /data/data/com.termux/files/home/.npm/_logs/2024-02-10T02_45_35_825Z-debug-0.log
```

**Comment by licy183** [comment]
`xproto.pc` exists in `xorgproto`. Try `pkg install xorgproto`

**Comment by 021Bedy** [comment]
My problem has been resolved, thank you very much.

**Comment by 021Bedy** [comment]
My problem has been resolved, thank you very much.
