### ISSUE TITLE
[Bug]: am tool does not work in proot-distro.

### ISSUE THREAD

**Issue by numberokta** [termux/termux-packages#19314]
### Problem description

Changing settings from termux works perfectly but from proot-distro, when i login to ubuntu, it doesn't work and gives error.

### What steps will reproduce the bug?

Running `am broadcast -a com.termux.x11.CHANGE_PREFERENCE -p com.termux.x11 -e list null` from proot-distro gives this error
```
Broadcasting: Intent { act=com.termux.x11.CHANGE_PREFERENCE pkg=com.termux.x11 (has extras) }
java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.termux.termuxam.CrossVersionReflectedMethod.invoke(CrossVersionReflectedMethod.java:175)
        at com.termux.termuxam.IActivityManager.broadcastIntent(IActivityManager.java:273)
        at com.termux.termuxam.Am.sendBroadcast(Am.java:984)
        at com.termux.termuxam.Am.onRun(Am.java:455)
        at com.termux.termuxam.BaseCommand.run(BaseCommand.java:46)
        at com.termux.termuxam.Am.main(Am.java:120)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:387)
Caused by: java.lang.SecurityException: Permission Denial: getIntentSender asks to run as user -2 but is calling from uid u0a316; this requires android.permission.INTERACT_ACROSS_USERS_FULL or android.permission.INTERACT_ACROSS_USERS
        at android.os.Parcel.createExceptionOrNull(Parcel.java:3011)
        at android.os.Parcel.createException(Parcel.java:2995)
        at android.os.Parcel.readException(Parcel.java:2978)
        at android.os.Parcel.readException(Parcel.java:2920)
        at android.app.IActivityManager$Stub$Proxy.getIntentSender(IActivityManager.java:6595)
        ... 9 more
Caused by: android.os.RemoteException: Remote stack trace:
        at com.android.server.am.UserController.handleIncomingUser(UserController.java:2296)
        at com.android.server.am.ActivityManagerService.getIntentSenderWithFeatureAsApp(ActivityManagerService.java:5646)
        at com.android.server.am.ActivityManagerService.getIntentSenderWithFeature(ActivityManagerService.java:5596)
        at com.android.server.am.ActivityManagerService.getIntentSender(ActivityManagerService.java:5586)
        at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:3219)
```
i think, it's something to do with user

### What is the expected behavior?

Work's with different user

**Comment by agnostic-apollo** [comment]
>That's an issue of am or something like. It checks current UID and if does not match, throws an exception.

- What's the output for `id -u` and `id -un` under proot?
- Is `termux-am` at `v0.8.0`? If uid is `>= 10000` (`FIRST_APPLICATION_UID`), the current user id should automatically be extracted from it. If not, then it passes `-2` (`USER_CURRENT`) to `am` service to ask it use the android's internal current user id itself, which requires the permission.
- You can also manually pass `--user 0` to `am` so that passed id is used instead, that may work. Also try passing `--user -3` (`USER_CURRENT_OR_SELF`).
- OP's `u0a316` should be valid app id though, so not sure for why the error.

https://github.com/termux/TermuxAm/blob/96c9b040ac10b9560ed80e75036e788903c795c4/app/src/main/java/com/termux/termuxam/Am.java#L672

https://github.com/termux/TermuxAm/blob/96c9b040ac10b9560ed80e75036e788903c795c4/app/src/main/java/com/termux/termuxam/Am.java#L579-L599
