### ISSUE TITLE
pip3 install pynacl error

### ISSUE THREAD

**Issue by pippognetow** [termux/termux-packages#1964]
$ pip3 install pynacl
Collecting pynacl
  Downloading PyNaCl-1.2.1.tar.gz (3.3MB)
    100% |████████████████████████████████| 3.3MB 52kB/s
    Complete output from command python setup.py egg_info:

        No working compiler found, or bogus compiler options passed to
        the compiler from Python's standard "distutils" module.  See
        the error messages above.  Likely, the problem is not related
        to CFFI but generic to the setup.py of any Python package that
        tries to compile C code.  (Hints: on OS/X 10.8, for errors about
        -mno-fused-madd see http://stackoverflow.com/questions/22313407/
        Otherwise, see https://wiki.python.org/moin/CompLangPython or
        the IRC channel #python on irc.freenode.net.)
    Traceback (most recent call last):
      File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/setuptools/sandbox.py", line 157, in save_modules
        yield saved
      File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/setuptools/sandbox.py", line 198, in setup_context
        yield
      File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/setuptools/sandbox.py", line 248, in run_setup
        DirectorySandbox(setup_dir).run(runner)
      File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/setuptools/sandbox.py", line 278, in run
        return func()
      File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/setuptools/sandbox.py", line 246, in runner
        _execfile(setup_script, ns)
      File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/setuptools/sandbox.py", line 47, in _execfile
        exec(code, globals, locals)
      File "/data/data/com.termux/files/usr/tmp/easy_install-ggsho_vv/cffi-1.11.2/setup.py", line 138, in <module>
        try:
      File "/data/data/com.termux/files/usr/tmp/easy_install-ggsho_vv/cffi-1.11.2/setup.py", line 73, in ask_supports_thread
        import nacl # flake8: noqa
      File "/data/data/com.termux/files/usr/tmp/easy_install-ggsho_vv/cffi-1.11.2/setup.py", line 55, in no_working_compiler_found
        requirements.append("cffi>=1.4.1")
    SystemExit: 1

During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 1101, in run_setup
        run_setup(setup_script, args)
      File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/setuptools/sandbox.py", line 251, in run_setup
        raise
      File "/data/data/com.termux/files/usr/lib/python3.6/contextlib.py", line 99, in __exit__
        self.gen.throw(type, value, traceback)
      File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/setuptools/sandbox.py", line 198, in setup_context
        yield
      File "/data/data/com.termux/files/usr/lib/python3.6/contextlib.py", line 99, in __exit__
        self.gen.throw(type, value, traceback)
      File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/setuptools/sandbox.py", line 169, in save_modules
        saved_exc.resume()
      File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/setuptools/sandbox.py", line 144, in resume
        six.reraise(type, exc, self._tb)
      File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/pkg_resources/_vendor/six.py", line 685, in reraise
        raise value.with_traceback(tb)
      File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/setuptools/sandbox.py", line 157, in save_modules
        yield saved
      File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/setuptools/sandbox.py", line 198, in setup_context
        yield
      File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/setuptools/sandbox.py", line 248, in run_setup
        DirectorySandbox(setup_dir).run(runner)
      File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/setuptools/sandbox.py", line 278, in run
        return func()
      File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/setuptools/sandbox.py", line 246, in runner
        _execfile(setup_script, ns)
      File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/setuptools/sandbox.py", line 47, in _execfile
        exec(code, globals, locals)
      File "/data/data/com.termux/files/usr/tmp/easy_install-ggsho_vv/cffi-1.11.2/setup.py", line 138, in <module>
        try:
      File "/data/data/com.termux/files/usr/tmp/easy_install-ggsho_vv/cffi-1.11.2/setup.py", line 73, in ask_supports_thread
        import nacl # flake8: noqa
      File "/data/data/com.termux/files/usr/tmp/easy_install-ggsho_vv/cffi-1.11.2/setup.py", line 55, in no_working_compiler_found
        requirements.append("cffi>=1.4.1")
    SystemExit: 1

During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/data/data/com.termux/files/usr/tmp/pip-build-a96xjhi7/pynacl/setup.py", line 251, in <module>
        "Programming Language :: Python :: 3.6",
      File "/data/data/com.termux/files/usr/lib/python3.6/distutils/core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/setuptools/dist.py", line 315, in __init__
        self.fetch_build_eggs(attrs['setup_requires'])
      File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/setuptools/dist.py", line 361, in fetch_build_eggs
        replace_conflicting=True,
      File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 850, in resolve
        dist = best[req.key] = env.best_match(req, ws, installer)
      File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1122, in best_match
        return self.obtain(req, installer)
      File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1134, in obtain
        return installer(requirement)
      File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/setuptools/dist.py", line 429, in fetch_build_egg
        return cmd.easy_install(req)
      File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 665, in easy_install
        return self.install_item(spec, dist.location, tmpdir, deps)
      File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 695, in install_item
        dists = self.install_eggs(spec, download, tmpdir)
      File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 876, in install_eggs
        return self.build_and_install(setup_script, setup_base)
      File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 1115, in build_and_install
        self.run_setup(setup_script, setup_base, args)
      File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 1103, in run_setup
        raise DistutilsError("Setup script exited with %s" % (v.args[0],))
    distutils.errors.DistutilsError: Setup script exited with 1

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /data/data/com.termux/files/usr/tmp/pip-build-a96xjhi7/pynacl/

**Comment by Grimler91** [comment]
You might not have clang installed (run `pkg install clang`). 
See the page about python packages in the [termux wiki](https://wiki.termux.com/wiki/Instructions_for_installing_python_packages), especially the [pynacl section](https://wiki.termux.com/wiki/Instructions_for_installing_python_packages#pynacl).

Help on installing pynacl has been asked a couple of times already, see issues https://github.com/termux/termux-packages/issues/1628 and https://github.com/termux/termux-packages/issues/1881.

**Comment by pippognetow** [comment]
Thank you, it worked. I had also to install python.h. The I ran again python3 setup.py install. Got another error... cffi missing. So I tried to install it with pip but I got this error:

pip3 install cffi
Collecting cffi
  Downloading cffi-1.11.2.tar.gz (435kB)
    100% |████████████████████████████████| 440kB 229kB/s
Collecting pycparser (from cffi)
  Retrying (Retry(total=4, connect=None, read=None, redirect=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='pypi.python.org', port=443): Read timed out. (read timeout=15)",)': /simple/pycparser/
  Downloading pycparser-2.18.tar.gz (245kB)
    100% |████████████████████████████████| 256kB 65kB/s
Installing collected packages: pycparser, cffi
  Running setup.py install for pycparser ... done
  Running setup.py install for cffi ... error
    Complete output from command /data/data/com.termux/files/usr/bin/python -u -c "import setuptools, tokenize;__file__='/data/data/com.termux/files/usr/tmp/pip-build-m590ncmi/cffi/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /data/data/com.termux/files/usr/tmp/pip-1o_vdatf-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-armv7l-3.6
    creating build/lib.linux-armv7l-3.6/cffi
    copying cffi/vengine_cpy.py -> build/lib.linux-armv7l-3.6/cffi
    copying cffi/model.py -> build/lib.linux-armv7l-3.6/cffi
    copying cffi/commontypes.py -> build/lib.linux-armv7l-3.6/cffi
    copying cffi/error.py -> build/lib.linux-armv7l-3.6/cffi
    copying cffi/backend_ctypes.py -> build/lib.linux-armv7l-3.6/cffi
    copying cffi/cparser.py -> build/lib.linux-armv7l-3.6/cffi
    copying cffi/ffiplatform.py -> build/lib.linux-armv7l-3.6/cffi
    copying cffi/vengine_gen.py -> build/lib.linux-armv7l-3.6/cffi
    copying cffi/api.py -> build/lib.linux-armv7l-3.6/cffi
    copying cffi/lock.py -> build/lib.linux-armv7l-3.6/cffi
    copying cffi/__init__.py -> build/lib.linux-armv7l-3.6/cffi
    copying cffi/setuptools_ext.py -> build/lib.linux-armv7l-3.6/cffi
    copying cffi/cffi_opcode.py -> build/lib.linux-armv7l-3.6/cffi
    copying cffi/verifier.py -> build/lib.linux-armv7l-3.6/cffi
    copying cffi/recompiler.py -> build/lib.linux-armv7l-3.6/cffi
    copying cffi/_cffi_include.h -> build/lib.linux-armv7l-3.6/cffi
    copying cffi/parse_c_type.h -> build/lib.linux-armv7l-3.6/cffi
    copying cffi/_embedding.h -> build/lib.linux-armv7l-3.6/cffi
    copying cffi/_cffi_errors.h -> build/lib.linux-armv7l-3.6/cffi
    running build_ext
    building '_cffi_backend' extension
    creating build/temp.linux-armv7l-3.6
    creating build/temp.linux-armv7l-3.6/c
    ‎arm-linux-androideabi-clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -march=armv7-a -mfpu=neon -mfloat-abi=softfp -mthumb -Oz -march=armv7-a -mfpu=neon -mfloat-abi=softfp -mthumb -Oz -fPIC -DUSE__THREAD -DHAVE_SYNC_SYNCHRONIZE -I/usr/include/ffi -I/usr/include/libffi -I/data/data/com.termux/files/usr/include/python3.6m -c c/_cffi_backend.c -o build/temp.linux-armv7l-3.6/c/_cffi_backend.o
    c/_cffi_backend.c:15:10: fatal error: 'ffi.h' file not found
    #include <ffi.h>
             ^~~~~~~
    1 error generated.
    error: command 'arm-linux-androideabi-clang' failed with exit status 1

    ----------------------------------------
Command "/data/data/com.termux/files/usr/bin/python -u -c "import setuptools, tokenize;__file__='/data/data/com.termux/files/usr/tmp/pip-build-m590ncmi/cffi/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /data/data/com.termux/files/usr/tmp/pip-1o_vdatf-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /data/data/com.termux/files/usr/tmp/pip-build-m590ncmi/cffi/

**Comment by Grimler91** [comment]
`apt search ffi` finds the packages libffi and libffi-dev. Header files like ffi.h are usually provided by the development -dev packages so in this case you need to install libffi-dev.
