### ISSUE TITLE
Couldn't install numexpr: Failed building wheel for numexpr

### ISSUE THREAD

**Issue by Duuckjing** [termux/termux-packages#19951]
The whole error log is too long so I just put the last few lines here. I'm installing [xiaogpt](https://github.com/yihong0618/xiaogpt) and after installing the dependencies, such as numpy and maturin, i stuck at this. You can try ```pip install numexpr``` or add a few arguments to this as mentioned in [numpy and python installation](https://github.com/termux/termux-packages/discussions/19126).

**Comment by tqfx** [comment]
numexpr can be installed on my device with the following command:

```
LDFLAGS="-lpython3.11" pip install numexpr
```

**Comment by Duuckjing** [comment]
> numexpr can be installed on my device with the following command:
> 
> ```
> LDFLAGS="-lpython3.11" pip install numexpr
> ```
> 

Thanks, though it does not work first, it made me believe installing was possible.
Actually I found it was due to pip's cache.
The error log is like
```
(phantom) ~/phantom $ LDFLAGS="-lpython3.11" pip install numexpr --no-cache                                                       Collecting numexpr                                                 Downloading numexpr-2.10.0.tar.gz (103 kB)                          ━━━━━━━━━━━━━━━━━━━━━━ 103.6/103.6 kB 558.0 kB/s eta 0:00:00  Installing build dependencies ... done                           Getting requirements to build wheel ... error                    error: subprocess-exited-with-error                                                                                               × Getting requirements to build wheel did not run successfully.  │ exit code: 1                                                   ╰─> [65 lines of output]                                             Traceback (most recent call last):                                 File "/data/data/com.termux/files/usr/tmp/pip-build-env-izr51w0a/overlay/lib/python3.11/site-packages/numpy/_core/__init__.py", line 23, in <module>                                                 from . import multiarray                                       File "/data/data/com.termux/files/usr/tmp/pip-build-env-izr51w0a/overlay/lib/python3.11/site-packages/numpy/_core/multiarray.py", line 10, in <module>                                               from . import overrides                                        File "/data/data/com.termux/files/usr/tmp/pip-build-env-izr51w0a/overlay/lib/python3.11/site-packages/numpy/_core/overrides.py", line 8, in <module>                                                 from numpy._core._multiarray_umath import (                  ImportError: dlopen failed: cannot locate symbol "PyExc_ValueError" referenced by "/data/data/com.termux/files/usr/tmp/pip-build-env-izr51w0a/overlay/lib/python3.11/site-packages/numpy/_core/_multiarray_umath.cpython-311.so"...                                                                                                  During handling of the above exception, another exception occurred:                                                                                                                                Traceback (most recent call last):                                 File "/data/data/com.termux/files/usr/tmp/pip-build-env-izr51w0a/overlay/lib/python3.11/site-packages/numpy/__init__.py", line 114, in <module>                                                      from numpy.__config__ import show as show_config               File "/data/data/com.termux/files/usr/tmp/pip-build-env-izr51w0a/overlay/lib/python3.11/site-packages/numpy/__config__.py", line 4, in <module>                                                      from numpy._core._multiarray_umath import (                    File "/data/data/com.termux/files/usr/tmp/pip-build-env-izr51w0a/overlay/lib/python3.11/site-packages/numpy/_core/__init__.py", line 49, in <module>                                                 raise ImportError(msg)                                       ImportError:                                                                                                                      IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!                                                                                                                                 Importing the numpy C-extensions failed. This error can happen for                                                                many reasons, often due to issues with your setup or how NumPy was                                                                installed.                                                                                                                        We have compiled some common reasons and troubleshooting tips at:                                                                                                                                      https://numpy.org/devdocs/user/troubleshooting-importerror.html                                                                                                                                Please note and check the following:                                                                                                * The Python version is: Python3.11 from "/data/data/com.termux/files/home/phantom/bin/python"                                    * The NumPy version is: "2.0.0rc1"                                                                                              and make sure that they are the versions you expect.             Please carefully study the documentation linked above for further help.                                                                                                                            Original error was: dlopen failed: cannot locate symbol "PyExc_ValueError" referenced by "/data/data/com.termux/files/usr/tmp/pip-build-env-izr51w0a/overlay/lib/python3.11/site-packages/numpy/_core/_multiarray_umath.cpython-311.so"...                                                                                                                                                            The above exception was the direct cause of the following exception:                                                                                                                               Traceback (most recent call last):                                 File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>                                                    main()                                                         File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main                                                        json_out['return_val'] = hook(**hook_input['kwargs'])                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^          File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel                                return hook(config_settings)                                            ^^^^^^^^^^^^^^^^^^^^^                                   File "/data/data/com.termux/files/usr/tmp/pip-build-env-izr51w0a/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 325, in get_requires_for_build_wheel                           return self._get_build_requires(config_settings, requirements=['wheel'])                                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                        File "/data/data/com.termux/files/usr/tmp/pip-build-env-izr51w0a/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 295, in _get_build_requires                                    self.run_setup()                                               File "/data/data/com.termux/files/usr/tmp/pip-build-env-izr51w0a/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 311, in run_setup                                              exec(code, locals())                                           File "<string>", line 16, in <module>                            File "/data/data/com.termux/files/usr/tmp/pip-build-env-izr51w0a/overlay/lib/python3.11/site-packages/numpy/__init__.py", line 119, in <module>                                                      raise ImportError(msg) from e                                ImportError: Error importing numpy: you should not try to import numpy from                                                               its source directory; please exit the numpy source tree, and relaunch                                                             your python interpreter from there.                      [end of output]                                                                                                               note: This error originates from a subprocess, and is likely not a problem with pip.                                            error: subprocess-exited-with-error
```
Because of using numpy in the pip's cache, even I used ```--no-cache```, it failed to build numpy.
Finally I uninstalled numpy(pip) and python-numpy(pkg), and
```
LDFLAGS="-lpython3.11" pkg install python-numpy
pip cache purge
LDFLAGS="-lpython3.11" pip install numexpr --no-cache
```
And numexpr is installed!
