### ISSUE TITLE
[Bug]: While upgrading/installing python-pip it cannot write to '/etc/pip.conf'

### ISSUE THREAD

**Issue by HaaiHenkie** [termux/termux-packages#20132]
### Problem description

While carrying out a `pkg upgrade` the upgrade of python-pip gives the following error:

```
Setting up python-pip (24.0-2) ...
pip setup...
Writing to /etc/pip.conf
ERROR: Unable to save configuration. Please report this as a bug.
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/.local/lib/python3.11/site-packages/pip/_internal/configuration.py", line 215, in save
    with open(fname, "w") as f:
         ^^^^^^^^^^^^^^^^
OSError: [Errno 30] Read-only file system: '/etc/pip.conf'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/data/com.termux/files/home/.local/lib/python3.11/site-packages/pip/_internal/commands/configuration.py", line 265, in _save_configuration
    self.configuration.save()
  File "/data/data/com.termux/files/home/.local/lib/python3.11/site-packages/pip/_internal/configuration.py", line 218, in save
    raise ConfigurationError(
pip._internal.exceptions.ConfigurationError: An error occurred while writing to the configuration file /etc/pip.conf: [Errno 30] Read-only file system: '/etc/pip.conf'
ERROR: Internal Error.
```

### What steps will reproduce the bug?

Pre-condition: python-pip is installed with a lower version than 24.0-2

Step 1:  `$ pkg upgrade`

This results in above message. python-pip is upgrade to version 24.0.

It cannot be reproduced with step 1, but with the following steps

Step 2: `$ pkg uninstall python-pip`
Step 3: `$ pkg install python-pip`

### What is the expected behavior?

That there is no error while upgrading or installing python-pip

### System information

```shell
u0_a444@localhost:~$ termux-info
Termux Variables:
TERMUX_APK_RELEASE=F_DROID
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=7820
TERMUX_IS_DEBUGGABLE_BUILD=0
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
TERMUX__USER_ID=0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://packages-cf.termux.dev/apt/termux-main stable main
Updatable packages:
All packages up to date
termux-tools version:
1.42.1
Android version:
10
Kernel build information:
Linux localhost 4.4.205-22915538 #1 SMP PREEMPT Mon Jul 25 12:20:21 KST 2022 aarch64 Android
Device manufacturer:
samsung
Device model:
SM-T830
LD Variables:
LD_LIBRARY_PATH=
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so
```
```

**Comment by HaaiHenkie** [comment]
Additional remark: the file `/etc/pip.conf` does not exist.

**Comment by TomJo2000** [comment]
Can't replicate this error.

**Comment by tqfx** [comment]
Run the following command for more information:

```sh
export PIP_VERBOSE=3
pkg un python-pip
pkg i python-pip
```

**Comment by tqfx** [comment]
This can happen by running the following command:

```sh
python -m ensurepip --user
export PATH="$HOME/.local/bin:$PATH"
pkg reinstall python-pip
```

We need a full path, what do you think? @TomJo2000 

https://github.com/termux/termux-packages/blob/ca3a29627051ced112563257a7f5674877c95585/packages/python-pip/build.sh#L50

```sh
$TERMUX_PREFIX/bin/pip config set --global global.disable-pip-version-check true
```

**Comment by TomJo2000** [comment]
So breaking the package breaks the package, got it.

**Comment by tqfx** [comment]
@HaaiHenkie You should uninstall the user package pip.

```sh
$HOME/.local/bin/pip3 uninstall pip
```

Then run it manually

```sh
pip config set --global global.disable-pip-version-check true
```

**Comment by HaaiHenkie** [comment]
If I do that, this happens:

```
u0_a444@localhost:~$ pip config set --global global.disable-pip-version-check true
bash: /data/data/com.termux/files/home/.local/bin/pip: No such file or directory
```

**Comment by tqfx** [comment]
```sh
rm -f $HOME/.local/bin/pip
pkg reinstall python-pip
```

**Comment by HaaiHenkie** [comment]
Hi,

That did not work. `$HOME/.local/bin/pip` was not present anyway. However a reboot of termux did the trick. Problem solved. Thank you all!
