### ISSUE TITLE
Failed to compile ninja

### ISSUE THREAD

**Issue by Duuckjing** [termux/termux-packages#20184]
Recently I tried to install manimgl, but after fixing the problem of 'fno-openmp-implicit-rpath', it still stucks at building wheels for skia-pathops. I have looked up its pyproject.toml and all of them are satisfied, but when installing, it still stucks at a typical error, failed building wheel for ninja.
When installing skia-pathops, it could not find a version of ninja. 
```
ERROR: Could not find a version that satisfies the requirement ninja (from versions: none)
      ERROR: No matching distribution found for ninja
      Traceback (most recent call last):
        File "/data/data/com.termux/files/usr/tmp/pip-install-ozvsqbb_/skia-pathops_49aebe4d49b1487b8f51329c251e723d/src/cpp/skia-builder/build_skia.py", line 205, in <module>
          env = make_virtualenv(venv_dir)
                ^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/data/data/com.termux/files/usr/tmp/pip-install-ozvsqbb_/skia-pathops_49aebe4d49b1487b8f51329c251e723d/src/cpp/skia-builder/build_skia.py", line 90, in make_virtualenv
          subprocess.check_call(
        File "/data/data/com.termux/files/usr/lib/python3.11/subprocess.py", line 413, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['/data/data/com.termux/files/usr/tmp/pip-install-ozvsqbb_/skia-pathops_49aebe4d49b1487b8f51329c251e723d/build/temp.linux-aarch64-cpython-311/src/cpp/skia-builder/skia/venv/bin/pip', 'install', '--only-binary=ninja', 'ninja']' returned non-zero exit status 1.
```
And when I then tried to install ninja through pip, it stuck at  1. `c++: error: invalid linker name in argument '-fuse-ld=gold` 2.SKBUILDError
While ninja is installed through pkg, I'm wondering if it can be linked to the installing process directly, to avoid compiling ninja, but as the problem seems to always arise during various installing processes, if ninja compilation can be solved it's better.
I think it is a little different from [pip does not work](https://github.com/termux/termux-app/issues/3649#issue-1944737999) 
 The ninja's compiling error is here [ninja_error.log](https://github.com/termux/termux-packages/files/15322908/ninja_error.log).

**Comment by Biswa96** [comment]
Could you install the ninja package with `apt install ninja` ?

**Comment by Biswa96** [comment]
Then skia-pathops and skia need some patches. Compiling skia and skia-pathops are not easy (speaking from experience of compiling those with mingw-w64 in Windows).

**Comment by Duuckjing** [comment]
Emmm,I see. It's really a headache

**Comment by licy183** [comment]
`ninja` is distributed from PyPI, and it is used as dependencies in many python projects. By default, ninja-python-distribution runs ninja tests. Run `export CMAKE_ARGS="-DRUN_NINJA_TEST=FALSE"` to bypass it.

~~Although it's a bit inappropriate to mention some of TUR's stuff as I'm both a Termux member and a TUR member,~~ I also hosts a custom PyPI index for Termux at TUR, and it provides prebuilt `ninja` wheels. You could install it through `pip install ninja --extra-index-url https://termux-user-repository.github.io/pypi/`.

**Comment by Manamama** [comment]
I confirm that https://github.com/termux/termux-packages/issues/20184#issuecomment-2113105108 worked. 

Without it:
```
...   [402/402] ElideMiddle.ElideInTheMiddle
  failed
  FAILED: build_ninja-prefix/src/build_ninja-stamp/build_ninja-run_ninja_test_suite /data/data/com.termux/files/usr/tmp/pip-install-8_65s6b0/ninja_4c4a24e56d564b89a9af530866742e20/_skbuild/linux-aarch64-3.11/cmake-build/build_ninja-prefix/src/build_ninja-stamp/build_ninja-run_ninja_test_suite
  cd /data/data/com.termux/files/usr/tmp/pip-install-8_65s6b0/ninja_4c4a24e56d564b89a9af530866742e20/_skbuild/linux-aarch64-3.11/cmake-build/Ninja-build && /data/data/com.termux/files/usr/tmp/pip-install-8_65s6b0/ninja_4c4a24e56d564b89a9af530866742e20/_skbuild/linux-aarch64-3.11/cmake-build/Ninja-build/ninja_test && /data/data/com.termux/files/usr/bin/cmake -E touch /data/data/com.termux/files/usr/tmp/pip-install-8_65s6b0/ninja_4c4a24e56d564b89a9af530866742e20/_skbuild/linux-aarch64-3.11/cmake-build/build_ninja-prefix/src/build_ninja-stamp/build_ninja-run_ninja_test_suite
  ninja: build stopped: subcommand failed.
  Traceback (most recent call last):
    File "/data/data/com.termux/files/usr/tmp/pip-build-env-lkj6xios/overlay/lib/python3.11/site-packages/skbuild/setuptools_wrap.py", line 674, in setup
      cmkr.make(make_args, install_target=cmake_install_target, env=env)
    File "/data/data/com.termux/files/usr/tmp/pip-build-env-lkj6xios/overlay/lib/python3.11/site-packages/skbuild/cmaker.py", line 697, in make
      self.make_impl(clargs=clargs, config=config, source_dir=source_dir, install_target=install_target, env=env)
    File "/data/data/com.termux/files/usr/tmp/pip-build-env-lkj6xios/overlay/lib/python3.11/site-packages/skbuild/cmaker.py", line 742, in make_impl
      raise SKBuildError(msg)

  An error occurred while building with CMake.
    Command:
      /data/data/com.termux/files/usr/bin/cmake --build . --target install --config Release --
... 
```

afterwards:

```
~/downloads/opencv-python $ export CMAKE_ARGS="-DRUN_NINJA_TEST=FALSE"
pip install ninja
Looking in indexes: https://pypi.org/simple, https://download.pytorch.org/whl/cpu
Collecting ninja
  Using cached ninja-1.11.1.1.tar.gz (132 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: ninja
  Building wheel for ninja (pyproject.toml) ... done
  Created wheel for ninja: filename=ninja-1.11.1.1-cp311-cp311-linux_aarch64.whl size=152474 sha256=09801bb72e35925e1b6ac03f51f18997782c45a1106ec9451862f068a01fc7fc
  Stored in directory: /data/data/com.termux/files/home/.cache/pip/wheels/2c/51/74/96551d6311f19f633cd825382459851b8e04a9555253538f2b
Successfully built ninja
Installing collected packages: ninja
Successfully installed ninja-1.11.1.1
~/downloads/opencv-python $ 

```

Another probable trick would be  to add `--no-build-isolation` and use OS ninja (which always installs fine), but then e.g. OpenCV kvetches about that one for some reason and I do not want to muck in its tomls or setup.pys to check why so.
