### ISSUE TITLE
[Bug]: Jupyterlab is not opening 

### ISSUE THREAD

**Issue by JahidCodeVoyage** [termux/termux-packages#20272]
### Problem description

jupyter lab                                      Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/bin/jupyter-lab", line 5, in <module>                                   from jupyterlab.labapp import main                  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/jupyterlab/__init__.py", line 8, in <module>                                                     from .handlers.announcements import (               File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/jupyterlab/handlers/announcements.py", line 15, in <module>
    from jupyterlab_server.translation_utils import translator                                                File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/jupyterlab_server/__init__.py", line 6, in <module>
    from .app import LabServerApp                       File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/jupyterlab_server/app.py", line 10, in <module>
    from jupyter_server.extension.application import ExtensionApp, ExtensionAppJinjaMixin
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/jupyter_server/extension/application.py", line 17, in <module>
    from jupyter_server.serverapp import ServerApp
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/jupyter_server/serverapp.py", line 33, in <module>                                               import jupyter_client
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/jupyter_client/__init__.py", line 3, in <module>
    from .asynchronous import AsyncKernelClient
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/jupyter_client/asynchronous/__init__.py", line 1, in <module>
    from .client import AsyncKernelClient  # noqa
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/jupyter_client/asynchronous/client.py", line 8, in <module>
    import zmq.asyncio
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/zmq/__init__.py", line 52, in <module>
    from zmq import backend
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/zmq/backend/__init__.py", line 30, in <module>
    raise original_error from None
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/zmq/backend/__init__.py", line 25, in <module>
    _ns = select_backend(first)
          ^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/zmq/backend/select.py", line 31, in select_backend
    mod = import_module(name)
          ^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/zmq/backend/cython/__init__.py", line 6, in <module>
    from . import _zmq
ImportError: dlopen failed: cannot locate symbol "PyExc_ImportError" referenced by "/data/data/com.termux/files/usr/lib/python3.11/site-packages/zmq/backend/cython/_zmq.cpython-311.so"...

### What steps will reproduce the bug?

pip install jupyterlab

Then 
jupyter lab, 
command show this issue

### What is the expected behavior?

Jupyter lab should open but fails 

### System information

```shell
Termux Variables:
TERMUX_APK_RELEASE=GITHUB
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=21146
TERMUX_IS_DEBUGGABLE_BUILD=1
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
TERMUX__USER_ID=0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://ro.mirror.flokinet.net/termux/termux-main stable main
# tur-repo (sources.list.d/tur.list)
deb https://tur.kcubeterm.com tur-packages tur tur-on-device tur-continuous
Updatable packages:
All packages up to date
termux-tools version:
1.42.1
Android version:
11
Kernel build information:
Linux localhost 4.14.186+ #1 SMP PREEMPT Mon Apr 25 15:49:22 CST 2022 aarch64 Android
Device manufacturer:
realme
Device model:
RMX3195
LD Variables:
LD_LIBRARY_PATH=
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so
```

**Comment by twaik** [comment]
Superseeded by #20271
No need to open issue every time you have problems with the same package. It is enough to update the existing issue (still opened btw).
Most of problems `cannot locate symbol ... referenced by` cause by partial update which is not supported.
First of all try `pkg update` and check if the problem is still reproducible.

**Comment by licy183** [comment]
Try `LDFLAGS=-lpython3.11 pip install pyzmq --force-reinstall --no-cache-dir`.

**Comment by JahidCodeVoyage** [comment]
> Try `LDFLAGS=-lpython3.11 pip install pyzmq --force-reinstall --no-cache-dir`.

Worked. Thanks 👍
