### ISSUE TITLE
error : sentencepiece python pip 

### ISSUE THREAD

**Issue by shaheen-coder** [termux/termux-packages#20327]
### Problem description

```
LDFLAGS=-llog pip install sentencepiece 
```

```                                                                                                Collecting sentencepiece
  Using cached sentencepiece-0.2.0.tar.gz (2.6 MB)
  Installing build dependencies ... done                                                                                                          Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done                                                                                                  Building wheels for collected packages: sentencepiece
  Building wheel for sentencepiece (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for sentencepiece (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [78 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.linux-aarch64-cpython-311
      creating build/lib.linux-aarch64-cpython-311/sentencepiece
      copying src/sentencepiece/__init__.py -> build/lib.linux-aarch64-cpython-311/sentencepiece
      copying src/sentencepiece/_version.py -> build/lib.linux-aarch64-cpython-311/sentencepiece
      copying src/sentencepiece/sentencepiece_model_pb2.py -> build/lib.linux-aarch64-cpython-311/sentencepiece
      copying src/sentencepiece/sentencepiece_pb2.py -> build/lib.linux-aarch64-cpython-311/sentencepiece
      running build_ext
      Package sentencepiece was not found in the pkg-config search path.
      Perhaps you should add the directory containing `sentencepiece.pc'
      to the PKG_CONFIG_PATH environment variable
      No package 'sentencepiece' found
      ./build_bundled.sh: 21: cmake: not found
      ./build_bundled.sh: 22: cmake: not found
      Traceback (most recent call last):
        File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 251, in build_wheel
          return _build_backend().build_wheel(wheel_directory, config_settings,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-ev_jk5bd/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 410, in build_wheel
          return self._build_with_temp_dir(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-ev_jk5bd/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 395, in _build_with_temp_dir
          self.run_setup()
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-ev_jk5bd/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 487, in run_setup
          super().run_setup(setup_script=setup_script)
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-ev_jk5bd/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 169, in <module>
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-ev_jk5bd/overlay/lib/python3.11/site-packages/setuptools/__init__.py", line 103, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-ev_jk5bd/overlay/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 184, in setup
          return run_commands(dist)
                 ^^^^^^^^^^^^^^^^^^
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-ev_jk5bd/overlay/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 200, in run_commands
          dist.run_commands()
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-ev_jk5bd/overlay/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-ev_jk5bd/overlay/lib/python3.11/site-packages/setuptools/dist.py", line 968, in run_command
          super().run_command(command)
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-ev_jk5bd/overlay/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-ev_jk5bd/normal/lib/python3.11/site-packages/wheel/bdist_wheel.py", line 368, in run
          self.run_command("build")
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-ev_jk5bd/overlay/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
          self.distribution.run_command(command)
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-ev_jk5bd/overlay/lib/python3.11/site-packages/setuptools/dist.py", line 968, in run_command
          super().run_command(command)
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-ev_jk5bd/overlay/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-ev_jk5bd/overlay/lib/python3.11/site-packages/setuptools/_distutils/command/build.py", line 132, in run
          self.run_command(cmd_name)
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-ev_jk5bd/overlay/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
          self.distribution.run_command(command)
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-ev_jk5bd/overlay/lib/python3.11/site-packages/setuptools/dist.py", line 968, in run_command
          super().run_command(command)
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-ev_jk5bd/overlay/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-ev_jk5bd/overlay/lib/python3.11/site-packages/setuptools/command/build_ext.py", line 91, in run
          _build_ext.run(self)
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-ev_jk5bd/overlay/lib/python3.11/site-packages/setuptools/_distutils/command/build_ext.py", line 359, in run
          self.build_extensions()
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-ev_jk5bd/overlay/lib/python3.11/site-packages/setuptools/_distutils/command/build_ext.py", line 479, in build_extensions
          self._build_extensions_serial()
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-ev_jk5bd/overlay/lib/python3.11/site-packages/setuptools/_distutils/command/build_ext.py", line 505, in _build_extensions_serial
          self.build_extension(ext)
        File "<string>", line 87, in build_extension
        File "/data/data/com.termux/files/usr/lib/python3.11/subprocess.py", line 413, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['./build_bundled.sh', '0.2.0']' returned non-zero exit status 127.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for sentencepiece
Failed to build sentencepiece
ERROR: Could not build wheels for sentencepiece, which is required to install pyproject.toml-based projects
```

### What steps will reproduce the bug?

idk

### System information

```shell
Termux Variables:
TERMUX_APK_RELEASE=F_DROID
TERMUX_APP_PACKAGE_MANAGER=apt                                                                                                                  TERMUX_APP_PID=16802
TERMUX_IS_DEBUGGABLE_BUILD=0
TERMUX_MAIN_PACKAGE_FORMAT=debian                                                                                                               TERMUX_VERSION=0.118.0
TERMUX__USER_ID=0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://packages-cf.termux.dev/apt/termux-main stable main
# x11-repo (sources.list.d/x11.list)
deb https://packages-cf.termux.dev/apt/termux-x11 x11 main
Updatable packages:
All packages up to date
termux-tools version:
1.42.1
Android version:
12
Kernel build information:
Linux localhost 4.19.191-perf-01022-gec293e668c0c #1 SMP PREEMPT Fri Mar 10 18:54:33 CST 2023 aarch64 Android
Device manufacturer:
Xiaomi
Device model:
22120RN86G
LD Variables:
LD_LIBRARY_PATH=
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so
```

**Comment by Grimler91** [comment]
> /build_bundled.sh: 21: cmake: not found

Install cmake

**Comment by shaheen-coder** [comment]
even after installed cmake 

```
LDFLAGS=-llog pip install sentencepiece
Collecting sentencepiece
  Using cached sentencepiece-0.2.0.tar.gz (2.6 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: sentencepiece
  Building wheel for sentencepiece (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for sentencepiece (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [159 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.linux-aarch64-cpython-311
      creating build/lib.linux-aarch64-cpython-311/sentencepiece
      copying src/sentencepiece/__init__.py -> build/lib.linux-aarch64-cpython-311/sentencepiece
      copying src/sentencepiece/_version.py -> build/lib.linux-aarch64-cpython-311/sentencepiece
      copying src/sentencepiece/sentencepiece_model_pb2.py -> build/lib.linux-aarch64-cpython-311/sentencepiece
      copying src/sentencepiece/sentencepiece_pb2.py -> build/lib.linux-aarch64-cpython-311/sentencepiece
      running build_ext
      Package sentencepiece was not found in the pkg-config search path.
      Perhaps you should add the directory containing `sentencepiece.pc'
      to the PKG_CONFIG_PATH environment variable
      No package 'sentencepiece' found
      CMake Deprecation Warning at CMakeLists.txt:15 (cmake_minimum_required):
        Compatibility with CMake < 3.5 will be removed from a future version of
        CMake.

        Update the VERSION argument <min> value or use a ...<max> suffix to tell
        CMake that the project does not need compatibility with older versions.


      -- VERSION: 0.2.0
      -- The C compiler identification is Clang 18.1.6
      -- The CXX compiler identification is Clang 18.1.6
      -- Detecting C compiler ABI info
      -- Detecting C compiler ABI info - done
      -- Check for working C compiler: /data/data/com.termux/files/usr/bin/cc - skipped
      -- Detecting C compile features
      -- Detecting C compile features - done
      -- Detecting CXX compiler ABI info
      -- Detecting CXX compiler ABI info - done
      -- Check for working CXX compiler: /data/data/com.termux/files/usr/bin/c++ - skipped
      -- Detecting CXX compile features
      -- Detecting CXX compile features - done
      -- Performing Test CMAKE_HAVE_LIBC_PTHREAD
      -- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
      -- Looking for pthread_create in pthreads
      -- Looking for pthread_create in pthreads - not found
      -- Looking for pthread_create in pthread
      -- Looking for pthread_create in pthread - found
      -- Found Threads: TRUE
      -- Not Found TCMalloc: TCMALLOC_LIB-NOTFOUND
      -- Found atomic: /data/data/com.termux/files/usr/lib/libatomic.a
      -- Configuring done (5.6s)
      -- Generating done (0.1s)
      -- Build files have been written to: /data/data/com.termux/files/usr/tmp/pip-install-xsidrxv1/sentencepiece_946c2a24bd2242f1b3955d376bbe895f/build
      [  1%] Building CXX object src/CMakeFiles/sentencepiece_train-static.dir/builder.cc.o
      [  3%] Building CXX object src/CMakeFiles/sentencepiece-static.dir/__/third_party/protobuf-lite/arena.cc.o
      [  6%] Building CXX object src/CMakeFiles/sentencepiece_train-static.dir/trainer_interface.cc.o
      [  8%] Building CXX object src/CMakeFiles/sentencepiece_train-static.dir/trainer_factory.cc.o
      [ 11%] Building CXX object src/CMakeFiles/sentencepiece-static.dir/__/third_party/protobuf-lite/bytestream.cc.o
      [  9%] Building CXX object src/CMakeFiles/sentencepiece_train-static.dir/unigram_model_trainer.cc.o
      [  8%] Building CXX object src/CMakeFiles/sentencepiece-static.dir/__/third_party/protobuf-lite/arenastring.cc.o
      [ 12%] Building CXX object src/CMakeFiles/sentencepiece_train-static.dir/unicode_script.cc.o
      [ 14%] Building CXX object src/CMakeFiles/sentencepiece-static.dir/__/third_party/protobuf-lite/coded_stream.cc.o
      [ 16%] Building CXX object src/CMakeFiles/sentencepiece-static.dir/__/third_party/protobuf-lite/common.cc.o
      [ 17%] Building CXX object src/CMakeFiles/sentencepiece-static.dir/__/third_party/protobuf-lite/extension_set.cc.o
      [ 19%] Building CXX object src/CMakeFiles/sentencepiece-static.dir/__/third_party/protobuf-lite/generated_enum_util.cc.o
      [ 20%] Building CXX object src/CMakeFiles/sentencepiece-static.dir/__/third_party/protobuf-lite/generated_message_table_driven_lite.cc.o
      /data/data/com.termux/files/usr/tmp/pip-install-xsidrxv1/sentencepiece_946c2a24bd2242f1b3955d376bbe895f/sentencepiece/src/builder.cc:47:15: warning: unused variable 'kMaxUnicode' [-Wunused-const-variable]
         47 | constexpr int kMaxUnicode = 0x10FFFF;
            |               ^~~~~~~~~~~
      /data/data/com.termux/files/usr/tmp/pip-install-xsidrxv1/sentencepiece_946c2a24bd2242f1b3955d376bbe895f/sentencepiece/src/builder.cc:49:23: warning: unused variable 'kDefaultNormalizerName' [-Wunused-const-variable]
         49 | static constexpr char kDefaultNormalizerName[] = "nfkc";
            |                       ^~~~~~~~~~~~~~~~~~~~~~
      [ 22%] Building CXX object src/CMakeFiles/sentencepiece-static.dir/__/third_party/protobuf-lite/generated_message_util.cc.o
      [ 24%] Building CXX object src/CMakeFiles/sentencepiece-static.dir/__/third_party/protobuf-lite/implicit_weak_message.cc.o
      [ 25%] Building CXX object src/CMakeFiles/sentencepiece-static.dir/__/third_party/protobuf-lite/int128.cc.o
      [ 27%] Building CXX object src/CMakeFiles/sentencepiece-static.dir/__/third_party/protobuf-lite/io_win32.cc.o
      [ 29%] Building CXX object src/CMakeFiles/sentencepiece-static.dir/__/third_party/protobuf-lite/message_lite.cc.o
      [ 30%] Building CXX object src/CMakeFiles/sentencepiece-static.dir/__/third_party/protobuf-lite/parse_context.cc.o
      [ 32%] Building CXX object src/CMakeFiles/sentencepiece-static.dir/__/third_party/protobuf-lite/repeated_field.cc.o
      2 warnings generated.
      [ 33%] Building CXX object src/CMakeFiles/sentencepiece_train-static.dir/word_model_trainer.cc.o
      [ 35%] Building CXX object src/CMakeFiles/sentencepiece_train-static.dir/char_model_trainer.cc.o
      [ 37%] Building CXX object src/CMakeFiles/sentencepiece-static.dir/__/third_party/protobuf-lite/status.cc.o
      [ 38%] Building CXX object src/CMakeFiles/sentencepiece-static.dir/__/third_party/protobuf-lite/statusor.cc.o
      [ 40%] Building CXX object src/CMakeFiles/sentencepiece-static.dir/__/third_party/protobuf-lite/stringpiece.cc.o
      [ 41%] Building CXX object src/CMakeFiles/sentencepiece-static.dir/__/third_party/protobuf-lite/stringprintf.cc.o
      [ 43%] Building CXX object src/CMakeFiles/sentencepiece-static.dir/__/third_party/protobuf-lite/structurally_valid.cc.o
      [ 45%] Building CXX object src/CMakeFiles/sentencepiece_train-static.dir/bpe_model_trainer.cc.o
      [ 46%] Building CXX object src/CMakeFiles/sentencepiece-static.dir/__/third_party/protobuf-lite/strutil.cc.o
      [ 48%] Building CXX object src/CMakeFiles/sentencepiece-static.dir/__/third_party/protobuf-lite/time.cc.o
      [ 50%] Building CXX object src/CMakeFiles/sentencepiece-static.dir/__/third_party/protobuf-lite/wire_format_lite.cc.o
      [ 51%] Building CXX object src/CMakeFiles/sentencepiece-static.dir/__/third_party/protobuf-lite/zero_copy_stream.cc.o
      [ 53%] Building CXX object src/CMakeFiles/sentencepiece_train-static.dir/sentencepiece_trainer.cc.o
      [ 54%] Building CXX object src/CMakeFiles/sentencepiece_train-static.dir/pretokenizer_for_training.cc.o
      [ 56%] Building CXX object src/CMakeFiles/sentencepiece-static.dir/__/third_party/protobuf-lite/zero_copy_stream_impl.cc.o
      [ 58%] Building CXX object src/CMakeFiles/sentencepiece-static.dir/__/third_party/protobuf-lite/zero_copy_stream_impl_lite.cc.o
      [ 59%] Building CXX object src/CMakeFiles/sentencepiece-static.dir/builtin_pb/sentencepiece.pb.cc.o
      [ 61%] Building CXX object src/CMakeFiles/sentencepiece-static.dir/builtin_pb/sentencepiece_model.pb.cc.o
      [ 62%] Building CXX object src/CMakeFiles/sentencepiece-static.dir/bpe_model.cc.o
      [ 64%] Building CXX object src/CMakeFiles/sentencepiece-static.dir/char_model.cc.o
      [ 66%] Building CXX object src/CMakeFiles/sentencepiece-static.dir/error.cc.o
      /data/data/com.termux/files/usr/tmp/pip-install-xsidrxv1/sentencepiece_946c2a24bd2242f1b3955d376bbe895f/sentencepiece/src/sentencepiece_trainer.cc:207:16: warning: 'done' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
        207 |   virtual bool done() const { return iter_ == end_; }
            |                ^
      /data/data/com.termux/files/usr/tmp/pip-install-xsidrxv1/sentencepiece_946c2a24bd2242f1b3955d376bbe895f/sentencepiece/src/sentencepiece_trainer.h:52:16: note: overridden virtual function is here
         52 |   virtual bool done() const = 0;
            |                ^
      [ 67%] Building CXX object src/CMakeFiles/sentencepiece-static.dir/filesystem.cc.o
      [ 69%] Building CXX object src/CMakeFiles/sentencepiece-static.dir/model_factory.cc.o
      [ 70%] Building CXX object src/CMakeFiles/sentencepiece-static.dir/model_interface.cc.o
      [ 72%] Building CXX object src/CMakeFiles/sentencepiece-static.dir/normalizer.cc.o
      [ 74%] Building CXX object src/CMakeFiles/sentencepiece-static.dir/sentencepiece_processor.cc.o
      [ 75%] Building CXX object src/CMakeFiles/sentencepiece-static.dir/unigram_model.cc.o
      [ 77%] Building CXX object src/CMakeFiles/sentencepiece-static.dir/util.cc.o
      [ 79%] Building CXX object src/CMakeFiles/sentencepiece-static.dir/word_model.cc.o
      [ 80%] Building CXX object src/CMakeFiles/sentencepiece-static.dir/__/third_party/absl/flags/flag.cc.o
      1 warning generated.
      [ 82%] Linking CXX static library libsentencepiece_train.a
      [ 82%] Built target sentencepiece_train-static
      [ 83%] Linking CXX static library libsentencepiece.a
      [ 83%] Built target sentencepiece-static
      [ 85%] Building CXX object src/CMakeFiles/spm_decode.dir/spm_decode_main.cc.o
      [ 87%] Building CXX object src/CMakeFiles/spm_encode.dir/spm_encode_main.cc.o
      [ 88%] Building CXX object src/CMakeFiles/spm_export_vocab.dir/spm_export_vocab_main.cc.o
      [ 91%] Building CXX object src/CMakeFiles/spm_train.dir/spm_train_main.cc.o
      [ 91%] Building CXX object src/CMakeFiles/spm_normalize.dir/spm_normalize_main.cc.o
      [ 93%] Linking CXX executable spm_normalize
      [ 93%] Built target spm_normalize
      [ 95%] Linking CXX executable spm_train
      [ 95%] Built target spm_train
      [ 96%] Linking CXX executable spm_export_vocab
      [ 96%] Built target spm_export_vocab
      [ 98%] Linking CXX executable spm_decode
      [ 98%] Built target spm_decode
      [100%] Linking CXX executable spm_encode
      [100%] Built target spm_encode
      Install the project...
      -- Install configuration: "RelWithDebInfo"
      -- Installing: /data/data/com.termux/files/usr/tmp/pip-install-xsidrxv1/sentencepiece_946c2a24bd2242f1b3955d376bbe895f/build/root/lib/pkgconfig/sentencepiece.pc
      -- Installing: /data/data/com.termux/files/usr/tmp/pip-install-xsidrxv1/sentencepiece_946c2a24bd2242f1b3955d376bbe895f/build/root/lib/libsentencepiece.a
      -- Installing: /data/data/com.termux/files/usr/tmp/pip-install-xsidrxv1/sentencepiece_946c2a24bd2242f1b3955d376bbe895f/build/root/lib/libsentencepiece_train.a
      -- Installing: /data/data/com.termux/files/usr/tmp/pip-install-xsidrxv1/sentencepiece_946c2a24bd2242f1b3955d376bbe895f/build/root/bin/spm_encode
      -- Installing: /data/data/com.termux/files/usr/tmp/pip-install-xsidrxv1/sentencepiece_946c2a24bd2242f1b3955d376bbe895f/build/root/bin/spm_decode
      -- Installing: /data/data/com.termux/files/usr/tmp/pip-install-xsidrxv1/sentencepiece_946c2a24bd2242f1b3955d376bbe895f/build/root/bin/spm_normalize
      -- Installing: /data/data/com.termux/files/usr/tmp/pip-install-xsidrxv1/sentencepiece_946c2a24bd2242f1b3955d376bbe895f/build/root/bin/spm_train
      -- Installing: /data/data/com.termux/files/usr/tmp/pip-install-xsidrxv1/sentencepiece_946c2a24bd2242f1b3955d376bbe895f/build/root/bin/spm_export_vocab
      -- Installing: /data/data/com.termux/files/usr/tmp/pip-install-xsidrxv1/sentencepiece_946c2a24bd2242f1b3955d376bbe895f/build/root/include/sentencepiece_trainer.h
      -- Installing: /data/data/com.termux/files/usr/tmp/pip-install-xsidrxv1/sentencepiece_946c2a24bd2242f1b3955d376bbe895f/build/root/include/sentencepiece_processor.h
      ## cflags=-std=c++17 -I./build/root/include -Wl,-strip-all
      ## libs=./build/root/lib/libsentencepiece.a ./build/root/lib/libsentencepiece_train.a -Wl,-strip-all -Wl,-Bsymbolic
      building 'sentencepiece._sentencepiece' extension
      creating build/temp.linux-aarch64-cpython-311
      creating build/temp.linux-aarch64-cpython-311/src
      creating build/temp.linux-aarch64-cpython-311/src/sentencepiece
      aarch64-linux-android-clang -DNDEBUG -g -fwrapv -O3 -Wall -fstack-protector-strong -O3 -fstack-protector-strong -O3 -fPIC -I/data/data/com.termux/files/usr/include/python3.11 -c src/sentencepiece/sentencepiece_wrap.cxx -o build/temp.linux-aarch64-cpython-311/src/sentencepiece/sentencepiece_wrap.o -std=c++17 -I./build/root/include -Wl,-strip-all
      aarch64-linux-android-clang: warning: -Wl,-strip-all: 'linker' input unused [-Wunused-command-line-argument]
      src/sentencepiece/sentencepiece_wrap.cxx:3349:13: warning: unused function 'ConvertToUnicodeSpans<sentencepiece::ImmutableNBestSentencePieceText>' [-Wunused-function]
       3349 | inline void ConvertToUnicodeSpans(sentencepiece::ImmutableNBestSentencePieceText *proto) {
            |             ^~~~~~~~~~~~~~~~~~~~~
      1 warning generated.
      aarch64-linux-android-clang++ -shared -L/data/data/com.termux/files/usr/lib -Wl,-rpath=/data/data/com.termux/files/usr/lib -fopenmp -static-openmp -fno-openmp-implicit-rpath -Wl,--enable-new-dtags -Wl,--as-needed -Wl,-z,relro,-z,now -Wl,--no-as-needed,-landroid-support,--as-needed -L/home/builder/.termux-build/_cache/android-r26b-api-24-v3/sysroot/usr/lib -L/data/data/com.termux/files/usr/lib -Wl,-rpath=/data/data/com.termux/files/usr/lib -fopenmp -static-openmp -fno-openmp-implicit-rpath -Wl,--enable-new-dtags -Wl,--as-needed -Wl,-z,relro,-z,now -Wl,--no-as-needed,-landroid-support,--as-needed -L/home/builder/.termux-build/_cache/android-r26b-api-24-v3/sysroot/usr/lib -llog build/temp.linux-aarch64-cpython-311/src/sentencepiece/sentencepiece_wrap.o -L/data/data/com.termux/files/usr/lib -lpython3.11 -o build/lib.linux-aarch64-cpython-311/sentencepiece/_sentencepiece.cpython-311.so ./build/root/lib/libsentencepiece.a ./build/root/lib/libsentencepiece_train.a -Wl,-strip-all -Wl,-Bsymbolic
      aarch64-linux-android-clang++: error: unknown argument: '-fno-openmp-implicit-rpath'
      aarch64-linux-android-clang++: error: unknown argument: '-fno-openmp-implicit-rpath'
      error: command '/data/data/com.termux/files/usr/bin/aarch64-linux-android-clang++' failed with exit code 1
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for sentencepiece
Failed to build sentencepiece
ERROR: Could not build wheels for sentencepiece, which is required to install pyproject.toml-based projects
```

**Comment by twaik** [comment]
And this log already shows another problem. It is not same.
Use workaround from #20039
