### ISSUE TITLE
[Bug]: pygame setup

### ISSUE THREAD

**Issue by mablue** [termux/termux-packages#20422]
### Problem description

Can't setup pygame

### Steps to reproduce the behavior.

```
~/.../!/!DEV $ python -m pip install -U pygame==2.5.2 --user
Collecting pygame==2.5.2
  Using cached pygame-2.5.2.tar.gz (15.8 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [51 lines of output]
      Skipping Cython compilation


      WARNING, No "Setup" File Exists, Running "buildconfig/config.py"
      Using UNIX configuration...

      /data/data/com.termux/files/usr/bin/sh: 1: dpkg-architecture: not found
      gcc: error: unsupported option '-print-multiarch'
      gcc: error: no input files
      /data/data/com.termux/files/usr/bin/sh: 1: sdl2-config: not found
      /data/data/com.termux/files/usr/bin/sh: 1: sdl2-config: not found
      /data/data/com.termux/files/usr/bin/sh: 1: sdl2-config: not found

      Hunting dependencies...

      ---
      For help with compilation see:
          https://www.pygame.org/wiki/Compilation
      To contribute to pygame development see:
          https://www.pygame.org/contribute.html
      ---

      Traceback (most recent call last):
        File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-_gta9r4x/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-_gta9r4x/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-_gta9r4x/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 487, in run_setup
          super().run_setup(setup_script=setup_script)
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-_gta9r4x/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 409, in <module>
        File "/data/data/com.termux/files/usr/tmp/pip-install-669gjj74/pygame_7202b61eda5a4876a7705f5efcf05509/buildconfig/config.py", line 231, in main
          deps = CFG.main(**kwds, auto_config=auto)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/data/data/com.termux/files/usr/tmp/pip-install-669gjj74/pygame_7202b61eda5a4876a7705f5efcf05509/buildconfig/config_unix.py", line 218, in main
          DependencyProg('SDL', 'SDL_CONFIG', 'sdl2-config', '2.0', ['sdl']),
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/data/data/com.termux/files/usr/tmp/pip-install-669gjj74/pygame_7202b61eda5a4876a7705f5efcf05509/buildconfig/config_unix.py", line 43, in __init__
          self.ver = config[0].strip()
                     ~~~~~~^^^
      IndexError: list index out of range
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
~/.../!/!DEV $
```

### System information

* Termux application version: 118
* Android OS version: 12
* Device model: xiaomi 12

**Comment by mablue** [comment]
I think I shoud test again with your steps.Thanks
