### ISSUE TITLE
Error importing matplotlib.pyplot 

### ISSUE THREAD

**Issue by conjectured1729** [termux/termux-packages#2049]
Here is the log:

import matplotlib.pyplot as plt              Traceback (most recent call last):                 File "<stdin>", line 1, in <module>
  File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/matplotlib/pyplot.py", line 116, in <module>                                       _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()                    File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/matplotlib/backends/__init__.py", line 60, in pylab_setup
    [backend_name], 0)
  File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/matplotlib/backends/backend_gtk3agg.py", line 9, in <module>                       from . import backend_agg, backend_gtk3
  File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/matplotlib/backends/backend_gtk3.py", line 9, in <module>
    import gi
  File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/gi/__init__.py", line 39
    print url
            ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(t url)?

**Comment by Grimler91** [comment]
I'm guessing that you installed it from source with `python setup.py install`, it looks like you've installed the python2 version. Try installing with python2 Instead, or install with pip (that works with both versions).

You will run into problems when you've installed it correctly due to the default backend being gtk. See this issue for instructions how to solve that: https://github.com/termux/termux-packages/issues/1629
