### ISSUE TITLE
Scikit 1.5.1 installation  error 

### ISSUE THREAD

**Issue by Chuanhuan** [termux/termux-packages#20905]
I'm struggling with scikit learn package installation. 
I try [this](https://github.com/termux/termux-packages/issues/19681) and `pip install scikit-learn --no-build-isolation`
My error as below 

```
Collecting scikit-learn                                Using cached scikit_learn-1.5.1.tar.gz (7.0 MB)      Preparing metadata (pyproject.toml) ... error        error: subprocess-exited-with-error                                                                       × Preparing metadata (pyproject.toml) did not run successfully.                                           │ exit code: 1                                       ╰─> [135 lines of output]                                + meson setup /data/data/com.termux/files/usr/tmp/pip-install-7a6nj7mp/scikit-learn_0801e56a3fa344e599d8d2862259dd8e /data/data/com.termux/files/usr/tmp/pip-install-7a6nj7mp/scikit-learn_0801e56a3fa344e599d8d2862259dd8e/.mesonpy-6s6_di0n -Dbuildtype=release -Db_ndebug=if-release -Db_vscrt=md --native-file=/data/data/com.termux/files/usr/tmp/pip-install-7a6nj7mp/scikit-learn_0801e56a3fa344e599d8d2862259dd8e/.mesonpy-6s6_di0n/meson-python-native-file.ini                     The Meson build system                               Version: 1.2.1                                       Source dir: /data/data/com.termux/files/usr/tmp/pip-install-7a6nj7mp/scikit-learn_0801e56a3fa344e599d8d2862259dd8e                                             Build dir: /data/data/com.termux/files/usr/tmp/pip-install-7a6nj7mp/scikit-learn_0801e56a3fa344e599d8d2862259dd8e/.mesonpy-6s6_di0n                            Build type: native build                             Project name: scikit-learn
      Project version: 1.5.1                               C compiler for the host machine: cc (clang 18.1.8 "clang version 18.1.8")                                 C linker for the host machine: cc ld.lld 18.1.8
      C++ compiler for the host machine: c++ (clang 18.1.8 "clang version 18.1.8")                              C++ linker for the host machine: c++ ld.lld 18.1.8                                                        Cython compiler for the host machine: cython (cython 3.0.5)                                               Host machine cpu family: aarch64                     Host machine cpu: aarch64                            Compiler for C supports arguments -Wno-unused-but-set-variable: YES                                       Compiler for C supports arguments -Wno-unused-function: YES                                               Compiler for C supports arguments -Wno-conversion: YES                                                    Compiler for C supports arguments -Wno-misleading-indentation: YES                                        Library m found: YES                                 Program python found: YES (/data/data/com.termux/files/usr/bin/python3.11)                                Run-time dependency OpenMP for c found: NO (tried system)                                                 ../sklearn/meson.build:88: WARNING:                                  ***********                                          * WARNING *                                          ***********
                                                           It seems that scikit-learn cannot be built with OpenMP.                                             
      - Make sure you have followed the installation instructions:
                                                               https://scikit-learn.org/dev/developers/advanced_installation.html                              
      - If your compiler supports OpenMP but you still see this                                                   message, please submit a bug report at:                                                                     https://github.com/scikit-learn/scikit-learn/issues                                                                                                        - The build will continue with OpenMP-based parallelism                                                     disabled. Note however that some estimators will run in                                                   sequential mode instead of leveraging thread-based                                                        parallelism.
                                                                               ***                                                                                   Found pkg-config: /data/data/com.termux/files/usr/bin/pkg-config (0.29.2)                                 Run-time dependency python found: YES 3.11           Build targets in project: 111                  
      scikit-learn 1.5.1                             
        User defined options                                   Native files: /data/data/com.termux/files/usr/tmp/pip-install-7a6nj7mp/scikit-learn_0801e56a3fa344e599d8d2862259dd8e/.mesonpy-6s6_di0n/meson-python-native-file.ini                                                 buildtype   : release
          b_ndebug    : if-release                             b_vscrt     : md                                                                                      Found ninja-1.12.1 at /data/data/com.termux/files/usr/bin/ninja                                                                                                Generating targets:   0%|          | 0/111 eta ?
      Generating targets:  17%|█▋        | 19/111 eta 00:01                                                                                                                                                               Writing build.ninja:   0%|          | 0/346 eta ?
                                                           + /data/data/com.termux/files/usr/bin/ninja
      [1/249] Generating sklearn/_loss/_loss.pxd with a custom command                                          [2/249] Generating sklearn/utils/__init__.py with a custom command                                        [3/249] Generating sklearn/__init__.py with a custom command                                              [4/249] Generating sklearn/utils/_cython_blas.pxd with a custom command                                   [5/249] Generating sklearn/utils/_random.pxd with a custom command                                        [6/249] Generating sklearn/utils/_openmp_helpers.pxd with a custom command                                [7/249] Generating sklearn/utils/_heap.pxd with a custom command                                          [8/249] Generating sklearn/utils/_typedefs.pxd with a custom command                                      [9/249] Generating sklearn/utils/_seq_dataset_pxd with a custom command                                   [10/249] Generating sklearn/utils/_sorting.pxd with a custom command                                      [11/249] Generating sklearn/metrics/_dist_metrics_pxd with a custom command                               [12/249] Generating sklearn/metrics/__init__.py with a custom command                                     [13/249] Generating sklearn/utils/_weight_vector_pxd with a custom command
      [14/249] Generating sklearn/utils/_vector_sentinel.pxd with a custom command
      [15/249] Generating sklearn/metrics/_pairwise_distances_reduction/_argkmin_pxd with a custom command
      [16/249] Generating sklearn/metrics/_pairwise_distances_reduction/_radius_neighbors_pxd with a custom command                                                  [17/249] Generating sklearn/metrics/_pairwise_distances_reduction/__init__.py with a custom command       [18/249] Generating sklearn/metrics/_pairwise_distances_reduction/_datasets_pair_pxd with a custom command                                                     [19/249] Generating sklearn/metrics/_pairwise_distances_reduction/_middle_term_computer_pxd with a custom command
      [20/249] Generating sklearn/metrics/_pairwise_distances_reduction/_classmode.pxd with a custom command                                                         [21/249] Generating sklearn/metrics/_pairwise_distances_reduction/_base_pxd with a custom command
      [22/249] Generating sklearn/neighbors/_binary_tree_pxi with a custom command
      [23/249] Generating sklearn/linear_model/__init__.py with a custom command                                [24/249] Generating sklearn/linear_model/_sgd_fast.pxd with a custom command                              [25/249] Generating sklearn/_loss/_loss_pyx with a custom command                                         [26/249] Generating sklearn/utils/_seq_dataset_pyx with a custom command                                  [27/249] Generating sklearn/neighbors/_partition_nodes.pxd with a custom command                          [28/249] Generating sklearn/utils/_weight_vector_pyx with a custom command
      [29/249] Generating sklearn/neighbors/__init__.py with a custom command                                   [30/249] Generating sklearn/metrics/_pairwise_distances_reduction/_datasets_pair_pyx with a custom command                                                     [31/249] Generating sklearn/metrics/_dist_metrics_pyx with a custom command                               [32/249] Generating sklearn/metrics/_pairwise_distances_reduction/_base_pyx with a custom command         [33/249] Generating sklearn/metrics/_pairwise_distances_reduction/_argkmin_classmode_pyx with a custom command                                                 [34/249] Generating sklearn/metrics/_pairwise_distances_reduction/_argkmin_pyx with a custom command      [35/249] Generating sklearn/metrics/_pairwise_distances_reduction/_middle_term_computer_pyx with a custom command                                              [36/249] Generating sklearn/metrics/_pairwise_distances_reduction/_radius_neighbors_pyx with a custom command                                                  [37/249] Generating sklearn/neighbors/_ball_tree_pyx with a custom command                                [38/249] Generating sklearn/metrics/_pairwise_distances_reduction/_radius_neighbors_classmode_pyx with a custom command                                        [39/249] Generating sklearn/linear_model/_sgd_fast_pyx with a custom command                              [40/249] Generating sklearn/linear_model/_sag_fast_pyx with a custom command
      [41/249] Generating sklearn/neighbors/_kd_tree_pyx with a custom command                                  [42/249] Compiling Cython source /data/data/com.termux/files/usr/tmp/pip-install-7a6nj7mp/scikit-learn_0801e56a3fa344e599d8d2862259dd8e/sklearn/__check_build/_check_build.pyx
      [43/249] Compiling Cython source /data/data/com.termux/files/usr/tmp/pip-install-7a6nj7mp/scikit-learn_0801e56a3fa344e599d8d2862259dd8e/sklearn/utils/_openmp_helpers.pyx                                           [44/249] Compiling Cython source /data/data/com.termux/files/usr/tmp/pip-install-7a6nj7mp/scikit-learn_0801e56a3fa344e599d8d2862259dd8e/sklearn/utils/sparsefuncs_fast.pyx                                          FAILED: sklearn/utils/sparsefuncs_fast.cpython-311.so.p/sklearn/utils/sparsefuncs_fast.pyx.c              cython -M --fast-fail -3 '-X language_level=3' '-X boundscheck=False' '-X wraparound=False' '-X initializedcheck=False' '-X nonecheck=False' '-X cdivision=True' '-X profile=False' --include-dir /data/data/com.termux/files/usr/tmp/pip-install-7a6nj7mp/scikit-learn_0801e56a3fa344e599d8d2862259dd8e/.mesonpy-6s6_di0n /data/data/com.termux/files/usr/tmp/pip-install-7a6nj7mp/scikit-learn_0801e56a3fa344e599d8d2862259dd8e/sklearn/utils/sparsefuncs_fast.pyx -o sklearn/utils/sparsefuncs_fast.cpython-311.so.p/sklearn/utils/sparsefuncs_fast.pyx.c                                                                                                Error compiling Cython file:                         ------------------------------------------------------------                                              ...                                                      cdef __Pyx_memviewslice memslice                     cdef Py_ssize_t itemsize                             cdef bint dtype_signed                               cdef char kind
          itemsize = -1                                        cdef bint ___pyx_const int32_t_is_signed
                                 ^                         ------------------------------------------------------------                                        
      (tree fragment):19:27: Syntax error in C variable declaration                                             [45/249] Compiling Cython source /data/data/com.termux/files/usr/tmp/pip-install-7a6nj7mp/scikit-learn_0801e56a3fa344e599d8d2862259dd8e/sklearn/utils/murmurhash.pyx
      [46/249] Compiling Cython source /data/data/com.termux/files/usr/tmp/pip-install-7a6nj7mp/scikit-learn_0801e56a3fa344e599d8d2862259dd8e/sklearn/utils/_fast_dict.pyx                                                [47/249] Compiling Cython source /data/data/com.termux/files/usr/tmp/pip-install-7a6nj7mp/scikit-learn_0801e56a3fa344e599d8d2862259dd8e/sklearn/_isotonic.pyx                                                       [48/249] Compiling Cython source /data/data/com.termux/files/usr/tmp/pip-install-7a6nj7mp/scikit-learn_0801e56a3fa344e599d8d2862259dd8e/sklearn/utils/arrayfuncs.pyx                                                [49/249] Compiling Cython source /data/data/com.termux/files/usr/tmp/pip-install-7a6nj7mp/scikit-learn_0801e56a3fa344e599d8d2862259dd8e/sklearn/utils/_typedefs.pyx                                                 [50/249] Compiling Cython source /data/data/com.termux/files/usr/tmp/pip-install-7a6nj7mp/scikit-learn_0801e56a3fa344e599d8d2862259dd8e/sklearn/utils/_random.pyx                                                   [51/249] Compiling Cython source /data/data/com.termux/files/usr/tmp/pip-install-7a6nj7mp/scikit-learn_0801e56a3fa344e599d8d2862259dd8e/sklearn/utils/_cython_blas.pyx                                              [52/249] Compiling Cython source sklearn/_loss/_loss.pyx
      ninja: build stopped: subcommand failed.             [end of output]
                                                       note: This error originates from a subprocess, and is likely not a problem with pip.                    error: metadata-generation-failed                                                                         × Encountered error while generating package metadata.                                                    ╰─> See above for output.                                                                                 note: This is an issue with the package mentioned above, not pip.                                         hint: See above for details.
```

**Comment by licy183** [comment]
It seems that the version of cython is too new. Try `pip install cython<3` before installing it.

**Comment by Chuanhuan** [comment]
> It seems that the version of cython is too new. Try `pip install cython<3` before installing it.

Thx for replying. I did downgrade but no luck. 
So, I upgraded package and it works. 

```
pip install cython==3.0.10 
pip install scikit-learn --no-build-isolation
```
But `python -c 'import sklearn;print(sklearn.__version__)'` , I got another error message 

```
Traceback (most recent call last):                     File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/sklearn/__check_build/__init__.py", line 49, in <module>                                      from ._check_build import check_build  # noqa        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^            ImportError: dlopen failed: cannot locate symbol "PyExc_ImportError" referenced by "/data/data/com.termux/files/usr/lib/python3.11/site-packages/sklearn/__check_build/_check_build.cpython-311.so"...                                                                   During handling of the above exception, another exception occurred:                                                                                            Traceback (most recent call last):                     File "<string>", line 1, in <module>                 File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/sklearn/__init__.py", line 80, in <module>                                                    from . import (                                    File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/sklearn/__check_build/__init__.py", line 51, in <module>                                      raise_build_error(e)                               File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/sklearn/__check_build/__init__.py", line 32, in raise_build_error                             raise ImportError(                               ImportError: dlopen failed: cannot locate symbol "PyExc_ImportError" referenced by "/data/data/com.termux/files/usr/lib/python3.11/site-packages/sklearn/__check_build/_check_build.cpython-311.so"...              ___________________________________________________________________________                               Contents of /data/data/com.termux/files/usr/lib/python3.11/site-packages/sklearn/__check_build:           _check_build.cpython-311.so__init__.py               _check_build.pyx                                     meson.build               __pycache__                ___________________________________________________________________________                               It seems that scikit-learn has not been built correctly.                                                                                                       If you have installed scikit-learn from source, please do not forget                                      to build the package before using it: run `python setup.py install` or                                    `make` in the source directory.                                                                           If you have used an installer, please check that it is suited for your                                    Python version, your operating system and your platform.
```

**Comment by licy183** [comment]
Run `export LDFLAGS="-lpython3.11"` before install `scikit-learn`.

**Comment by Chuanhuan** [comment]
> Run `export LDFLAGS="-lpython3.11"` before install `scikit-learn`.

Thx, now I can import sklearn!!!
