### ISSUE TITLE
[Bug]: Qt6 Unknown CMake command "qt6_android_apply_arch_suffix"

### ISSUE THREAD

**Issue by DuilioPerez** [termux/termux-packages#21004]
### Problem description

Hello, I'm trying to port a KDE's game for Termux, and I've compiled some KF6 modules that aren't in the Termux's repos. But when I try to compile kf6-kiconthemes cmake can't find that macro. Acording to Qt documentation, "qt6_android_apply_arch_suffix" was introduced in Qt 6 [link here](https://doc.qt.io/qt-6/qt-android-apply-arch-suffix.html).
But when I try to compile I have the next error:
cmake -S . -B build -DQT_REQUIRE_HOST_PATH_CHECK=NO -DQt6HostInfo_DIR=/data/data/com.termux/files/usr/lib/cmake/Qt6HostInfo/
-- The C compiler identification is Clang 18.1.8
-- The CXX compiler identification is Clang 18.1.8
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /data/data/com.termux/files/usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info                                                                                      -- Detecting CXX compiler ABI info - done                                                                               -- Check for working CXX compiler: /data/data/com.termux/files/usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
--

-- Check if compiler accepts -pthread
-- Check if compiler accepts -pthread - yes
-- Installing in the same prefix as Qt, adopting their path scheme.
-- Performing Test HAVE_STDATOMIC
-- Performing Test HAVE_STDATOMIC - Success
-- Found WrapAtomic: TRUE
-- Looking for __GLIBC__
-- Looking for __GLIBC__ - not found
-- Performing Test _OFFT_IS_64BIT
-- Performing Test _OFFT_IS_64BIT - Success
-- Performing Test HAVE_DATE_TIME
-- Performing Test HAVE_DATE_TIME - Success
-- Found OpenGL: /data/data/com.termux/files/usr/lib/libOpenGL.so
-- Found WrapOpenGL: TRUE
-- Found XKB: /data/data/com.termux/files/usr/lib/libxkbcommon.so (found suitable version "1.7.0", minimum required is "0.5.0")
-- Could NOT find WrapVulkanHeaders (missing: Vulkan_INCLUDE_DIR)
-- Could NOT find WrapVulkanHeaders (missing: Vulkan_INCLUDE_DIR)
-- Found Gettext: /data/data/com.termux/files/usr/bin/msgmerge (found version "0.22.5")
CMake Error at /data/data/com.termux/files/usr/lib/cmake/Qt6Core/Qt6CoreMacros.cmake:2676 (qt6_android_apply_arch_suffix):
  Unknown CMake command "qt6_android_apply_arch_suffix".
Call Stack (most recent call first):
  /data/data/com.termux/files/usr/lib/cmake/Qt6Core/Qt6CoreMacros.cmake:2451 (_qt_internal_add_library)
  /data/data/com.termux/files/usr/lib/cmake/Qt6Qml/Qt6QmlMacros.cmake:2043 (qt6_add_plugin)
  /data/data/com.termux/files/usr/lib/cmake/Qt6Qml/Qt6QmlMacros.cmake:379 (qt6_add_qml_plugin)
  /data/data/com.termux/files/usr/share/ECM/modules/ECMQmlModule6.cmake:77 (qt6_add_qml_module)
  src/qml/CMakeLists.txt:1 (ecm_add_qml_module)

-- Configuring incomplete, errors occurred!

### What steps will reproduce the bug?

Try to compile kf6-kiconthemes

### What is the expected behavior?

Don't show that error

### System information

```shell
ATermux Variables:
TERMUX_API_VERSION=0.50.1
TERMUX_APK_RELEASE=F_DROID
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=24119
TERMUX_IS_DEBUGGABLE_BUILD=0
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
TERMUX__USER_ID=0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://packages-cf.termux.dev/apt/termux-main/ stable main
# glibc-repo (sources.list.d/glibc.list)
deb https://packages-cf.termux.dev/apt/termux-glibc/ glibc stable
# tur-repo (sources.list.d/tur.list)
deb https://tur.kcubeterm.com tur-packages tur tur-on-device tur-continuous
# x11-repo (sources.list.d/x11.list)
deb https://packages-cf.termux.dev/apt/termux-x11/ x11 main
Updatable packages:
All packages up to date
termux-tools version:
1.43.1
Android version:
11
Kernel build information:
Linux localhost 4.14.186-22735277 #1 SMP PREEMPT Sat Feb 19 02:14:57 KST 2022 aarch64 Android
Device manufacturer:
samsung
Device model:
SM-A225M
LD Variables:
LD_LIBRARY_PATH=
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so
Installed termux plugins:
com.termux.api versionCode:51
com.termux.x11 versionCode:15
com.termux.styling versionCode:32
```

**Comment by Biswa96** [comment]
The actual issue in qt6 can be fixed. Also, how many packages do you need for that KDE game? I could try to add those packages after asking permission to do so.

**Comment by DuilioPerez** [comment]
> The actual issue in qt6 can be fixed. Also, how many packages do you need for that KDE game? I could try to add those packages after asking permission to do so.

I need the following packages: kf6-kcolorscheme kf6-kconfigwidgets kf6-kcrash kf6-kdbusaddons kf6-kiconthemes kf6-kxmlgui kf6-doctools kf6-newstuff. I've compiled most of them. I've not compiled kf6-kxmlgui, wich depends on kf6-kiconthemes, kf6-doctools and kf6-knewstuff, these I've not tried to compile. The others compile successfully. kf6-kcrash and kf6-kdbrusaddons need to be compiled with KF_IGNORE_PLATFORM_CHECK variable set to true because Android isn't supported. Also all those packages need the following configuration in cmake -DQT_REQUIRE_HOST_PATH_CHECK=NO -DQt6HostInfo_DIR=/data/data/com.termux/files/usr/lib/cmake/Qt6HostInfo/. It was confusing to me because I'm not familiar with Qt and KDE, but it seems it try cross compilation everytime, so this is needed

**Comment by Biswa96** [comment]
For quick workaround, you could try to comment out the following line in `$PREFIX/lib/cmake/Qt6Core/Qt6CoreMacros.cmake` file.

```diff
--- a/Qt6CoreMacros.cmake
+++ b/Qt6CoreMacros.cmake
@@ -2673,7 +2673,7 @@
     if(ANDROID)
         set_property(TARGET "${target}"
                      PROPERTY _qt_android_apply_arch_suffix_called_from_qt_impl TRUE)
-        qt6_android_apply_arch_suffix("${target}")
+        # qt6_android_apply_arch_suffix("${target}")
     endif()
 endfunction()
 ```

**Comment by DuilioPerez** [comment]
After doing that:
![Screenshot_20240731-135255_Termux](https://github.com/user-attachments/assets/6fdb2d3b-0e48-4a9a-b66c-8991eb2e63c3)
It happens the same error, even deleting the cmake build cache directory:
```
cmake -S . -B build -DQT_REQUIRE_HOST_PATH_CHECK=NO -DQt6HostInfo_DIR=/data/data/com.termux/files/usr/lib/cmake/Qt6HostInfo/
-- The C compiler identification is Clang 18.1.8
-- The CXX compiler identification is Clang 18.1.8
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /data/data/com.termux/files/usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /data/data/com.termux/files/usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
--

-- Check if compiler accepts -pthread
-- Check if compiler accepts -pthread - yes
-- Installing in the same prefix as Qt, adopting their path scheme.
-- Performing Test HAVE_STDATOMIC
-- Performing Test HAVE_STDATOMIC - Success
-- Found WrapAtomic: TRUE
-- Looking for __GLIBC__
-- Looking for __GLIBC__ - not found
-- Performing Test _OFFT_IS_64BIT
-- Performing Test _OFFT_IS_64BIT - Success
-- Performing Test HAVE_DATE_TIME
-- Performing Test HAVE_DATE_TIME - Success
-- Found OpenGL: /data/data/com.termux/files/usr/lib/libOpenGL.so
-- Found WrapOpenGL: TRUE
-- Found XKB: /data/data/com.termux/files/usr/lib/libxkbcommon.so (found suitable version "1.7.0", minimum required is "0.5.0")
-- Could NOT find WrapVulkanHeaders (missing: Vulkan_INCLUDE_DIR)
-- Could NOT find WrapVulkanHeaders (missing: Vulkan_INCLUDE_DIR)
-- Found Gettext: /data/data/com.termux/files/usr/bin/msgmerge (found version "0.22.5")
CMake Error at /data/data/com.termux/files/usr/lib/cmake/Qt6Qml/Qt6QmlMacros.cmake:2149 (qt6_android_apply_arch_suffix):
  Unknown CMake command "qt6_android_apply_arch_suffix".
Call Stack (most recent call first):
  /data/data/com.termux/files/usr/lib/cmake/Qt6Qml/Qt6QmlMacros.cmake:379 (qt6_add_qml_plugin)
  /data/data/com.termux/files/usr/share/ECM/modules/ECMQmlModule6.cmake:77 (qt6_add_qml_module)
  src/qml/CMakeLists.txt:1 (ecm_add_qml_module)
```

**Comment by Biswa96** [comment]
Does adding `-DCMAKE_SYSTEM_NAME=Linux` option with cmake make any change? Also, the host info option is not required when compiling in same Android system.

**Comment by DuilioPerez** [comment]
Ok, it seems it worked. But it requires breeze icons. The problem is, I can't compile it because it crashes termux.

**Comment by DuilioPerez** [comment]
I'll try to compile the others two modules and then I'll see how to compile this one. It's just breeze icons the problem.

**Comment by DuilioPerez** [comment]
@Biswa96 Almost all done! Just need two modules that I can't compile, kf6-kdoctools and kf6-kxmlgui, the last depends of kf6-kiconthemes and this depends on breeze-icons

**Comment by Biswa96** [comment]
Could this issue be closed now? IIUC, there is nothing actionable in this repository.

**Comment by DuilioPerez** [comment]
Yes, closing now

**Comment by Manamama** [comment]
FYI still a problem in 2025. Termux. This helped: https://github.com/termux/termux-packages/issues/21004#issuecomment-2261220593

**Comment by DuilioPerez** [comment]
Now most of KDE Framework Modules are available through apt in Termux repos. There is not need to recompile them from source. They are available since the inclusion of kdenlive, which have a lot of dependencies

**Comment by Manamama** [comment]
None of the apt's qt6* helps with:
```
~/.../BitNet/3rdparty $ gguf-
gguf-convert-endian  gguf-new-metadata            gguf-dump            gguf-set-metadata
gguf-editor-gui
~/.../BitNet/3rdparty $ gguf-dump                 Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/bin/gguf-dump", line 5, in <module>
    from gguf.scripts import gguf_dump_entrypoint
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/gguf/scripts/__init__.py", line 7, in <module>
    from .gguf_editor_gui import main as gguf_editor_gui_entrypoint                                   File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/gguf/scripts/gguf_editor_gui.py", line 15, in <module>
    from PySide6.QtWidgets import (
ModuleNotFoundError: No module named 'PySide6'
~/.../BitNet/3rdparty $ pip install pyside6                                              Looking in indexes: https://pypi.org/simple, https://termux-user-repository.github.io/pypi/         ERROR: Could not find a version that satisfies the requirement pyside6 (from versions: none)        ERROR: No matching distribution found for pyside6
~/.../BitNet/3rdparty $ uname -a
Linux localhost 4.14.186+ #1 SMP PREEMPT Thu Mar 17 16:28:22 CST 2022 aarch64 Android               ~/.../BitNet/3rdparty $
```

So I tried to compile it and was almost successful...

**Comment by DuilioPerez** [comment]
You need to install pyqt5
`apt install pyqt5`

**Comment by Manamama** [comment]
Install qt5 to solve a qt6 advertise led error? Interesting train of thoughts.

Let us try:
```
apt install pyqt5
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
pyqt5 is already the newest version (5.15.11-1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

```
Ooos, it has been here all the time. 

Assuming some IT gremlins ate smth:

```
~ $ apt reinstall pyqt5
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
0 upgraded, 0 newly installed, 1 reinstalled, 0 to remove and 0 not upgraded.
Need to get 2484 kB of archives.
After this operation, 0 B of additional disk space will be used.
Get:1 https://grimler.se/termux/termux-x11 x11/main aarch64 pyqt5 aarch64 5.15.11-1 [2484 kB]
Fetched 2484 kB in 19s (134 kB/s)
(Reading database ... 229056 files and directories currently installed.)
Preparing to unpack .../pyqt5_5.15.11-1_aarch64.deb ...
Requirement already satisfied: PyQt5-sip<13,>=12.13 in /data/data/com.termux/files/usr/lib/python3.12/site-packages (12.16.0)
```

And then, the cold logic : "5 is not 6" wins over this dream yet again:
```
gguf-
gguf-convert-endian  gguf-new-metadata
gguf-dump            gguf-set-metadata
gguf-editor-gui
~ $ gguf-dump
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/bin/gguf-dump", line 5, in <module>
    from gguf.scripts import gguf_dump_entrypoint
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/gguf/scripts/__init__.py", line 7, in <module>
    from .gguf_editor_gui import main as gguf_editor_gui_entrypoint
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/gguf/scripts/gguf_editor_gui.py", line 15, in <module>
    from PySide6.QtWidgets import (
ModuleNotFoundError: No module named 'PySide6'
~
```

**Comment by Manamama** [comment]
FYI, reinstalled gguf itself, out of curiosity and no luck:
```
Successfully built sentencepiece
Installing collected packages: sentencepiece, tqdm, pyyaml, numpy, gguf
  Attempting uninstall: sentencepiece
    Found existing installation: sentencepiece 0.2.0
    Uninstalling sentencepiece-0.2.0:
      Successfully uninstalled sentencepiece-0.2.0
  Attempting uninstall: tqdm
    Found existing installation: tqdm 4.67.1
    Uninstalling tqdm-4.67.1:
      Successfully uninstalled tqdm-4.67.1
  Attempting uninstall: pyyaml
    Found existing installation: PyYAML 6.0.2
    Uninstalling PyYAML-6.0.2:
      Successfully uninstalled PyYAML-6.0.2
  Attempting uninstall: numpy
    Found existing installation: numpy 2.0.2
    Uninstalling numpy-2.0.2:
      Successfully uninstalled numpy-2.0.2
  Attempting uninstall: gguf
    Found existing installation: gguf 0.16.2
    Uninstalling gguf-0.16.2:
      Successfully uninstalled gguf-0.16.2
...
Successfully installed gguf-0.16.2 numpy-2.2.5 pyyaml-6.0.2 sentencepiece-0.2.0 tqdm-4.67.1
~ $ gguf-dump
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/bin/gguf-dump", line 5, in <module>
    from gguf.scripts import gguf_dump_entrypoint
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/gguf/scripts/__init__.py", line 7, in <module>
    from .gguf_editor_gui import main as gguf_editor_gui_entrypoint
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/gguf/scripts/gguf_editor_gui.py", line 15, in <module>
    from PySide6.QtWidgets import (
ModuleNotFoundError: No module named 'PySide6'
~ $
```

I guess hand compiling PySide6 is needed, just as this error shows.

**Comment by Manamama** [comment]
Oh. This worked instead: `pip install gguf[gui]` (sic!), but I have no idea why so:
```
Installing collected packages: gguf
  Attempting uninstall: gguf
    Found existing installation: gguf 0.16.2
    Uninstalling gguf-0.16.2:
      Successfully uninstalled gguf-0.16.2
```
sic - it aomehow downgrades and is `gui`full,
```python /data/data/com.termux/files/usr/bin/gguf-dump
usage: gguf-dump [-h] [--no-tensors] [--json]
                 [--json-array] [--data-offset]
                 [--data-alignment] [--markdown]
                 [--verbose]
                 model

Dump GGUF file metadata... ```
