### ISSUE TITLE
[Bug]: gradle 8 not found libstdc++.so.6

### ISSUE THREAD

**Issue by qidizi** [termux/termux-packages#21144]
### Problem description

gradle --debug log

```text
2024-08-16T11:39:23.928+0000 [DEBUG] [org.gradle.internal.nativeintegration.services.NativeServices] Native-platform is not available.
net.rubygrapefruit.platform.NativeIntegrationLinkageException: Native library 'libnative-platform.so' could not be loaded for Linux aarch64.
	at net.rubygrapefruit.platform.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:61)
	at net.rubygrapefruit.platform.Native.init(Native.java:56)
	at org.gradle.internal.nativeintegration.services.NativeServices.initializeNativeIntegrations(NativeServices.java:234)
	at org.gradle.internal.nativeintegration.services.NativeServices.initialize(NativeServices.java:213)
	at org.gradle.internal.nativeintegration.services.NativeServices.initializeOnClient(NativeServices.java:184)
	at org.gradle.launcher.cli.NativeServicesInitializingAction.execute(NativeServicesInitializingAction.java:48)
	at org.gradle.launcher.cli.NativeServicesInitializingAction.execute(NativeServicesInitializingAction.java:27)
	at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:41)
	at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:26)
	at org.gradle.launcher.cli.DefaultCommandLineActionFactory$WithLogging.execute(DefaultCommandLineActionFactory.java:444)
	at org.gradle.launcher.Main.doAction(Main.java:35)
	at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:52)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:72)
	at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:39)
	at org.gradle.launcher.GradleMain.main(GradleMain.java:31)
Caused by: java.lang.UnsatisfiedLinkError: /data/data/com.termux/files/home/.gradle/native/c067742578af261105cb4f569cf0c3c89f3d7b1fecec35dd04571415982c5e48/linux-aarch64/libnative-platform.so: dlopen failed: library "libstdc++.so.6" not found: needed by /data/data/com.termux/files/home/.gradle/native/c067742578af261105cb4f569cf0c3c89f3d7b1fecec35dd04571415982c5e48/linux-aarch64/libnative-platform.so in namespace (default)
	at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
	at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:331)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:197)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:139)
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2409)
	at java.base/java.lang.Runtime.load0(Runtime.java:852)
	at java.base/java.lang.System.load(System.java:2021)
	at net.rubygrapefruit.platform.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:51)
	... 16 more
2024-08-16T11:39:24.013+0000 [INFO] [org.gradle.internal.nativeintegration.services.NativeServices] Initialized native services in: /data/data/com.termux/files/home/.gradle/native
2024-08-16T11:39:24.029+0000 [LIFECYCLE] [org.gradle.launcher.cli.DebugLoggerWarningAction] 
#############################################################################
   WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING

   Debug level logging will leak security sensitive information!

   For more details, please refer to https://docs.gradle.org/8.10/userguide/logging.html#sec:debug_security in the Gradle documentation.
#############################################################################
```

### What steps will reproduce the bug?

pkg install gradle  

gradle --debug  

### System information

```shell
.../com.termux/files $ java -version
openjdk version "21-internal" 2023-09-19
OpenJDK Runtime Environment (build 21-internal-adhoc.builder.src)
OpenJDK 64-Bit Server VM (build 21-internal-adhoc.builder.src, mixed mode)

.../com.termux/files $ gradle --version

------------------------------------------------------------
Gradle 8.10
------------------------------------------------------------

Build time:    2024-08-14 11:07:45 UTC
Revision:      fef2edbed8af1022cefaf44d4c0514c5f89d7b78

Kotlin:        1.9.24
Groovy:        3.0.22
Ant:           Apache Ant(TM) version 1.10.14 compiled on August 16 2023
Launcher JVM:  21-internal (Oracle Corporation 21-internal-adhoc.builder.src)
Daemon JVM:    /data/data/com.termux/files/usr/lib/jvm/java-21-openjdk (no JDK specified, using current Java home)
OS:            Linux 4.14.180-perf-gb24d113 aarch64


android 11

termux version:  googleplay.2024.07.07
```

**Comment by twaik** [comment]
Is this still reproducible?

**Comment by twaik** [comment]
1. As of moment you posted this issue we did not have `openjdk-21` packaged, your java build is 3rd party and we offer zero support for it.
2. Your termux version is installed from google play. We do not maintain it, issues should be reported to https://github.com/termux-play-store/termux-packages.
