### ISSUE TITLE
Can't install python package with c

### ISSUE THREAD

**Issue by magician333** [termux/termux-packages#218]
if i use pip install python package which include C (such as lxml , misaka ) , it will wrong. By the way ,I installed gcc and python-dev

**Comment by fornwall** [comment]
For lxml you add `libxml2-dev` and `libxslt-dev`, so the full list of dependencies to install should be:

    apt install gcc libxml2-dev libxslt-dev python-dev

After that you should be able to `pip install lxml` - show me the error message if this does not work for you!

**Comment by fornwall** [comment]
For misaka, you need to first update gcc to the newly released `5.3.0-2` version which fixes TLS:

    apt update gcc

You can then install the dependency (for cffi, which misaka depends on):

    apt install libffi-dev

and finally install misaka with:

    pip install --upgrade --force-reinstall misaka

where `--upgrade --force-reinstall` forces rebuilds of packages that you may have builkt with older gcc versions. Let me know if this works for you!

**Comment by magician333** [comment]
@fornwall Still can't this is response message

 Installed /data/data/com.termux/files/usr/tmp/pip-build-p7kbv_ef/misaka/.eggs/cffi-1.5.2-py3.5-linux-aarch64.egg
    Searching for pycparser
    Reading https://pypi.python.org/simple/pycparser/
    Best match: pycparser 2.14
    Downloading https://pypi.python.org/packages/source/p/pycparser/pycparser-2.14.tar.gz#md5=a2bc8d28c923b4fe2b2c3b4b51a4f935
    Processing pycparser-2.14.tar.gz
    Writing /data/data/com.termux/files/usr/tmp/easy_install-pv94m74k/pycparser-2.14/setup.cfg
    Running pycparser-2.14/setup.py -q bdist_egg --dist-dir /data/data/com.termux/files/usr/tmp/easy_install-pv94m74k/pycparser-2.14/egg-dist-tmp-ryhgcdb6
    warning: no previously-included files matching 'yacctab.*' found under directory 'tests'
    warning: no previously-included files matching 'lextab.*' found under directory 'tests'
    warning: no previously-included files matching 'yacctab.*' found under directory 'examples'
    warning: no previously-included files matching 'lextab.*' found under directory 'examples'
    zip_safe flag not set; analyzing archive contents...
    Moving pycparser-2.14-py3.5.egg to /data/data/com.termux/files/usr/tmp/pip-build-p7kbv_ef/misaka/.eggs

    Installed /data/data/com.termux/files/usr/tmp/pip-build-p7kbv_ef/misaka/.eggs/pycparser-2.14-py3.5.egg
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/data/data/com.termux/files/usr/tmp/pip-build-p7kbv_ef/misaka/setup.py", line 68, in <module>
        cffi_modules=['build_ffi.py:ffi'],
      File "/data/data/com.termux/files/usr/lib/python3.5/distutils/core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "/data/data/com.termux/files/usr/lib/python3.5/site-packages/setuptools/dist.py", line 272, in __init__
        _Distribution.__init__(self,attrs)
      File "/data/data/com.termux/files/usr/lib/python3.5/distutils/dist.py", line 281, in __init__
        self.finalize_options()
      File "/data/data/com.termux/files/usr/lib/python3.5/site-packages/setuptools/dist.py", line 327, in finalize_options
        ep.load()(self, ep.name, value)
      File "/data/data/com.termux/files/usr/tmp/pip-build-p7kbv_ef/misaka/.eggs/cffi-1.5.2-py3.5-linux-aarch64.egg/cffi/setuptools_ext.py", line 161, in cffi_modules
        add_cffi_module(dist, cffi_module)
      File "/data/data/com.termux/files/usr/tmp/pip-build-p7kbv_ef/misaka/.eggs/cffi-1.5.2-py3.5-linux-aarch64.egg/cffi/setuptools_ext.py", line 48, in add_cffi_module
        execfile(build_file_name, mod_vars)
      File "/data/data/com.termux/files/usr/tmp/pip-build-p7kbv_ef/misaka/.eggs/cffi-1.5.2-py3.5-linux-aarch64.egg/cffi/setuptools_ext.py", line 24, in execfile
        exec(code, glob, glob)
      File "build_ffi.py", line 51, in <module>
        ffi = cffi.FFI()
      File "/data/data/com.termux/files/usr/tmp/pip-build-p7kbv_ef/misaka/.eggs/cffi-1.5.2-py3.5-linux-aarch64.egg/cffi/api.py", line 56, in __init__
        import _cffi_backend as backend
    ImportError: dlopen failed: unknown reloc type 17 @ 0x4120f350 (442)

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /data/data/com.termux/files/usr/tmp/pip-build-p7kbv_ef/misaka/

**Comment by fornwall** [comment]
@magician333 Ok, can you double-check that you have the right gcc version by running `apt-cache show gcc | grep Version` and verify that the output is `Version: 5.3.0-2`?

Can you also try to reinstall cffi:

    pip uninstall cffi
    pip install cffi

and then try to install misaka again?

**Comment by magician333** [comment]
@fornwall Thanks a lot, I already installed,I'll close this issue

**Comment by magician333** [comment]
eee,@fornwall And another thing ,I install gevent for python also failed,How to do?

**Comment by ravimathi** [comment]
@fornwall following your suggestion, I updated the gcc and installed libffi-dev. I installed cffi through pip.
Currently I am having gcc version (Ubuntu 5.3.0-3ubuntu1~14.04) 5.3.0 20151204
But I am getting the following error when i try installing misaka. Can you please let me know what am doing wrong.

```
sudo pip install --upgrade --force-reinstall misaka

Downloading/unpacking misaka
  Downloading misaka-2.0.0.tar.gz (121kB): 121kB downloaded
  Running setup.py (path:/tmp/pip_build_root/misaka/setup.py) egg_info for package misaka
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip_build_root/misaka/setup.py", line 68, in <module>
        cffi_modules=['build_ffi.py:ffi'],
      File "/usr/lib/python2.7/distutils/core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)
      File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 243, in __init__
        _Distribution.__init__(self,attrs)
      File "/usr/lib/python2.7/distutils/dist.py", line 287, in __init__
        self.finalize_options()
      File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 277, in finalize_options
        ep.load()(self, ep.name, value)
      File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2088, in load
        entry = __import__(self.module_name, globals(),globals(), ['__name__'])
    ImportError: No module named setuptools_ext

```

**Comment by fornwall** [comment]
Closed as part of https://github.com/termux/termux-packages/issues/283.
