### ISSUE TITLE
[Bug]: hiding app from launcher using adb

### ISSUE THREAD

**Issue by HusniMuhammad** [termux/termux-packages#21832]
### Problem description

I want to hide external downloader from Nova launcher through  wirelessly connected adb hosted by Termux 

``
Exception occurred while executing 'disable-user':
java.lang.SecurityException: Shell cannot change component state for de.markusfisch.android.binaryeye/de.markusfisch.android.binaryeye.activity.SplashActivity to 3
        at com.android.server.pm.PackageManagerService.setEnabledSetting(PackageManagerService.java:21395)
        at com.android.server.pm.PackageManagerService.setComponentEnabledSetting(PackageManagerService.java:21286)
        at com.android.server.pm.PackageManagerShellCommand.runSetEnabledSetting(PackageManagerShellCommand.java:2199)
        at com.android.server.pm.PackageManagerShellCommand.onCommand(PackageManagerShellCommand.java:235)
        at android.os.BasicShellCommandHandler.exec(BasicShellCommandHandler.java:98)
        at android.os.ShellCommand.exec(ShellCommand.java:44)
        at com.android.server.pm.PackageManagerService.onShellCommand(PackageManagerService.java:22020)
        at android.os.Binder.shellCommand(Binder.java:929)
        at android.os.Binder.onTransact(Binder.java:813)
        at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:4742)
        at com.android.server.pm.PackageManagerService.onTransact(PackageManagerService.java:4454)
        at android.os.Binder.execTransactInternal(Binder.java:1159)
        at android.os.Binder.execTransact(Binder.java:1123)
``

### What steps will reproduce the bug?

```
adb shell pm disable-user com.tachibana.downloader/.ui.main.MainActivity
```

### What is the expected behavior?

 app become hidden from launcher 

### System information

```shell
Termux Variables:
TERMUX_APP_PACKAGE_MANAGER=apt                        
TERMUX_APP__APK_FILE=/data/app/~~Iy_M9qEGd8uffro2xLjBw
g==/com.termux-q58c8BHzpgLqjr2ppjoeuQ==/base.apk
TERMUX_APP__APK_RELEASE=GITHUB                        
TERMUX_APP__APP_VERSION_CODE=1020                     
TERMUX_APP__APP_VERSION_NAME=0.119.0-beta.1
TERMUX_APP__DATA_DIR=/data/user/0/com.termux          
TERMUX_APP__IS_DEBUGGABLE_BUILD=true
TERMUX_APP__IS_INSTALLED_ON_EXTERNAL_STORAGE=false    
TERMUX_APP__PACKAGE_NAME=com.termux
TERMUX_APP__PID=12131                                 
TERMUX_APP__TARGET_SDK=28
TERMUX_VERSION=0.119.0-beta.1                         
TERMUX__SE_FILE_CONTEXT=u:object_r:app_data_file:s0:c2
50,c256,c512,c768                                     
TERMUX__SE_INFO=default:targetSdkVersion=28:complete
TERMUX__SE_PROCESS_CONTEXT=u:r:untrusted_app_27:s0:c25
0,c256,c512,c768
TERMUX__UID=10250                                     
TERMUX__USER_ID=0
Packages CPU architecture:                            
aarch64
Subscribed repositories:                              
# sources.list
deb https://packages-cf.termux.dev/apt/termux-main/ st
able main
Updatable packages:
c-ares/stable 1.34.1 aarch64 [upgradable from: 1.33.1]
termux-tools version:
1.43.6
Android version:
13
Kernel build information:
Linux localhost 4.19.111-27127798 #1 SMP PREEMPT Tue M
ay 14 18:19:35 KST 2024 aarch64 Android
Device manufacturer:
samsung
Device model:
SM-M127F
LD Variables:
LD_LIBRARY_PATH=
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libterm
ux-exec.so

```

**Comment by zavocc** [comment]
This is not a Termux related issue, you cannot disable specific app activities without root unless it is marked testOnly
