### ISSUE TITLE
python setup.py sdist doesn't work

### ISSUE THREAD

**Issue by j-bennet** [termux/termux-packages#2218]
I have this error when trying to create a package distribution:

```
(pgspecial) --- code/pgspecial ‹master➔› » python setup.py sdist
running sdist
running egg_info
writing pgspecial.egg-info/PKG-INFO
writing dependency_links to pgspecial.egg-info/dependency_links.txt
writing requirements to pgspecial.egg-info/requires.txt
writing top-level names to pgspecial.egg-info/top_level.txt
reading manifest file 'pgspecial.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'pgspecial.egg-info/SOURCES.txt'
running check
creating pgspecial-1.10.0
creating pgspecial-1.10.0/pgspecial
creating pgspecial-1.10.0/pgspecial.egg-info
creating pgspecial-1.10.0/pgspecial/help
creating pgspecial-1.10.0/tests
copying files to pgspecial-1.10.0...
copying License.txt -> pgspecial-1.10.0
error: [Errno 1] Operation not permitted
```

I'm running `termux` on a Samsung Chromebook Pro.

**Comment by tomty89** [comment]
Do not do it with files under the (emulated) SD card:
```
$ tar -xf /sdcard/Download/pgspecial-1.9.0.tar.gz
$ cd pgspecial-1.9.0/
$ pwd
/data/data/com.termux/files/home/pgspecial-1.9.0
$ python setup.py sdist
running sdist
running egg_info
writing pgspecial.egg-info/PKG-INFO
writing dependency_links to pgspecial.egg-info/dependency_links.txt
writing requirements to pgspecial.egg-info/requires.txt
writing top-level names to pgspecial.egg-info/top_level.txt
reading manifest file 'pgspecial.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'pgspecial.egg-info/SOURCES.txt'
running check
creating pgspecial-1.9.0
creating pgspecial-1.9.0/pgspecial
creating pgspecial-1.9.0/pgspecial.egg-info
creating pgspecial-1.9.0/pgspecial/help
creating pgspecial-1.9.0/tests
creating pgspecial-1.9.0/tests/.cache
creating pgspecial-1.9.0/tests/.cache/v
creating pgspecial-1.9.0/tests/.cache/v/cache
creating pgspecial-1.9.0/tests/__pycache__
copying files to pgspecial-1.9.0...
copying License.txt -> pgspecial-1.9.0
copying MANIFEST.in -> pgspecial-1.9.0
copying README.rst -> pgspecial-1.9.0
copying setup.cfg -> pgspecial-1.9.0
copying setup.py -> pgspecial-1.9.0
copying pgspecial/__init__.py -> pgspecial-1.9.0/pgspecial
copying pgspecial/dbcommands.py -> pgspecial-1.9.0/pgspecial
copying pgspecial/iocommands.py -> pgspecial-1.9.0/pgspecial
copying pgspecial/main.py -> pgspecial-1.9.0/pgspecial
copying pgspecial/namedqueries.py -> pgspecial-1.9.0/pgspecial
copying pgspecial.egg-info/PKG-INFO -> pgspecial-1.9.0/pgspecial.egg-info
copying pgspecial.egg-info/SOURCES.txt -> pgspecial-1.9.0/pgspecial.egg-info
copying pgspecial.egg-info/dependency_links.txt -> pgspecial-1.9.0/pgspecial.egg-info
copying pgspecial.egg-info/requires.txt -> pgspecial-1.9.0/pgspecial.egg-info
copying pgspecial.egg-info/top_level.txt -> pgspecial-1.9.0/pgspecial.egg-info
copying pgspecial/help/__init__.py -> pgspecial-1.9.0/pgspecial/help
copying pgspecial/help/commands.py -> pgspecial-1.9.0/pgspecial/help
copying tests/conftest.py -> pgspecial-1.9.0/tests
copying tests/dbutils.py -> pgspecial-1.9.0/tests
copying tests/dbutils.pyc -> pgspecial-1.9.0/tests
copying tests/pytest.ini -> pgspecial-1.9.0/tests
copying tests/test_specials.py -> pgspecial-1.9.0/tests
copying tests/.cache/v/cache/lastfailed -> pgspecial-1.9.0/tests/.cache/v/cache
copying tests/__pycache__/conftest.cpython-27-PYTEST.pyc -> pgspecial-1.9.0/tests/__pycache__
copying tests/__pycache__/conftest.cpython-33-PYTEST.pyc -> pgspecial-1.9.0/tests/__pycache__
copying tests/__pycache__/dbutils.cpython-33.pyc -> pgspecial-1.9.0/tests/__pycache__
copying tests/__pycache__/test_specials.cpython-27-PYTEST.pyc -> pgspecial-1.9.0/tests/__pycache__
copying tests/__pycache__/test_specials.cpython-33-PYTEST.pyc -> pgspecial-1.9.0/tests/__pycache__
Writing pgspecial-1.9.0/setup.cfg
creating dist
Creating tar archive
removing 'pgspecial-1.9.0' (and everything under it)
$ cd /sdcard/Download/
$ tar -xf pgspecial-1.9.0.tar.gz
$ cd pgspecial-1.9.0
$ pwd
/sdcard/Download/pgspecial-1.9.0
$ python setup.py sdist
running sdist
running egg_info
writing pgspecial.egg-info/PKG-INFO
writing dependency_links to pgspecial.egg-info/dependency_links.txt
writing requirements to pgspecial.egg-info/requires.txt
writing top-level names to pgspecial.egg-info/top_level.txt
reading manifest file 'pgspecial.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'pgspecial.egg-info/SOURCES.txt'
running check
creating pgspecial-1.9.0
creating pgspecial-1.9.0/pgspecial
creating pgspecial-1.9.0/pgspecial.egg-info
creating pgspecial-1.9.0/pgspecial/help
creating pgspecial-1.9.0/tests
creating pgspecial-1.9.0/tests/.cache
creating pgspecial-1.9.0/tests/.cache/v
creating pgspecial-1.9.0/tests/.cache/v/cache
creating pgspecial-1.9.0/tests/__pycache__
copying files to pgspecial-1.9.0...
copying License.txt -> pgspecial-1.9.0
error: [Errno 1] Operation not permitted: 'pgspecial-1.9.0/License.txt'
$
```

**Comment by tomty89** [comment]
It's because:
```
$ cd /sdcard
$ touch test_a test_b
$ python
Python 3.6.4 (default, Jan  7 2018, 03:52:16)
[GCC 4.2.1 Compatible Android Clang 5.0.300080 ] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from shutil import copystat
>>> copystat('test_a', 'test_b')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/data/data/com.termux/files/usr/lib/python3.6/shutil.py", line 203, in copystat
    lookup("chmod")(dst, mode, follow_symlinks=follow)
PermissionError: [Errno 1] Operation not permitted: 'test_b'
>>>
$ ls -l test_*
-rw-rw----    1 root     everybod         0 Mar  2 14:18 test_a
-rw-rw----    1 root     everybod         0 Mar  2 14:18 test_b
$ chmod 660 test_*
chmod: test_a: Operation not permitted
chmod: test_b: Operation not permitted
$
```

**Comment by j-bennet** [comment]
This was not an sdcard location.

```
--- code/pgspecial ‹master*➔ ?› » pwd
/data/data/com.termux/files/home/code/pgspecial
```

**Comment by Grimler91** [comment]
Works without errors for me as well. @j-bennet which arch are you on?

**Comment by tomty89** [comment]
Can you test `copystat` like I did?

**Comment by j-bennet** [comment]
Here is the copystat test:

```
--- code/pgspecial ‹master*➔ ?› » touch test_a test_b                                                                     1 ↵
--- code/pgspecial ‹master*➔ ?› » python
Python 3.6.3 (default, Oct  6 2017, 07:49:11)
[GCC 4.2.1 Compatible Android Clang 5.0.300080 ] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from shutil import copystat
>>> copystat('test_a', 'test_b')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/data/data/com.termux/files/usr/lib/python3.6/shutil.py", line 201, in copystat
    follow_symlinks=follow)
PermissionError: [Errno 1] Operation not permitted
>>>
--- code/pgspecial ‹master*➔ ?› » ls -l test_*
-rw-rw---- 1 root everybody 0 Mar  4 07:50 test_a
-rw-rw---- 1 root everybody 0 Mar  4 07:50 test_b
```

**Comment by j-bennet** [comment]
Also system information from `termux-info`:

```
System information:
Linux localhost 3.18.0-16505-g3f26a8efd173-dirty #1 SMP PREEMPT Tue Feb 27 22:29:43 PST 2018 i686 Android
Termux-packages arch:
i686
Android version:
7.1.1
Device manufacturer:
google
Device model:
Samsung Chromebook Pro
```

**Comment by tomty89** [comment]
Hmm weird. Files under `/data/data/com.termux` should not be owned by `root:everybody` but `$(whoami):$(whoami)`, and you should be able to change atime and mtime in either case:
```
$ whoami
u0_a292
$ ls -l $HOME/test
ls: cannot access '/data/data/com.termux/files/home/test': No such file or directory
$ touch $HOME/test
$ ls -l $HOME/test
-rw------- 1 u0_a292 u0_a292 0 Mar  5 00:28 /data/data/com.termux/files/home/test
$ touch -t 01010101 $HOME/test
$ ls -l $HOME/test
-rw------- 1 u0_a292 u0_a292 0 Jan  1 01:01 /data/data/com.termux/files/home/test
$ ls -l /sdcard/test
ls: cannot access '/sdcard/test': No such file or directory
$ touch /sdcard/test
$ ls -l /sdcard/test
-rw-rw---- 1 root everybody 0 Mar  5 00:30 /sdcard/test
$ touch -t 01010101 /sdcard/test
$ ls -l /sdcard/test
-rw-rw---- 1 root everybody 0 Jan  1 01:01 /sdcard/test
$
```

How does `realpath $(pwd)` look?

**Comment by j-bennet** [comment]
```
--- code/pgspecial ‹master› » whoami
u0_a56
--- code/pgspecial ‹master› » realpath $(pwd)
/storage/emulated/0/Download/code/pgspecial
```

I run `termux-chroot` on startup. Can that be a problem?

**Comment by tomty89** [comment]
`/storage/emulated/0` is the sdcard. Symlinking to it from `$HOME` doesn't change the fact.

**Comment by j-bennet** [comment]
I actually don't have an sdcard in my Chromebook. Isn't this internal storage?

**Comment by j-bennet** [comment]
I see. Thanks.

**Comment by tomty89** [comment]
Well "internal storage" (as in, `/storage/emulated/0`, where `/sdcard` is symlinked to) is the "emulated" sdcard, where limitations of a "real" sdcard (with a FAT-family filesystem) also apply.
