### ISSUE TITLE
Unable to fully install nala (incompatible pip dependencies)

### ISSUE THREAD

**Issue by Nikitf777** [termux/termux-packages#22686]
### Problem description

I can't install nala properly using apt. It says:

Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
nala is already the newest version (0.15.4-2).
0 upgraded, 0 newly installed, 0 to remove and 40 not upgraded.
1 not fully installed or removed.
After this operation, 0 B of additional disk space will be used.
Do you want to continue? [Y/n] y
Setting up nala (0.15.4-2) ...
Installing dependencies through pip...
WARNING: Disabling truststore since ssl support is missing
WARNING: pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/anyio/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/anyio/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/anyio/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/anyio/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/anyio/
Could not fetch URL https://pypi.org/simple/anyio/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/anyio/ (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.")) - skipping
ERROR: Could not find a version that satisfies the requirement anyio (from versions: none)
ERROR: No matching distribution found for anyio
dpkg: error processing package nala (--configure):
 installed nala package post-installation script subprocess returned error exit status 1
Errors were encountered while processing:
 nala
E: Sub-process /data/data/com.termux/files/usr/bin/dpkg returned an error code (1)

However, nala executable appears in the system, but executing `nala install [package]` result in an error:

Traceback (most recent call last):                                                                File "/data/data/com.termux/files/usr/bin/nala", line 5, in <module>
    from nala.__main__ import main                                                                File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/nala/__init__.py", line 60, in <module>
    from rich.console import Console                                                            ModuleNotFoundError: No module named 'rich'

`apt upgrade` also result in an error:

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
nala 0.15.4 requires anyio<4.0.0,>=3.6.1, but you have anyio 4.7.0 which is incompatible.
nala 0.15.4 requires httpx<0.24.0,>=0.23.0, but you have httpx 0.28.1 which is incompatible.
nala 0.15.4 requires rich<13.0.0,>=12.4.4, but you have rich 13.9.4 which is incompatible.
nala 0.15.4 requires typer<0.5.0,>=0.4.1, but you have typer 0.15.1 which is incompatible.

### What steps will reproduce the bug?

`apt install nala`
`nala install git`
`apt upgrade`

### What is the expected behavior?

Should be installed and work without errors

### System information

```shell
Termux Variables:                                                                               TERMUX_API_VERSION=0.50.1
TERMUX_APK_RELEASE=F_DROID                                                                      TERMUX_APP_PACKAGE_MANAGER=apt                                                                  TERMUX_APP_PID=9479
TERMUX_IS_DEBUGGABLE_BUILD=0                                                                    TERMUX_MAIN_PACKAGE_FORMAT=debian                                                               TERMUX_VERSION=0.118.1
TERMUX__USER_ID=0                                                                               Packages CPU architecture:                                                                      aarch64                                                                                         Subscribed repositories:                                                                        # sources.list
deb https://packages-cf.termux.dev/apt/termux-main/ stable main                                 Updatable packages:                                                                             apt/stable 2.8.1-1 aarch64 [upgradable from: 2.7.14]
bash/stable 5.2.37 aarch64 [upgradable from: 5.2.26-1]                                          ca-certificates/stable 1:2024.09.24 all [upgradable from: 1:2024.03.11-2]                       command-not-found/stable 2.4.0-55 aarch64 [upgradable from: 2.4.0-29]
coreutils/stable 9.5-3 aarch64 [upgradable from: 9.5]                                           curl/stable 8.11.1 aarch64 [upgradable from: 8.8.0]                                             debianutils/stable 5.21 aarch64 [upgradable from: 5.19]                                         dpkg/stable 1.22.6-1 aarch64 [upgradable from: 1.22.6]                                          fastfetch/stable 2.33.0 aarch64 [upgradable from: 2.32.1]                                       findutils/stable 4.10.0 aarch64 [upgradable from: 4.9.0-2]                                      gpgv/stable 2.4.5-3 aarch64 [upgradable from: 2.4.5-1]                                          inetutils/stable 2.5 aarch64 [upgradable from: 2.4-1]                                           less/stable 668 aarch64 [upgradable from: 633-1]                                                libandroid-support/stable 29 aarch64 [upgradable from: 28-3]                                    libassuan/stable 3.0.1-2 aarch64 [upgradable from: 2.5.7]
libc++/stable 27c aarch64 [upgradable from: 26b]                                                libcurl/stable 8.11.1 aarch64 [upgradable from: 8.8.0]                                          libgcrypt/stable 1.11.0 aarch64 [upgradable from: 1.10.3]
libgmp/stable 6.3.0-1 aarch64 [upgradable from: 6.3.0]                                          libgpg-error/stable 1.50 aarch64 [upgradable from: 1.49]                                        liblz4/stable 1.10.0 aarch64 [upgradable from: 1.9.4]
liblzma/stable 5.6.3 aarch64 [upgradable from: 5.6.2]                                           libnettle/stable 3.10 aarch64 [upgradable from: 3.9.1]                                          libnghttp2/stable 1.64.0 aarch64 [upgradable from: 1.62.1]                                      libnghttp3/stable 1.7.0 aarch64 [upgradable from: 1.3.0]
libsmartcols/stable 2.40.2-2 aarch64 [upgradable from: 2.39.3-4]                                libssh2/stable 1.11.1 aarch64 [upgradable from: 1.11.0]
libtirpc/stable 1.3.6 aarch64 [upgradable from: 1.3.4-1]
libunbound/stable 1.22.0 aarch64 [upgradable from: 1.20.0]
libunistring/stable 1.3 aarch64 [upgradable from: 1.1]
lsof/stable 4.99.4 aarch64 [upgradable from: 4.99.3]
nano/stable 8.3 aarch64 [upgradable from: 8.0]
openssl/stable 1:3.3.2 aarch64 [upgradable from: 1:3.2.1-1]
patch/stable 2.7.6-4 aarch64 [upgradable from: 2.7.6-3]
readline/stable 8.2.13 aarch64 [upgradable from: 8.2.10]
termux-am/stable 0.8.0-1 all [upgradable from: 0.8.0]
termux-keyring/stable 3.12-1 all [upgradable from: 3.12]
termux-tools/stable 1.44.6 all [upgradable from: 1.42.4]
util-linux/stable 2.40.2-2 aarch64 [upgradable from: 2.39.3-4]
xz-utils/stable 5.6.3 aarch64 [upgradable from: 5.6.2]
zstd/stable 1.5.6-2 aarch64 [upgradable from: 1.5.6]
termux-tools version:
1.42.4
Android version:
15
Kernel build information:
Linux localhost 4.19.322-perf-gcda8a00e48f6 #1 SMP PREEMPT Sat Nov 30 16:12:24 UTC 2024 aarch64 Android
Device manufacturer:
realme
Device model:
RMX3371
LD Variables:
LD_LIBRARY_PATH=
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so
Installed termux plugins:
com.termux.window versionCode:15
com.termux.widget versionCode:13
com.termux.styling versionCode:1000
com.termux.api versionCode:51
com.termux.boot versionCode:1000
com.termux.tasker versionCode:6
```

**Comment by Biswa96** [comment]
Could you try to uninstall those conflicting python modules with pip and reinstall nala?

**Comment by Nikitf777** [comment]
> Could you try to uninstall those conflicting python modules with pip and reinstall nala?

Ok, I will. But I highly doubt this will work, because it's a completely fresh install of both OS (flashed my ROM yesterday) and Termux. And the same issue was on my previous OS and Termux installation, and also on Waydroid on my x86 laptop.

**Comment by Nikitf777** [comment]
> Could you try to uninstall those conflicting python modules with pip and reinstall nala?

So, I tried this solution. As expected, it didn't help, because those packages are being installed with the nala package, despite the fact they are incompatible.

**Comment by queso42** [comment]
I do have that issue too! But nala still worked fine, upgrade openssl first so pip will work

**Comment by licy183** [comment]
Try `pip install nala` to let pip resolve issues about nala's dependency.

**Comment by Nikitf777** [comment]
> Try `pip install nala` to let pip resolve issues about nala's dependency.

Thanks, it works. I installed nala through pip, then `apt install nala` and everything works. So I think we can just use `pip install nala` in the `postinstall` instead of `pip3 install anyio httpx jsbeautifier pexpect python-debian rich tomli typer typing-extensions`.

**Comment by 4rg1l** [comment]
@licy183 I just did a clean reinstall of `Termux` and `Nala` didn't work out of the box.

Had to do `pip install python-debian` to fix it.  


Still something funny going on with postinst?


ps. the above suggested `pip install nala` installed some testing library for C lol...

**Comment by licy183** [comment]
`python-debian` doesn't exist in nala's dependencies but it depends on it. This is a bug of nala and should be reported upstream.
