### ISSUE TITLE
[Bug]: Please help me to solve the problem about how to start my jupyter notebook

### ISSUE THREAD

**Issue by hunghunsongge** [termux/termux-packages#22726]
### Problem description

I have downloaded jupyter notebook in termux, however it gives me the following problem when I start jupyter notebook,can anyone help me to solve it?

Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/bin/jupyter-notebook", line 5, in <module>
    from notebook.app import main
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/notebook/app.py", line 9, in <module>
    from jupyter_client.utils import ensure_async  # type:ignore[attr-defined]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/jupyter_client/__init__.py", line 3, in <module>
    from .asynchronous import AsyncKernelClient
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/jupyter_client/asynchronous/__init__.py", line 1, in <module>
    from .client import AsyncKernelClient  # noqa
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/jupyter_client/asynchronous/client.py", line 8, in <module>
    import zmq.asyncio
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/zmq/__init__.py", line 52, in <module>
    from zmq import backend
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/zmq/backend/__init__.py", line 30, in <module>
    raise original_error from None
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/zmq/backend/__init__.py", line 25, in <module>
    _ns = select_backend(first)
          ^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/zmq/backend/select.py", line 31, in select_backend
    mod = import_module(name)
          ^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/zmq/backend/cython/__init__.py", line 6, in <module>
    from . import _zmq
ImportError: dlopen failed: cannot locate symbol "PyExc_ImportError" referenced by "/data/data/com.termux/files/usr/lib/python3.12/site-packages/zmq/backend/cython/_zmq.cpython-312.so"...

![Screenshot_2024-12-31-22-54-57-56_84d3000e3f4017145260f7618db1d683 (小)](https://github.com/user-attachments/assets/820372ce-b274-4bc6-9db7-7225d19a82bb)

### What steps will reproduce the bug?

here is my full command about termux
pkg install python
pkg install numpy
pkg install python-numpy
pkg install python-pandas
pkg install rust
pkg i binutils-is-llvm
cargo install maturin
pkg install -y libjpeg-turbo libtiff
pip install pillow
pkg install -y freetype libpng
pkg install vim
pkg install pandoc
apt install libxml2
apt install libxslt
pip install lxml
MATHLIB=m pip install markitdown
MATHLIB=m pip install jupyter
pip install --upgrade setuptools
pip install Pyrebase4
wget https://its-pointless.github.io/setup-pointless-repo.sh
bash setup-pointless-repo.sh
pkg install scipy
pip install kiwisolver cycler pyparsing python-dateutil
pkg install libjpeg-turbo libtiff littlecms tk libwebp
pkg install libzmq libcrypt pkg-config
pkg install clang
pip install jupyter
pip install pandas
jupyter notebook --generate-config
LDFLAGS="-lpython3.12" pip3 install --no-cache-dir pyzmq
jupyter notebook
LDFLAGS=-lpython3.11 pip install pyzmq --force-reinstall --no-cache-dir
pkg install pyzmq
cd pyzmq/
CC=clang python setup.py build
SODIUM_INSTALL=system CC=clang pip install --no-binary=pyzmq pyzmq

### System information

```shell
Termux Variables:
TERMUX_APK_RELEASE=F_DROID
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=10575
TERMUX_IS_DEBUGGABLE_BUILD=0
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.1
TERMUX__USER_ID=0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://packages-cf.termux.dev/apt/termux-main/ stable main
# sources.list.d/pointless.list
deb https://its-pointless.github.io/files/21 termux extras
# tur-repo (sources.list.d/tur.list)
deb https://tur.kcubeterm.com tur-packages tur tur-on-device tur-continuous
Updatable packages:
All packages up to date
termux-tools version:
1.44.6
Android version:
15
Kernel build information:
Linux localhost 6.1.75-android14-11-o-g47c8194d882f #1 SMP PREEMPT Mon Oct 28 13:11:55 UTC 2024 aarch64 Android
Device manufacturer:
OnePlus
Device model:
OPD2404
LD Variables:
LD_LIBRARY_PATH=
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so
```

**Comment by atikattar1104** [comment]
I Would Love To Use Jupyter Notebook/Lab In Termux Natively. Termux Already Have A Lot Of Potential, This Is Just A Small Missing Feature.
