### ISSUE TITLE
How to run mariadb on Termux

### ISSUE THREAD

**Issue by miracle0403** [termux/termux-packages#2283]
I installed mariadb and required it after i ran <code> mysqld_safe -u root & </code> in termux but i get this error

node app
server started at localhost:3000
{ Error: ER_ACCESS_DENIED_ERROR: Access denied for user 'myusername'@'localhost' (using password: YES)
    at Handshake.Sequence._packetToError (/data/data/com.termux/files/home/test/node_modules/mysql/lib/protocol/sequences/Sequence.js:52:14)
    at Handshake.ErrorPacket (/data/data/com.termux/files/home/test/node_modules/mysql/lib/protocol/sequences/Handshake.js:130:18)
    at Protocol._parsePacket (/data/data/com.termux/files/home/test/node_modules/mysql/lib/protocol/Protocol.js:279:23)
    at Parser.write (/data/data/com.termux/files/home/test/node_modules/mysql/lib/protocol/Parser.js:76:12)
    at Protocol.write (/data/data/com.termux/files/home/test/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/data/data/com.termux/files/home/test/node_modules/mysql/lib/Connection.js:103:28)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.

**Comment by Atavic** [comment]
Related: https://github.com/termux/termux-packages/issues/216

**Comment by vishalbiswas** [comment]
You configuration is wrong. Can you post the snippet of code where the actual mysql related code is?
