### ISSUE TITLE
Python eventlet unable to find protocols

### ISSUE THREAD

**Issue by TheLastDestroyer** [termux/termux-packages#2387]
Attempting to use eventlet in python leads to an error where it is unable to 'get' the TCP protocol, seems to require a /etc/protocols file which is absent in termux, and simply creating one in /usr/etc does not seem to fix the problem.

Sorry if this is the wrong place, rather new to all this.

Steps to recreate:
pkg install python clang libcrypt-dev
pip install eventlet
python
import eventlet

Running python 3.6.5, termux 0.6, android 8.1 April patch

Error:
`
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/eventlet/__init__.py", line 10, in <module>
    from eventlet import convenience
  File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/eventlet/convenience.py", line 7, in <module>
    from eventlet.green import socket
  File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/eventlet/green/socket.py", line 21, in <module>
    from eventlet.support import greendns
  File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/eventlet/support/greendns.py", line 71, in <module>
    setattr(dns.rdtypes.IN, pkg, import_patched('dns.rdtypes.IN.' + pkg))
  File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/eventlet/support/greendns.py", line 61, in import_patched
    return patcher.import_patched(module_name, **modules)
  File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/eventlet/patcher.py", line 120, in import_patched
    *additional_modules + tuple(kw_additional_modules.items()))
  File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/eventlet/patcher.py", line 94, in inject
    module = __import__(module_name, {}, {}, module_name.split('.')[:-1])
  File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/eventlet/support/dns/rdtypes/IN/WKS.py", line 23, in <module>
    _proto_tcp = socket.getprotobyname('tcp')
OSError: protocol not found`

**Comment by ypnos** [comment]
I can confirm the problem. Patching WKS.py by using fixed numbers (TCP: 6, UDP: 17) worked.

**Comment by fornwall** [comment]
Right, getprotobyname seems to be a stub in bionic: https://android.googlesource.com/platform/bionic/+/master/libc/bionic/netdb.cpp#51

I've made a local patch in the python package as of version `3.6.5-3`: c78b7f43af2e260783cd40ed85dd99eb9eb46475

@ypnos @opyate @TheLastDestroyer Could you update the python package with `pkg up` and verify that this fixes the issue?

**Comment by TheLastDestroyer** [comment]
@fornwall that seems to have done the trick, thank you
