### ISSUE TITLE
Jupyter notebook doesn't work

### ISSUE THREAD

**Issue by prid** [termux/termux-packages#2444]
I installed python 3.6 (as well as the python-dev package), the `pip install jupyter` process goes smoothly. However, after installation, when I type `jupyter notebook`, the following error appears

```
bash-4.4$ jupyter notebook
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/bin/jupyter-notebook", line 7, in <module>
    from notebook.notebookapp import main
  File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/notebook/notebookapp.py", line 45, in <module>
    from zmq.eventloop import ioloop
  File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/zmq/__init__.py", line 47, in <module>
    from zmq import backend
  File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/zmq/backend/__init__.py", line 40, in <module>
    reraise(*exc_info)
  File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/zmq/utils/sixcerpt.py", line 34, in reraise
    raise value
  File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/zmq/backend/__init__.py", line 27, in <module>
    _ns = select_backend(first)
  File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/zmq/backend/select.py", line 26, in select_backend
    mod = __import__(name, fromlist=public_api)
  File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/zmq/backend/cython/__init__.py", line 6, in <module>
    from . import (constants, error, message, context,
ImportError: dlopen failed: cannot locate symbol "zmq_strerror" referenced by "/data/data/com.termux/files/usr/lib/python3.6/site-packages/zmq/backend/cython/error.cpython-36m.so"...
```

**Comment by Grimler91** [comment]
See https://github.com/termux/termux-packages/issues/2260.
