### ISSUE TITLE
gdb Segmentation fault when attach to a running process

### ISSUE THREAD

**Issue by elliott10** [termux/termux-packages#2445]
Please help. 
When I run the command：
`gdb --pid=PID`

 I got the following error:
```
Program received signal SIGSEGV, Segmentation fault.
0x0000555555728779 in ?? ()

```
Backtrace:
```
#0  0x0000555555728779 in ?? ()
#1  0x000055555572d8eb in ?? ()
#2  0x0000555555726e9d in ?? ()
#3  0x0000555555727e77 in ?? ()
#4  0x00005555556f71d0 in ?? ()
#5  0x00005555556f6f3c in ?? ()
#6  0x00005555557c9413 in ?? ()
#7  0x0000555555740fa9 in ?? ()
#8  0x00005555557407fb in ?? ()
#9  0x00005555555dd5cc in ?? ()
#10 0x00007ffff7c0590d in __libc_init () from /system/lib64/libc.so
#11 0x00005555555dd584 in ?? ()
#12 0x0000000000000002 in ?? ()
#13 0x00007fffffffe9fd in ?? ()
#14 0x00007fffffffea25 in ?? ()
#15 0x0000000000000000 in ?? ()
```

**Comment by truboxl** [comment]
Closing old issue. Not reproducible with Android 13 and assuming this is on aarch64.
