### ISSUE TITLE
seaborn import

### ISSUE THREAD

**Issue by fedebarabas** [termux/termux-packages#2470]
Has anyone tried to install seaborn for python? pip install seaborn seems to work but when I try to import seaborn, this is what I get

>>> import seaborn
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/seaborn/__init__.py", line 6, in <module>
    from .rcmod import *
  File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/seaborn/rcmod.py", line 8, in <module>
    from . import palettes, _orig_rc_params
  File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/seaborn/palettes.py", line 12, in <module>
    from .utils import desaturate, set_hls_values, get_color_cycle
  File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/seaborn/utils.py", line 7, in <module>
    from scipy import stats
  File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/scipy-1.1.0-py3.6-linux-i686.egg/scipy/stats/__init__.py", line 345, in <module>
    from .stats import *
  File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/scipy-1.1.0-py3.6-linux-i686.egg/scipy/stats/stats.py", line 171, in <module>
    from . import distributions
  File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/scipy-1.1.0-py3.6-linux-i686.egg/scipy/stats/distributions.py", line 10, in <module>
    from ._distn_infrastructure import (entropy, rv_discrete, rv_continuous,
  File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/scipy-1.1.0-py3.6-linux-i686.egg/scipy/stats/_distn_infrastructure.py", line 16, in <module>
    from scipy.misc import doccer
  File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/scipy-1.1.0-py3.6-linux-i686.egg/scipy/misc/__init__.py", line 68, in <module>
    from scipy.interpolate._pade import pade as _pade
  File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/scipy-1.1.0-py3.6-linux-i686.egg/scipy/interpolate/__init__.py", line 175, in <module>
    from .interpolate import *
  File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/scipy-1.1.0-py3.6-linux-i686.egg/scipy/interpolate/interpolate.py", line 32, in <module>
    from .interpnd import _ndim_coords_from_arrays
  File "interpnd.pyx", line 1, in init scipy.interpolate.interpnd
  File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/scipy-1.1.0-py3.6-linux-i686.egg/scipy/spatial/__init__.py", line 96, in <module>
    from .qhull import *
  File "messagestream.pxd", line 5, in init scipy.spatial.qhull
ImportError: dlopen failed: cannot locate symbol "messagestream_open_memstream" referenced by "messagestream.cpython-36m.so"...

**Comment by xeffyr** [comment]
Closing since no answer for 2 years...
