### ISSUE TITLE
Some APIs cannot be used

### ISSUE THREAD

**Issue by ngxlua** [termux/termux-packages#2560]
Termux-api is installed from Google's Play store.

termux api log

```
$ logcat -s "termux:* termux-api:*"--------- beginning of main
06-21 11:08:54.455  2820  2820 E termux-api: FingerprintAPI06-21 11:08:54.455  2820  2820 E termux-api: java.security.ProviderException: Keystore operation failed
06-21 11:08:54.455  2820  2820 E termux-api:    at android.security.keystore.AndroidKeyStoreKeyGeneratorSpi.engineGenerateK
ey(AndroidKeyStoreKeyGeneratorSpi.java:322)
06-21 11:08:54.455  2820  2820 E termux-api:    at javax.crypto.KeyGenerator.generateKey(KeyGenerator.java:604)06-21 11:08:54.455  2820  2820 E termux-api:    at com.termux.api.FingerprintAPI$FingerprintActivity.generateKey(Fingerprin
tAPI.java:274)
06-21 11:08:54.455  2820  2820 E termux-api:    at com.termux.api.FingerprintAPI$FingerprintActivity.handleFingerprint(Fing
erprintAPI.java:172)
06-21 11:08:54.455  2820  2820 E termux-api:    at com.termux.api.FingerprintAPI$FingerprintActivity.onCreate(FingerprintAPI.java:158)
06-21 11:08:54.455  2820  2820 E termux-api:    at android.app.Activity.performCreate(Activity.java:7174)06-21 11:08:54.455  2820  2820 E termux-api:    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:12
20)
06-21 11:08:54.455  2820  2820 E termux-api:    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2908)
06-21 11:08:54.455  2820  2820 E termux-api:    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3030)
06-21 11:08:54.455  2820  2820 E termux-api:    at android.app.ActivityThread.-wrap11(Unknown Source:0)06-21 11:08:54.455  2820  2820 E termux-api:    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1696)
06-21 11:08:54.455  2820  2820 E termux-api:    at android.os.Handler.dispatchMessage(Handler.java:105)
06-21 11:08:54.455  2820  2820 E termux-api:    at android.os.Looper.loop(Looper.java:164)
06-21 11:08:54.455  2820  2820 E termux-api:    at android.app.ActivityThread.main(ActivityThread.java:6938)
06-21 11:08:54.455  2820  2820 E termux-api:    at java.lang.reflect.Method.invoke(Native Method)
06-21 11:08:54.455  2820  2820 E termux-api:    at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
06-21 11:08:54.455  2820  2820 E termux-api:    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
06-21 11:08:54.455  2820  2820 E termux-api:    at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:108)
06-21 11:08:54.455  2820  2820 E termux-api: Caused by: android.security.KeyStoreException: User authentication required
06-21 11:08:54.455  2820  2820 E termux-api:    at android.security.KeyStore.getKeyStoreException(KeyStore.java:1112)
06-21 11:08:54.455  2820  2820 E termux-api:    at android.security.keystore.AndroidKeyStoreKeyGeneratorSpi.engineGenerateK
ey(AndroidKeyStoreKeyGeneratorSpi.java:323)
06-21 11:08:54.455  2820  2820 E termux-api:    ... 17 more
06-21 11:08:54.459  2820  2820 E termux-api: FingerprintAPI
06-21 11:08:54.459  2820  2820 E termux-api: java.security.InvalidKeyException: Only SecretKey is supported
06-21 11:08:54.459  2820  2820 E termux-api:    at com.android.org.conscrypt.OpenSSLCipher.checkAndSetEncodedKey(OpenSSLCip
her.java:436)
06-21 11:08:54.459  2820  2820 E termux-api:    at com.android.org.conscrypt.OpenSSLCipher.engineInit(OpenSSLCipher.java:26
1)
06-21 11:08:54.459  2820  2820 E termux-api:    at javax.crypto.Cipher.tryTransformWithProvider(Cipher.java:2663)
06-21 11:08:54.459  2820  2820 E termux-api:    at javax.crypto.Cipher.tryCombinations(Cipher.java:2570)
06-21 11:08:54.459  2820  2820 E termux-api:    at javax.crypto.Cipher$SpiAndProviderUpdater.updateAndGetSpiAndProvider(Cipher.java:2475)
06-21 11:08:54.459  2820  2820 E termux-api:    at javax.crypto.Cipher.chooseProvider(Cipher.java:566)
06-21 11:08:54.459  2820  2820 E termux-api:    at javax.crypto.Cipher.init(Cipher.java:830)
06-21 11:08:54.459  2820  2820 E termux-api:    at javax.crypto.Cipher.init(Cipher.java:771)
06-21 11:08:54.459  2820  2820 E termux-api:    at com.termux.api.FingerprintAPI$FingerprintActivity.handleFingerprint(FingerprintAPI.java:176)
06-21 11:08:54.459  2820  2820 E termux-api:    at com.termux.api.FingerprintAPI$FingerprintActivity.onCreate(FingerprintAPI.java:158)
06-21 11:08:54.459  2820  2820 E termux-api:    at android.app.Activity.performCreate(Activity.java:7174)
06-21 11:08:54.459  2820  2820 E termux-api:    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1220)
06-21 11:08:54.459  2820  2820 E termux-api:    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2908)
06-21 11:08:54.459  2820  2820 E termux-api:    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3030)
06-21 11:08:54.459  2820  2820 E termux-api:    at android.app.ActivityThread.-wrap11(Unknown Source:0)
06-21 11:08:54.459  2820  2820 E termux-api:    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1696)
06-21 11:08:54.459  2820  2820 E termux-api:    at android.os.Handler.dispatchMessage(Handler.java:105)
06-21 11:08:54.459  2820  2820 E termux-api:    at android.os.Looper.loop(Looper.java:164)
06-21 11:08:54.459  2820  2820 E termux-api:    at android.app.ActivityThread.main(ActivityThread.java:6938)
06-21 11:08:54.459  2820  2820 E termux-api:    at java.lang.reflect.Method.invoke(Native Method)
06-21 11:08:54.459  2820  2820 E termux-api:    at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
06-21 11:08:54.459  2820  2820 E termux-api:    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
06-21 11:08:54.459  2820  2820 E termux-api:    at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:108)
06-21 11:14:22.230  6296  6296 E termux-api: FingerprintAPI
06-21 11:14:22.230  6296  6296 E termux-api: java.security.ProviderException: Keystore operation failed
06-21 11:14:22.230  6296  6296 E termux-api:    at android.security.keystore.AndroidKeyStoreKeyGeneratorSpi.engineGenerateKey(AndroidKeyStoreKeyGeneratorSpi.java:322)
06-21 11:14:22.230  6296  6296 E termux-api:    at javax.crypto.KeyGenerator.generateKey(KeyGenerator.java:604)
06-21 11:14:22.230  6296  6296 E termux-api:    at com.termux.api.FingerprintAPI$FingerprintActivity.generateKey(FingerprintAPI.java:274)
06-21 11:14:22.230  6296  6296 E termux-api:    at com.termux.api.FingerprintAPI$FingerprintActivity.handleFingerprint(FingerprintAPI.java:172)
06-21 11:14:22.230  6296  6296 E termux-api:    at com.termux.api.FingerprintAPI$FingerprintActivity.onCreate(FingerprintAPI.java:158)
06-21 11:14:22.230  6296  6296 E termux-api:    at android.app.Activity.performCreate(Activity.java:7174)
06-21 11:14:22.230  6296  6296 E termux-api:    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1220)
06-21 11:14:22.230  6296  6296 E termux-api:    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2908)
06-21 11:14:22.230  6296  6296 E termux-api:    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3030)
06-21 11:14:22.230  6296  6296 E termux-api:    at android.app.ActivityThread.-wrap11(Unknown Source:0)
06-21 11:14:22.230  6296  6296 E termux-api:    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1696)
06-21 11:14:22.230  6296  6296 E termux-api:    at android.os.Handler.dispatchMessage(Handler.java:105)
06-21 11:14:22.230  6296  6296 E termux-api:    at android.os.Looper.loop(Looper.java:164)
06-21 11:14:22.230  6296  6296 E termux-api:    at android.app.ActivityThread.main(ActivityThread.java:6938)
06-21 11:14:22.230  6296  6296 E termux-api:    at java.lang.reflect.Method.invoke(Native Method)
06-21 11:14:22.230  6296  6296 E termux-api:    at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
06-21 11:14:22.230  6296  6296 E termux-api:    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
06-21 11:14:22.230  6296  6296 E termux-api:    at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:108)
06-21 11:14:22.230  6296  6296 E termux-api: Caused by: android.security.KeyStoreException: User authentication required
06-21 11:14:22.230  6296  6296 E termux-api:    at android.security.KeyStore.getKeyStoreException(KeyStore.java:1112)
06-21 11:14:22.230  6296  6296 E termux-api:    at android.security.keystore.AndroidKeyStoreKeyGeneratorSpi.engineGenerateKey(AndroidKeyStoreKeyGeneratorSpi.java:323)
06-21 11:14:22.230  6296  6296 E termux-api:    ... 17 more
06-21 11:14:22.242  6296  6296 E termux-api: FingerprintAPI
06-21 11:14:22.242  6296  6296 E termux-api: java.security.InvalidKeyException: Only SecretKey is supported
06-21 11:14:22.242  6296  6296 E termux-api:    at com.android.org.conscrypt.OpenSSLCipher.checkAndSetEncodedKey(OpenSSLCipher.java:436)
06-21 11:14:22.242  6296  6296 E termux-api:    at com.android.org.conscrypt.OpenSSLCipher.engineInit(OpenSSLCipher.java:261)
06-21 11:14:22.242  6296  6296 E termux-api:    at javax.crypto.Cipher.tryTransformWithProvider(Cipher.java:2663)
06-21 11:14:22.242  6296  6296 E termux-api:    at javax.crypto.Cipher.tryCombinations(Cipher.java:2570)
06-21 11:14:22.242  6296  6296 E termux-api:    at javax.crypto.Cipher$SpiAndProviderUpdater.updateAndGetSpiAndProvider(Cipher.java:2475)
06-21 11:14:22.242  6296  6296 E termux-api:    at javax.crypto.Cipher.chooseProvider(Cipher.java:566)
06-21 11:14:22.242  6296  6296 E termux-api:    at javax.crypto.Cipher.init(Cipher.java:830)
06-21 11:14:22.242  6296  6296 E termux-api:    at javax.crypto.Cipher.init(Cipher.java:771)
06-21 11:14:22.242  6296  6296 E termux-api:    at com.termux.api.FingerprintAPI$FingerprintActivity.handleFingerprint(FingerprintAPI.java:176)
06-21 11:14:22.242  6296  6296 E termux-api:    at com.termux.api.FingerprintAPI$FingerprintActivity.onCreate(FingerprintAPI.java:158)
06-21 11:14:22.242  6296  6296 E termux-api:    at android.app.Activity.performCreate(Activity.java:7174)
06-21 11:14:22.242  6296  6296 E termux-api:    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1220)
06-21 11:14:22.242  6296  6296 E termux-api:    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2908)
06-21 11:14:22.242  6296  6296 E termux-api:    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3030)
06-21 11:14:22.242  6296  6296 E termux-api:    at android.app.ActivityThread.-wrap11(Unknown Source:0)
06-21 11:14:22.242  6296  6296 E termux-api:    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1696)
06-21 11:14:22.242  6296  6296 E termux-api:    at android.os.Handler.dispatchMessage(Handler.java:105)
06-21 11:14:22.242  6296  6296 E termux-api:    at android.os.Looper.loop(Looper.java:164)
06-21 11:14:22.242  6296  6296 E termux-api:    at android.app.ActivityThread.main(ActivityThread.java:6938)
06-21 11:14:22.242  6296  6296 E termux-api:    at java.lang.reflect.Method.invoke(Native Method)
06-21 11:14:22.242  6296  6296 E termux-api:    at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
06-21 11:14:22.242  6296  6296 E termux-api:    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
06-21 11:14:22.242  6296  6296 E termux-api:    at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:108)
```

**Comment by Atavic** [comment]
Seems related to keystore and xposed: https://github.com/PhilippC/keepass2android/issues/362

**Comment by federicoiosue** [comment]
@Atavic not strictly, it happens even without using Xposed (see [this](https://github.com/PhilippC/keepass2android/issues/362#issuecomment-401731733) comment)
