### ISSUE TITLE
ruby: pry requires readline

### ISSUE THREAD

**Issue by vainikkaj** [termux/termux-packages#257]
Pry has worked previously on Nexus 9 but stopped working after latest ruby upgrade.

Running `pry` with following versions 

```
$ ruby --version
ruby 2.3.1p112 (2016-04-26 revision 54768) [aarch64-linux-android]

$ gem list
*** LOCAL GEMS ***

asciidoctor (1.5.4)
awesome_print (1.6.1)
bundler (1.11.2)
coderay (1.1.1)
erubis (2.7.0)
json (1.8.3)
lolcat (42.1.43)
method_source (0.8.2)
mini_portile2 (2.0.0)
nokogiri (1.6.7.2)
paint (1.0.1)
pry (0.10.3)
pry-doc (0.8.0)
pry-theme (1.1.3)
rake (11.1.1)
slop (3.6.0)
thor (0.19.1)
tmuxinator (0.6.9)
trollop (2.1.2)
yard (0.8.7.6)
```
gives this now error
```
Sorry, you can't use Pry without Readline or a compatible library.
Possible solutions:
 * Rebuild Ruby with Readline support using `--with-readline`
 * Use the rb-readline gem, which is a pure-Ruby port of Readline
 * Use the pry-coolline gem, a pure-ruby alternative to Readline
/data/data/com.termux/files/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- readline (LoadError)
	from /data/data/com.termux/files/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /data/data/com.termux/files/usr/lib/ruby/gems/2.3.0/gems/pry-0.10.3/lib/pry/config/default.rb:151:in `lazy_readline'
	from /data/data/com.termux/files/usr/lib/ruby/gems/2.3.0/gems/pry-0.10.3/lib/pry/config/default.rb:6:in `block in <class:Default>'
	from /data/data/com.termux/files/usr/lib/ruby/gems/2.3.0/gems/pry-0.10.3/lib/pry/config/default.rb:125:in `instance_eval'
	from /data/data/com.termux/files/usr/lib/ruby/gems/2.3.0/gems/pry-0.10.3/lib/pry/config/default.rb:125:in `block (2 levels) in <class:Default>'
	from /data/data/com.termux/files/usr/lib/ruby/gems/2.3.0/gems/pry-0.10.3/lib/pry/config/behavior.rb:54:in `public_send'
	from /data/data/com.termux/files/usr/lib/ruby/gems/2.3.0/gems/pry-0.10.3/lib/pry/config/behavior.rb:54:in `method_missing'
	from /data/data/com.termux/files/usr/lib/ruby/gems/2.3.0/gems/pry-0.10.3/lib/pry/history.rb:19:in `restore_default_behavior'
	from /data/data/com.termux/files/usr/lib/ruby/gems/2.3.0/gems/pry-0.10.3/lib/pry/history.rb:14:in `initialize'
	from /data/data/com.termux/files/usr/lib/ruby/gems/2.3.0/gems/pry-0.10.3/lib/pry/pry_class.rb:33:in `new'
	from /data/data/com.termux/files/usr/lib/ruby/gems/2.3.0/gems/pry-0.10.3/lib/pry/pry_class.rb:33:in `history'
	from /data/data/com.termux/files/usr/lib/ruby/gems/2.3.0/gems/pry-0.10.3/lib/pry/pry_class.rb:222:in `load_history'
	from /data/data/com.termux/files/usr/lib/ruby/gems/2.3.0/gems/pry-0.10.3/lib/pry/pry_class.rb:129:in `initial_session_setup'
	from /data/data/com.termux/files/usr/lib/ruby/gems/2.3.0/gems/pry-0.10.3/lib/pry/cli.rb:206:in `block in <top (required)>'
	from /data/data/com.termux/files/usr/lib/ruby/gems/2.3.0/gems/pry-0.10.3/lib/pry/cli.rb:83:in `block in parse_options'
	from /data/data/com.termux/files/usr/lib/ruby/gems/2.3.0/gems/pry-0.10.3/lib/pry/cli.rb:83:in `each'
	from /data/data/com.termux/files/usr/lib/ruby/gems/2.3.0/gems/pry-0.10.3/lib/pry/cli.rb:83:in `parse_options'
	from /data/data/com.termux/files/usr/lib/ruby/gems/2.3.0/gems/pry-0.10.3/bin/pry:16:in `<top (required)>'
	from /data/data/com.termux/files/usr/bin/pry:23:in `load'
	from /data/data/com.termux/files/usr/bin/pry:23:in `<main>'
```

**Comment by fornwall** [comment]
Thanks! Fixed in version `2.3.1-2` of the ruby package (along with a check so that it doesn't happen again), to which you can update with

    apt update && apt upgrade
