### ISSUE TITLE
SciPy import fails

### ISSUE THREAD

**Issue by Ranjan-Bagri** [termux/termux-packages#2630]
I have installed SciPy from @its-pointless repo. But when I'm trying to import SciPy it throws `ImportError: dlopen failed`. How to solve this issue?

```sh
>>> import scipy
WARNING: linker: /data/data/com.termux/files/usr/lib/python3.6/site-packages/numpy/core/multiarray.cpython-36m.so: unused DT entry: type 0x6ffffef5 arg 0x1580       WARNING: linker: /data/data/com.termux/files/usr/lib/python3.6/site-packages/numpy/core/umath.cpython-36m.so: unused DT entry: type 0x6ffffef5 arg 0xd20             WARNING: linker: /data/data/com.termux/files/usr/lib/python3.6/site-packages/numpy/linalg/lapack_lite.cpython-36m.so: unused DT entry: type 0x6ffffef5 arg 0x2e0
WARNING: linker: /data/data/com.termux/files/usr/lib/python3.6/site-packages/numpy/linalg/_umath_linalg.cpython-36m.so: unused DT entry: type 0x6ffffef5 arg 0xb98   WARNING: linker: /data/data/com.termux/files/usr/lib/python3.6/site-packages/numpy/fft/fftpack_lite.cpython-36m.so: unused DT entry: type 0x6ffffef5 arg 0x268
WARNING: linker: /data/data/com.termux/files/usr/lib/python3.6/site-packages/numpy/random/mtrand.cpython-36m.so: unused DT entry: type 0x6ffffef5 arg 0x7f8
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/scipy-1.1.0-py3.6-linux-aarch64.egg/scipy/__init__.py", line 119, in <module>
    from scipy._lib._ccallback import LowLevelCallable
  File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/scipy-1.1.0-py3.6-linux-aarch64.egg/scipy/_lib/_ccallback.py", line 1, in <module>
    from . import _ccallback_c
ImportError: dlopen failed: library name "/data/data/com.termux/files/usr/lib/python3.6/site-packages/scipy-1.1.0-py3.6-linux-aarch64.egg/scipy/_lib/_ccallback_c.cpython-36m.so" too long
```

**Comment by its-pointless** [comment]
This on arm or i686 or android 5?

**Comment by Ranjan-Bagri** [comment]
It's on android 5.1.1

**Comment by its-pointless** [comment]
not much i can do apart from suggest installing proot and executing termux-chroot.

**Comment by Ranjan-Bagri** [comment]
Hi @its-pointless
Thanks for your quick reply. I've tried both with chroot and without chroot, it throws the same error in both occasions. Have a look.
```sh
$ pwd                                                  /home
$ python                                               Python 3.6.5 (default, Jun  8 2018, 01:39:02)          [GCC 4.2.1 Compatible Android (4691093 based on r316199) Clang 6.0.2 (https://a on linux
Type "help", "copyright", "credits" or "license" for more information.                                        >>> import scipy                                       WARNING: linker: /data/data/com.termux/files/usr/lib/python3.6/site-packages/numpy/core/multiarray.cpython-36m.so: unused DT entry: type 0x6ffffef5 arg 0x1580       WARNING: linker: /data/data/com.termux/files/usr/lib/python3.6/site-packages/numpy/core/umath.cpython-36m.so: unused DT entry: type 0x6ffffef5 arg 0xd20
WARNING: linker: /data/data/com.termux/files/usr/lib/python3.6/site-packages/numpy/linalg/lapack_lite.cpython-36m.so: unused DT entry: type 0x6ffffef5 arg 0x2e0     WARNING: linker: /data/data/com.termux/files/usr/lib/python3.6/site-packages/numpy/linalg/_umath_linalg.cpython-36m.so: unused DT entry: type 0x6ffffef5 arg 0xb98
WARNING: linker: /data/data/com.termux/files/usr/lib/python3.6/site-packages/numpy/fft/fftpack_lite.cpython-36m.so: unused DT entry: type 0x6ffffef5 arg 0x268
WARNING: linker: /data/data/com.termux/files/usr/lib/python3.6/site-packages/numpy/random/mtrand.cpython-36m.so: unused DT entry: type 0x6ffffef5 arg 0x7f8
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/scipy-1.1.0-py3.6-linux-aarch64.egg/scipy/__init__.py", line 119, in <module>
    from scipy._lib._ccallback import LowLevelCallable
  File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/scipy-1.1.0-py3.6-linux-aarch64.egg/scipy/_lib/_ccallback.py", line 1, in <module>
    from . import _ccallback_c
ImportError: dlopen failed: library name "/data/data/com.termux/files/usr/lib/python3.6/site-packages/scipy-1.1.0-py3.6-linux-aarch64.egg/scipy/_lib/_ccallback_c.cpython-36m.so" too long
>>>
```

**Comment by xeffyr** [comment]
Seems that this issue is the same as https://github.com/termux/termux-app/issues/213
