### ISSUE TITLE
scipy issue when importing lfilter from scipy.signal

### ISSUE THREAD

**Issue by aaronavi** [termux/termux-packages#2852]
Hi
I am using scipy package with Python3 and i am getting the following error when importing:

Traceback (most recent call last):
  File "initiate_monitor.py", line 28, in <module>
    import batch_monitor
  File "/storage/emulated/0/DCIM/test/python/batch_monitor.py", line 45, in <module>
    import filter_data
  File "/storage/emulated/0/DCIM/test/python/filter_data.py", line 27, in <module>
    from eegfilt import eegfilt
  File "/storage/emulated/0/DCIM/test/python/eegfilt.py", line 2, in <module>
    from filtfilt import filtfilt
  File "/storage/emulated/0/DCIM/test/python/filtfilt.py", line 1, in <module>
    from scipy.signal import lfilter
  File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/scipy-1.1.0-py3.6-linux-i686.egg/scipy/signal/__init__.py", line 321, in <module>
    from .filter_design import *
  File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/scipy-1.1.0-py3.6-linux-i686.egg/scipy/signal/filter_design.py", line 18, in <module>
    from scipy import special, optimize, fftpack
  File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/scipy-1.1.0-py3.6-linux-i686.egg/scipy/optimize/__init__.py", line 271, in <module>
    from ._minimize import *
  File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/scipy-1.1.0-py3.6-linux-i686.egg/scipy/optimize/_minimize.py", line 30, in <module>
    from ._trustregion_krylov import _minimize_trust_krylov
  File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/scipy-1.1.0-py3.6-linux-i686.egg/scipy/optimize/_trustregion_krylov.py", line 2, in <module>
    from ._trlib import (get_trlib_quadratic_subproblem)
  File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/scipy-1.1.0-py3.6-linux-i686.egg/scipy/optimize/_trlib/__init__.py", line 1, in <module>                                                                                                                                          from ._trlib import TRLIBQuadraticSubproblem
  File "messagestream.pxd", line 5, in init scipy.optimize._trlib._trlib                                                                         ImportError: dlopen failed: cannot locate symbol "messagestream_open_memstream" referenced by "/data/data/com.termux/files/usr/lib/python3.6/site-packages/scipy-1.1.0-py3.6-linux-i686.egg/scipy/_lib/messagestream.cpython-36m.so"...

**Comment by Grimler91** [comment]
Importing scipy or importing what?
What's the output of `termux-info`?

**Comment by aaronavi** [comment]
Hi
thanks on your response
from the output it fails when calling this code 'from scipy.signal import lfilter'
and termux-info:
$ termux-info

Updatable packages:
All packages up to date
System information:
Linux localhost 4.9.31-android #1 SMP PREEMPT Thu Jun 21 14:57:41 IST 2018 i686 Android
Termux-packages arch:
i686
Android version:
7.1.2
Device manufacturer:
samsung
Device model:
SM-G950F
$

**Comment by Grimler91** [comment]
Isn't the G950F the galaxy s8? I'm surprised to see it has installed termux as i686.

Could you try installing scipy from [its-pointless repo](https://wiki.termux.com/wiki/Package_Management#By_its-pointless_.28live_the_dream.29:) instead? (Unless that's what you've done already)

**Comment by aaronavi** [comment]
This error  is from the its-pointless repo version, i got a response that this will be fixed in next version hopefully, thanks all for your response, i guess this issue is closed.
