### ISSUE TITLE
termux:API bug

### ISSUE THREAD

**Issue by megdimka** [termux/termux-packages#2974]
my logcat:
```

9542
10-20 21:34:08.740 19542 19542 E AndroidRuntime: java.lang.RuntimeException: Unable to start receiver com.termux.api.TermuxApiReceiver: android.util.AndroidRuntimeException: Calling startActivity() from outside of an Activity  context requires the FLAG_ACTIVITY_NEW_TASK flag. Is this really what you want?
10-20 21:34:08.740 19542 19542 E AndroidRuntime:        at android.app.ActivityThread.handleReceiver(ActivityThread.java:2928)
10-20 21:34:08.740 19542 19542 E AndroidRuntime:        at android.app.ActivityThread.-wrap14(ActivityThread.java)
10-20 21:34:08.740 19542 19542 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1576)
10-20 21:34:08.740 19542 19542 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:111)
10-20 21:34:08.740 19542 19542 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:207)
10-20 21:34:08.740 19542 19542 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:5765)
10-20 21:34:08.740 19542 19542 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
10-20 21:34:08.740 19542 19542 E AndroidRuntime:        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
10-20 21:34:08.740 19542 19542 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)
10-20 21:34:08.740 19542 19542 E AndroidRuntime: Caused by: android.util.AndroidRuntimeException: Calling startActivity() from outside of an Activity  context requires the FLAG_ACTIVITY_NEW_TASK flag. Is this really what you want?
10-20 21:34:08.740 19542 19542 E AndroidRuntime:        at android.app.ContextImpl.startActivity(ContextImpl.java:677)
10-20 21:34:08.740 19542 19542 E AndroidRuntime:        at android.app.ContextImpl.startActivity(ContextImpl.java:664)
10-20 21:34:08.740 19542 19542 E AndroidRuntime:        at android.content.ContextWrapper.startActivity(ContextWrapper.java:331)
10-20 21:34:08.740 19542 19542 E AndroidRuntime:        at android.content.ContextWrapper.startActivity(ContextWrapper.java:331)
10-20 21:34:08.740 19542 19542 E AndroidRuntime:        at com.termux.api.TermuxApiReceiver.onReceive(TermuxApiReceiver.java:68)
10-20 21:34:08.740 19542 19542 E AndroidRuntime:        at android.app.ActivityThread.handleReceiver(ActivityThread.java:2921)
10-20 21:34:08.740 19542 19542 E AndroidRuntime:        ... 8 more
10-20 21:34:50.870 19821 19821 E AndroidRuntime: FATAL EXCEPTION: main
10-20 21:34:50.870 19821 19821 E AndroidRuntime: Process: com.termux.api, PID: 19821
```

**Comment by megdimka** [comment]
all termux:API commands are not working

**Comment by Grimler91** [comment]
What's your output of `termux-info`?

**Comment by megdimka** [comment]
Updatable packages:
All packages up to date
System information:
Linux localhost 3.18.19 #1 SMP PREEMPT Tue Oct 10 19:38:17 CST 2017 aarch64 Android
Termux-packages arch:
aarch64
Android version:
6.0
Device manufacturer:
LENOVO
Device model:
Lenovo TB3-850F
