### ISSUE TITLE
Termux-create-package

### ISSUE THREAD

**Issue by Wjsfj51najdk** [termux/termux-packages#2994]
termux-create-package manifest.json
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/bin/termux-create-package", line 144, in <module>
    main(sys.argv[1:])
  File "/data/data/com.termux/files/usr/bin/termux-create-package", line 122, in main
    with open(manifest_file_path, 'r') as manifest_file:
FileNotFoundError: [Errno 2] No such file or directory: 'manifest.json'

**Comment by Grimler91** [comment]
You don't seem to have a manifest.json file in the current directory
