### ISSUE TITLE
libandroid-cutils.so not found 

### ISSUE THREAD

**Issue by BilalArfi** [termux/termux-packages#3080]
Hi , i am try to creat metasploit payload with msfvenom embeding in original apk and i install java and jdk from hax4us 

So i find this issues

Sorry for my bad english

Building resources...
Exception in thread "main" W: CANNOT LINK EXECUTABLE: library "libandroid-cutils.so" not found
W: page record for 0x7fb5c80010 was not found (block_size=64)
brut.androlib.AndrolibException: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [aapt, p, --forced-package-id, 127, --min-sdk-version, 8, --target-sdk-version, 26, --version-code, 28, --version-name, 1.28, -F, /data/data/com.termux/files/home/apktool/APKTOOL8781047701431594534.tmp, -0, arsc, -0, arsc, -I, /data/data/com.termux/files/home/apktool/1.apk, -S, /data/data/com.termux/files/usr/tmp/d20181124-10530-mjtkgf/original/res, -M, /data/data/com.termux/files/usr/tmp/d20181124-10530-mjtkgf/original/AndroidManifest.xml]
        at brut.androlib.Androlib.buildResourcesFull(Androlib.java:473)
        at brut.androlib.Androlib.buildResources(Androlib.java:407)
        at brut.androlib.Androlib.build(Androlib.java:306)
        at brut.androlib.Androlib.build(Androlib.java:263)
        at brut.apktool.Main.cmdBuild(Main.java:224)
        at brut.apktool.Main.main(Main.java:84)
Caused by: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [aapt, p, --forced-package-id, 127, --min-sdk-version, 8, --target-sdk-version, 26, --version-code, 28, --version-name, 1.28, -F, /data/data/com.termux/files/home/apktool/APKTOOL8781047701431594534.tmp, -0, arsc, -0, arsc, -I, /data/data/com.termux/files/home/apktool/1.apk, -S, /data/data/com.termux/files/usr/tmp/d20181124-10530-mjtkgf/original/res, -M, /data/data/com.termux/files/usr/tmp/d20181124-10530-mjtkgf/original/AndroidManifest.xml]
        at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:439)
        at brut.androlib.Androlib.buildResourcesFull(Androlib.java:459)
        ... 5 more
Caused by: brut.common.BrutException: could not exec (exit code = 1): [aapt, p, --forced-package-id, 127, --min-sdk-version, 8, --target-sdk-version, 26, --version-code, 28, --version-name, 1.28, -F, /data/data/com.termux/files/home/apktool/APKTOOL8781047701431594534.tmp, -0, arsc, -0, arsc, -I, /data/data/com.termux/files/home/apktool/1.apk, -S, /data/data/com.termux/files/usr/tmp/d20181124-10530-mjtkgf/original/res, -M, /data/data/com.termux/files/usr/tmp/d20181124-10530-mjtkgf/original/AndroidManifest.xml]
        at brut.util.OS.exec(OS.java:95)
        at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:433)
        ... 6 more
Error: Unable to rebuild apk with apktool

**Comment by xeffyr** [comment]
Have you tried `pkg install aapt` ?

**Comment by BilalArfi** [comment]
Ign:1 https://termux.net stable InRelease
Ign:2 https://termux-x11.ml x11 InRelease
Hit:3 https://grimler.se root InRelease
Hit:4 https://termux-x11.ml x11 Release
Get:5 https://termux.net stable Release [1183 B]
Ign:6 https://termux.net stable Release.gpg
Reading package lists... Done
E: The repository 'https://termux.net stable Release' is no longer signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

**Comment by BilalArfi** [comment]
ans this with apt install aapt


apt install aapt
Reading package lists... Done
Building dependency tree
Reading state information... Done
aapt is already the newest version (7.1.2.33-2).
0 upgraded, 0 newly installed, 0 to remove and 17 not upgraded.

**Comment by xeffyr** [comment]
Okay, can you run `aapt` without arguments ? Just execute `aapt`, this needed to check if it is working.

**Comment by BilalArfi** [comment]
yes ,it work and  show the help banner
