### ISSUE TITLE
create-react-app error: cb() never called!

### ISSUE THREAD

**Issue by tchoutri** [termux/termux-packages#3188]
**Problem description**
Using `create-react-app` after having installed with `npm i -g create-react-app` results in a fatal error.
I saw several people on the Internet recommending to erase the cache, but this workaround did not work.

**Steps to reproduce**
1. `pkg i nodejs`
2. `npm i -g create-react-app`
3. `create-react-app app`

**Expected behavior**
I would have expected a bootstrapped React app

**Additional information**
```bash
$ termux-info
Updatable packages:
All packages up to date
System information:
Linux localhost 4.4.23+ #1 SMP PREEMPT Tue Dec 4 09:52:16 CST 2018 aarch64 Android
Termux-packages arch:
aarch64
Android version:
8.0.0
Device manufacturer:
HUAWEI
Device model:
SHT-W09
```

![photo_2019-01-06_14-27-38](https://user-images.githubusercontent.com/15848443/50736625-ea5e8700-11bf-11e9-9397-2d66443bafb8.jpg)

**Comment by bakaika** [comment]
Attempted to reproduce, didn't get any errors from npm. Only got an error from `create-react-app` due to it attepting to hardlink.

```bash
$ pkg i nodejs
Hit:2 https://termux.net stable InRelease
Ign:3 https://dl.bintray.com/xeffyr/unstable-packages unstable InRelease
Ign:4 https://dl.bintray.com/xeffyr/x11-packages x11 InRelease
Get:5 https://its-pointless.github.io/files termux/extras aarch64 Packages [18.5 kB]
Get:6 https://dl.bintray.com/xeffyr/unstable-packages unstable Release [6065 B]
Hit:6 https://dl.bintray.com/xeffyr/unstable-packages unstable Release
Get:7 https://dl.bintray.com/xeffyr/x11-packages x11 Release [6055 B]
Hit:7 https://dl.bintray.com/xeffyr/x11-packages x11 Release
Fetched 18.5 kB in 3s (4874 B/s)
Reading package lists... Done
Building dependency tree
Reading state information... Done
All packages are up to date.
Reading package lists... Done
Building dependency tree
Reading state information... Done
nodejs is already the newest version (11.9.0).
nodejs set to manually installed.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

$ npm i -g create-react-app
/data/data/com.termux/files/usr/bin/create-react-app -> /data/data/com.termux/files/usr/lib/node_modules/create-react-app/index.js
+ create-react-app@2.1.5
added 63 packages from 20 contributors in 11.52s

$ create-react-app app
Creating a new React app in /data/data/com.termux/files/home/app.

Installing packages. This might take a couple of minutes.
Installing react, react-dom, and react-scripts...

+ react-dom@16.8.1
+ react@16.8.1
+ react-scripts@2.1.5
added 1847 packages from 719 contributors and audited 36343 packages in 178.284s
found 0 vulnerabilities

/data/data/com.termux/files/home/app/node_modules/react-scripts/scripts/init.js:153
      throw err;
      ^

Error: EACCES: permission denied, link '/data/data/com.termux/files/home/app/gitignore' -> '/data/data/com.termux/files/home/app/.gitignore'
    at Object.linkSync (fs.js:955:3)
    at tryRenameSync (/data/data/com.termux/files/home/app/node_modules/fs-extra/lib/move-sync/index.js:40:12)
    at Object.moveSync (/data/data/com.termux/files/home/app/node_modules/fs-extra/lib/move-sync/index.js:22:3)
    at module.exports (/data/data/com.termux/files/home/app/node_modules/react-scripts/scripts/init.js:141:8)
    at [eval]:3:14
    at Script.runInThisContext (vm.js:123:20)
    at Object.runInThisContext (vm.js:312:38)
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (internal/modules/cjs/loader.js:734:30)
    at evalScript (internal/process/execution.js:56:25)

Aborting installation.
  node  has failed.

Deleting generated file... node_modules
Deleting generated file... package.json
Done.
```

Perhaps use yarn? `npm i -g yarn`.

```bash
$ npm i -g yarn
/data/data/com.termux/files/usr/bin/yarn -> /data/data/com.termux/files/usr/lib/node_modules/yarn/bin/yarn.js
/data/data/com.termux/files/usr/bin/yarnpkg -> /data/data/com.termux/files/usr/lib/node_modules/yarn/bin/yarn.js
+ yarn@1.13.0
added 1 package in 2.37s

$ create-react-app app

Creating a new React app in /data/data/com.termux/files/home/app.

Installing packages. This might take a couple of minutes.
Installing react, react-dom, and react-scripts...

yarn add v1.13.0
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.2.7: The platform "android" is incompatible with this module.
info "fsevents@1.2.7" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@1.2.4: The platform "android" is incompatible with this module.
info "fsevents@1.2.4" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning "react-scripts > pnp-webpack-plugin > ts-pnp@1.0.0" has unmet peer dependency "typescript@*".
[4/4] Building fresh packages...
success Saved lockfile.
success Saved 4 new dependencies.
info Direct dependencies
├─ react-dom@16.8.1
├─ react-scripts@2.1.5
└─ react@16.8.1
info All dependencies
├─ react-dev-utils@7.0.3
├─ react-dom@16.8.1
├─ react-scripts@2.1.5
└─ react@16.8.1
Done in 68.01s.
/data/data/com.termux/files/home/app/node_modules/react-scripts/scripts/init.js:153
      throw err;
      ^

Error: EACCES: permission denied, link '/data/data/com.termux/files/home/app/gitignore' -> '/data/data/com.termux/files/home/app/.gitignore'
    at Object.linkSync (fs.js:955:3)
    at tryRenameSync (/data/data/com.termux/files/home/app/node_modules/fs-extra/lib/move-sync/index.js:40:12)
    at Object.moveSync (/data/data/com.termux/files/home/app/node_modules/fs-extra/lib/move-sync/index.js:22:3)
    at module.exports (/data/data/com.termux/files/home/app/node_modules/react-scripts/scripts/init.js:141:8)
    at [eval]:3:14
    at Script.runInThisContext (vm.js:123:20)
    at Object.runInThisContext (vm.js:312:38)
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (internal/modules/cjs/loader.js:734:30)
    at evalScript (internal/process/execution.js:56:25)

Aborting installation.
  node  has failed.

Deleting generated file... node_modules
Deleting generated file... package.json
Deleting generated file... yarn.lock
Done.
```

**Comment by ReemaGowda** [comment]
![image](https://user-images.githubusercontent.com/37684418/58525272-345cff00-8199-11e9-9543-9f92251bce27.png)
Had a similar issue, I just restart my mac it started working all fine

**Comment by darwinfont** [comment]
Estoy presentando el mismo problema y ejecuto todos los comandos al pie de la letra y nada

**Comment by darwinfont** [comment]
![Screenshot_20210225-190041](https://user-images.githubusercontent.com/61401618/109225317-dd37f400-779b-11eb-807c-fb777795f9db.png)

**Comment by thunder-coding** [comment]
Check out https://github.com/npm/cli/wiki/%22cb()-never-called%3F-Exit-handler-never-called%3F-I'm-having-the-same-problem!%22. Every exit handler error is unique and is really hard to crack out and find the root cause of the issue.

For a popular npm package `mathjs`, I could fix it by removing package-lock.json and running `npm install`, weird right? The npm team is tracking the issue here https://github.com/npm/statusboard/issues/395
