### ISSUE TITLE
CVS segmentation fault

### ISSUE THREAD

**Issue by Keith-S-Thompson** [termux/termux-packages#3300]
**Problem description**
Some CVS commands die with a segmentation fault. The script below demonstrates the problem with the `cvs import` command, but I've also seen it with `cvs update`.

I see the problem on devices running Android 6.0.1 and 7.1.1. It does **not** occur under Android 8.1.0.

I have a CVS repo that I regularly update. I've been able to work around this bug by deleting the directory tree before checking it out, rather than updating it in place.

**Steps to reproduce**
The following script demonstrates the problem. It requires the `cvs` package to be installed.

If I manually run the `cvs import` command under `gdb`, it indicates that the seg fault occurs in `mbsnrtowcs`, with a possibly corrupt stack:

```
(gdb) run -d /data/data/com.termux/files/home/cvs-bug-demo-24982/REPO import -m Message tree vendortag releasetag
Starting program: /data/data/com.termux/files/usr/bin/cvs -d /data/data/com.termux/files/home/cvs-bug-demo-24982/REPO import -m Message tree vendortag releasetag

Program received signal SIGSEGV, Segmentation fault.
0xb6ed5762 in mbsnrtowcs () from /system/lib/libc.so
(gdb) where
#0  0xb6ed5762 in mbsnrtowcs () from /system/lib/libc.so
#1  0xb6ed586e in mbsrtowcs () from /system/lib/libc.so
#2  0x2a048bbc in ?? ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
(gdb) 
```

Script follows:
```
#!/bin/bash

# Demonstrate a CVS bug (seg fault) under Termux on Android

try() {
    echo "% $*"
    "$@" || exit $?
}

tmpdir=$HOME/cvs-bug-demo-$$
repo=$tmpdir/REPO
tree=$tmpdir/tree
checkout=$tmpdir/checkout

try mkdir $tmpdir

try rm -rf $repo $tree $checkout

try mkdir $repo
try cvs -d $repo init

try mkdir $tree
try cd $tree

echo hello > $tree/hello.txt
try cat $tree/hello.txt

try cvs -d $repo import -m Message tree vendortag releasetag

try mkdir $checkout
try cd $checkout
try cvs -d $repo checkout tree

try cd tree
try cvs update

try cd $checkout/tree
try cvs log hello.txt
```

Output of the script:
```
$ cvs-bug-demo 
% mkdir /data/data/com.termux/files/home/cvs-bug-demo-19204
% rm -rf /data/data/com.termux/files/home/cvs-bug-demo-19204/REPO /data/data/com.termux/files/home/cvs-bug-demo-19204/tree /data/data/com.termux/files/home/cvs-bug-demo-19204/checkout
% mkdir /data/data/com.termux/files/home/cvs-bug-demo-19204/REPO
% cvs -d /data/data/com.termux/files/home/cvs-bug-demo-19204/REPO init
% mkdir /data/data/com.termux/files/home/cvs-bug-demo-19204/tree
% cd /data/data/com.termux/files/home/cvs-bug-demo-19204/tree
% cat /data/data/com.termux/files/home/cvs-bug-demo-19204/tree/hello.txt
hello
% cvs -d /data/data/com.termux/files/home/cvs-bug-demo-19204/REPO import -m Message tree vendortag releasetag
/data/data/com.termux/files/home/bin/cvs-bug-demo: line 8: 19211 Segmentation fault      "$@"
```

**Expected behavior**
The script should create, initialize, and checkout from a new CVS repo, and show the output of `cvs log` from a file in the repo. This is in fact what happens under Android 8.1.0. Output follows (problem **not** occurring):

```
$ cvs-bug-demo
% mkdir /data/data/com.termux/files/home/cvs-bug-demo-5499
% rm -rf /data/data/com.termux/files/home/cvs-bug-demo-5499/REPO /data/data/com.termux/files/home/cvs-bug-demo-5499/tree /data/data/com.termux/files/home/cvs-bug-demo-5499/checkout
% mkdir /data/data/com.termux/files/home/cvs-bug-demo-5499/REPO
% cvs -d /data/data/com.termux/files/home/cvs-bug-demo-5499/REPO init
% mkdir /data/data/com.termux/files/home/cvs-bug-demo-5499/tree
% cd /data/data/com.termux/files/home/cvs-bug-demo-5499/tree
% cat /data/data/com.termux/files/home/cvs-bug-demo-5499/tree/hello.txt
hello
% cvs -d /data/data/com.termux/files/home/cvs-bug-demo-5499/REPO import -m Message tree vendortag releasetag
N tree/hello.txt

No conflicts created by this import

% mkdir /data/data/com.termux/files/home/cvs-bug-demo-5499/checkout
% cd /data/data/com.termux/files/home/cvs-bug-demo-5499/checkout
% cvs -d /data/data/com.termux/files/home/cvs-bug-demo-5499/REPO checkout tree
U tree/hello.txt
% cd tree
% cvs update
% cd /data/data/com.termux/files/home/cvs-bug-demo-5499/checkout/tree
% cvs log hello.txt

RCS file: /data/data/com.termux/files/home/cvs-bug-demo-5499/REPO/tree/hello.txt,v
Working file: hello.txt
head: 1.1
branch: 1.1.1
locks: strict
access list:
symbolic names:
        releasetag: 1.1.1.1
        vendortag: 1.1.1
keyword substitution: kv
total revisions: 2;     selected revisions: 2
description:
----------------------------
revision 1.1
date: 2019-01-29 20:23:20 -0800;  author: u0_a136;  state: Exp;  commitid: 1005C5126B81584E9B4;
branches:  1.1.1;
Initial revision
----------------------------
revision 1.1.1.1
date: 2019-01-29 20:23:20 -0800;  author: u0_a136;  state: Exp;  lines: +0 -0;  commitid: 1005C5126B81584E9B4;
Message
=============================================================================
```

**Additional information**
```
$ termux-info
Updatable packages:
All packages up to date
System information:
Linux localhost 3.10.40-gc7ebca13933 #1 SMP PREEMPT Wed Aug 16 15:25:44 UTC 2017 armv7l Android
Termux-packages arch:
arm
Android version:
7.1.1
Device manufacturer:
motorola
Device model:
Nexus 6
```

**Comment by Keith-S-Thompson** [comment]
Glad to see this was fixed.

Amusingly, the fix showed up after I (finally!) migrated my CVS repos to Git. Oh, well. 8-)}

**Comment by Grimler91** [comment]
@Keith-S-Thompson yeah, sorry for the long wait. 

I have not verified that the commit fixed the issue though (it only happens on some devices and I am unable to reproduce it). The fix apparently did not work for mediainfo (as seen in https://github.com/termux/termux-packages/issues/5124), so I don't know if it worked here either
