### ISSUE TITLE
problem about ruby

### ISSUE THREAD

**Issue by huitc** [termux/termux-packages#3457]
`$ gem`
```
Traceback (most recent call last):
        19: from /data/data/com.termux/files/usr/bin/gem:9:in `<main>'
        18: from /data/data/com.termux/files/usr/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        17: from /data/data/com.termux/files/usr/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        16: from /data/data/com.termux/files/usr/lib/ruby/site_ruby/2.6.0/rubygems/gem_runner.rb:86:in `<top (required)>'
        15: from /data/data/com.termux/files/usr/lib/ruby/site_ruby/2.6.0/rubygems.rb:1111:in `load_plugins'
        14: from /data/data/com.termux/files/usr/lib/ruby/site_ruby/2.6.0/rubygems.rb:546:in `find_latest_files'
        13: from /data/data/com.termux/files/usr/lib/ruby/site_ruby/2.6.0/rubygems/specification.rb:1131:in `latest_specs'
        12: from /data/data/com.termux/files/usr/lib/ruby/site_ruby/2.6.0/rubygems/specification.rb:747:in `_all'
        11: from /data/data/com.termux/files/usr/lib/ruby/site_ruby/2.6.0/rubygems/specification.rb:826:in `stubs'
        10: from /data/data/com.termux/files/usr/lib/ruby/site_ruby/2.6.0/rubygems/specification.rb:788:in `installed_stubs'
         9: from /data/data/com.termux/files/usr/lib/ruby/site_ruby/2.6.0/rubygems/specification.rb:795:in `map_stubs'
         8: from /data/data/com.termux/files/usr/lib/ruby/site_ruby/2.6.0/rubygems/specification.rb:795:in `flat_map'
         7: from /data/data/com.termux/files/usr/lib/ruby/site_ruby/2.6.0/rubygems/specification.rb:795:in `each'
         6: from /data/data/com.termux/files/usr/lib/ruby/site_ruby/2.6.0/rubygems/specification.rb:798:in `block in map_stubs'
         5: from /data/data/com.termux/files/usr/lib/ruby/site_ruby/2.6.0/rubygems/specification.rb:774:in `gemspec_stubs_in'
         4: from /data/data/com.termux/files/usr/lib/ruby/site_ruby/2.6.0/rubygems/specification.rb:774:in `select'
         3: from /data/data/com.termux/files/usr/lib/ruby/site_ruby/2.6.0/rubygems/stub_specification.rb:204:in `valid?'
         2: from /data/data/com.termux/files/usr/lib/ruby/site_ruby/2.6.0/rubygems/stub_specification.rb:114:in `data'
         1: from /data/data/com.termux/files/usr/lib/ruby/site_ruby/2.6.0/rubygems/stub_specification.rb:114:in `open'
/data/data/com.termux/files/usr/lib/ruby/site_ruby/2.6.0/rubygems/stub_specification.rb:114:in `initialize': Permission denied @ rb_sysopen - /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/specifications/bundler-2.0.1.gemspec (Errno::EACCES)
```

**Comment by huitc** [comment]
`ruby/stable,now 2.6.1-1 aarch64 [installed]`
`Linux localhost 4.4.78-perf-gdaac017 #1 SMP PREEMPT Fri Feb 15 21:20:47 CST 2019 aarch64 Android`

**Comment by xeffyr** [comment]
Do not install anything with ROOT (su/tsu/tsudo/sudo).

**Comment by huitc** [comment]
...

**Comment by huitc** [comment]
So I can't do anything about it?
