### ISSUE TITLE
Getsploit Error

### ISSUE THREAD

**Issue by ng1nX4O4** [termux/termux-packages#4220]
I Have Installed Getsploit Using `pip install getsploit``

But When I Try To Run It Using `getsploit` it gives the following error

```$ getsploit
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/bin/getsploit", line 11, in <module>
    load_entry_point('getsploit==0.3.3', 'console_scripts', 'getsploit')()
  File "/data/data/com.termux/files/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 487, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/data/data/com.termux/files/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2728, in load_entry_point
    return ep.load()
  File "/data/data/com.termux/files/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2346, in load
    return self.resolve()
  File "/data/data/com.termux/files/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2352, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/data/data/com.termux/files/usr/lib/python2.7/site-packages/getsploit/getsploit.py", line 8, in <module>
    import vulners
  File "/data/data/com.termux/files/usr/lib/python2.7/site-packages/vulners/__init__.py", line 5, in <module>
    from vulners.api import Vulners
  File "/data/data/com.termux/files/usr/lib/python2.7/site-packages/vulners/api.py", line 26, in <module>
    class Vulners(object):
  File "/data/data/com.termux/files/usr/lib/python2.7/site-packages/vulners/api.py", line 177, in Vulners
    @rate_limited(api_rate_limits)
  File "/data/data/com.termux/files/usr/lib/python2.7/site-packages/vulners/common/ratelimit.py", line 95, in rate_limited
    LT = LastTime('rate_limited')
  File "/data/data/com.termux/files/usr/lib/python2.7/site-packages/vulners/common/ratelimit.py", line 40, in __init__
    self.ratelock = multiprocessing.Lock()
  File "/data/data/com.termux/files/usr/lib/python2.7/multiprocessing/__init__.py", line 176, in Lock
    return Lock()
  File "/data/data/com.termux/files/usr/lib/python2.7/multiprocessing/synchronize.py", line 147, in __init__
    SemLock.__init__(self, SEMAPHORE, 1, 1)
  File "/data/data/com.termux/files/usr/lib/python2.7/multiprocessing/synchronize.py", line 75, in __init__
    sl = self._semlock = _multiprocessing.SemLock(kind, value, maxvalue)
OSError: [Errno 38] Function not implemented
$

**Comment by xeffyr** [comment]
Termux doesn't have support for *semaphores* (sem_open(), etc...).
Your script won't work.
