### ISSUE TITLE
aapt broke: library can't find logging function

### ISSUE THREAD

**Issue by joakim-noah** [termux/termux-packages#444]
Any invocation of `aapt` now fails with this error, likely because of the aapt package update last weekend:
```
CANNOT LINK EXECUTABLE: could not load library "libandroid-cutils.so" needed by "aapt";
caused by cannot locate symbol "__android_log_print" referenced by "libandroid-cutils.so"...
```
It looks like the problem is that `libandroid-cutils.so` isn't linked against `liblog.so` or `libcutils.so`, both of which provide `__android_log_print`, as `ldd ~/../usr/lib/libandroid-cutils.so` shows this:
```
libdl.so
libc.so
```
I think this can be fixed by linking one of those libraries in with `libandroid-cutils.so`.  You may want to check it works by running `aapt --help` in Termux to make sure.

**Comment by fornwall** [comment]
@joakim-noah Can you check the latest version (`7.0.0.6`) fixes this problem for you?

Strangely enough, I couldn't reproduce the problem when testing on some devices...

**Comment by joakim-noah** [comment]
I think your adding `-llog` when linking fixed that problem, but I now get another error:
```
CANNOT LINK EXECUTABLE: could not load library "libandroid-cutils.so" needed by "aapt";
caused by cannot locate symbol "__android_log_print" referenced by "libandroid-cutils.so"...
```
Can you reproduce this one?  I'll note that it happens on two Android tablets running 5.0 and 5.1.1, but `aapt` works fine on a phone running 6.0.1.

Is there some difference in how the dynamic linker works between Android 5 and 6?  Maybe you're hitting some change like that.

**Comment by fornwall** [comment]
Thanks - I was able to reproduce it on an Android 5.x device (probably due to difference in dynamic linker as you say).

This should now be fixed also on 5.x devices in version `7.0.0.6-1` - let me know if the problem remains for you!

**Comment by joakim-noah** [comment]
Yes, aapt works again, thanks for fixing!

**Comment by Auxilus** [comment]
I am getting this error again ,

```
apktool b base
Java HotSpot(TM) 64-Bit Server VM warning: No monotonic clock was available - timed services may be adversely affected if the time-of-day clock changes
Picked up JAVA_TOOL_OPTIONS: -Duser.home=/data/data/com.termux/files/home
I: Using Apktool 2.3.0
I: Checking whether sources has changed...
I: Checking whether resources has changed...
I: Building apk file...
Exception in thread "main" W: CANNOT LINK EXECUTABLE: library "libandroid-cutils.so" not found
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [aapt, p, --forced-package-id, 127, --min-sdk-version, 9, --target-sdk-version, 23, --version-code, 130, --version-name, 0.3.130, --no-version-vectors, -F, /data/data/com.termux/files/home/apps/mirage/base/dist/base.apk, -0, arsc, -0, arsc, -A, /data/data/com.termux/files/home/apps/mirage/base/assets, /data/data/com.termux/files/home/apps/mirage/base/build/apk]
        at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:454)
        at brut.androlib.Androlib.buildApk(Androlib.java:682)
        at brut.androlib.Androlib.build(Androlib.java:322)
        at brut.androlib.Androlib.build(Androlib.java:270)
        at brut.apktool.Main.cmdBuild(Main.java:224)
        at brut.apktool.Main.main(Main.java:75)
Caused by: brut.common.BrutException: could not exec (exit code = 1): [aapt, p, --forced-package-id, 127, --min-sdk-version, 9, --target-sdk-version, 23, --version-code, 130, --version-name, 0.3.130, --no-version-vectors, -F, /data/data/com.termux/files/home/apps/mirage/base/dist/base.apk, -0, arsc, -0, arsc, -A, /data/data/com.termux/files/home/apps/mirage/base/assets, /data/data/com.termux/files/home/apps/mirage/base/build/apk]
        at brut.util.OS.exec(OS.java:95)
        at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:448)
        ... 5 more
[17:48]~/a/mirage >
```
