### ISSUE TITLE
python build does not disable HAVE_SEM_OPEN and results in multiprocessing crash

### ISSUE THREAD

**Issue by grandrew** [termux/termux-packages#4698]
Python 3.8 seems to be compiled with wrong options

Steps to reproduse

```bash
$ pip install flake8
$ flake8
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.8/multiprocessing/synchronize.py", line 28, in <module>
    from _multiprocessing import SemLock, sem_unlink
ImportError: cannot import name 'SemLock' from '_multiprocessing' (/data/data/com.termux/files/usr/lib/python3.8/lib-dynload/_multiprocessing.cpython-38.so)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/bin/flake8", line 8, in <module>
    sys.exit(main())
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/flake8/main/cli.py", line 18, in main
    app.run(argv)
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/flake8/main/application.py", line 393, in run
    self._run(argv)
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/flake8/main/application.py", line 381, in _run
    self.run_checks()
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/flake8/main/application.py", line 300, in run_checks
    self.file_checker_manager.run()
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/flake8/checker.py", line 329, in run
    self.run_parallel()
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/flake8/checker.py", line 277, in run_parallel
    pool = multiprocessing.Pool(self.jobs, _pool_init)
  File "/data/data/com.termux/files/usr/lib/python3.8/multiprocessing/context.py", line 119, in Pool
    return Pool(processes, initializer, initargs, maxtasksperchild,
  File "/data/data/com.termux/files/usr/lib/python3.8/multiprocessing/pool.py", line 191, in __init__
    self._setup_queues()
  File "/data/data/com.termux/files/usr/lib/python3.8/multiprocessing/pool.py", line 343, in _setup_queues
    self._inqueue = self._ctx.SimpleQueue()
  File "/data/data/com.termux/files/usr/lib/python3.8/multiprocessing/context.py", line 113, in SimpleQueue
    return SimpleQueue(ctx=self.get_context())
  File "/data/data/com.termux/files/usr/lib/python3.8/multiprocessing/queues.py", line 336, in __init__
    self._rlock = ctx.Lock()
  File "/data/data/com.termux/files/usr/lib/python3.8/multiprocessing/context.py", line 67, in Lock
    from .synchronize import Lock
  File "/data/data/com.termux/files/usr/lib/python3.8/multiprocessing/synchronize.py", line 30, in <module>
    raise ImportError("This platform lacks a functioning sem_open" +
ImportError: This platform lacks a functioning sem_open implementation, therefore, the required synchronization primitives needed will not function, see issue 3770.
$
```

**Comment by xeffyr** [comment]
Everything correct, semaphores are disabled because they are not supported on Android anyway.
