### ISSUE TITLE
cannot import numpy

### ISSUE THREAD

**Issue by makerdark98** [termux/termux-packages#488]
>>> import numpy

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/data/data/com.termux/files/usr/lib/python3.5/site-packages/numpy/__init__.py", line 142, in <module>
    from . import add_newdocs
  File "/data/data/com.termux/files/usr/lib/python3.5/site-packages/numpy/add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "/data/data/com.termux/files/usr/lib/python3.5/site-packages/numpy/lib/__init__.py", line 8, in <module>
    from .type_check import *
  File "/data/data/com.termux/files/usr/lib/python3.5/site-packages/numpy/lib/type_check.py", line 11, in <module>
    import numpy.core.numeric as _nx
  File "/data/data/com.termux/files/usr/lib/python3.5/site-packages/numpy/core/__init__.py", line 21, in <module>
    from . import umath
ImportError: dlopen failed: cannot locate symbol "__mulodi4" referenced by "/data/data/com.termux/files/usr/lib/python3.5/site-packages/numpy/core/umath.cpython-35m-arm-linux-gnueabi.so"...

I search this , I found I must install gcc but gcc remove apt list(i installed clang but still cannot operate)

How can I fix it?

**Comment by its-pointless** [comment]
the __mulodi4 means you haven't linked against compiler_rt 
i think you need to specifically add -lm and -lcompiler_rt flags to compiler and it will work

**Comment by makerdark98** [comment]
I try
LDFLAGS=" -lm -lcompiler_rt" pip install numpy
But I didn't work.
How can I add -lm -lcompiler_rt flags to compiler while installing numpy?

**Comment by makerdark98** [comment]
Ooooooh~
I fixed it
LDFLAGS="-lm -lcompiler_rt" pip install --no-cache-dir numpy
I think I was stupid.
Thanks your answer add LDFLAGS
I am really really happy . Yeah!

**Comment by che769776082** [comment]
Thanks for the solution. I meet the same situation.

**Comment by 4thirteen2one** [comment]
Thanks a lot for solving my problem too!

**Comment by its-pointless** [comment]
For the sake of completeness I have scipy working as well in a repo of mine.

**Comment by Eliran79** [comment]
Can anyone explain me the purpose of:LDFLAGS="-lm -lcompiler_rt" ?

My termux is *8 times faster them my (i3 4G ram) laptop and I suspect it has something to do with it...
