### ISSUE TITLE
Node.js npm segfaults

### ISSUE THREAD

**Issue by pollen5** [termux/termux-packages#4898]
All was fine but i wanted to update my Node.js installation so i did a fresh install of `nodejs-lts` but npm isn't working:
```sh
pollen@localhost ~> npm
fish: 'npm' terminated by signal SIGSEGV (Address boundary error)
```
`termux-info`
```
Subscribed repositories:
https://dl.bintray.com/xeffyr/x11-packages x11/main
https://dl.bintray.com/xeffyr/unstable-packages unstable/main
https://dl.bintray.com/grimler/science-packages-24 science/stable
https://its-pointless.github.io/files/24 termux/extras
https://its-pointless.github.io/files/24 termux/extras
https://dl.bintray.com/grimler/game-packages-24 games/stable
https://dl.bintray.com/termux/termux-packages-24 stable/main
System information:
Linux localhost 4.9.117+ #1 SMP PREEMPT Fri Apr 19 13:20:06 CST 2019 armv8l Android
Termux-packages arch:
arm
Android version:
9
Device manufacturer:
HUAWEI
Device model:
AMN-LX9
```

**Comment by pollen5** [comment]
Very strange, seems to be related to connectivity, it works offline but when I'm connected to internet it segfaults.

**Comment by pollen5** [comment]
Tried to debug it and seems like it's coming from openssl's libcrypto.so i have latest openssl installed.
```
pollen@localhost ~> gdb node
GNU gdb (GDB) 8.3
Copyright (C) 2019 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "arm-linux-androideabi".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from node...
(No debugging symbols found in node)
(gdb) r /data/data/com.termux/files/usr/bin/npm
Starting program: /data/data/com.termux/files/usr/bin/node /data/data/com.termux/files/usr/bin/npm

Program received signal SIGILL, Illegal instruction.
0xf5378346 in ?? () from /data/data/com.termux/files/usr/lib/libcrypto.so.1.1
(gdb) bt
#0  0xf5378346 in ?? () from /data/data/com.termux/files/usr/lib/libcrypto.so.1.1
#1  0xf537824c in ?? () from /data/data/com.termux/files/usr/lib/libcrypto.so.1.1
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
```

**Comment by xeffyr** [comment]
> Program received signal SIGILL, Illegal instruction.

This is **expected behaviour** of libcrypto under GDB. Use command
```
handle SIGILL nostop
```
before debugging.

**Comment by pollen5** [comment]
I just installed the `nodejs` package over LTS, (Node.js 13) which works fine here, no idea why LTS fails, all good but the npm that ships with this version is outdated and warns about Node.js 13 not supported, it can be fixed by updating npm manually but Node also released a new patch to fix the bundled npm which i recommend updating the Node.js package.
