### ISSUE TITLE
New Package Request: emsdk

### ISSUE THREAD

**Issue by xloem** [termux/termux-packages#5043]
**Package description**

Emscripten compiles C code to web-compatible files.

**Link to home page and sources**
1. Home page: https://emscripten.org
2. Source code: https://github.com/emscripten-core/emsdk

**Additional information**
Have you compiled or tried to compile the package on device?
* If it didn't work then please provide the error you ran into.
  `./emsdk install sdk-fastcomp-master-32bit` seems to start ok but uses too much storage space for my system to handle
* If it did work then please share any patches that you had to apply.

**Comment by oxr463** [comment]
This is a heavy project. It's hard to maintain even for desktop distributions, (I recently bumped the Alpine package and it was a nightmare).

**Comment by RossComputerGuy** [comment]
Why is it hard to maintain?

**Comment by oxr463** [comment]
> Why is it hard to maintain?

Well for one, they forked llvm/clang.. There is just a lot to it, and not all of it has been upstreamed yet. Moving to new releases requires drastic changes.

**Comment by truboxl** [comment]
Ok I managed to build emscripten and others via emsdk on 4GB RAM, 8 core phone under half a day or less
`./emsdk install llvm-git-main-64bit binaryen-master-64bit emscripten-master-64bit --build=Release -j6`

The resulting emsdk folder will use less than 6GB or ~5.6GB space
I will checkout how to integrate binaryen from termux-package so that I can drop building that...

However trying to do a simple hello world is problematic
```
$ paste hello.c
#include <stdio.h>

int main() {
    puts("Hello world!");
    return 0;
}
```
```
$ emcc hello.c
shared:INFO: (Emscripten: config changed, clearing cache)
shared:INFO: (Emscripten: Running sanity checks)
cache:INFO: generating system headers: sysroot_install.stamp... (this will be cached in "/data/data/com.termux/files/home/emsdk/emscripten/master/cache/sysroot_install.stamp" for subsequent builds)
cache:INFO:  - ok
cache:INFO: generating system library: sysroot/lib/wasm32-emscripten/libgl.a... (this will be cached in "/data/data/com.termux/files/home/emsdk/emscripten/master/cache/sysroot/lib/wasm32-emscripten/libgl.a" for subsequent builds)
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.9/multiprocessing/synchronize.py", line 28, in <module>
    from _multiprocessing import SemLock, sem_unlink
ImportError: cannot import name 'SemLock' from '_multiprocessing' (/data/data/com.termux/files/usr/lib/python3.9/lib-dynload/_multiprocessing.cpython-39.so)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/data/com.termux/files/home/emsdk/emscripten/master/emcc.py", line 3304, in <module>
    sys.exit(main(sys.argv))
  File "/data/data/com.termux/files/home/emsdk/emscripten/master/emcc.py", line 3297, in main
    ret = run(args)
  File "/data/data/com.termux/files/home/emsdk/emscripten/master/emcc.py", line 2105, in run
    extra_files_to_link += system_libs.calculate([f for _, f in sorted(temp_files)] + extra_files_to_link, link_as_cxx, forced=forced_stdlibs)
  File "/data/data/com.termux/files/home/emsdk/emscripten/master/tools/system_libs.py", line 1468, in calculate
    add_library(system_libs_map['libgl'])
  File "/data/data/com.termux/files/home/emsdk/emscripten/master/tools/system_libs.py", line 1452, in add_library
    libs_to_link.append((lib.get_path(), need_whole_archive))
  File "/data/data/com.termux/files/home/emsdk/emscripten/master/tools/system_libs.py", line 318, in get_path
    return shared.Cache.get_lib(self.get_filename(), self.build)
  File "/data/data/com.termux/files/home/emsdk/emscripten/master/tools/cache.py", line 130, in get_lib
    return self.get(name, *args, **kwargs)
  File "/data/data/com.termux/files/home/emsdk/emscripten/master/tools/cache.py", line 158, in get
    creator(cachename)
  File "/data/data/com.termux/files/home/emsdk/emscripten/master/tools/system_libs.py", line 372, in build
    create_lib(out_filename, self.build_objects(build_dir))
  File "/data/data/com.termux/files/home/emsdk/emscripten/master/tools/system_libs.py", line 365, in build_objects
    run_build_commands(commands)
  File "/data/data/com.termux/files/home/emsdk/emscripten/master/tools/system_libs.py", line 101, in run_build_commands
    pool = building.get_multiprocessing_pool()
  File "/data/data/com.termux/files/home/emsdk/emscripten/master/tools/building.py", line 204, in get_multiprocessing_pool
    multiprocessing_pool = multiprocessing.Pool(processes=cores, initializer=g_multiprocessing_initializer, initargs=child_env)
  File "/data/data/com.termux/files/usr/lib/python3.9/multiprocessing/context.py", line 119, in Pool
    return Pool(processes, initializer, initargs, maxtasksperchild,
  File "/data/data/com.termux/files/usr/lib/python3.9/multiprocessing/pool.py", line 191, in __init__
    self._setup_queues()
  File "/data/data/com.termux/files/usr/lib/python3.9/multiprocessing/pool.py", line 343, in _setup_queues
    self._inqueue = self._ctx.SimpleQueue()
  File "/data/data/com.termux/files/usr/lib/python3.9/multiprocessing/context.py", line 113, in SimpleQueue
    return SimpleQueue(ctx=self.get_context())
  File "/data/data/com.termux/files/usr/lib/python3.9/multiprocessing/queues.py", line 342, in __init__
    self._rlock = ctx.Lock()
  File "/data/data/com.termux/files/usr/lib/python3.9/multiprocessing/context.py", line 67, in Lock
    from .synchronize import Lock
  File "/data/data/com.termux/files/usr/lib/python3.9/multiprocessing/synchronize.py", line 30, in <module>
    raise ImportError("This platform lacks a functioning sem_open" +
ImportError: This platform lacks a functioning sem_open implementation, therefore, the required synchronization primitives needed will not function, see issue 3770.
```

Someone beat me to it long ago and even fix some issues 😂
https://github.com/emscripten-core/emscripten/issues/9098
However, using `EMCC_CORES=1` is slow and takes time to build cache.
```
$ EMCC_CORES=1 emcc hello.c
cache:INFO: generating system library: sysroot/lib/wasm32-emscripten/libgl.a... (this will be cached in "/data/data/com.termux/files/home/emsdk/emscripten/master/cache/sysroot/lib/wasm32-emscripten/libgl.a" for subsequent builds)
cache:INFO:  - ok
cache:INFO: generating system library: sysroot/lib/wasm32-emscripten/libal.a... (this will be cached in "/data/data/com.termux/files/home/emsdk/emscripten/master/cache/sysroot/lib/wasm32-emscripten/libal.a" for subsequent builds)
cache:INFO:  - ok
cache:INFO: generating system library: sysroot/lib/wasm32-emscripten/libhtml5.a... (this will be cached in "/data/data/com.termux/files/home/emsdk/emscripten/master/cache/sysroot/lib/wasm32-emscripten/libhtml5.a" for subsequent builds)
cache:INFO:  - ok
cache:INFO: generating system library: sysroot/lib/wasm32-emscripten/libc.a... (this will be cached in "/data/data/com.termux/files/home/emsdk/emscripten/master/cache/sysroot/lib/wasm32-emscripten/libc.a" for subsequent builds)
cache:INFO:  - ok
cache:INFO: generating system library: sysroot/lib/wasm32-emscripten/libcompiler_rt.a... (this will be cached in "/data/data/com.termux/files/home/emsdk/emscripten/master/cache/sysroot/lib/wasm32-emscripten/libcompiler_rt.a" for subsequent builds)
cache:INFO:  - ok
cache:INFO: generating system library: sysroot/lib/wasm32-emscripten/libc++-noexcept.a... (this will be cached in "/data/data/com.termux/files/home/emsdk/emscripten/master/cache/sysroot/lib/wasm32-emscripten/libc++-noexcept.a" for subsequent builds)
cache:INFO:  - ok
cache:INFO: generating system library: sysroot/lib/wasm32-emscripten/libc++abi-noexcept.a... (this will be cached in "/data/data/com.termux/files/home/emsdk/emscripten/master/cache/sysroot/lib/wasm32-emscripten/libc++abi-noexcept.a" for subsequent builds)
cache:INFO:  - ok
cache:INFO: generating system library: sysroot/lib/wasm32-emscripten/libdlmalloc.a... (this will be cached in "/data/data/com.termux/files/home/emsdk/emscripten/master/cache/sysroot/lib/wasm32-emscripten/libdlmalloc.a" for subsequent builds)
cache:INFO:  - ok
cache:INFO: generating system library: sysroot/lib/wasm32-emscripten/libc_rt_wasm.a... (this will be cached in "/data/data/com.termux/files/home/emsdk/emscripten/master/cache/sysroot/lib/wasm32-emscripten/libc_rt_wasm.a" for subsequent builds)
cache:INFO:  - ok
cache:INFO: generating system library: sysroot/lib/wasm32-emscripten/libsockets.a... (this will be cached in "/data/data/com.termux/files/home/emsdk/emscripten/master/cache/sysroot/lib/wasm32-emscripten/libsockets.a" for subsequent builds)
cache:INFO:  - ok
cache:INFO: generating system asset: generated_struct_info.json... (this will be cached in "/data/data/com.termux/files/home/emsdk/emscripten/master/cache/generated_struct_info.json" for subsequent builds)
cache:INFO:  - ok
```

I think I will closely monitor them moving away from `multiprocessing.Pool` which should solve a lot of slow emscripten issues and Android incompatibility https://github.com/termux/termux-packages/issues/570
https://github.com/emscripten-core/emscripten/pull/13493

With that all out of the way, emscripten on Termux is possible, so maybe we can try restart the effort so that I don't have to build this heavy project every now and then?
```
$ node a.out.js
Hello world!
```

**Comment by truboxl** [comment]
With #6578 merged, you no longer have to waste 6GB+ space and half a day of compiling on-device anymore 🎉

Unless you need the latest version directly from upstream, the `emscripten` package should serve the purpose
After all, `emsdk` is just a package manager for installing `emscripten` and (compililng) its dependencies...
