### ISSUE TITLE
Nodejs-lts crashes when used with yarn

### ISSUE THREAD

**Issue by xeffyr** [termux/termux-packages#5141]
**Problem description**

Crashes with segmentation fault in certain cases, e.g. when used with `yarn`.

**Steps to reproduce**
1. Install nodejs-lts and yarn:
```
pkg install nodejs-lts
pkg install yarn
```

2. Execute `yarn`:
```
$ yarn
yarn install v1.22.4
Segmentation fault
```

**Expected behavior**

Nodejs shouldn't crash during runtime.

**Additional information**

NPM doesn't crash when used.

Termux info:
```
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://main.termux-mirror.ml stable main
# science-repo (sources.list.d/science.list)
deb https://dl.bintray.com/grimler/science-packages-24 science stable
# game-repo (sources.list.d/game.list)
deb https://dl.bintray.com/grimler/game-packages-24 games stable
Updatable packages:
All packages up to date
Android version:
8.0.0
Kernel build information:
Linux localhost 3.18.91-15877854-QB29744875 #1 SMP PREEMPT Mon Mar 9 17:41:37 KST 2020 aarch64 Android
Device manufacturer:
samsung
Device model:
SM-G930F
```

**Comment by xeffyr** [comment]
Just noticed that following lines appear in logcat each time `yarn` is called:
```
04-10 20:47:30.819 22745 22745 E libc    : Access denied finding property "net.dns1"
04-10 20:50:08.348 22830 22830 E libc    : Access denied finding property "net.dns1"
04-10 20:50:22.854 22854 22854 E libc    : Access denied finding property "net.dns1"
```

**Comment by xeffyr** [comment]
GDB backtrace for `nodejs-lts`:
```
#0  addToEnd (p_resultList=<optimized out>, p_entry=0x7fb50743c0) at ../deps/uv/src/unix/android-ifaddrs.c:316
#1  0x00000055575a3958 in interpretAddr (p_hdr=<optimized out>, p_resultList=0x7fffffd0e0, p_numLinks=<optimized out>) at ../deps/uv/src/unix/android-ifaddrs.c:587
#2  0x00000055575a2f90 in interpretAddrs (p_socket=21, p_pid=2580, p_netlinkList=0x7fb51c3140, p_resultList=0x7fffffd0e0, p_numLinks=15)
    at ../deps/uv/src/unix/android-ifaddrs.c:644
#3  0x00000055575a2bd8 in getifaddrs (ifap=0x7fffffd0e0) at ../deps/uv/src/unix/android-ifaddrs.c:692
#4  0x00000055575a12f8 in uv_interface_addresses (addresses=0x7fffffd180, count=0x7fffffd17c) at ../deps/uv/src/unix/linux-core.c:890
#5  0x0000005556ae2fa8 in node::os::GetInterfaceAddresses (args=...) at ../src/node_os.cc:189
#6  0x0000005556c9b160 in v8::internal::FunctionCallbackArguments::Call (this=0x7fffffd370, handler=...) at ../deps/v8/src/api/api-arguments-inl.h:158
#7  0x0000005556c9a52c in v8::internal::(anonymous namespace)::HandleApiCallHelper<false> (isolate=0x7fb508c040, function=..., new_target=..., fun_data=..., receiver=..., 
    args=...) at ../deps/v8/src/builtins/builtins-api.cc:111
#8  0x0000005556c99718 in v8::internal::Builtin_Impl_HandleApiCall (args=..., isolate=0x7fb508c040) at ../deps/v8/src/builtins/builtins-api.cc:141
#9  0x0000005556c99380 in v8::internal::Builtin_HandleApiCall (args_length=6, args_object=0x7fffffd588, isolate=0x7fb508c040) at ../deps/v8/src/builtins/builtins-api.cc:129
#10 0x000000005f28a85c in ?? ()
#11 0x0000000047ca2a01 in ?? ()
Backtrace stopped: previous frame inner to this frame (corrupt stack?)
```

**Comment by xeffyr** [comment]
Fixed in https://github.com/termux/termux-packages/commit/1435b6ff9b6a0b7a2380b36a048e3ada0f09548b.
