### ISSUE TITLE
command `pip list --outdated` fails

### ISSUE THREAD

**Issue by Xohwie1i** [termux/termux-packages#5275]
**Problem description**
Running `pip list --outdated` fails with the following error:

    ERROR: Exception:
    Traceback (most recent call last):
      File "/data/data/com.termux/files/usr/lib/python3.8/multiprocessing/synchronize.py", line 28, in <module>
        from _multiprocessing import SemLock, sem_unlink
    ImportError: cannot import name 'SemLock' from '_multiprocessing' (/data/data/com.termux/files/usr/lib/python3.8/lib-dynload/_multiprocessing.cpython-38.so)
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/pip/_internal/cli/base_command.py", line 188, in _main
        status = self.run(options, args)
      File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/pip/_internal/commands/list.py", line 160, in run
        packages = self.get_outdated(packages, options)
      File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/pip/_internal/commands/list.py", line 167, in get_outdated
        return [
      File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/pip/_internal/commands/list.py", line 167, in <listcomp>
        return [
      File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/pip/_internal/commands/list.py", line 216, in iter_packages_latest_infos
        pool = Pool(DEFAULT_POOLSIZE)
      File "/data/data/com.termux/files/usr/lib/python3.8/multiprocessing/dummy/__init__.py", line 124, in Pool
        return ThreadPool(processes, initializer, initargs)
      File "/data/data/com.termux/files/usr/lib/python3.8/multiprocessing/pool.py", line 922, in __init__
        Pool.__init__(self, processes, initializer, initargs)
      File "/data/data/com.termux/files/usr/lib/python3.8/multiprocessing/pool.py", line 196, in __init__
        self._change_notifier = self._ctx.SimpleQueue()
      File "/data/data/com.termux/files/usr/lib/python3.8/multiprocessing/context.py", line 113, in SimpleQueue
        return SimpleQueue(ctx=self.get_context())
      File "/data/data/com.termux/files/usr/lib/python3.8/multiprocessing/queues.py", line 336, in __init__
        self._rlock = ctx.Lock()
      File "/data/data/com.termux/files/usr/lib/python3.8/multiprocessing/context.py", line 67, in Lock
        from .synchronize import Lock
      File "/data/data/com.termux/files/usr/lib/python3.8/multiprocessing/synchronize.py", line 30, in <module>
        raise ImportError("This platform lacks a functioning sem_open" +
    ImportError: This platform lacks a functioning sem_open implementation, therefore, the required synchronization primitives needed will not function, see issue 3770.

**Steps to reproduce**
run `pip list --outdated`

**Expected behavior**
Should output outdated python packages

**Comment by Grimler91** [comment]
Happens with pip 20.1, downgrading to 20.0.X works. Discussed previously in https://github.com/termux/termux-packages/issues/5222 and linked issues

**Comment by landfillbaby** [comment]
in case you're curious, the next release of pip will have a fix for this, pypa/pip#8167 is the fix, already merged into master

**Comment by voidzero** [comment]
Until this gets pushed to the repos, how can I downgrade pip?

**Comment by landfillbaby** [comment]
`pip install pip==20.0.2`
or you could do what i've done and manually apply https://github.com/pypa/pip/commit/d18ebcfe41c037bc21dcc3b92fc614034c17f3c1.diff to your local pip installation

**Comment by voidzero** [comment]
Ah, perfect. Thank you!

**Comment by landfillbaby** [comment]
also for future-proof checking of pip upgrades:
`pip install -U pip!=20.1`

**Comment by landfillbaby** [comment]
pip 20.1.1 is out! this issue is fixed
