### ISSUE TITLE
python ssl and pip broken

### ISSUE THREAD

**Issue by LeadRDRK** [termux/termux-packages#5473]
Hi,
After installing python 3.8.3, I noticed that pip doesn't want to work correctly anymore and complains about the ssl package not being available. I tried to import the ssl package in the python interpreter and this is what I got:
```
Python 3.8.3 (default, Jun 27 2020, 11:30:16)
[Clang 8.0.7 (https://android.googlesource.com/toolchain/clang b55f2d4ebfd35bf6 on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import ssl                                          
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>                     
  File "/data/data/com.termux/files/usr/lib/python3.8/ssl.py", line 98, in <module>                                 
import _ssl             # if we can't import it, let the error propagate                                    
  ImportError: dlopen failed: cannot locate symbol "COMP_get_type" referenced by "/data/data/com.termux/files/usr/lib/python3.8/lib-dynload/_ssl.cpython-38.so"...      
```

**Comment by Grimler91** [comment]
Hi, I can't reproduce the error. What is your output of `termux-info`?

**Comment by LeadRDRK** [comment]
sorry for being late, here's the output
```
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://termux.org/packages/ stable main
# science-repo (sources.list.d/science.list)
deb https://dl.bintray.com/grimler/science-packages-24 science stable
# game-repo (sources.list.d/game.list)
deb https://dl.bintray.com/grimler/game-packages-24 games stable
Updatable packages:
bash/stable 5.0.17-2 aarch64 [upgradable from: 5.0.17]
bzip2/stable 1.0.8-6 aarch64 [upgradable from: 1.0.8-5]
c-ares/stable 1.16.1-1 aarch64 [upgradable from: 1.16.1]
ca-certificates/stable 20200626 all [upgradable from: 20200101]
clang/stable 9.0.1-8 aarch64 [upgradable from: 9.0.1-7]
command-not-found/stable 1.54 aarch64 [upgradable from: 1.52]
coreutils/stable 8.32-2 aarch64 [upgradable from: 8.32-1]
curl/stable 7.71.0-1 aarch64 [upgradable from: 7.70.0-1]
dash/stable 0.5.11-3 aarch64 [upgradable from: 0.5.11]
diffutils/stable 3.7-3 aarch64 [upgradable from: 3.7-2]
dos2unix/stable 7.4.1-1 aarch64 [upgradable from: 7.4.1]
dpkg/stable 1.20.4-4 aarch64 [upgradable from: 1.20.0-3]
ed/stable 1.16-1 aarch64 [upgradable from: 1.16]
findutils/stable 4.7.0-2 aarch64 [upgradable from: 4.7.0]
gawk/stable 5.1.0-1 aarch64 [upgradable from: 5.1.0]
glib/stable 2.64.3-2 aarch64 [upgradable from: 2.64.3-1]
grep/stable 3.4-1 aarch64 [upgradable from: 3.4]
gzip/stable 1.10-4 aarch64 [upgradable from: 1.10-3]
inetutils/stable 1.9.4-10 aarch64 [upgradable from: 1.9.4-9]
libandroid-glob/stable 0.6-2 aarch64 [upgradable from: 0.6]
libbz2/stable 1.0.8-6 aarch64 [upgradable from: 1.0.8-5]
libcrypt/stable 0.2-3 aarch64 [upgradable from: 0.2-2]
libcurl/stable 7.71.0-1 aarch64 [upgradable from: 7.70.0-1]
libffi/stable 3.3-2 aarch64 [upgradable from: 3.3]
libgcrypt/stable 1.8.5-4 aarch64 [upgradable from: 1.8.5-1]
libgmp/stable 6.2.0-1 aarch64 [upgradable from: 6.2.0]
libicu/stable 66.1-2 aarch64 [upgradable from: 66.1-1]
libllvm/stable 9.0.1-8 aarch64 [upgradable from: 9.0.1-7]
libmpfr/stable 4.0.2-3 aarch64 [upgradable from: 4.0.2-2]
libnghttp2/stable 1.41.0-1 aarch64 [upgradable from: 1.41.0]
libssh2/stable 1.9.0-2 aarch64 [upgradable from: 1.9.0-1]
libtirpc/stable 1.2.6-1 aarch64 [upgradable from: 1.2.6]
libunistring/stable 0.9.10-4 aarch64 [upgradable from: 0.9.10-3]
libuuid/stable 1.0.3-4 aarch64 [upgradable from: 1.0.3-3]
nano/stable 4.9.3-4 aarch64 [upgradable from: 4.9.3-3]
ncurses/stable 6.2.20200222-1 aarch64 [upgradable from: 6.2.20200222]
ncurses-ui-libs/stable 6.2.20200222-1 aarch64 [upgradable from: 6.2.20200222]
nodejs/stable 14.4.0-1 aarch64 [upgradable from: 14.4.0]
openssl/stable 1.1.1g-4 aarch64 [upgradable from: 1.1.1g-2]
pcre/stable 8.44-1 aarch64 [upgradable from: 8.44]
pcre2/stable 10.35-1 aarch64 [upgradable from: 10.35]
python/stable 3.8.3-3 aarch64 [upgradable from: 3.8.3-1]
readline/stable 8.0.4-1 aarch64 [upgradable from: 8.0.4]
sed/stable 4.8-1 aarch64 [upgradable from: 4.8]
tar/stable 1.32-6 aarch64 [upgradable from: 1.32-5]
termux-licenses/stable 2.0-1 all [upgradable from: 1.0]
termux-tools/stable 0.83-1 all [upgradable from: 0.81-3]
unzip/stable 6.0-7 aarch64 [upgradable from: 6.0-5]
util-linux/stable 2.35.2-1 aarch64 [upgradable from: 2.35.2]
zlib/stable 1.2.11-5 aarch64 [upgradable from: 1.2.11-4]
Android version:
10
Kernel build information:
Linux localhost 4.4.177-MinhKer_Q-V14.3_Pro-A305F-20200405 #47 SMP PREEMPT Sun Apr 5 14:25:40 +07 2020 aarch64 Android
Device manufacturer:
unknown
Device model:
Phh-Treble vanilla
```

**Comment by xeffyr** [comment]
@LeadRDRK Time to upgrade your packages. `apt update && apt full-upgrade`

Partial updates aren't supported as well as using older dependencies for packages of "current" version.
