### ISSUE TITLE
Termux is not installed on NoxPlayer

### ISSUE THREAD

**Issue by airvzxf** [termux/termux-packages#5600]
I'm trying to install and use Termux in [NoxPlayer ](https://es.bignox.com)which is a Android emulator for PC/Win focus on Games.

**I used `logcat` and these are the errors during the installation.**
```
E/termux  (16823): Bootstrap error
E/termux  (16823): java.io.FileNotFoundException: /data/data/com.termux/files/usr-staging/include/proc/version.h: open failed: EROFS (Read-only file system)
E/termux  (16823):      at libcore.io.IoBridge.open(IoBridge.java:456)
E/termux  (16823):      at java.io.FileOutputStream.<init>(FileOutputStream.java:87)
E/termux  (16823):      at java.io.FileOutputStream.<init>(FileOutputStream.java:72)
E/termux  (16823):      at com.termux.app.g0$a.run(SourceFile:22)
E/termux  (16823): Caused by: android.system.ErrnoException: open failed: EROFS (Read-only file system)
E/termux  (16823):      at libcore.io.Posix.open(Native Method)
E/termux  (16823):      at libcore.io.BlockGuardOs.open(BlockGuardOs.java:186)
E/termux  (16823):      at libcore.io.IoBridge.open(IoBridge.java:442)
E/termux  (16823):      ... 3 more
```

`ls -la /data/data/com.termux/files/usr-staging/include/proc/`

```
root@shamu:/ # ll /data/data/com.termux/files/usr-staging/include/proc/
-rw------- u0_a60   u0_a60        913 2020-07-26 20:30 escape.h
-rw------- u0_a60   u0_a60       1068 2020-07-26 20:30 numa.h
-rw------- u0_a60   u0_a60        305 2020-07-26 20:30 pwcache.h
root@shamu:/ #
```

**These are the errors when I tap "Try Again"**
```
E/termux  (16823): Bootstrap error
E/termux  (16823): java.lang.RuntimeException: Unable to delete directory /data/data/com.termux/files/usr-staging/bin
E/termux  (16823):      at com.termux.app.g0.b(SourceFile:10)
E/termux  (16823):      at com.termux.app.g0.b(SourceFile:8)
E/termux  (16823):      at com.termux.app.g0$a.run(SourceFile:3)
V/WindowManager( 1802): not Base app: Adding window Window{13636ad3 u0 com.termux/com.termux.app.TermuxActivity} at 12 of 15
```

`ls -la /data/data/com.termux/files/usr-staging/`

```
root@shamu:/data/data/com.termux/files/usr-staging # ll
drwx------ u0_a60   u0_a60            2020-07-26 20:33 bin
drwx------ u0_a60   u0_a60            2020-07-26 20:33 etc
drwx------ u0_a60   u0_a60            2020-07-26 20:33 include
```

`ls -la /data/data/com.termux/files/usr-staging/bin/`

```
root@shamu:/data/data/com.termux/files/usr-staging/bin # ll
-rwx------ u0_a60   u0_a60     140984 2020-07-26 20:33 curl
```

**If I delete manually the bin folder then I try to install again, it comes to the first step.**

During the installation I see the bin folder good.

`ls -la /data/data/com.termux/files/usr-staging/bin/`

```
root@shamu:/data/data/com.termux/files/usr-staging/bin # ll
-rwx------ u0_a60   u0_a60      18108 2020-07-26 20:36 addpart
-rwx------ u0_a60   u0_a60        208 2020-07-26 20:36 am
drwx------ u0_a60   u0_a60            2020-07-26 20:36 applets
-rwx------ u0_a60   u0_a60      14036 2020-07-26 20:36 apt
-rwx------ u0_a60   u0_a60      83668 2020-07-26 20:36 apt-cache
-rwx------ u0_a60   u0_a60      26324 2020-07-26 20:36 apt-config
-rwx------ u0_a60   u0_a60      50900 2020-07-26 20:36 apt-get
-rwx------ u0_a60   u0_a60      26772 2020-07-26 20:36 apt-key
-rwx------ u0_a60   u0_a60      46804 2020-07-26 20:36 apt-mark
-rwx------ u0_a60   u0_a60      44056 2020-07-26 20:36 arp
-rwx------ u0_a60   u0_a60     686552 2020-07-26 20:36 bash
-rwx------ u0_a60   u0_a60      18108 2020-07-26 20:36 blkdiscard
-rwx------ u0_a60   u0_a60      83668 2020-07-26 20:36 blkid
-rwx------ u0_a60   u0_a60      46780 2020-07-26 20:36 blkzone
-rwx------ u0_a60   u0_a60      38504 2020-07-26 20:36 blockdev
-rwx------ u0_a60   u0_a60     791916 2020-07-26 20:36 busybox
-rwx------ u0_a60   u0_a60       2197 2020-07-26 20:36 bzdiff
-rwx------ u0_a60   u0_a60       2085 2020-07-26 20:36 bzgrep
-rwx------ u0_a60   u0_a60      26240 2020-07-26 20:36 bzip2
-rwx------ u0_a60   u0_a60      13872 2020-07-26 20:36 bzip2recover
-rwx------ u0_a60   u0_a60       1290 2020-07-26 20:36 bzmore
-rwx------ u0_a60   u0_a60      46948 2020-07-26 20:36 cal
-rwx------ u0_a60   u0_a60      26216 2020-07-26 20:36 chcpu
-rwx------ u0_a60   u0_a60      34492 2020-07-26 20:36 choom
-rwx------ u0_a60   u0_a60      26300 2020-07-26 20:36 chrt
-rwx------ u0_a60   u0_a60        986 2020-07-26 20:36 chsh
-rwx------ u0_a60   u0_a60       9828 2020-07-26 20:36 clear
-rwx------ u0_a60   u0_a60      26324 2020-07-26 20:36 cmp
-rwx------ u0_a60   u0_a60      18108 2020-07-26 20:36 col
-rwx------ u0_a60   u0_a60       9832 2020-07-26 20:36 colcrt
-rwx------ u0_a60   u0_a60      18108 2020-07-26 20:36 colrm
-rwx------ u0_a60   u0_a60      34492 2020-07-26 20:36 column
-rwx------ u0_a60   u0_a60    1031016 2020-07-26 20:36 coreutils
-rwx------ u0_a60   u0_a60      22120 2020-07-26 20:36 ctrlaltdel
-rwx------ u0_a60   u0_a60     140984 2020-07-26 20:36 curl
-rwx------ u0_a60   u0_a60       6580 2020-07-26 20:36 curl-config
-rwx------ u0_a60   u0_a60        320 2020-07-26 20:36 dalvikvm
-rwx------ u0_a60   u0_a60      83940 2020-07-26 20:36 dash
-rwx------ u0_a60   u0_a60      18108 2020-07-26 20:36 delpart
-rwx------ u0_a60   u0_a60        122 2020-07-26 20:36 df
-rwx------ u0_a60   u0_a60     157492 2020-07-26 20:36 diff
-rwx------ u0_a60   u0_a60      38636 2020-07-26 20:36 diff3
-rwx------ u0_a60   u0_a60      52024 2020-07-26 20:36 dmesg
-rwx------ u0_a60   u0_a60      34548 2020-07-26 20:36 dnsdomainname
-rwx------ u0_a60   u0_a60      42596 2020-07-26 20:36 dos2unix
-rwx------ u0_a60   u0_a60     219024 2020-07-26 20:36 dpkg
-rwx------ u0_a60   u0_a60     112460 2020-07-26 20:36 dpkg-deb
-rwx------ u0_a60   u0_a60     104292 2020-07-26 20:36 dpkg-divert
-rwx------ u0_a60   u0_a60     108380 2020-07-26 20:36 dpkg-query
-rwx------ u0_a60   u0_a60      87888 2020-07-26 20:36 dpkg-split
-rwx------ u0_a60   u0_a60      55088 2020-07-26 20:36 dpkg-trigger
-rwx------ u0_a60   u0_a60       9824 2020-07-26 20:36 dumpsexp
-rwx------ u0_a60   u0_a60      38656 2020-07-26 20:36 ed
```

**Comment by xeffyr** [comment]
Sorry, but non-standard Android emulators are out of support. The only supported emulators are ones which are backed by full virtualization and thus run the normal Android/Linux kernel and have /data partition placed on EXT4 or F2FS file system.

**Comment by airvzxf** [comment]
Thank you for your time and the answer, keep tracking the issues reported for users is a good signal for a great software.

I understand, it's because Android/Linux is not able to run on Windows at least if the Emulator in this case NoxPlayer doesn't has a full virtualization.

Is there some way to I contribute to fix this? Is this really difficult?

**Comment by xeffyr** [comment]
> Is there some way to I contribute to fix this?

You can't make Termux run on systems lacking required features. Specifically, Termux requires:
* Installation path equals exactly `/data/data/com.termux` and is read-write.
* File system on installation path has support for: Unix permissions, symlinks, sockets.
* `execve()` Linux system call must also be functional.

So you can't fix that within Termux unless NoxPlayer supports Linux fundamentals regarding what I'm in doubt. I see `libcore.io.*` in your stacktrace which points that whole I/O subsystem is emulated.

**Comment by airvzxf** [comment]
That's right, I'll close this issue, thanks for the information again, I'll rate this attention with 5 starts.
