### ISSUE TITLE
Caddy crashes on start

### ISSUE THREAD

**Issue by xeffyr** [termux/termux-packages#5724]
**Problem description**

Recent version of package `caddy` doesn't work due to immediate crash on startup.

**Steps to reproduce**

```
pkg install caddy
caddy
```

**Expected behavior**

A brief help information should be printed.

**Additional information**
```
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://dl.bintray.com/termux/termux-packages-24/ stable main
# game-repo (sources.list.d/game.list)
deb https://dl.bintray.com/grimler/game-packages-24 games stable
# science-repo (sources.list.d/science.list)
deb https://dl.bintray.com/grimler/science-packages-24 science stable
Updatable packages:
All packages up to date
Android version:
10
Kernel build information:
Linux localhost 3.18.91-Seal-g73da5e01b83 #1 SMP PREEMPT Tue Aug 11 13:12:31 UTC 2020 aarch64 Android
Device manufacturer:
samsung
Device model:
SM-G930F
```

Crash log (from Go 1.15 `caddy` rebuild, Termux official one looks nearly same):
```
SIGILL: illegal instruction
PC=0x7111be8ae0 m=0 sigcode=1
instruction bytes: 0x0 0x4 0x38 0xd5 0xe0 0x7 0x0 0xf9 0xc0 0x3 0x5f 0xd6 0x0 0x0 0x0 0x0

goroutine 1 [running, locked to thread]:
github.com/klauspost/cpuid.getProcFeatures(0x7112a76340, 0x40001107e0, 0x71126bb5f4, 0xc, 0x4000144d90, 0x7111be734c, 0x71136b9720, 0x7111be7348, 0x40001107b0, 0x711183a3d4, ...)
	/home/builder/.termux-build/caddy/build/pkg/mod/github.com/klauspost/cpuid@v1.3.0/cpuid_arm64.s:15 fp=0x40000f5dd0 sp=0x40000f5dd0 pc=0x7111be8ae0
github.com/klauspost/cpuid.addInfo(0x71136b9720)
	/home/builder/.termux-build/caddy/build/pkg/mod/github.com/klauspost/cpuid@v1.3.0/detect_arm64.go:42 +0x18 fp=0x40000f5e00 sp=0x40000f5dd0 pc=0x7111be7918
github.com/klauspost/cpuid.Detect()
	/home/builder/.termux-build/caddy/build/pkg/mod/github.com/klauspost/cpuid@v1.3.0/cpuid.go:289 +0x68 fp=0x40000f5e20 sp=0x40000f5e00 pc=0x7111be73c8
github.com/klauspost/cpuid.init.0()
	/home/builder/.termux-build/caddy/build/pkg/mod/github.com/klauspost/cpuid@v1.3.0/cpuid.go:272 +0x1c fp=0x40000f5e30 sp=0x40000f5e20 pc=0x7111be734c
runtime.doInit(0x711361e780)
	/home/builder/.termux-build/_cache/go1.15/src/runtime/proc.go:5625 +0x94 fp=0x40000f5e70 sp=0x40000f5e30 pc=0x711183a3d4
runtime.doInit(0x71136332c0)
	/home/builder/.termux-build/_cache/go1.15/src/runtime/proc.go:5620 +0x50 fp=0x40000f5eb0 sp=0x40000f5e70 pc=0x711183a390
runtime.doInit(0x71136304c0)
	/home/builder/.termux-build/_cache/go1.15/src/runtime/proc.go:5620 +0x50 fp=0x40000f5ef0 sp=0x40000f5eb0 pc=0x711183a390
runtime.doInit(0x71136305e0)
	/home/builder/.termux-build/_cache/go1.15/src/runtime/proc.go:5620 +0x50 fp=0x40000f5f30 sp=0x40000f5ef0 pc=0x711183a390
runtime.doInit(0x711361dac0)
	/home/builder/.termux-build/_cache/go1.15/src/runtime/proc.go:5620 +0x50 fp=0x40000f5f70 sp=0x40000f5f30 pc=0x711183a390
runtime.main()
	/home/builder/.termux-build/_cache/go1.15/src/runtime/proc.go:191 +0x1b0 fp=0x40000f5fd0 sp=0x40000f5f70 pc=0x711182dbf0
runtime.goexit()
	/home/builder/.termux-build/_cache/go1.15/src/runtime/asm_arm64.s:1136 +0x4 fp=0x40000f5fd0 sp=0x40000f5fd0 pc=0x711185e594

r0      0x71136b9720
r1      0x40000f43a0
r2      0x40000f5e00
r3      0x3
r4      0x7112a76340
r5      0x0
r6      0x71126bb5f4
r7      0xd1
r8      0xf
r9      0x4
r10     0x0
r11     0xd
r12     0x1
r13     0x71128f2c34
r14     0x802aaaa00aaaa
r15     0xf8
r16     0x0
r17     0x34
r18     0x7110e9c000
r19     0x68
r20     0xd0
r21     0x40001323a0
r22     0x1
r23     0x71136ed375
r24     0x71136b7b20
r25     0x18
r26     0x711361e7a8
r27     0xffffffffffffffc9
r28     0x4000000180
r29     0x0
lr      0x7111be7918
sp      0x40000f5dd0
pc      0x7111be8ae0
fault   0x0
```

Notes:
* Rebuilding package does not solve the issue.
* Issue is related to detection of CPU features - we had exact issue with OpenSSL.

**Comment by xeffyr** [comment]
Seems to be fixed now.
