### ISSUE TITLE
Eoror

### ISSUE THREAD

**Issue by F4hK0** [termux/termux-packages#5752]
Collecting coincurve
  Using cached coincurve-13.0.0.tar.gz (961 kB)
    ERROR: Command errored out with exit status 1:              command: /data/data/com.termux/files/usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/data/data/com.termux/files/usr/tmp/pip-install-vuplgkzk/coincurve/setup.py'"'"'; __file__='"'"'/data/data/com.termux/files/usr/tmp/pip-install-vuplgkzk/coincurve/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /data/data/com.termux/files/usr/tmp/pip-pip-egg-info-bfg6194o                                                                 cwd: /data/data/com.termux/files/usr/tmp/pip-install-vuplgkzk/coincurve/
    Complete output (45 lines):
    WARNING: The wheel package is not available.               WARNING: The wheel package is not available.
      ERROR: Command errored out with exit status 1:
       command: /data/data/com.termux/files/usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/data/data/com.termux/files/usr/tmp/pip-wheel-8jyskz2g/cffi/setup.py'"'"'; __file__='"'"'/data/data/com.termux/files/usr/tmp/pip-wheel-8jyskz2g/cffi/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /data/data/com.termux/files/usr/tmp/pip-wheel-cwn4wm8w                             cwd: /data/data/com.termux/files/usr/tmp/pip-wheel-8jyskz2g/cffi/
      Complete output (6 lines):                                 usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
         or: setup.py --help [cmd1 cmd2 ...]
         or: setup.py --help-commands                               or: setup.py cmd --help                           
      error: invalid command 'bdist_wheel'
      ----------------------------------------                   ERROR: Failed building wheel for cffi                    ERROR: Failed to build one or more wheels
    Traceback (most recent call last):
      File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/setuptools/installer.py", line 128, in fetch_build_egg
        subprocess.check_call(cmd)
      File "/data/data/com.termux/files/usr/lib/python3.8/subprocess.py", line 364, in check_call                             raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['/data/data/com.termux/files/usr/bin/python3', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/data/data/com.termux/files/usr/tmp/tmpu5tv8or5', '--quiet', 'cffi>=1.3.0']' returned non-zero exit status 1.                     
    During handling of the above exception, another exception occurred:                                               
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/data/data/com.termux/files/usr/tmp/pip-install-vuplgkzk/coincurve/setup.py", line 250, in <module>
        setup(                                                   File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/setuptools/__init__.py", line 143, in setup           _install_setup_requires(attrs)                           File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/setuptools/__init__.py", line 138, in _install_setup_requires                                                    dist.fetch_build_eggs(dist.setup_requires)               File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/setuptools/dist.py", line 695, in fetch_build_eggs                                                               resolved_dists = pkg_resources.working_set.resolve(
      File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 781, in resolve
        dist = best[req.key] = env.best_match(
      File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1066, in best_match                                                             return self.obtain(req, installer)                       File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1078, in obtain                                                                 return installer(requirement)                            File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/setuptools/dist.py", line 754, in fetch_build_egg
        return fetch_build_egg(self, req)
      File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/setuptools/installer.py", line 130, in fetch_build_egg
        raise DistutilsError(str(e))
    distutils.errors.DistutilsError: Command '['/data/data/com.termux/files/usr/bin/python3', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/data/data/com.termux/files/usr/tmp/tmpu5tv8or5', '--quiet', 'cffi>=1.3.0']' returned non-zero exit status 1.
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by JCWasmx86** [comment]
You have to install wheel. Try `pip3 install wheel` and then try again.
