### ISSUE TITLE
Python3.8.5 dnspython is having a weird issue

### ISSUE THREAD

**Issue by Sakon13** [termux/termux-packages#5800]
I was trying to connect my flask app to mongodb using Flask-PyMongo for that purpose i installed dnspython package but i am not able to connect it to my database 
The error
```
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/dns/resolver.py", line 743, in read_resolv_conf
    f = stack.enter_context(open(f))
FileNotFoundError: [Errno 2] No such file or directory: '/etc/resolv.conf'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/pymongo/srv_resolver.py", line 72, in _resolve_uri
    results = resolver.query('_mongodb._tcp.' + self.__fqdn, 'SRV',
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/dns/resolver.py", line 1221, in query
    return resolve(qname, rdtype, rdclass, tcp, source,
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/dns/resolver.py", line 1205, in resolve
    return get_default_resolver().resolve(qname, rdtype, rdclass, tcp, source,
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/dns/resolver.py", line 1178, in get_default_resolver
    reset_default_resolver()
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/dns/resolver.py", line 1190, in reset_default_resolver
    default_resolver = Resolver()
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/dns/resolver.py", line 695, in __init__
    self.read_resolv_conf(filename)
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/dns/resolver.py", line 746, in read_resolv_conf
    raise NoResolverConfiguration
dns.resolver.NoResolverConfiguration: Resolver configuration could not be read or specified no nameservers.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "app.py", line 10, in <module>
    mongo = PyMongo(app)
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/flask_pymongo/__init__.py", line 110, in __init__
    self.init_app(app, uri, *args, **kwargs)
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/flask_pymongo/__init__.py", line 147, in init_app
    parsed_uri = uri_parser.parse_uri(uri)
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/pymongo/uri_parser.py", line 500, in parse_uri
    nodes = dns_resolver.get_hosts()
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/pymongo/srv_resolver.py", line 102, in get_hosts
    _, nodes = self._get_srv_response_and_hosts(True)
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/pymongo/srv_resolver.py", line 83, in _get_srv_response_and_hosts
    results = self._resolve_uri(encapsulate_errors)
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/pymongo/srv_resolver.py", line 79, in _resolve_uri
    raise ConfigurationError(str(exc))
pymongo.errors.ConfigurationError: Resolver configuration could not be read or specified no nameservers.
```
please help

**Comment by Sakon13** [comment]
I guess the package dependencies in the termux repository is broken

**Comment by Grimler91** [comment]
Problem is that android is not a GNU/Linux system, in particular `/etc/resolv.conf` does not exist on android.

Try with dnspython v1.16 (`pip3 install dnspython==1.16`) instead of the latest version, the older version falls back to `127.0.0.1` if `/etc/resolv.conf` does not exist.

**Comment by Sakon13** [comment]
thanks the error is solved

**Comment by xeffyr** [comment]
`pkg install proot resolv-conf`, then running things under `termux-chroot` (so /etc/resolv.conf will be available) should fix the issue.
