### ISSUE TITLE
seafile-client missing the seafile Python module

### ISSUE THREAD

**Issue by roukydesbois** [termux/termux-packages#6006]
**Problem description**
Not rooted phone, up to date termux, latest version of seafile-client termux package (7.0.9-1). Running seaf-cli init is not working, this error is displayed:
```
$ seaf-cli init -d .
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/bin/seaf-cli", line 98, in <module>
    import seafile
ModuleNotFoundError: No module named 'seafile'
```

**Steps to reproduce**

```
$ pkg install seafile-client
$ mkdir test_dir
$ seaf-cli init -d test_dir/
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/bin/seaf-cli", line 98, in <module>
    import seafile
ModuleNotFoundError: No module named 'seafile'
```
**Expected behavior**

No error should be displayed
**Additional information**

```
Packages CPU architecture:
arm
Subscribed repositories:
# sources.list
deb https://termux.mentality.rip/termux-packages-24/ stable main
# science-repo (sources.list.d/science.list)
deb https://dl.bintray.com/grimler/science-packages-24 science stable
# game-repo (sources.list.d/game.list)
deb https://dl.bintray.com/grimler/game-packages-24 games stable
Updatable packages:
apt/stable 2.1.11-2 arm [upgradable from: 1.4.10-6]
git/stable 2.29.2 arm [upgradable from: 2.28.0]
libgcrypt/stable 1.8.7 arm [upgradable from: 1.8.6]
Android version:
10
Kernel build information:
Linux localhost 3.4.113-perf-gd817f7d #1 SMP PREEMPT Fri Nov 6 03:13:39 UTC 2020 armv7l Android
Device manufacturer:
Fairphone
Device model:
FP2
```

**Comment by xeffyr** [comment]
Fixed with seafile `7.0.9-4` which should be available shortly.
