### ISSUE TITLE
PyFFTW cannot be installed because of the way fftw was compiled.

### ISSUE THREAD

**Issue by tigran123** [termux/termux-packages#605]
If I try to install PyFFTW package via `pip install PyFFW` I get:

```
    gcc -shared -L/data/data/com.termux/files/usr/lib -march=armv7-a -Wl,--fix-cortex-a8 -landroid-support build/temp.linux-armv7l-3.5/data/data/com.termux/files/home/tmp/pip-build-p1gdj34y/pyFFTW/pyfftw/pyfftw.o -L/data/data/com.termux/files/usr/lib -lfftw3 -lfftw3f -lfftw3l -lfftw3_threads -lfftw3f_threads -lfftw3l_threads -lpython3.5m -o build/lib.linux-armv7l-3.5/pyfftw/pyfftw.cpython-35m-arm-linux-gnueabi.so
    /data/data/com.termux/files/usr/bin/ld: cannot find -lfftw3f
    /data/data/com.termux/files/usr/bin/ld: cannot find -lfftw3l
    /data/data/com.termux/files/usr/bin/ld: cannot find -lfftw3_threads
    /data/data/com.termux/files/usr/bin/ld: cannot find -lfftw3f_threads
    /data/data/com.termux/files/usr/bin/ld: cannot find -lfftw3l_threads
    clang-3.9: error: linker command failed with exit code 1 (use -v to see invocation)
    error: command 'gcc' failed with exit status 1
```

And, indeed, the multithreaded, single and long-double versions of the library are missing:

```
$ l $PREFIX/lib/*fftw*
lrwxrwxrwx 1 u0_a119 u0_a119     17 Dec 20 14:44 /data/data/com.termux/files/usr/lib/libfftw3.so -> libfftw3.so.3.5.5
lrwxrwxrwx 1 u0_a119 u0_a119     17 Dec 20 14:44 /data/data/com.termux/files/usr/lib/libfftw3.so.3 -> libfftw3.so.3.5.5
-rwxr-x--- 1 u0_a119 u0_a119 628004 Oct 19 23:46 /data/data/com.termux/files/usr/lib/libfftw3.so.3.5.5
```

Now, I haven't tested this, but presumably, adding these to `./configure` invocation should solve the problem:

```
./configure --enable-threads --enable-float --enable-threads --enable-long-double
```

The reason why this is not as trivial as it sounds is that I suspect we need some of those arch-specific "--enable-blah-blah" like "--enable-neon" etc which I am not so sure about.

I suppose, I could try as a first approximation to compile it without those arch-specific bits and see what happens :)

The reason why PyFFTW is essential is because scipy.fftpack is not present in termux (and cannot be compiled) and in any case it is very slow compared to PyFFTW (not to mention numpy.fft which is present, but is even slower). So, I found PyFFTW to be the fastest FFTW implementation for Python3 and it would be very nice to have it running inside Termux.

**Comment by tigran123** [comment]
The alternative approach would be to somehow force PyFFTW to NOT use those optional extra (or less) precision versions and also not to use the threads support (presumably you disabled the multithreaded fftw because it is unsafe on Android).

**Comment by its-pointless** [comment]
https://github.com/its-pointless/gcc_termux
I have scipy working on termux arm using netlibs blas.
I might update that further...

**Comment by tigran123** [comment]
Thank you, I will try it (the last time I tried it was for Python 2.x only). Presumably one must uninstall clang and clang-dev first?

**Comment by tigran123** [comment]
@its-pointless On armv7l (Android 5.1.1, Nexus10) your scipy fails to import scipy.integrate:

```
$ cat test.py
from scipy.integrate import dblquad, simps
$ python3 test.py
WARNING: linker: _ufuncs.cpython-35m-arm-linux-gnueabi.so: unused DT entry: type 0x6ffffffe arg 0x7b1c
WARNING: linker: _ufuncs.cpython-35m-arm-linux-gnueabi.so: unused DT entry: type 0x6fffffff arg 0x2
WARNING: linker: _ufuncs_cxx.cpython-35m-arm-linux-gnueabi.so: unused DT entry: type 0x6ffffffe arg 0x2c94
WARNING: linker: _ufuncs_cxx.cpython-35m-arm-linux-gnueabi.so: unused DT entry: type 0x6fffffff arg 0x2
Traceback (most recent call last):
  File "test.py", line 1, in <module>
    from scipy.integrate import dblquad, simps
  File "/data/data/com.termux/files/usr/lib/python3.5/site-packages/scipy-0.18.1-py3.5-linux-armv7l.egg/scipy/integrate/__init__.py", line 55, in <module>
    from .quadrature import *
  File "/data/data/com.termux/files/usr/lib/python3.5/site-packages/scipy-0.18.1-py3.5-linux-armv7l.egg/scipy/integrate/quadrature.py", line 10, in <module>
    from scipy.special.orthogonal import p_roots
  File "/data/data/com.termux/files/usr/lib/python3.5/site-packages/scipy-0.18.1-py3.5-linux-armv7l.egg/scipy/special/__init__.py", line 636, in <module>
    from ._ufuncs import *
  File "scipy/special/_ufuncs.pyx", line 1, in init scipy.special._ufuncs (scipy/special/_ufuncs.c:36541)
ImportError: dlopen failed: cannot locate symbol "__muldc3" referenced by "_ufuncs_cxx.cpython-35m-arm-linux-gnueabi.so"...
```

**Comment by its-pointless** [comment]
Iv been meaning to do this properly and allow clang and gcc to live together in a reasonable way. i will loom into it in a bit. Should just be a small issue.

**Comment by tigran123** [comment]
@its-pointless On aarch64 architecture this problem doesn't happen, but I encountered a different problem there (because I had to reinstall python from scratch) --- matplotlib install fine (via "pip install matplotlib") but fails to import. The only difference from the previous installation is that I thought I should "save time" by skipping the step "pip install wheel" which causes a very long recompilation of almost every package subsequently installed (without "bdist_wheel" stage they install instantly). So, now I am re-installing everything again via "wheel" in hope that the problem goes away. Previously matplotlib worked absolutely fine (with 'Agg' front-end of course).

Also, I don't understand why you provide numpy package --- the command "pip install numpy" usually completes successfully. Or should we use your provided numpy package instead?

**Comment by its-pointless** [comment]
Try my numpy. The linker in android in tempremental...

**Comment by tigran123** [comment]
No, I still get the same problem:

```
In [1]: import matplotlib as mplt

In [2]: mplt.use('Agg')

In [3]: import matplotlib.pyplot as plt
WARNING: linker: unexpected ST_BIND value: 10 for '_ZGVN3agg14sRGB_conv_baseIfE3lutE' in '/data/data/com.termux/files/usr/lib/python3.5/site-packages/matplotlib/_path.cpython-35m-aarch64-linux-gnu.so'
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-3-eff513f636fd> in <module>()
----> 1 import matplotlib.pyplot as plt

/data/data/com.termux/files/usr/lib/python3.5/site-packages/matplotlib/pyplot.py in <module>()
     27 from cycler import cycler
     28 import matplotlib
---> 29 import matplotlib.colorbar
     30 from matplotlib import style
     31 from matplotlib import _pylab_helpers, interactive

/data/data/com.termux/files/usr/lib/python3.5/site-packages/matplotlib/colorbar.py in <module>()
     30 
     31 import matplotlib as mpl
---> 32 import matplotlib.artist as martist
     33 import matplotlib.cbook as cbook
     34 import matplotlib.collections as collections

/data/data/com.termux/files/usr/lib/python3.5/site-packages/matplotlib/artist.py in <module>()
     12 from matplotlib.cbook import mplDeprecation
     13 from matplotlib import docstring, rcParams
---> 14 from .transforms import (Bbox, IdentityTransform, TransformedBbox,
     15                          TransformedPath, Transform)
     16 from .path import Path

/data/data/com.termux/files/usr/lib/python3.5/site-packages/matplotlib/transforms.py in <module>()
     37 import numpy as np
     38 from numpy import ma
---> 39 from matplotlib._path import (affine_transform, count_bboxes_overlapping_bbox,
     40     update_path_extents)
     41 from numpy.linalg import inv

ImportError: dlopen failed: cannot locate symbol "_ZGVN3agg14sRGB_conv_baseIfE3lutE" referenced by "/data/data/com.termux/files/usr/lib/python3.5/site-packages/matplotlib/_path.cpython-35m-aarch64-linux-gnu.so"...

```

Very strange. In the past matplotlib installed and worked just fine. Something has changed recently which causes the above failure.

Ah, one thing that changed is that I removed clang/clang-dev and installed your gcc instead! Maybe I should go back to clang and recompile matplotlib....

**Comment by its-pointless** [comment]
Yes only really want numpy + scipy compiled with gcc

**Comment by tigran123** [comment]
On aarch64 I got everything working --- the trick was to only keep libgfortran* libraries and use your scipy+numpy but NOT the whole gcc/g++/gcov. The result is tested (FFT works fine, plotting etc works fine, so all three numpy+scipy+matplotlib).

However, on armv7l the same approach doesn't work. And installing everything from scratch (starting from "apt install python python-dev") also doesn't work, look:

```
$ easy_install numpy-1.11.2-py3.5-linux-armv7l.egg 
Processing numpy-1.11.2-py3.5-linux-armv7l.egg
creating /data/data/com.termux/files/usr/lib/python3.5/site-packages/numpy-1.11.2-py3.5-linux-armv7l.egg
Extracting numpy-1.11.2-py3.5-linux-armv7l.egg to /data/data/com.termux/files/usr/lib/python3.5/site-packages
Adding numpy 1.11.2 to easy-install.pth file
Installing f2py script to /data/data/com.termux/files/usr/bin

Installed /data/data/com.termux/files/usr/lib/python3.5/site-packages/numpy-1.11.2-py3.5-linux-armv7l.egg
Processing dependencies for numpy==1.11.2
Finished processing dependencies for numpy==1.11.2
$ python -c "import numpy"
WARNING: linker: multiarray.cpython-35m-arm-linux-gnueabi.so: unused DT entry: type 0x6ffffffe arg 0x676c
WARNING: linker: multiarray.cpython-35m-arm-linux-gnueabi.so: unused DT entry: type 0x6fffffff arg 0x2
WARNING: linker: umath.cpython-35m-arm-linux-gnueabi.so: unused DT entry: type 0x6ffffffe arg 0x439c
WARNING: linker: umath.cpython-35m-arm-linux-gnueabi.so: unused DT entry: type 0x6fffffff arg 0x2
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/data/data/com.termux/files/usr/lib/python3.5/site-packages/numpy-1.11.2-py3.5-linux-armv7l.egg/numpy/__init__.py", line 142, in <module>
    from . import add_newdocs
  File "/data/data/com.termux/files/usr/lib/python3.5/site-packages/numpy-1.11.2-py3.5-linux-armv7l.egg/numpy/add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "/data/data/com.termux/files/usr/lib/python3.5/site-packages/numpy-1.11.2-py3.5-linux-armv7l.egg/numpy/lib/__init__.py", line 8, in <module>
    from .type_check import *
  File "/data/data/com.termux/files/usr/lib/python3.5/site-packages/numpy-1.11.2-py3.5-linux-armv7l.egg/numpy/lib/type_check.py", line 11, in <module>
    import numpy.core.numeric as _nx
  File "/data/data/com.termux/files/usr/lib/python3.5/site-packages/numpy-1.11.2-py3.5-linux-armv7l.egg/numpy/core/__init__.py", line 21, in <module>
    from . import umath
ImportError: dlopen failed: cannot locate symbol "catan" referenced by "umath.cpython-35m-arm-linux-gnueabi.so"...
$ easy_install scipy-0.18.1-py3.5-linux-armv7l.egg 
Processing scipy-0.18.1-py3.5-linux-armv7l.egg
creating /data/data/com.termux/files/usr/lib/python3.5/site-packages/scipy-0.18.1-py3.5-linux-armv7l.egg
Extracting scipy-0.18.1-py3.5-linux-armv7l.egg to /data/data/com.termux/files/usr/lib/python3.5/site-packages
Adding scipy 0.18.1 to easy-install.pth file

Installed /data/data/com.termux/files/usr/lib/python3.5/site-packages/scipy-0.18.1-py3.5-linux-armv7l.egg
Processing dependencies for scipy==0.18.1
Finished processing dependencies for scipy==0.18.1
$ python -c "import scipy"
WARNING: linker: multiarray.cpython-35m-arm-linux-gnueabi.so: unused DT entry: type 0x6ffffffe arg 0x676c
WARNING: linker: multiarray.cpython-35m-arm-linux-gnueabi.so: unused DT entry: type 0x6fffffff arg 0x2
WARNING: linker: umath.cpython-35m-arm-linux-gnueabi.so: unused DT entry: type 0x6ffffffe arg 0x439c
WARNING: linker: umath.cpython-35m-arm-linux-gnueabi.so: unused DT entry: type 0x6fffffff arg 0x2
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/data/data/com.termux/files/usr/lib/python3.5/site-packages/scipy-0.18.1-py3.5-linux-armv7l.egg/scipy/__init__.py", line 61, in <module>
    from numpy import show_config as show_numpy_config
  File "/data/data/com.termux/files/usr/lib/python3.5/site-packages/numpy-1.11.2-py3.5-linux-armv7l.egg/numpy/__init__.py", line 142, in <module>
    from . import add_newdocs
  File "/data/data/com.termux/files/usr/lib/python3.5/site-packages/numpy-1.11.2-py3.5-linux-armv7l.egg/numpy/add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "/data/data/com.termux/files/usr/lib/python3.5/site-packages/numpy-1.11.2-py3.5-linux-armv7l.egg/numpy/lib/__init__.py", line 8, in <module>
    from .type_check import *
  File "/data/data/com.termux/files/usr/lib/python3.5/site-packages/numpy-1.11.2-py3.5-linux-armv7l.egg/numpy/lib/type_check.py", line 11, in <module>
    import numpy.core.numeric as _nx
  File "/data/data/com.termux/files/usr/lib/python3.5/site-packages/numpy-1.11.2-py3.5-linux-armv7l.egg/numpy/core/__init__.py", line 21, in <module>
    from . import umath
ImportError: dlopen failed: cannot locate symbol "catan" referenced by "umath.cpython-35m-arm-linux-gnueabi.so"...
$ gcc --version
gcc (GCC) 6.2.0
Copyright (C) 2016 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

$ g++ --version
g++ (GCC) 6.2.0
Copyright (C) 2016 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by its-pointless** [comment]
k im going to redo everything on arm version and also allow a full less annoying numpy + scipy  working versions for arm and maybe even for aarch64  without fiddling with libgfortran. So it just works(tm).

**Comment by tigran123** [comment]
Actually, I managed to install numpy with

```
LDFLAGS=" -lm -lcompiler_rt" pip install numpy
```

Then I extracted libgfortran* from your gcc*arm*.deb file and moved them to $PREFIX/lib. Then I installed your scipy*.egg file. Then I installed matplotlib with the same LDFLAGS line as numpy (see above). Then tested my programs and only scipy.integrate doesn't work:

```
$ python -c "import scipy.integrate"
WARNING: linker: _ufuncs.cpython-35m-arm-linux-gnueabi.so: unused DT entry: type 0x6ffffffe arg 0x7b1c
WARNING: linker: _ufuncs.cpython-35m-arm-linux-gnueabi.so: unused DT entry: type 0x6fffffff arg 0x2
WARNING: linker: _ufuncs_cxx.cpython-35m-arm-linux-gnueabi.so: unused DT entry: type 0x6ffffffe arg 0x2c94
WARNING: linker: _ufuncs_cxx.cpython-35m-arm-linux-gnueabi.so: unused DT entry: type 0x6fffffff arg 0x2
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/data/data/com.termux/files/usr/lib/python3.5/site-packages/scipy-0.18.1-py3.5-linux-armv7l.egg/scipy/integrate/__init__.py", line 55, in <module>
    from .quadrature import *
  File "/data/data/com.termux/files/usr/lib/python3.5/site-packages/scipy-0.18.1-py3.5-linux-armv7l.egg/scipy/integrate/quadrature.py", line 10, in <module>
    from scipy.special.orthogonal import p_roots
  File "/data/data/com.termux/files/usr/lib/python3.5/site-packages/scipy-0.18.1-py3.5-linux-armv7l.egg/scipy/special/__init__.py", line 636, in <module>
    from ._ufuncs import *
  File "scipy/special/_ufuncs.pyx", line 1, in init scipy.special._ufuncs (scipy/special/_ufuncs.c:36541)
ImportError: dlopen failed: cannot locate symbol "__muldc3" referenced by "_ufuncs_cxx.cpython-35m-arm-linux-gnueabi.so"...
```

**Comment by its-pointless** [comment]
yeah that symbol is from libgcc.a

**Comment by its-pointless** [comment]
anyway im uploading all the variations of fftw you need for pyfftw https://github.com/its-pointless/gcc_termux/tree/master/fftwlibs

**Comment by tigran123** [comment]
Thank you very much, brother! I will test all these! :)

**Comment by its-pointless** [comment]
At least one method is working. Spent a little bit of time trying to get atlas blas to work on android since openblas doesn't work(atlas would probably be faster than the current blas on arm). if i can get it to work i will update.

**Comment by fornwall** [comment]
About the fftw variants, I guess we need to have an (or several) additional fftw packages with the extra variants required by ft.

* [Instructions about building fftw three times for all versions](http://pyqg.readthedocs.io/en/stable/installation.html#the-hard-way-installing-from-source)
* [Open pyFFTW issue about not requiring all fftw variants](https://github.com/pyFFTW/pyFFTW/issues/70)

**Comment by its-pointless** [comment]
#826 ...

**Comment by fornwall** [comment]
Thanks - the variants are now bundled in the fftw package, so after an update (`apt update && apt upgrade`) they should be available!

**Comment by mindbound** [comment]
I'm still getting the `ImportError: dlopen failed: cannot locate symbol "__muldc3" referenced by "_ufuncs_cxx.cpython-35m-arm-linux-gnueabi.so"` error with `import scipy.integrate` or `import scipy.special` (armv7, Marshmallow 6.0.1). Was this fixed (and, if so, what should I do) or is this still a known problem? TIA.

P.S. I have scipy installed from https://github.com/its-pointless/gcc_termux repo (and probably should be asking questions there but this ws the issue I found when searching for a solution).

**Comment by its-pointless** [comment]
easy solution for now export LD_PRELOAD=/system/lib/libcompiler_rt.so

**Comment by mindbound** [comment]
Thanks! That worked.
