### ISSUE TITLE
OpenCV does not work anymore

### ISSUE THREAD

**Issue by gXLg** [termux/termux-packages#6160]
**Problem description**
I can't use opencv in python anymore
It worked until two days ago I installed some packages and ran ```pkg update```
Now on importing it says
```python
>>> import cv2
```
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/cv2/__init__.py", line 96, in <module>
    bootstrap()
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/cv2/__init__.py", line 86, in bootstrap
    import cv2
ImportError: dlopen failed: cannot locate symbol "_ZN6google8protobuf8internal18EpsCopyInputStream12DoneFallbackEPKci" referenced by "/data/data/com.termux/files/usr/lib/libopencv_dnn.so.4.5.0"...
```
Some people suggested to ```pkg install libopencv-contrib```
But it ends up in
```
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libopencv-contrib : Depends: opencv but it is not going to be installed
                     Depends: opencv (= 4.4.0-2) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```

**Steps to reproduce**
1) subscribe to its-pointless-repo
2) run ```pkg install opencv```

**Expected behavior**
```import cv2``` in python would work

**Additional information**
I ran ```pkg show opencv libopencv-contrib```
and was curious about the conflict and depend:
```
Package: opencv
Version: 4.5.0
Maintainer: Termux members @termux
Installed-Size: 66.9 MB
Depends: gst-plugins-base, numpy, ffmpeg, libwebp, libprotobuf, libpng, libtiff, openjpeg
Conflicts: libopencv-contrib
Replaces: libopencv-contrib
Homepage: https://opencv.org
Download-Size: 14.0 MB
APT-Manual-Installed: yes
APT-Sources: https://its-pointless.github.io/files/24 termux/extras aarch64 Packages
Description: computer vision image library (with python2 python3 libraries

Package: libopencv-contrib
Version: 4.4.0-2
Maintainer: Termux members @termux
Installed-Size: 14.7 MB
Depends: opencv, opencv (= 4.4.0-2)
Homepage: https://opencv.org
Download-Size: 4461 kB
APT-Sources: https://its-pointless.github.io/files/24 termux/extras aarch64 Packages
Description: computer vision contrlib libraries
```

**Comment by xeffyr** [comment]
Just its maintainer should rebuild it.

Please report opencv problems to https://github.com/its-pointless/its-pointless.github.io/issues - that's a community repo which does not covered by official Termux support.
