### ISSUE TITLE
tergent stops working after some time when screen is off

### ISSUE THREAD

**Issue by Grimler91** [termux/termux-packages#6168]
**Problem description**

If I ssh into termux I can ssh into other hosts using pubkeys in tergent. After screen turns off and phone locks itself it stops working and I have to unlock the screen to make it work again. 

Maybe this is intended behavior? If not then I am not sure if the problem is in termux-api, termux-am, tergent or with my ROM,  so I have not opened an issue in the tergent repo, yet.

Have other people experienced the same behavior? 

**Steps to reproduce**

1. ssh into termux ([over usb](https://glow.li/posts/access-termux-via-usb/) or wifi).
2. Setup tergent with the instructions in the [tergent readme](https://github.com/aeolwyr/tergent/blob/master/README.md)
3. Add the pubkey for the key you generated to some other device
4. Try to ssh into the other device, it should work
5. Wait a few minutes for the phone to lock itself
6. Try to ssh again, you get a `sign_and_send_pubkey: signing failed for RSA "key_name": error in libcrypto` error

**Expected behavior**

ssh'ing should still work (or at least show some info message that the keystore is locked or something)

**Additional information**

When I get the `sign_and_send_pubkey: signing failed for RSA "key_name": error in libcrypto` message, a logcat shows something like:

```
12-23 15:26:03.879  9190  9190 W ssh     : type=1400 audit(0.0:1198): avc: granted { execute } for name="am" dev="sda24" ino=4865014 scontext=u:r:untrusted_app_27:s0:c115,c256,c512,c768 tcontext=u:object_r:app_data_file:s0:c115,c256,c512,c768 tclass=file app=com.termux.api
12-23 15:26:04.101  9190  9190 D AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 10115 <<<<<<
12-23 15:26:04.105  9190  9190 E libc    : Access denied finding property "persist.device_config.runtime_native_boot.enable_apex_image"
12-23 15:26:04.105  9190  9190 I AndroidRuntime: Using default boot image
12-23 15:26:04.105  9190  9190 E libc    : Access denied finding property "persist.device_config.runtime_native_boot.disable_lock_profiling"
12-23 15:26:04.105  9190  9190 I AndroidRuntime: Leaving lock profiling enabled
12-23 15:26:04.105  9190  9190 E libc    : Access denied finding property "persist.device_config.runtime_native_boot.enable_generational_cc"
12-23 15:26:04.108  9190  9190 I /system/bin/app_process: Core platform API reporting enabled, enforcing=false
12-23 15:26:04.141  4589  4695 D bauth_FPBAuthService: pcf : 0x1012, 0 ,1 ,0 ,0 ,0 ,0, 
12-23 15:26:04.141  4589  4695 D bauth_FPBAuthService: thread id : 1, preenroll_flag : 0, nd cnt : 0, cso : 0, et : 0
12-23 15:26:04.141  4589  4695 D bauth_FPBAuthService: FPBAuthService, 9983
12-23 15:26:04.187  9190  9190 D ICU     : Time zone APEX file found: /apex/com.android.tzdata/etc/icu/icu_tzdata.dat
12-23 15:26:04.212  9190  9190 W /system/bin/app_process: JNI RegisterNativeMethods: attempt to register 0 native methods for android.media.AudioAttributes
12-23 15:26:04.216  9190  9190 D AndroidRuntime: Calling main entry com.termux.termuxam.Am
12-23 15:26:04.250  4368  4368 I keymaster_tee: [INFO]:  (nwd_keymaster_mdfpp.cpp:791) entered get_key_characteristics function.
12-23 15:26:04.256  4368  4368 D keymaster_tee: [DEBUG]: (nwd_keymaster_mobicore.c:353) TLC_COMMAND(e): cmd = 0x00000009, ret = 0x00000000
12-23 15:26:04.256  4368  4368 D keymaster_tee: [DEBUG]: (keymaster_params_log.c:282) ret OK PARAMS: SIZE:4096 RSA SIG VERI PKCSS DIGNO SHA1 SHA256 SHA384 SHA512 AUT:120 RSA:65537 20201222064532 
12-23 15:26:04.257  4368  4368 I keymaster_tee: [INFO]:  (nwd_keymaster_mdfpp.cpp:805) exit get_key_characteristics function, returns 0
12-23 15:26:04.257  4368  4368 I keymaster_tee: [INFO]:  (nwd_keymaster_mdfpp.cpp:839) entered export_key function.
12-23 15:26:04.260  4368  4368 D keymaster_tee: [DEBUG]: (nwd_keymaster_mobicore.c:353) TLC_COMMAND(e): cmd = 0x0000000B, ret = 0x00000000
12-23 15:26:04.260  4368  4368 I keymaster_tee: [INFO]:  (nwd_keymaster_mdfpp.cpp:855) exit export_key function, returns 0
12-23 15:26:04.268  4555  9206 E keymaster_worker: getAuthToken failed: -2
12-23 15:26:04.276  5864  9203 E termux-api: Error in ResultReturner
12-23 15:26:04.276  5864  9203 E termux-api: android.security.keystore.UserNotAuthenticatedException: User not authenticated
12-23 15:26:04.276  5864  9203 E termux-api: 	at android.security.KeyStore.getInvalidKeyException(KeyStore.java:1348)
12-23 15:26:04.276  5864  9203 E termux-api: 	at android.security.KeyStore.getInvalidKeyException(KeyStore.java:1413)
12-23 15:26:04.276  5864  9203 E termux-api: 	at android.security.keystore.KeyStoreCryptoOperationUtils.getInvalidKeyExceptionForInit(KeyStoreCryptoOperationUtils.java:54)
12-23 15:26:04.276  5864  9203 E termux-api: 	at android.security.keystore.AndroidKeyStoreSignatureSpiBase.ensureKeystoreOperationInitialized(AndroidKeyStoreSignatureSpiBase.java:219)
12-23 15:26:04.276  5864  9203 E termux-api: 	at android.security.keystore.AndroidKeyStoreSignatureSpiBase.engineInitSign(AndroidKeyStoreSignatureSpiBase.java:99)
12-23 15:26:04.276  5864  9203 E termux-api: 	at android.security.keystore.AndroidKeyStoreSignatureSpiBase.engineInitSign(AndroidKeyStoreSignatureSpiBase.java:77)
12-23 15:26:04.276  5864  9203 E termux-api: 	at java.security.Signature$Delegate.init(Signature.java:1357)
12-23 15:26:04.276  5864  9203 E termux-api: 	at java.security.Signature$Delegate.chooseProvider(Signature.java:1310)
12-23 15:26:04.276  5864  9203 E termux-api: 	at java.security.Signature$Delegate.engineInitSign(Signature.java:1385)
12-23 15:26:04.276  5864  9203 E termux-api: 	at java.security.Signature.initSign(Signature.java:679)
12-23 15:26:04.276  5864  9203 E termux-api: 	at com.termux.api.KeystoreAPI$2.writeResult(KeystoreAPI.java:256)
12-23 15:26:04.276  5864  9203 E termux-api: 	at com.termux.api.util.ResultReturner.lambda$returnData$0(ResultReturner.java:130)
12-23 15:26:04.276  5864  9203 E termux-api: 	at com.termux.api.util.-$$Lambda$ResultReturner$oCU8JqHW5HLMrNZa40ThjAWcwzo.run(Unknown Source:8)
12-23 15:26:04.276  5864  9203 E termux-api: 	at java.lang.Thread.run(Thread.java:919)
12-23 15:26:04.278  9190  9190 D AndroidRuntime: Shutting down VM
12-23 15:26:05.142  4589  4695 D bauth_FPBAuthService: pcf : 0x1012, 0 ,1 ,0 ,0 ,0 ,0, 
12-23 15:26:05.142  4589  4695 D bauth_FPBAuthService: thread id : 1, preenroll_flag : 0, nd cnt : 0, cso : 0, et : 0
12-23 15:26:05.142  4589  4695 D bauth_FPBAuthService: FPBAuthService, 9983
```

while when screen is unlocked, and everything works, I get something like

```
12-23 15:49:47.639 10751 10751 W bash    : type=1400 audit(0.0:8038): avc: granted { execute } for name="ssh" dev="sda24" ino=4857569 scontext=u:r:untrusted_app_27:s0:c115,c256,c512,c768 tcontext=u:object_r:app_data_file:s0:c115,c256,c512,c768 tclass=file app=com.termux.api
12-23 15:49:47.925 10752 10752 D AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 10115 <<<<<<
12-23 15:49:47.929 10752 10752 E libc    : Access denied finding property "persist.device_config.runtime_native_boot.enable_apex_image"
12-23 15:49:47.929 10752 10752 I AndroidRuntime: Using default boot image
12-23 15:49:47.929 10752 10752 E libc    : Access denied finding property "persist.device_config.runtime_native_boot.disable_lock_profiling"
12-23 15:49:47.929 10752 10752 I AndroidRuntime: Leaving lock profiling enabled
12-23 15:49:47.929 10752 10752 E libc    : Access denied finding property "persist.device_config.runtime_native_boot.enable_generational_cc"
12-23 15:49:47.931 10752 10752 I /system/bin/app_process: Core platform API reporting enabled, enforcing=false
12-23 15:49:48.012 10752 10752 D ICU     : Time zone APEX file found: /apex/com.android.tzdata/etc/icu/icu_tzdata.dat
12-23 15:49:48.040 10752 10752 W /system/bin/app_process: JNI RegisterNativeMethods: attempt to register 0 native methods for android.media.AudioAttributes
12-23 15:49:48.044 10752 10752 D AndroidRuntime: Calling main entry com.termux.termuxam.Am
12-23 15:49:48.077  4368  4368 I keymaster_tee: [INFO]:  (nwd_keymaster_mdfpp.cpp:791) entered get_key_characteristics function.
12-23 15:49:48.080  4368  4368 D keymaster_tee: [DEBUG]: (nwd_keymaster_mobicore.c:353) TLC_COMMAND(e): cmd = 0x00000009, ret = 0x00000000
12-23 15:49:48.080  4368  4368 D keymaster_tee: [DEBUG]: (keymaster_params_log.c:282) ret OK PARAMS: SIZE:4096 RSA SIG VERI PKCSS DIGNO SHA1 SHA256 SHA384 SHA512 AUT:120 RSA:65537 20201222064532 
12-23 15:49:48.080  4368  4368 I keymaster_tee: [INFO]:  (nwd_keymaster_mdfpp.cpp:805) exit get_key_characteristics function, returns 0
12-23 15:49:48.081  4368  4368 I keymaster_tee: [INFO]:  (nwd_keymaster_mdfpp.cpp:839) entered export_key function.
12-23 15:49:48.084  4368  4368 D keymaster_tee: [DEBUG]: (nwd_keymaster_mobicore.c:353) TLC_COMMAND(e): cmd = 0x0000000B, ret = 0x00000000
12-23 15:49:48.084  4368  4368 I keymaster_tee: [INFO]:  (nwd_keymaster_mdfpp.cpp:855) exit export_key function, returns 0
12-23 15:49:48.095 10752 10752 D AndroidRuntime: Shutting down VM
12-23 15:49:48.542 10769 10769 D AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 10115 <<<<<<
12-23 15:49:48.547 10769 10769 E libc    : Access denied finding property "persist.device_config.runtime_native_boot.enable_apex_image"
12-23 15:49:48.547 10769 10769 I AndroidRuntime: Using default boot image
12-23 15:49:48.547 10769 10769 E libc    : Access denied finding property "persist.device_config.runtime_native_boot.disable_lock_profiling"
12-23 15:49:48.547 10769 10769 I AndroidRuntime: Leaving lock profiling enabled
12-23 15:49:48.547 10769 10769 E libc    : Access denied finding property "persist.device_config.runtime_native_boot.enable_generational_cc"
12-23 15:49:48.543 10769 10769 W app_process: type=1400 audit(0.0:8088): avc: denied { read } for name="u:object_r:device_config_runtime_native_boot_prop:s0" dev="tmpfs" ino=17206 scontext=u:r:untrusted_app_27:s0:c115,c256,c512,c768 tcontext=u:object_r:device_config_runtime_native_boot_prop:s0 tclass=file permissive=0 app=com.termux.api
12-23 15:49:48.632 10769 10769 D ICU     : Time zone APEX file found: /apex/com.android.tzdata/etc/icu/icu_tzdata.dat
12-23 15:49:48.660 10769 10769 W /system/bin/app_process: JNI RegisterNativeMethods: attempt to register 0 native methods for android.media.AudioAttributes
12-23 15:49:48.664 10769 10769 D AndroidRuntime: Calling main entry com.termux.termuxam.Am
12-23 15:49:48.697  4368  4368 I keymaster_tee: [INFO]:  (nwd_keymaster_mdfpp.cpp:791) entered get_key_characteristics function.
12-23 15:49:48.701  4368  4368 D keymaster_tee: [DEBUG]: (nwd_keymaster_mobicore.c:353) TLC_COMMAND(e): cmd = 0x00000009, ret = 0x00000000
12-23 15:49:48.701  4368  4368 D keymaster_tee: [DEBUG]: (keymaster_params_log.c:282) ret OK PARAMS: SIZE:4096 RSA SIG VERI PKCSS DIGNO SHA1 SHA256 SHA384 SHA512 AUT:120 RSA:65537 20201222064532 
12-23 15:49:48.701  4368  4368 I keymaster_tee: [INFO]:  (nwd_keymaster_mdfpp.cpp:805) exit get_key_characteristics function, returns 0
12-23 15:49:48.701  4368  4368 I keymaster_tee: [INFO]:  (nwd_keymaster_mdfpp.cpp:839) entered export_key function.
12-23 15:49:48.704  4368  4368 D keymaster_tee: [DEBUG]: (nwd_keymaster_mobicore.c:353) TLC_COMMAND(e): cmd = 0x0000000B, ret = 0x00000000
12-23 15:49:48.704  4368  4368 I keymaster_tee: [INFO]:  (nwd_keymaster_mdfpp.cpp:855) exit export_key function, returns 0
12-23 15:49:48.712  4368  4368 I keymaster_tee: [INFO]:  (nwd_keymaster_mdfpp.cpp:791) entered get_key_characteristics function.
12-23 15:49:48.714  4368  4368 D keymaster_tee: [DEBUG]: (nwd_keymaster_mobicore.c:353) TLC_COMMAND(e): cmd = 0x00000009, ret = 0x00000000
12-23 15:49:48.715  4368  4368 D keymaster_tee: [DEBUG]: (keymaster_params_log.c:282) ret OK PARAMS: SIZE:4096 RSA SIG VERI PKCSS DIGNO SHA1 SHA256 SHA384 SHA512 AUT:120 RSA:65537 20201222064532 
12-23 15:49:48.715  4368  4368 I keymaster_tee: [INFO]:  (nwd_keymaster_mdfpp.cpp:805) exit get_key_characteristics function, returns 0
12-23 15:49:48.715  4368  4368 I keymaster_tee: [INFO]:  (nwd_keymaster_mdfpp.cpp:839) entered export_key function.
12-23 15:49:48.717  4368  4368 D keymaster_tee: [DEBUG]: (nwd_keymaster_mobicore.c:353) TLC_COMMAND(e): cmd = 0x0000000B, ret = 0x00000000
12-23 15:49:48.717  4368  4368 I keymaster_tee: [INFO]:  (nwd_keymaster_mdfpp.cpp:855) exit export_key function, returns 0
12-23 15:49:48.717  4368  4368 I keymaster_tee: [INFO]:  (nwd_keymaster_mdfpp.cpp:880) entered begin function.
12-23 15:49:48.728  4368  4368 D keymaster_tee: [DEBUG]: (nwd_keymaster_mobicore.c:353) TLC_COMMAND(e): cmd = 0x0000000E, ret = 0x00000000
12-23 15:49:48.729  4368  4368 I keymaster_tee: [INFO]:  (nwd_keymaster_mdfpp.cpp:889) exit begin function, returns 0
12-23 15:49:48.731  4368  4368 I keymaster_tee: [INFO]:  (nwd_keymaster_mdfpp.cpp:900) entered update function.
12-23 15:49:48.732  4368  4368 D keymaster_tee: [DEBUG]: (nwd_keymaster_mobicore.c:353) TLC_COMMAND(e): cmd = 0x0000000F, ret = 0x00000000
12-23 15:49:48.732  4368  4368 I keymaster_tee: [INFO]:  (nwd_keymaster_mdfpp.cpp:910) exit update function, returns 0
12-23 15:49:48.733  4368  4368 I keymaster_tee: [INFO]:  (nwd_keymaster_mdfpp.cpp:920) entered finish function.
12-23 15:49:48.838  4368  4368 D keymaster_tee: [DEBUG]: (nwd_keymaster_mobicore.c:353) TLC_COMMAND(e): cmd = 0x00000010, ret = 0x00000000
12-23 15:49:48.838  4368  4368 I keymaster_tee: [INFO]:  (nwd_keymaster_mdfpp.cpp:930) exit finish function, returns 0
12-23 15:49:48.843 10769 10769 D AndroidRuntime: Shutting down VM
```

termux-info:
```
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://grimler.se/termux-packages-24 stable main
# unstable-repo (sources.list.d/unstable.list)
deb https://grimler.se/unstable-packages unstable main
# game-repo (sources.list.d/game.list)
deb https://grimler.se/game-packages-24 games stable
# root-repo (sources.list.d/root.list)
deb https://grimler.se/termux-root-packages-24 root stable
# science-repo (sources.list.d/science.list)
deb https://grimler.se/science-packages-24 science stable
# x11-repo (sources.list.d/x11.list)
deb https://grimler.se/x11-packages x11 main
# sources.list.d/game.list.dpkg-dist
deb https://dl.bintray.com/grimler/game-packages-24 games stable
# sources.list.d/pointless.list
deb https://its-pointless.github.io/files/24 termux extras
# sources.list.d/science.list.dpkg-dist
deb https://dl.bintray.com/grimler/science-packages-24 science stable
Updatable packages:
All packages up to date
Android version:
10
Kernel build information:
Linux localhost 4.4.111-g3d23f5e2bc86 #1 SMP PREEMPT Mon Dec 21 21:24:58 CET 2020 aarch64 Android
Device manufacturer:
samsung
Device model:
SM-G955F
```

**Comment by xeffyr** [comment]
Seems like something to do with `valididy` (setUserAuthenticationValidityDurationSeconds) - that parameter is used to configure keystore behavior like in yours case.

But `termux-keystore` should have it disabled by default.

**Comment by Grimler91** [comment]
Oh, yeah, I did set validity to 120 s when I generated this key. Generating a new key with validity = 0 seem to work, thanks.

Closing since this is intended behavior if validity != 0 then!
