### ISSUE TITLE
The latest npm package '@mapbox/mapbox-gl-native' required old version nodejs(10.20.0/10.20.1)

### ISSUE THREAD

**Issue by fengzidan** [termux/termux-packages#6479]
## Requesting new package

*Not every package request can be fulfilled. Our repository is big enough to imply some issues with maintaining and hosting.*

- [x] I have read [Termux policy on package requests](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#a-note-about-package-requests).

[@mapbox/mapbox-gl-native](https://www.npmjs.com/package/@mapbox/mapbox-gl-native)

The latest npm package '@mapbox/mapbox-gl-native' required old version nodejs(10.20.0/10.20.1),But termux-packages contains of nodejs-lts(12.*).

**Additional information**
Have you compiled or tried to compile the package on device?
* If it did not work then please provide the error you ran into.
* If it did work then please share build steps and any patches that you had to apply.

PC(Not Android):
```shell
node-pre-gyp WARN Using request for node-pre-gyp https download
node-pre-gyp ERR! install error
node-pre-gyp ERR! stack Error: 403 status code downloading tarball https://mapbox-node-binary.s3.amazonaws.com/@mapbox/mapbox-gl-native/v5.0.2/node-v83-darwin-x64-Release.tar.gz
node-pre-gyp ERR! stack     at Request.<anonymous> (/Users/jianju/Desktop/code/gt-dataviz-engine/node_modules/@mapbox/mapbox-gl-native/node_modules/node-pre-gyp/lib/install.js:137:27)
node-pre-gyp ERR! stack     at Request.emit (events.js:327:22)
node-pre-gyp ERR! stack     at Request.onRequestResponse (/Users/jianju/Desktop/code/gt-dataviz-engine/node_modules/request/request.js:1059:10)
node-pre-gyp ERR! stack     at ClientRequest.emit (events.js:315:20)
node-pre-gyp ERR! stack     at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:632:27)
node-pre-gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:117:17)
node-pre-gyp ERR! stack     at TLSSocket.socketOnData (_http_client.js:501:22)
node-pre-gyp ERR! stack     at TLSSocket.emit (events.js:315:20)
node-pre-gyp ERR! stack     at addChunk (_stream_readable.js:296:12)
node-pre-gyp ERR! stack     at readableAddChunk (_stream_readable.js:272:9)
node-pre-gyp ERR! System Darwin 20.2.0
node-pre-gyp ERR! command "/usr/local/bin/node" "/Users/jianju/Desktop/code/gt-dataviz-engine/node_modules/@mapbox/mapbox-gl-native/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build=false"
node-pre-gyp ERR! cwd /Users/jianju/Desktop/code/gt-dataviz-engine/node_modules/@mapbox/mapbox-gl-native
node-pre-gyp ERR! node -v v14.0.0
node-pre-gyp ERR! node-pre-gyp -v v0.10.3
node-pre-gyp ERR! not ok
403 status code downloading tarball https://mapbox-node-binary.s3.amazonaws.com/@mapbox/mapbox-gl-native/v5.0.2/node-v83-darwin-x64-Release.tar.gz
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @mapbox/mapbox-gl-native@5.0.2 install: `node-pre-gyp install --fallback-to-build=false`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @mapbox/mapbox-gl-native@5.0.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

And `npm i` successed when `nvm use 10.20.0`

**Comment by Grimler91** [comment]
Nodejs 10 has its EOL in april, does not make sense to add it. The real issue here is that mapbox requires an old node version, so consider opening an issue in their repo about that. 

Does not look like mapbox is actively developed anymore though so I guess you have to look for another solution (or make mapbox compatible with newer versions yourself)
