### ISSUE TITLE
buildorder.py causes UnicodeDecodeError when run from within Docker

### ISSUE THREAD

**Issue by Neo-Oli** [termux/termux-packages#665]
Because of @vaites' name, buildorder.py encounters a non-ascii character (in packages/ne/build.sh). For some reason the docker process doesn't have the proper locale set, and python will encode with ascii by default. 
```
$ ./scripts/run-docker ./build-package.sh par2
Traceback (most recent call last):
  File "./scripts/buildorder.py", line 228, in <module>
    populate()
  File "./scripts/buildorder.py", line 138, in populate
    pkg = TermuxPackage(pkgdir_name)
  File "./scripts/buildorder.py", line 77, in __init__
    self.deps = self.buildfile._get_dependencies()
  File "./scripts/buildorder.py", line 45, in _get_dependencies
    for line in f:
  File "/usr/lib/python3.5/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 162: ordinal not in range(128)
```

**Comment by Neo-Oli** [comment]
I created a Pull Request with a possible fix. 
Another approach to fixing that would be to fix the Docker environment to use the proper locale, but *I think* this would cause everyone to need to rebuilt the Docker container.
