### ISSUE TITLE
Openjdk cannot use graphics.

### ISSUE THREAD

**Issue by Local-Micro** [termux/termux-packages#7313]
**Problem description**

I get some errors when I try to start HMCL or BurpSuite.
HMCL
```
JavaFX is missing.
If you are using Java 11 or later, please downgrade to Java 8 or 10.
If you are using OpenJDK, please ensure OpenJFX is included.
A fatal error has occurred, forcibly exiting.
Exception in thread "main" java.lang.UnsatisfiedLinkError: Can't load library: /data/data/com.termux/files/usr/opt/openjdk/lib/libawt_xawt.so
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2393)
	at java.base/java.lang.Runtime.load0(Runtime.java:751)
	at java.base/java.lang.System.load(System.java:1912)
	at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
	at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:384)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:228)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:170)
	at java.base/jdk.internal.loader.NativeLibraries.findFromPaths(NativeLibraries.java:311)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:281)
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2398)
	at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:814)
	at java.base/java.lang.System.loadLibrary(System.java:1948)
	at java.desktop/java.awt.Toolkit$2.run(Toolkit.java:1388)
	at java.desktop/java.awt.Toolkit$2.run(Toolkit.java:1386)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
	at java.desktop/java.awt.Toolkit.loadLibraries(Toolkit.java:1385)
	at java.desktop/java.awt.Toolkit.initStatic(Toolkit.java:1423)
	at java.desktop/java.awt.Toolkit.<clinit>(Toolkit.java:1397)
	at java.desktop/java.awt.Component.<clinit>(Component.java:624)
	at org.jackhuang.hmcl.Main.showErrorAndExit(Main.java:114)
	at org.jackhuang.hmcl.Main.checkJavaFX(Main.java:82)
	at org.jackhuang.hmcl.Main.main(Main.java:51)
```
BurpSuite:
```
Could not start Burp:java.lang.UnsatisfiedLinkError: Can't load library: /data/data/com.termux/files/usr/opt/openjdk/lib/libawt_xawt.so
```
**Additional information**

```
Application version:
0.117
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://mirrors.tuna.tsinghua.edu.cn/termux/apt/termux-main stable main
# game-repo (sources.list.d/game.list)
deb https://mirrors.tuna.tsinghua.edu.cn/termux/apt/termux-games games stable
# science-repo (sources.list.d/science.list)
deb https://mirrors.tuna.tsinghua.edu.cn/termux/apt/termux-science science stable
# unstable-repo (sources.list.d/unstable.list)
deb https://mirrors.tuna.tsinghua.edu.cn/termux/apt/termux-unstable unstable main
# x11-repo (sources.list.d/x11.list)
deb https://mirrors.tuna.tsinghua.edu.cn/termux/apt/termux-x11 x11 main
Updatable packages:
All packages up to date
Android version:
10
Kernel build information:
Linux localhost 4.14.116 #1 SMP PREEMPT Thu Jul 1 17:09:17 CST 2021 aarch64 Android
Device manufacturer:
HUAWEI
Device model:
STK-AL00
```

**Comment by xeffyr** [comment]
Expected behavior, this is headless build.

**Comment by suhan-paradkar** [comment]
If you want a non-headless build of openJDK17.. with x enabled.. checkout the debs here.. https://github.com/suhan-paradkar/tewmux-disabled/releases/tag/jdk-with-x11

**Comment by xeffyr** [comment]
@suhan-paradkar In OP's case downgrade to Java 8/10 would be required as well.

**Comment by suhan-paradkar** [comment]
Yes... Also OP would require openJFX also...

**Comment by masterjavaofficial** [comment]
Please upgrade the OpenJDK-17 package as full package, NOT headless, its a request from my heart. I wanted Java in Termux only for graphical perposes, and now its in Termux but it doesn't support graphics!!!

**Comment by suhan-paradkar** [comment]
> Please upgrade the OpenJDK-17 package as full package, NOT headless, its a request from my heart. I wanted Java in Termux only for graphical perposes, and now its in Termux but it doesn't support graphics!!!

Its already enabled...

**Comment by masterjavaofficial** [comment]
> > Please upgrade the OpenJDK-17 package as full package, NOT headless, its a request from my heart. I wanted Java in Termux only for graphical perposes, and now its in Termux but it doesn't support graphics!!!
> 
> Its already enabled...

Swing and AWT are supporting??

**Comment by masterjavaofficial** [comment]
> > Please upgrade the OpenJDK-17 package as full package, NOT headless, its a request from my heart. I wanted Java in Termux only for graphical perposes, and now its in Termux but it doesn't support graphics!!!
> 
> Its already enabled...
> OpenJDK17 currently has gui support and also errors pertaining to arm devices are fixed

Ohh I didn't update it since I'm in village and having data shortage. 😅 Thanks for your information! ❤️

**Comment by Yonle** [comment]
Remember that **__porting some package is not easier than you though__**. If you want something you should request and not be arrogant stating that I want it anyhow
