### ISSUE TITLE
[Bug]: Python3.10: Cannot access $PREFIX/lib

### ISSUE THREAD

**Issue by Yisus7u7** [termux/termux-packages#8013]
### Problem description

when you use some python modules that you want to access $PREFIX/lib you get a permission denied error 

### What steps will reproduce the bug?

This affects very important things, such as meson. 

### What is the expected behavior?

A simple compilation with meson :

```bash
Version: 0.60.1
Source dir: /data/data/com.termux/files/home/Documents/gtk-apps
Build dir: /data/data/com.termux/files/home/Documents/gtk-apps/build
Build type: native build
Project name: gtk-example
Project version: 0.0.1
C++ compiler for the host machine: c++ (clang 13.0.0 "clang version 13.0.0")
C++ linker for the host machine: c++ ld.lld 13.0.0
Host machine cpu family: arm
Host machine cpu: armv7l
Found pkg-config: /data/data/com.termux/files/usr/bin/pkg-config (0.29.2)
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/mesonbuild/mesonmain.py", line 138, in run
    return options.run_func(options)
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/mesonbuild/msetup.py", line 294, in run
    app.generate()
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/mesonbuild/msetup.py", line 185, in generate
    self._generate(env)
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/mesonbuild/msetup.py", line 229, in _generate
    intr.run()
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/mesonbuild/interpreter/interpreter.py", line 2484, in run
    super().run()
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/mesonbuild/interpreterbase/interpreterbase.py", line 148, in run
    self.evaluate_codeblock(self.ast, start=1)
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/mesonbuild/interpreterbase/interpreterbase.py", line 173, in evaluate_codeblock
    raise e
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/mesonbuild/interpreterbase/interpreterbase.py", line 166, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/mesonbuild/interpreterbase/interpreterbase.py", line 181, in evaluate_statement
    self.assignment(cur)
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/mesonbuild/interpreterbase/interpreterbase.py", line 566, in assignment
    value = self.evaluate_statement(node.value)
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/mesonbuild/interpreterbase/interpreterbase.py", line 179, in evaluate_statement
    return self.function_call(cur)
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/mesonbuild/interpreterbase/interpreterbase.py", line 454, in function_call
    res = func(node, func_args, kwargs)
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/mesonbuild/interpreterbase/decorators.py", line 713, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/mesonbuild/interpreterbase/decorators.py", line 713, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/mesonbuild/interpreterbase/decorators.py", line 713, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  [Previous line repeated 5 more times]
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/mesonbuild/interpreterbase/decorators.py", line 96, in wrapped
    ret = f(*wrapped_args, **wrapped_kwargs)
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/mesonbuild/interpreterbase/decorators.py", line 115, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/mesonbuild/interpreterbase/decorators.py", line 276, in wrapper
    return f(*nargs, **wrapped_kwargs)
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/mesonbuild/interpreter/interpreter.py", line 1521, in func_dependency
    d = df.lookup(kwargs)
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/mesonbuild/interpreter/dependencyfallbacks.py", line 347, in lookup
    dep = func(kwargs, func_args, func_kwargs)
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/mesonbuild/interpreter/dependencyfallbacks.py", line 90, in _do_dependency
    dep = dependencies.find_external_dependency(name, self.environment, kwargs)
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/mesonbuild/dependencies/detect.py", line 114, in find_external_dependency
    d = c()
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/mesonbuild/dependencies/pkgconfig.py", line 96, in __init__
    self._set_libs()
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/mesonbuild/dependencies/pkgconfig.py", line 384, in _set_libs
    self.link_args, self.raw_link_args = self._search_libs(out, out_raw)
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/mesonbuild/dependencies/pkgconfig.py", line 308, in _search_libs
    args = self.clib_compiler.find_library(lib[2:], self.env,
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/mesonbuild/compilers/mixins/clike.py", line 1118, in find_library
    return self._find_library_impl(libname, env, extra_dirs, code, libtype)
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/mesonbuild/compilers/mixins/clike.py", line 1107, in _find_library_impl
    value = self._find_library_real(libname, env, extra_dirs, code, libtype)
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/mesonbuild/compilers/mixins/clike.py", line 1087, in _find_library_real
    for d in itertools.chain(extra_dirs, self.get_library_dirs(env, elf_class)):
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/mesonbuild/compilers/mixins/clike.py", line 254, in get_library_dirs
    return self._get_library_dirs(env, elf_class).copy()
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/mesonbuild/compilers/mixins/clike.py", line 224, in _get_library_dirs
    files = [f for f in os.listdir(d) if f.endswith('.so') and os.path.isfile(os.path.join(d, f))]
PermissionError: [Errno 13] Permission denied: '/data/data/com.termux/files/lib'
```

This happens with everything you want to access lib from a python script. 

### System information

termux-info:

```
Application version:
0.117
Packages CPU architecture:
arm
Subscribed repositories:
# sources.list
deb https://termux.mentality.rip/termux-main/ stable main
# game-repo (sources.list.d/game.list)
deb https://packages.termux.org/apt/termux-games games stable
# science-repo (sources.list.d/science.list)
deb https://packages.termux.org/apt/termux-science science stable
# x11-repo (sources.list.d/x11.list)
deb https://packages.termux.org/apt/termux-x11 x11 main
Updatable packages:
All packages up to date
Android version:
8.0.0
Kernel build information:
Linux localhost 3.18.71-perf-gb847930 #1 SMP PREEMPT Fri Sep 27 14:15:01 CDT 2019 armv7l Android
Device manufacturer:
motorola
Device model:
moto e5 cruise
```

**Comment by Grimler91** [comment]
What do you mean with `This happens with everything you want to access lib from a python script.`? 
How can the issue be reproduced?

Seems like something that should be [reported to the meson developers](https://github.com/mesonbuild/meson/issues/new?assignees=&labels=&template=bug_report.md&title=), erroring on "permission denied" when looping over a list of directories seems like undesired behaviour in this case.

Since the error is in meson, which is not a termux package, there is not really anything we can do from termux side of things

**Comment by xtkoba** [comment]
I guess `c++ --print-search-dirs | grep ^libraries:` contains `/data/data/com.termux/files/lib` that does not exist.

**Comment by xtkoba** [comment]
Or rather, `/data/data/com.termux/files/lib` does exist but has funny permissions.

**Comment by xtkoba** [comment]
Note that `/data/data/com.termux/files` is not `$TERMUX_PREFIX` but `$TERMUX_BASE_DIR`. It is the default sysroot for Clang in Termux.

**Comment by Yisus7u7** [comment]
Solved. 
I had some folders that pointed to Android folders in `/data/data/com.termux/files`, I don't know how they were created, but after deleting them everything returned to normal. 

But I find this very strange, I do not run third-party scripts, the only thing I do is compile
