### ISSUE TITLE
[Bug]: erlang build need ssl

### ISSUE THREAD

**Issue by zlfera** [termux/termux-packages#8158]
### Problem description

hex need ssl, but erlang  did  not  use ssl 

### What steps will reproduce the bug?

use  command   `mix local.hex`

### System information

termux-info:

```

```
Android version:
10
Kernel build information:
Linux localhost 4.9.193-perf-gc285628 #1 SMP PREEMPT Fri Jul 23 00:16:52 CST 2021 aarch64 Android

**Comment by Barkatzangidodo** [comment]
Termux installation

**Comment by xtkoba** [comment]
I can reproduce this (on Android 8.1.0 aarch64):

```
$ mix local.hex

12:39:15.018 [error] Task #PID<0.105.0> started from #PID<0.94.0> terminating
** (MatchError) no match of right hand side value: {:error, {:ssl, {'no such file or directory', 'ssl.app'}}}
    (mix 1.13.0) lib/mix/utils.ex:640: Mix.Utils.read_httpc/1
    (mix 1.13.0) lib/mix/utils.ex:572: anonymous fn/2 in Mix.Utils.read_path/2
    (elixir 1.13.0) lib/task/supervised.ex:89: Task.Supervised.invoke_mfa/2
    (elixir 1.13.0) lib/task/supervised.ex:34: Task.Supervised.reply/4
    (stdlib 3.16.1) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Function: #Function<5.25885739/0 in Mix.Utils.read_path/2>
    Args: []
** (EXIT from #PID<0.94.0>) an exception was raised:
    ** (MatchError) no match of right hand side value: {:error, {:ssl, {'no such file or directory', 'ssl.app'}}}
        (mix 1.13.0) lib/mix/utils.ex:640: Mix.Utils.read_httpc/1
        (mix 1.13.0) lib/mix/utils.ex:572: anonymous fn/2 in Mix.Utils.read_path/2
        (elixir 1.13.0) lib/task/supervised.ex:89: Task.Supervised.invoke_mfa/2
        (elixir 1.13.0) lib/task/supervised.ex:34: Task.Supervised.reply/4
        (stdlib 3.16.1) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
```

BTW, `bin/mix` belongs to the `elixir` package.
