### ISSUE TITLE
[Package]: python-libtorrent

### ISSUE THREAD

**Issue by giedriusStan** [termux/termux-packages#8197]
### Package description

This package is needed to run deluged, otherwise a following error occurs

`Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/deluge/_libtorrent.py", line 23, in <module>
    import deluge.libtorrent as lt
ModuleNotFoundError: No module named 'deluge.libtorrent'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/bin/deluged", line 8, in <module>
    sys.exit(start_daemon())
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/deluge/core/daemon_entry.py", line 90, in start_daemon
    from deluge.core.daemon import is_daemon_running
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/deluge/core/daemon.py", line 22, in <module>
    from deluge.core.core import Core
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/deluge/core/core.py", line 28, in <module>
    from deluge._libtorrent import LT_VERSION, lt
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/deluge/_libtorrent.py", line 25, in <module>
    import libtorrent as lt
ImportError: dlopen failed: "/data/data/com.termux/files/usr/lib/python3.10/site-packages/libtorrent.so" has unexpected e_machine: 62 (EM_X86_64`

Build instructions are provided here http://www.libtorrent.org/python_binding.html , but I was unable to get it working

### Source code URL

https://github.com/arvidn/libtorrent/tree/RC_2_0/bindings/python

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

**Comment by xtkoba** [comment]
A part of `libtorrent-rasterbar` (#3327).

The question is that if we can make an exception for this, just like we did for `gobject-introspection`.
