### ISSUE TITLE
matplotlib stopped working after recent python upgrade

### ISSUE THREAD

**Issue by tigran123** [termux/termux-packages#881]
Note that with Python 3.6.0 it seemed to work, if I remember correctly. But now (with Python 3.6.1) I get this:

```
$ python3 solplay.py -o test.mp4 -s ~/tmp/solanim.ZVA7/solqr
Traceback (most recent call last):
  File "solplay.py", line 26, in <module>
    import matplotlib.pyplot as plt
  File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/matplotlib/pyplot.py", line 29, in <module>
    import matplotlib.colorbar
  File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/matplotlib/colorbar.py", line 32, in <module>
    import matplotlib.artist as martist
  File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/matplotlib/artist.py", line 15, in <module>
    from .transforms import (Bbox, IdentityTransform, TransformedBbox,
  File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/matplotlib/transforms.py", line 39, in <module>
    from matplotlib._path import (affine_transform, count_bboxes_overlapping_bbox,
ModuleNotFoundError: No module named 'matplotlib._path'
```

Do I need to recompile matplotlib for 3.6.1? It is trying to use the one compiled for 3.6.0.

**Comment by tigran123** [comment]
Yes, recompiling matplotlib (simply by `pip install matplotlib`) fixes the problem, so I am closing the issue.

**Comment by fornwall** [comment]
Hm, recompiling python modules shouldn't be needed after version upgrades, right? Tracking the issue at https://github.com/termux/termux-packages/issues/883
