### ISSUE TITLE
Python modules broken after upgrading to python 3.6.1, needs reinstallation from pip

### ISSUE THREAD

**Issue by clancia** [termux/termux-packages#883]
After upgrading to python 3.6.1 importing zmq raises an error

```python
>>> import zmq
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/zmq/__init__.py", line 34, in <module>
    from zmq import backend
  File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/zmq/backend/__init__.py", line 40, in <module>
    reraise(*exc_info)
  File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/zmq/utils/sixcerpt.py", line 34, in reraise
    raise value
  File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/zmq/backend/__init__.py", line 27, in <module>
    _ns = select_backend(first)
  File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/zmq/backend/select.py", line 26, in select_backend
    mod = __import__(name, fromlist=public_api)
  File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/zmq/backend/cython/__init__.py", line 6, in <module>
    from . import (constants, error, message, context,
ImportError: cannot import name 'constants'
```
packages installed:

python/stable,now 3.6.1 x86_64 [installed]
  Python 3 programming language intended to enable clear programs

python-dev/stable,now 3.6.1 x86_64 [installed]
  Development files for python

libzmq/stable,now 4.2.2 x86_64 [installed]
  Fast messaging system built on sockets. C and C++ bindings. aka 0MQ, ZMQ.

libzmq-dev/stable,now 4.2.2 x86_64 [installed]
  Development files for libzmq

**Comment by fornwall** [comment]
Does it work if you uninstall the python bindings and install again?

If so, I suspect the `prerm` trigger not working correctly (it tries to uninstall everything install through pip when uninstalling python, perhaps it runs by mistake even when updating).

**Comment by clancia** [comment]
I have reinstalled both python and pyzmq. I am quite unexperienced, sorry.
I understood what reinstalling the python bindings meant only too late.
Anyway, it works again now, so I think you were right!
Thanks

**Comment by clancia** [comment]
BTW, after upgrading to python 3.6.1, also numpy ans pandas were not working and reinstalling them had solved the issue...

**Comment by fornwall** [comment]
Ok, so seems to be a problem here (that can be fixed by re-installing python modules after upgrading - but that shouldn't be needed for minor python updates).
