### ISSUE TITLE
Issue while installing sqlite3 with npm

### ISSUE THREAD

**Issue by Z0LDevs-varnion** [termux/termux-packages#8879]
### Problem description

Hello,im trying to install sqlite3 from command ``npm install sqlite3`` after i failed to install n8n by command ``npx n8n``

```
npm v 8.1.2
python 3.10.2 
nodejs v 16.13.2
```

Ive tried consulting with n8n but they suggested me to contact termux team

Heres the full logs:
```
pkg install  sqlite3
Checking availability of current mirror: ok
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package sqlite3
~ $ npm install sqlite3
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated node-pre-gyp@0.11.0: Please upgrade to @mapbox/node-pre-gyp: the non-scoped node-pre-gyp package is deprecated and only the @mapbox scoped package will recieve updates in the future
npm WARN deprecated tar@2.2.2: This version of tar is no longer supported, and will not receive security updates. Please upgrade asap.
[##################] | reify:tar: WARN deprecated tar@2.2.2: This version o
> sqlite3@5.0.2 install
> node-pre-gyp install --fallback-to-build

node-pre-gyp info it worked if it ends with okted tar@2.2.2: This version o
node-pre-gyp info using node-pre-gyp@0.11.0
node-pre-gyp info using node@16.13.2 | android | arm64
node-pre-gyp WARN Using request for node-pre-gyp https download s version o
node-pre-gyp info check checked for "/data/data/com.termux/files/home/node_modules/sqlite3/lib/binding/napi-v3-android-arm64/node_sqlite3.node" (not found)
node-pre-gyp http GET https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v5.0.2/napi-v3-android-arm64.tar.gz
node-pre-gyp http 403 https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v5.0.2/napi-v3-android-arm64.tar.gz
node-pre-gyp WARN Tried to download(403): https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v5.0.2/napi-v3-android-arm64.tar.gz
node-pre-gyp WARN Pre-built binaries not found for sqlite3@5.0.2 and node@16.13.2 (node-v93 ABI, unknown) (falling back to source compile with node-gyp)
node-pre-gyp http 403 status code downloading tarball https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v5.0.2/napi-v3-android-arm64.tar.gz
gyp info it worked if it ends with okN deprecated tar@2.2.2: This version o
gyp info using node-gyp@8.3.0
gyp info using node@16.13.2 | android | arm64
gyp info ok #######] | reify:tar: WARN deprecated tar@2.2.2: This version o
gyp info it worked if it ends with okN deprecated tar@2.2.2: This version o
gyp info using node-gyp@8.3.0
gyp info using node@16.13.2 | android | arm64
gyp info find Python using Python version 3.10.2 found at "/data/data/com.termux/files/usr/bin/python3"
gyp http GET https://nodejs.org/download/release/v16.13.2/node-v16.13.2-headers.tar.gz
gyp http 200 https://nodejs.org/download/release/v16.13.2/node-v16.13.2-headers.tar.gz
gyp http GET https://nodejs.org/download/release/v16.13.2/SHASUMS256.txtn o
gyp http 200 https://nodejs.org/download/release/v16.13.2/SHASUMS256.txtn o
gyp info spawn /data/data/com.termux/files/usr/bin/python32: This version o
gyp info spawn args [
gyp info spawn args   '/data/data/com.termux/files/usr/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/data/data/com.termux/files/home/node_modules/sqlite3/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/data/data/com.termux/files/usr/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/data/data/com.termux/files/home/.cache/node-gyp/16.13.2/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/data/data/com.termux/files/home/.cache/node-gyp/16.13.2',
gyp info spawn args   '-Dnode_gyp_dir=/data/data/com.termux/files/usr/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/data/data/com.termux/files/home/.cache/node-gyp/16.13.2/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/data/data/com.termux/files/home/node_modules/sqlite3',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info ok #######] | reify:tar: WARN deprecated tar@2.2.2: This version o
gyp info it worked if it ends with[##################] | reify:tar: WARN dep okated tar@2.2.2: This version o
gyp info using node-gyp@8.3.0
gyp info using node@16.13.2 | android | arm64
gyp info spawn make] | reify:tar: WARN deprecated tar@2.2.2: This version o
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory '/data/data/com.termux/files/home/node_modules/sqlite3/build'
  CC(target) Release/obj.target/nothing/../node-addon-api/nothing.o
  AR(target) Release/obj.target/../node-addon-api/nothing.a: This version o
/data/data/com.termux/files/usr/bin/sh: 1: ar: not found2.2: This version o
make: *** [../node-addon-api/nothing.target.mk:132: Release/obj.target/../node-addon-api/nothing.a] Error 127
make: Leaving directory '/data/data/com.termux/files/home/node_modules/sqlite3/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/data/data/com.termux/files/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (node:events:390:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
gyp ERR! System Linux 4.4.299-Mystic-EAS_x8.9-OC
gyp ERR! command "/data/data/com.termux/files/usr/bin/node" "/data/data/com.termux/files/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/data/data/com.termux/files/home/node_modules/sqlite3/lib/binding/napi-v3-android-arm64/node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=/data/data/com.termux/files/home/node_modules/sqlite3/lib/binding/napi-v3-android-arm64" "--napi_version=8" "--node_abi_napi=napi" "--napi_build_version=3" "--node_napi_label=napi-v3"
gyp ERR! cwd /data/data/com.termux/files/home/node_modules/sqlite3
gyp ERR! node -v v16.13.2
gyp ERR! node-gyp -v v8.3.0
gyp ERR! not ok
node-pre-gyp ERR! build error ar: WARN deprecated tar@2.2.2: This version o
node-pre-gyp ERR! stack Error: Failed to execute '/data/data/com.termux/files/usr/bin/node /data/data/com.termux/files/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/data/data/com.termux/files/home/node_modules/sqlite3/lib/binding/napi-v3-android-arm64/node_sqlite3.node --module_name=node_sqlite3 --module_path=/data/data/com.termux/files/home/node_modules/sqlite3/lib/binding/napi-v3-android-arm64 --napi_version=8 --node_abi_napi=napi --napi_build_version=3 --node_napi_label=napi-v3' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/data/data/com.termux/files/home/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:390:28)
node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1064:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
node-pre-gyp ERR! System Linux 4.4.299-Mystic-EAS_x8.9-OC
node-pre-gyp ERR! command "/data/data/com.termux/files/usr/bin/node" "/data/data/com.termux/files/home/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /data/data/com.termux/files/home/node_modules/sqlite3
node-pre-gyp ERR! node -v v16.13.2
node-pre-gyp ERR! node-pre-gyp -v v0.11.0
node-pre-gyp ERR! not ok
Failed to execute '/data/data/com.termux/files/usr/bin/node /data/data/com.termux/files/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/data/data/com.termux/files/home/node_modules/sqlite3/lib/binding/napi-v3-android-arm64/node_sqlite3.node --module_name=node_sqlite3 --module_path=/data/data/com.termux/files/home/node_modules/sqlite3/lib/binding/napi-v3-android-arm64 --napi_version=8 --node_abi_napi=napi --napi_build_version=3 --node_napi_label=napi-v3' (1)
npm notice
npm notice New minor version of npm available! 8.1.2 -> 8.4.0
npm notice Changelog: https://github.com/npm/cli/releases/tag/v8.4.0
npm notice Run npm install -g npm@8.4.0 to update!
npm notice
npm ERR! code 1
npm ERR! path /data/data/com.termux/files/home/node_modules/sqlite3
npm ERR! command failed
npm ERR! command sh -c node-pre-gyp install --fallback-to-build

npm ERR! A complete log of this run can be found in:
npm ERR!     /data/data/com.termux/files/home/.npm/_logs/2022-02-02T10_22_13_574Z-debug.log
```

### What steps will reproduce the bug?

Trying to install required ``sqlite3`` packange needed for ``n8n`` to run
Ive manually installed the required packange because when im using cmd ``npx n8n`` it shows error

### System information

termux-info:

```
Application version:
0.118.0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://packages-cf.termux.org/apt/termux-main/ stable main
Updatable packages:
All packages up to date
Android version:
11
Kernel build information:
Linux localhost 4.4.299-Mystic-EAS_x8.9-OC #1 SMP PREEMPT Wed Jan 12 10:40:02 WIB 2022 aarch64 Android
Device manufacturer:
Google
Device model:
Pixel 5
```

**Comment by Grimler91** [comment]
> /data/data/com.termux/files/usr/bin/sh: 1: ar: not found

Looks like you need to install binutils

**Comment by Z0LDevs-varnion** [comment]
Thanks now it worked

**Comment by FxPixels** [comment]
> Thanks now it worked

how to do ?
