### ISSUE TITLE
'repo init' error: No such file or directory: '/dev/shm'

### ISSUE THREAD

**Issue by Mark-Joy** [termux/termux-packages#8938]
### Problem description

Download `repo` tool and run `repo init`

```
 λ [~] $ wget https://storage.googleapis.com/git-repo-downloads/repo -O repo
--2022-02-07 09:12:01--  https://storage.googleapis.com/git-repo-downloads/repo
Resolving storage.googleapis.com... 2404:6800:4005:80b::2010, 2404:6800:4005:812::2010, 2404:6800:4005:813::2010, ...
Connecting to storage.googleapis.com|2404:6800:4005:80b::2010|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 45277 (44K) [application/octet-stream]
Saving to: ‘repo’

repo           100�====>]  44.22K  --.-KB/s    in 0.1s

2022-02-07 09:12:01 (319 KB/s) - ‘repo’ saved [45277/45277]

λ [~] $ chmod +x repo
λ [~] $ repo init
Downloading Repo source from https://gerrit.googlesource.com/git-repo
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/.repo/repo/main.py", line 39, in <module>
    import event_log
  File "/data/data/com.termux/files/home/.repo/repo/event_log.py", line 163, in <module>
    _EVENT_ID = multiprocessing.Value('i', 1)
  File "/data/data/com.termux/files/usr/lib/python3.10/multiprocessing/context.py", line 135, in Value
    return Value(typecode_or_type, *args, lock=lock,
  File "/data/data/com.termux/files/usr/lib/python3.10/multiprocessing/sharedctypes.py", line 74, in Value
    obj = RawValue(typecode_or_type, *args)
  File "/data/data/com.termux/files/usr/lib/python3.10/multiprocessing/sharedctypes.py", line 49, in RawValue
    obj = _new_value(type_)
  File "/data/data/com.termux/files/usr/lib/python3.10/multiprocessing/sharedctypes.py", line 41, in _new_value
    wrapper = heap.BufferWrapper(size)
  File "/data/data/com.termux/files/usr/lib/python3.10/multiprocessing/heap.py", line 331, in __init__
    block = BufferWrapper._heap.malloc(size)
  File "/data/data/com.termux/files/usr/lib/python3.10/multiprocessing/heap.py", line 309, in malloc
    (arena, start, stop) = self._malloc(size)
  File "/data/data/com.termux/files/usr/lib/python3.10/multiprocessing/heap.py", line 192, in _malloc
    return self._new_arena(size)
  File "/data/data/com.termux/files/usr/lib/python3.10/multiprocessing/heap.py", line 166, in _new_arena
    arena = Arena(length)
  File "/data/data/com.termux/files/usr/lib/python3.10/multiprocessing/heap.py", line 85, in __init__
    dir=self._choose_dir(size))
  File "/data/data/com.termux/files/usr/lib/python3.10/multiprocessing/heap.py", line 95, in _choose_dir
    st = os.statvfs(d)
FileNotFoundError: [Errno 2] No such file or directory: '/dev/shm'
λ [~] $
```

### What steps will reproduce the bug?

```
wget https://storage.googleapis.com/git-repo-downloads/repo -O repo
chmod +x repo
repo init
```

### System information

termux-info:

```
Application version:
0.118.0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://packages.termux.org/apt/termux-main/ stable main
# game-repo (sources.list.d/game.list)
deb https://packages.termux.org/apt/termux-games games stable
# sources.list.d/unstable.list
deb https://packages.termux.org/apt/termux-unstable unstable main
# science-repo (sources.list.d/science.list)
deb https://packages.termux.org/apt/termux-science science stable
Updatable packages:
git/stable 2.35.1 aarch64 [upgradable from: 2.35.0]
Android version:
9
Kernel build information:
Linux localhost 4.14.94+ #1 SMP PREEMPT Mon Nov 18 23:44:03 CST 2019 aarch64 Android
Device manufacturer:
Xiaomi
Device model:
Redmi Note 8 Pro

```

**Comment by chyn0907** [comment]
Maybe you can fix it by remove candidate directories in multiprocessing module.

**Comment by licy183** [comment]
Maybe you can fix it by removing candidate directories in multiprocessing module.

```
diff -uNr Python-3.10.1/Lib/multiprocessing/heap.py Python-3.10.1.mod/
Lib/multiprocessing/heap.py
--- Python-3.10.1/Lib/multiprocessing/heap.py   2022-02-07 11:51:46.427116300 +0800
+++ Python-3.10.1.mod/Lib/multiprocessing/heap.py       2022-02-07 11:52:48.432577700 +0800
@@ -70,7 +70,7 @@
         """

         if sys.platform == 'linux':
-            _dir_candidates = ['/dev/shm']
+            _dir_candidates = []
         else:
             _dir_candidates = []

```

**Comment by Mark-Joy** [comment]
@licy183 
I got the following error after edit heap.py
```
λ [~] $ repo init
Traceback (most recent call last):                            File "/data/data/com.termux/files/usr/lib/python3.10/multiprocessing/synchronize.py", line 28, in <module>                from _multiprocessing import SemLock, sem_unlink
ImportError: cannot import name 'SemLock' from '_multiprocessing' (/data/data/com.termux/files/usr/lib/python3.10/lib-dynload/_multiprocessing.cpython-310.so)                      
During handling of the above exception, another exception occurred:
                                                            Traceback (most recent call last):
  File "/data/data/com.termux/files/home/.repo/repo/main.py", line 39, in <module>
    import event_log                                          File "/data/data/com.termux/files/home/.repo/repo/event_log.py", line 163, in <module>                                    _EVENT_ID = multiprocessing.Value('i', 1)
  File "/data/data/com.termux/files/usr/lib/python3.10/multiprocessing/context.py", line 135, in Value
    return Value(typecode_or_type, *args, lock=lock,
  File "/data/data/com.termux/files/usr/lib/python3.10/multiprocessing/sharedctypes.py", line 79, in Value
    lock = ctx.RLock()
  File "/data/data/com.termux/files/usr/lib/python3.10/multiprocessing/context.py", line 72, in RLock
    from .synchronize import RLock
  File "/data/data/com.termux/files/usr/lib/python3.10/multiprocessing/synchronize.py", line 30, in <module>
    raise ImportError("This platform lacks a functioning sem_open" +
ImportError: This platform lacks a functioning sem_open implementation, therefore, the required synchronization primitives needed will not function, see issue 3770.
λ [~] $
```

**Comment by licy183** [comment]
Android doesn't implement sem_open, so multiprocessing cannot work on Termux. See #570.
But using `multiprocessing.dummy` module may be helpful. It is a wrapper around the threading module but replicates the API of multiprocessing.

**Comment by Mark-Joy** [comment]
@licy183 
Thank you very much for your help.
With below patches, I was able to run this command successfully:
```
repo init -u https://android.googlesource.com/platform/manifest -b tools_r21
repo sync build --jobs=1 --current-branch --no-tags
```

Patches:
```
diff -uNr Python-3.10.1/Lib/multiprocessing/heap.py Python-3.10.1.mod/
Lib/multiprocessing/heap.py
--- Python-3.10.1/Lib/multiprocessing/heap.py   2022-02-07 11:51:46.427116300 +0800
+++ Python-3.10.1.mod/Lib/multiprocessing/heap.py       2022-02-07 11:52:48.432577700 +0800
@@ -70,7 +70,7 @@
         """

         if sys.platform == 'linux':
-            _dir_candidates = ['/dev/shm']
+            _dir_candidates = []
         else:
             _dir_candidates = []

```

```
--- .repo/repo/event_log.py     2022-02-07 05:08:54.868168632 +0000
+++ .repo/repo/event_log.mod.py  2022-02-07 05:08:26.371823431 +0000
@@ -14,6 +14,7 @@
 
 import json
 import multiprocessing
+import multiprocessing.dummy
 
 TASK_COMMAND = 'command'
 TASK_SYNC_NETWORK = 'sync-network'
@@ -160,7 +161,7 @@
 
 
 # An integer id that is unique across this invocation of the program.
-_EVENT_ID = multiprocessing.Value('i', 1)
+_EVENT_ID = multiprocessing.dummy.Value('i', 1)
 
 
 def _NextEventId():
@@ -169,7 +170,6 @@
   Returns:
     A unique, to this invocation of the program, integer id.
   """
-  with _EVENT_ID.get_lock():
-    val = _EVENT_ID.value
-    _EVENT_ID.value += 1
+  val = _EVENT_ID.value
+  _EVENT_ID.value += 1
   return val

--- .repo/repo/ssh.py	2022-02-07 14:44:00.000000000 +0700
+++ .repo/repo/ssh.mod.py	2022-02-07 14:45:42.084886154 +0700
@@ -16,6 +16,7 @@
 
 import functools
 import multiprocessing
+import multiprocessing.dummy
 import os
 import re
 import signal
@@ -80,7 +81,7 @@
 
   def __init__(self, manager):
     # Protect access to the list of active masters.
-    self._lock = multiprocessing.Lock()
+    self._lock = multiprocessing.dummy.Lock()
     # List of active masters (pid).  These will be spawned on demand, and we are
     # responsible for shutting them all down at the end.
     self._masters = manager.list()

--- .repo/repo/subcmds/sync.py	2022-02-07 13:53:00.000000000 +0700
+++ .repo/repo/subcmds/sync.mod.py	2022-02-07 15:13:29.196886253 +0700
@@ -17,6 +17,7 @@
 import io
 import json
 import multiprocessing
+import multiprocessing.dummy
 import netrc
 from optparse import SUPPRESS_HELP
 import os
@@ -959,7 +960,7 @@
           print('error: failed to remove existing smart sync override manifest: %s' %
                 e, file=sys.stderr)
 
-    err_event = multiprocessing.Event()
+    err_event = multiprocessing.dummy.Event()
 
     rp = self.manifest.repoProject
     rp.PreSync()

```
 
It still fails if `jobs`  > 1. Any idea to solve it?

`repo sync build sdk --jobs=2 --current-branch --no-tags`

```
$ repo sync build sdk --jobs=2 --current-branch --no-tags
Fetching:  0�(0/2) warming upTraceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.10/multiprocessing/synchronize.py", line 28, in <module>                from _multiprocessing import SemLock, sem_unlink
ImportError: cannot import name 'SemLock' from '_multiprocessing' (/data/data/com.termux/files/usr/lib/python3.10/lib-dynload/_multiprocessing.cpython-310.so)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):                            File "/data/data/com.termux/files/home/SourceCode/android-sdk-tools-4.2.2-r1.2/.repo/repo/main.py", line 651, in <module>                                                             _Main(sys.argv[1:])
  File "/data/data/com.termux/files/home/SourceCode/android-sdk-tools-4.2.2-r1.2/.repo/repo/main.py", line 627, in _Main
    result = run()                                            File "/data/data/com.termux/files/home/SourceCode/android-sdk-tools-4.2.2-r1.2/.repo/repo/main.py", line 620, in <lambda>
    run = lambda: repo._Run(name, gopts, argv) or 0
  File "/data/data/com.termux/files/home/SourceCode/android-sdk-tools-4.2.2-r1.2/.repo/repo/main.py", line 286, in _Run
    result = cmd.Execute(copts, cargs)
  File "/data/data/com.termux/files/home/SourceCode/android-sdk-tools-4.2.2-r1.2/.repo/repo/subcmds/sync.py", line 1052, in Execute
    all_projects = self._FetchMain(opt, args, all_projects, err_event,
  File "/data/data/com.termux/files/home/SourceCode/android-sdk-tools-4.2.2-r1.2/.repo/repo/subcmds/sync.py", line 500, in _FetchMain
    success, fetched = self._Fetch(to_fetch, opt, err_event, ssh_proxy)
  File "/data/data/com.termux/files/home/SourceCode/android-sdk-tools-4.2.2-r1.2/.repo/repo/subcmds/sync.py", line 452, in _Fetch
    with multiprocessing.Pool(jobs, initializer=self._FetchInitChild,
  File "/data/data/com.termux/files/usr/lib/python3.10/multiprocessing/context.py", line 119, in Pool
    return Pool(processes, initializer, initargs, maxtasksperchild,
  File "/data/data/com.termux/files/usr/lib/python3.10/multiprocessing/pool.py", line 191, in __init__
    self._setup_queues()
  File "/data/data/com.termux/files/usr/lib/python3.10/multiprocessing/pool.py", line 343, in _setup_queues
    self._inqueue = self._ctx.SimpleQueue()
  File "/data/data/com.termux/files/usr/lib/python3.10/multiprocessing/context.py", line 113, in SimpleQueue
    return SimpleQueue(ctx=self.get_context())
  File "/data/data/com.termux/files/usr/lib/python3.10/multiprocessing/queues.py", line 342, in __init__
    self._rlock = ctx.Lock()
  File "/data/data/com.termux/files/usr/lib/python3.10/multiprocessing/context.py", line 67, in Lock
    from .synchronize import Lock
  File "/data/data/com.termux/files/usr/lib/python3.10/multiprocessing/synchronize.py", line 30, in <module>
    raise ImportError("This platform lacks a functioning sem_open" +
ImportError: This platform lacks a functioning sem_open implementation, therefore, the required synchronization primitives needed will not function, see issue 3770.
λ [~/SourceCode/android-sdk-tools-4.2.2-r1.2] $
```

**Comment by licy183** [comment]
#8990 has been merged. Maybe `repo` command can work correctly.

**Comment by Mark-Joy** [comment]
Thank you!!
It's working well now!!
