### ISSUE TITLE
[Bug]: cant install tldp

### ISSUE THREAD

**Issue by bidyut1153** [termux/termux-packages#9152]
### Problem description

Can't install tldp
Error log:
```
Collecting tldp
  Using cached tldp-0.7.13.tar.gz (51 kB)
    ERROR: Command errored out with exit status 1:
     command: /data/data/com.termux/files/usr/bin/python3 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/data/data/com.termux/files/usr/tmp/pip-install-3_p9yq4q/tldp_242aa36a0d2f40078acde328f7da9d59/setup.py'"'"'; __file__='"'"'/data/data/com.termux/files/usr/tmp/pip-install-3_p9yq4q/tldp_242aa36a0d2f40078acde328f7da9d59/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /data/data/com.termux/files/usr/tmp/pip-pip-egg-info-13vs3y64
         cwd: /data/data/com.termux/files/usr/tmp/pip-install-3_p9yq4q/tldp_242aa36a0d2f40078acde328f7da9d59/
    Complete output (11 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/data/data/com.termux/files/usr/tmp/pip-install-3_p9yq4q/tldp_242aa36a0d2f40078acde328f7da9d59/setup.py", line 6, in <module>
        from tldp import VERSION
      File "/data/data/com.termux/files/usr/tmp/pip-install-3_p9yq4q/tldp_242aa36a0d2f40078acde328f7da9d59/tldp/__init__.py", line 8, in <module>
        import tldp.outputs
      File "/data/data/com.termux/files/usr/tmp/pip-install-3_p9yq4q/tldp_242aa36a0d2f40078acde328f7da9d59/tldp/outputs.py", line 15, in <module>
        from tldp.ldpcollection import LDPDocumentCollection
      File "/data/data/com.termux/files/usr/tmp/pip-install-3_p9yq4q/tldp_242aa36a0d2f40078acde328f7da9d59/tldp/ldpcollection.py", line 11, in <module>
        class LDPDocumentCollection(collections.MutableMapping):
    AttributeError: module 'collections' has no attribute 'MutableMapping'
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/9e/0a/ab517ecaa2d55e052a20233c65925b7e8159c489b958464ae935d4f5f7f4/tldp-0.7.13.tar.gz#sha256=3e805e8ef7de4a99db1855aad5bb37dca2b42a30590128e174bac25858e2fc33 (from https://pypi.org/simple/tldp/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Using cached tldp-0.7.12.tar.gz (50 kB)
    ERROR: Command errored out with exit status 1:
     command: /data/data/com.termux/files/usr/bin/python3 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/data/data/com.termux/files/usr/tmp/pip-install-3_p9yq4q/tldp_4afcfa1612d844d8b026941b4dceab27/setup.py'"'"'; __file__='"'"'/data/data/com.termux/files/usr/tmp/pip-install-3_p9yq4q/tldp_4afcfa1612d844d8b026941b4dceab27/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /data/data/com.termux/files/usr/tmp/pip-pip-egg-info-mrp214tj
         cwd: /data/data/com.termux/files/usr/tmp/pip-install-3_p9yq4q/tldp_4afcfa1612d844d8b026941b4dceab27/
    Complete output (11 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/data/data/com.termux/files/usr/tmp/pip-install-3_p9yq4q/tldp_4afcfa1612d844d8b026941b4dceab27/setup.py", line 6, in <module>
        from tldp import VERSION
      File "/data/data/com.termux/files/usr/tmp/pip-install-3_p9yq4q/tldp_4afcfa1612d844d8b026941b4dceab27/tldp/__init__.py", line 8, in <module>
        import tldp.outputs
      File "/data/data/com.termux/files/usr/tmp/pip-install-3_p9yq4q/tldp_4afcfa1612d844d8b026941b4dceab27/tldp/outputs.py", line 15, in <module>
        from tldp.ldpcollection import LDPDocumentCollection
      File "/data/data/com.termux/files/usr/tmp/pip-install-3_p9yq4q/tldp_4afcfa1612d844d8b026941b4dceab27/tldp/ldpcollection.py", line 11, in <module>
        class LDPDocumentCollection(collections.MutableMapping):
    AttributeError: module 'collections' has no attribute 'MutableMapping'
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/39/4c/cdab2321f77713a82890005be84198d337932c6b4f811a40468457363a43/tldp-0.7.12.tar.gz#sha256=8a99e38d2b960b550d09136b20a419a58099c07da242cc1749f7ae6f7b33e4b1 (from https://pypi.org/simple/tldp/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Using cached tldp-0.7.3.tar.gz (37 kB)
Requirement already satisfied: networkx in /data/data/com.termux/files/usr/lib/python3.10/site-packages (from tldp) (2.6.3)
Requirement already satisfied: nose in /data/data/com.termux/files/usr/lib/python3.10/site-packages (from tldp) (1.3.7)
Using legacy 'setup.py install' for tldp, since package 'wheel' is not installed.
Installing collected packages: tldp
    Running setup.py install for tldp ... error
    ERROR: Command errored out with exit status 1:
     command: /data/data/com.termux/files/usr/bin/python3 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/data/data/com.termux/files/usr/tmp/pip-install-3_p9yq4q/tldp_cf466ad677aa48c8a99c901b5f639481/setup.py'"'"'; __file__='"'"'/data/data/com.termux/files/usr/tmp/pip-install-3_p9yq4q/tldp_cf466ad677aa48c8a99c901b5f639481/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /data/data/com.termux/files/usr/tmp/pip-record-w2segc_h/install-record.txt --single-version-externally-managed --compile --install-headers /data/data/com.termux/files/usr/include/python3.10/tldp
         cwd: /data/data/com.termux/files/usr/tmp/pip-install-3_p9yq4q/tldp_cf466ad677aa48c8a99c901b5f639481/
    Complete output (40 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib
    creating build/lib/tldp
    copying tldp/typeguesser.py -> build/lib/tldp
    copying tldp/cascadingconfig.py -> build/lib/tldp
    copying tldp/inventory.py -> build/lib/tldp
    copying tldp/__init__.py -> build/lib/tldp
    copying tldp/config.py -> build/lib/tldp
    copying tldp/sources.py -> build/lib/tldp
    copying tldp/utils.py -> build/lib/tldp
    copying tldp/ldpcollection.py -> build/lib/tldp
    copying tldp/outputs.py -> build/lib/tldp
    copying tldp/driver.py -> build/lib/tldp
    creating build/lib/tldp/doctypes
    copying tldp/doctypes/docbook5xml.py -> build/lib/tldp/doctypes
    copying tldp/doctypes/markdown.py -> build/lib/tldp/doctypes
    copying tldp/doctypes/docbook4xml.py -> build/lib/tldp/doctypes
    copying tldp/doctypes/common.py -> build/lib/tldp/doctypes
    copying tldp/doctypes/linuxdoc.py -> build/lib/tldp/doctypes
    copying tldp/doctypes/__init__.py -> build/lib/tldp/doctypes
    copying tldp/doctypes/rst.py -> build/lib/tldp/doctypes
    copying tldp/doctypes/asciidoc.py -> build/lib/tldp/doctypes
    copying tldp/doctypes/docbooksgml.py -> build/lib/tldp/doctypes
    copying tldp/doctypes/example.py -> build/lib/tldp/doctypes
    running egg_info
    writing tldp.egg-info/PKG-INFO
    writing dependency_links to tldp.egg-info/dependency_links.txt
    writing entry points to tldp.egg-info/entry_points.txt
    writing requirements to tldp.egg-info/requires.txt
    writing top-level names to tldp.egg-info/top_level.txt
    reading manifest file 'tldp.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    writing manifest file 'tldp.egg-info/SOURCES.txt'
    running install_lib
    running install_data
    creating /etc/ldptool
    error: could not create '/etc/ldptool': Read-only file system
    ----------------------------------------
ERROR: Command errored out with exit status 1: /data/data/com.termux/files/usr/bin/python3 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/data/data/com.termux/files/usr/tmp/pip-install-3_p9yq4q/tldp_cf466ad677aa48c8a99c901b5f639481/setup.py'"'"'; __file__='"'"'/data/data/com.termux/files/usr/tmp/pip-install-3_p9yq4q/tldp_cf466ad677aa48c8a99c901b5f639481/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /data/data/com.termux/files/usr/tmp/pip-record-w2segc_h/install-record.txt --single-version-externally-managed --compile --install-headers /data/data/com.termux/files/usr/include/python3.10/tldp Check the logs for full command output.
WARNING: You are using pip version 21.2.4; however, version 22.0.3 is available.
You should consider upgrading via the '/data/data/com.termux/files/usr/bin/python3 -m pip install --upgrade pip' command.
```

### What steps will reproduce the bug?

pip install tldp

### What is the expected behavior?

tldp should be installed

### System information

termux-info:

```

```

**Comment by xtkoba** [comment]
Seems like just a matter of hardcoded path:

```
error: could not create '/etc/ldptool': Read-only file system
```

**Comment by xtkoba** [comment]
```patch
--- python-tldp-tldp-0.7.5/setup.py.orig
+++ python-tldp-tldp-0.7.5/setup.py
@@ -27,7 +27,7 @@
                   'extras/css': glob.glob('extras/css/*.css'),
                   'extras/dsssl': glob.glob('extras/dsssl/*.dsl'),
                   },
-    data_files=[('/etc/ldptool', ['etc/ldptool.ini']), ],
+    data_files=[('/data/data/com.termux/files/usr/etc/ldptool', ['etc/ldptool.ini']), ],
     entry_points={
         'console_scripts': ['ldptool = tldp.driver:main', ],
     },
```
