### ISSUE TITLE
Issues with installing nodejs 

### ISSUE THREAD

**Issue by Rehan587** [termux/termux-packages#9507]
I'm trying to install nodejs.

![Screenshot_2022_0322_122804.jpg](https://user-images.githubusercontent.com/84271835/159425193-fae64baa-1aa2-4ea4-9772-fdc681b92ce9.jpg)

Trying it since yesterday, still doesn't work properly for some reason?

I kindly request everyone to please let me know if nodejs is under maintenance. 
Thank you.

**Comment by xtkoba** [comment]
I cannot hardly read the content of the screenshot. Could you please copy and paste the content as a plain text? (Or I might have to use some service for super-resolution.)

**Comment by Rehan587** [comment]
> I ~~cannot~~ can hardly read the content of the screenshot. Could you please copy and paste the content as a plain text? (Or I might have to use some service for super-resolution.)
```
pkg install nodejs
Checking availability of current mirror: ok
Hit:1 https://termux.astra.in.ua/apt/termux-main stable InRelease
Hit:2 https://grimler.se/termux-root-packages-24 root InRelease
Get:3 https://grimler.se/x11-packages x11 InRelease [16.8 kB]
Get:4 https://grimler.se/x11-packages x11/main all Packages [6782 B]
Get:5 https://grimler.se/x11-packages x11/main aarch64 Packages [101 kB]
Fetched 124 kB in 6s (22.5 kB/s)
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
All packages are up to date.
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following NEW packages will be installed:
  nodejs
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B/7954 kB of archives.
After this operation, 47.3 MB of additional disk space will be used.
Selecting previously unselected package nodejs.
(Reading database ... 41164 files and directories currently installed.)
Preparing to unpack .../nodejs_17.7.2_aarch64.deb ...
Unpacking nodejs (17.7.2) ...
Setting up nodejs (17.7.2) ...
TypeError: Class extends value undefined is not a constructor or null
    at Object.<anonymous> (/data/data/com.termux/files/usr/lib/node_modules/npm/node_modules/socks-proxy-agent/dist/agent.js:114:44)
    at Module._compile (node:internal/modules/cjs/loader:1099:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/data/data/com.termux/files/usr/lib/node_modules/npm/node_modules/socks-proxy-agent/dist/index.js:5:33)
    at Module._compile (node:internal/modules/cjs/loader:1099:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/data/data/com.termux/files/usr/lib/node_modules/npm/node_modules/make-fetch-happen/lib/agent.js:171:25)
    at Module._compile (node:internal/modules/cjs/loader:1099:14)
dpkg: error processing package nodejs (--configure):
 installed nodejs package post-installation script subprocess returned error exit status 1
Errors were encountered while processing:
 nodejs
E: Sub-process /data/data/com.termux/files/usr/bin/dpkg returned an error code (1)
```


I'm sorry for the image idk why is my screenshot res so low.

**Comment by thunder-coding** [comment]
Seems like you have had installed a custom version of npm using `npm install -g npm@version`. Try `rm -rf $PREFIX/lib/node_modules` and installing nodejs again.

**Comment by Rehan587** [comment]
> Seems like you have had installed a custom version of npm using `npm install -g npm@version`. Try `rm -rf $PREFIX/lib/node_modules` and installing nodejs again. 

Lol I totally forgot about that, thanks for helping out :) .
Closing the issue here.

**Comment by thunder-coding** [comment]
Maybe we should consider splitting npm into a separate package. Should make many people happy, also we will be able to package a few npm versions so that users don't need to rely on npm to install npm!

**Comment by Rehan587** [comment]
> Maybe we should consider splitting npm into a separate package. Should make many people happy, also we will be able to package a few npm versions so that users don't need to rely on npm to install npm!

Will be very nice of y'all if you do so, thanks :)
