### ISSUE TITLE
Fix ruby syslog module to link against liblog

### ISSUE THREAD

**Issue by davide125** [termux/termux-packages#962]
Similar to #41, it looks like the syslog module in ruby needs to be linked against the android liblog. I found the issue while trying to run `chef-client` (after installing it with `gem install chef`):

```
$ chef-client
/data/data/com.termux/files/usr/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require': dlopen failed: cannot locate symbol "__android_log_print" referenced by "/data/data/com.termux/files/usr/lib/ruby/2.4.0/aarch64-linux-android/syslog.so"... - /data/data/com.termux/files/usr/lib/ruby/2.4.0/aarch64-linux-android/syslog.so (LoadError)
        from /data/data/com.termux/files/usr/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /data/data/com.termux/files/usr/lib/ruby/gems/2.4.0/gems/syslog-logger-1.6.8/lib/syslog-logger.rb:1:in `<top (required)>'
        from /data/data/com.termux/files/usr/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /data/data/com.termux/files/usr/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /data/data/com.termux/files/usr/lib/ruby/gems/2.4.0/gems/chef-13.0.118/lib/chef/log/syslog.rb:20:in `<top (required)>'
        from /data/data/com.termux/files/usr/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /data/data/com.termux/files/usr/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /data/data/com.termux/files/usr/lib/ruby/gems/2.4.0/gems/chef-13.0.118/lib/chef/log.rb:24:in `<top (required)>'
        from /data/data/com.termux/files/usr/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /data/data/com.termux/files/usr/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /data/data/com.termux/files/usr/lib/ruby/gems/2.4.0/gems/chef-13.0.118/lib/chef.rb:23:in `<top (required)>'
        from /data/data/com.termux/files/usr/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /data/data/com.termux/files/usr/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /data/data/com.termux/files/usr/lib/ruby/gems/2.4.0/gems/chef-13.0.118/bin/chef-client:23:in `<top (required)>'
        from /data/data/com.termux/files/usr/bin/chef-client:22:in `load'
        from /data/data/com.termux/files/usr/bin/chef-client:22:in `<main>'
```

**Comment by fornwall** [comment]
Thanks a lot! This has been fixed in version `2.4.1-1` of the ruby package, which can be updated to by running:

    packages upgrade
