### ISSUE TITLE
[Package]: Poezio

### ISSUE THREAD

**Issue by aicynide** [termux/termux-packages#9682]
### Package description

Poezio is a free console XMPP client (the protocol on which the Jabber IM network is built).

### Home page URL

https://poez.io

### Source code URL

https://lab.louiz.org/poezio/poezio.git 

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

### Additional information

Try to build using official instructions that is;

```
git clone https://lab.louiz.org/poezio/poezio.git
cd poezio
./update.sh
./launch.sh
```
(Had changed TEMPDIR in line 1 of Makefile to /data/data/com.termux/files/usr/tmp)

But got this error

```
Sphinx not found, the build_man command will be unavailable.


Sphinx-built manpages not found. Only the short handwritten manpages will be installed

Traceback (most recent call last):
  File "/data/data/com.termux/files/home/poezio/setup.py", line 100, in <module>
    os.link(os.path.join(current_dir, 'data', 'default_config.cfg'),
AttributeError: module 'os' has no attribute 'link'. Did you mean: 'unlink'?
make: *** [Makefile:6: all] Error 1
```

Also, tried to install using pip but got this error

```
Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [48 lines of output]
      WARNING: The wheel package is not available.
        error: subprocess-exited-with-error

        × python setup.py bdist_wheel did not run successfully.
        │ exit code: 1
        ╰─> [6 lines of output]
            usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
               or: setup.py --help [cmd1 cmd2 ...]
               or: setup.py --help-commands
               or: setup.py cmd --help

            error: invalid command 'bdist_wheel'
            [end of output]

        note: This error originates from a subprocess, and is likely not a problem with pip.
        ERROR: Failed building wheel for cffi
      ERROR: Failed to build one or more wheels
      Traceback (most recent call last):
        File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/setuptools/installer.py", line 75, in fetch_build_egg
          subprocess.check_call(cmd)
        File "/data/data/com.termux/files/usr/lib/python3.10/subprocess.py", line 369, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['/data/data/com.termux/files/usr/bin/python3', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/data/data/com.termux/files/usr/tmp/tmpn9lxj9uz', '--quiet', 'cffi>=1.5.0']' returned non-zero exit status 1.

      The above exception was the direct cause of the following exception:

      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/data/data/com.termux/files/usr/tmp/pip-install-_mkhh10s/pycares_5bc0d090ec824480801c9724c3493d8a/setup.py", line 16, in <module>
          setup(name             = 'pycares',
        File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/setuptools/__init__.py", line 152, in setup
          _install_setup_requires(attrs)
        File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/setuptools/__init__.py", line 147, in _install_setup_requires
          dist.fetch_build_eggs(dist.setup_requires)
        File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/setuptools/dist.py", line 806, in fetch_build_eggs
          resolved_dists = pkg_resources.working_set.resolve(
        File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 766, in resolve
          dist = best[req.key] = env.best_match(
        File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 1051, in best_match
          return self.obtain(req, installer)
        File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 1063, in obtain
          return installer(requirement)
        File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/setuptools/dist.py", line 877, in fetch_build_egg
          return fetch_build_egg(self, req)
        File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/setuptools/installer.py", line 77, in fetch_build_egg
          raise DistutilsError(str(e)) from e
      distutils.errors.DistutilsError: Command '['/data/data/com.termux/files/usr/bin/python3', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/data/data/com.termux/files/usr/tmp/tmpn9lxj9uz', '--quiet', 'cffi>=1.5.0']' returned non-zero exit status 1.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

Is it possible to use it in termux?

**Comment by xtkoba** [comment]
A workaround:

```bash
pip install cffi
pip install poezio
```

(separately install `cffi` beforehand.)

**Comment by aicynide** [comment]
Worked thank you very muci
