### ISSUE TITLE
[Bug]:  can't install anything with pip

### ISSUE THREAD

**Issue by SuperProCz** [termux/termux-packages#9818]
### Problem description

When i write $pip install requests it throws me this error. Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/bin/pip", line 5, in <module>
    from pip._internal.cli.main import main
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/pip/_internal/cli/main.py", line 9, in <module>
    from pip._internal.cli.autocompletion import autocomplete
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/pip/_internal/cli/autocompletion.py", line 10, in <module>
    from pip._internal.cli.main_parser import create_main_parser
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/pip/_internal/cli/main_parser.py", line 8, in <module>
    from pip._internal.cli import cmdoptions
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/pip/_internal/cli/cmdoptions.py", line 23, in <module>
    from pip._internal.cli.parser import ConfigOptionParser
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/pip/_internal/cli/parser.py", line 12, in <module>
    from pip._internal.configuration import Configuration, ConfigurationError
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/pip/_internal/configuration.py", line 20, in <module>
    from pip._internal.exceptions import (
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/pip/_internal/exceptions.py", line 14, in <module>
    from pip._vendor.rich.console import Console, ConsoleOptions, RenderResult
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/pip/_vendor/rich/__init__.py", line 16, in <module>
    _IMPORT_CWD = os.path.abspath(os.getcwd())
FileNotFoundError: [Errno 2] No such file or directory

### What steps will reproduce the bug?

Idk

### What is the expected behavior?

To pip install the package requests.

### System information

termux-info:

```
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
sh: 0: getcwd() failed: No such file or directory
sh: 0: getcwd() failed: No such file or directory
sh: 0: getcwd() failed: No such file or directory
Application version:
unsupported
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://termux.org/packages/ stable main
# game-repo (sources.list.d/game.list)
deb https://dl.bintray.com/grimler/game-packages-24 games stable
# science-repo (sources.list.d/science.list)
deb https://dl.bintray.com/grimler/science-packages-24 science stable
Updatable packages:
apt/stable 2.4.1-2 aarch64 [upgradable from: 1.4.10-6]
Android version:
12
Kernel build information:
Linux localhost 4.14.190-perf-g75e9984dc8e8 #1 SMP PREEMPT Tue Jan 25 10:52:58 CST 2022 aarch64 Android
Device manufacturer:
Xiaomi
Device model:
M2101K6G
```

**Comment by Grimler91** [comment]
You seem to be using a *very* old installation. Re-install termux-app from f-droid or at least upgrade all packages (will require `apt remove science-repo game-repo`, those repositories no longer exist), and try again.

**Comment by SuperProCz** [comment]
Oh ty
